### ISSUE TITLE
how to mute audio?

### ISSUE THREAD

**Issue by GamGiG** [ZeBobo5/Vlc.DotNet#10]
Hello
Thank you to the great job.
I am using the Vlc.DotNet in my project (IPTV multi-viewer). Everything works fine, but i have no idea how to mute the volume. It is possible?

**Comment by ZeBobo5** [comment]
Corrected, now you have :

```csharp
bool isMuted = myVlcControl.Audio.IsMute;
myVlcControl.Audio.ToggleMute();
```

**Comment by CBDlkl** [comment]
This method does not work.
`vlcControl.Audio.Volume = 0;
 vlcControl.Audio.IsMute = true;
vlcControl.Audio.ToggleMute();
vlcControl.Play(...);`
Still not Mute.

**Comment by miaolinvip** [comment]
vlcControl.Audio.Volume = 0;
vlcControl.Audio.IsMute = true; 
vlcControl.Audio.ToggleMute();

All Everthing not Mute.

**Comment by Franck-E** [comment]
Has anyone got a solution for this?

**Comment by jeremyVignelles** [comment]
I'm not aware there if they are still issues around this. Presumably, since I got other bug reports about muting doing weird things, I'd expect that it's "kind of working". See #524 and #381

**Comment by Franck-E** [comment]
var mediaOptions = new string[] { "--aout=directsound" };
vlcControl.SetMedia(new FileInfo(playlist.FilePath), mediaOptions);
vlcControl.Audio.IsMute = true;
vlcControl.Play();

This doesn't work, but thank you Jeremy, I will check further.

**Comment by Franck-E** [comment]
After looking at it, I see that this does not work:

var mediaOptions = new string[] { "--aout=directsound" };
vlcControl.SetMedia(new FileInfo(path), mediaOptions);
vlcControl.Play();
vlcControl.Audio.IsMute = true;

But this works ok:

vlcControl.SetMedia(new FileInfo(playlist.FilePath));
vlcControl.Play();
var directsound = vlcControl.Audio.Outputs.All.FirstOrDefault(x => x.Name == "directsound");
if (directsound != null)
{
       vlcControl.Audio.Outputs.Current = directsound;
       vlcControl.Audio.IsMute = true;
}

And then later calling vlcControl.Audio.ToggleMute() is fine even with multiple controls.
Setting the audio device via mediaOptions for some reason has issues.. 
Hopefully this can help someone.
