### ISSUE TITLE
VLC player crashes on wpf form

### ISSUE THREAD

**Issue by aisa213** [ZeBobo5/Vlc.DotNet#100]
I've used VLC.Dotnet 1.2.0.0 (Core & wpf) to make a media player on my rtsp stream on wpf form.
(I install VLC 2.2.0 x86 on my system and use it's dll and plugins. and my code is in VS 2013.)
in background and in another thread, I've used vlc to get every frame and do some process on them and then return the result to update my wpf UI.
The problem is after some time, the player on wpf crashes and freezes on random frame.
I used the code sample in here to use the VLC.Dotnet.
Why this happen and how can I prevent it?

**Comment by riddlemd** [comment]
Have you tried using the dll that are provided in the repo? They're from 2.1.2 some of the changes in 2.2 might be causing issues.

**Comment by ZeBobo5** [comment]
Close with latest nuget packages
