### ISSUE TITLE
I dont find any how to usage for this library

### ISSUE THREAD

**Issue by yosualie8** [ZeBobo5/Vlc.DotNet#104]
i go into this link https://github.com/ZeBobo5/Vlc.DotNet/wiki and find this

Here you can find information and tutorials about stating using our control in your project!

Using Vlc.DotNet in WinForms
Using Vlc.DotNet in WPF
Class Reference (Generated by Sandcastle Help File Builder)

but when i click Using Vlc.DotNet in WPF it keeps redirect me into the same page. Where can i find a how ot usage for this library? thank you

**Comment by coczero** [comment]
The wiki does not seem to contain any information, 
I recommend just downloading the repo and looking at the samples, thats how I got it (somehow) working.

**Comment by yosualie8** [comment]
Hi coczero thanks for you reply, i got it working too, but when the app is closed i always got a system access violation exception, do you get that error too? oh and one more thing, i already downloaded the repo but i dont find any samples..Just the library source code only.. Can you tell me where the sample path is? Thank you..

**Comment by coczero** [comment]
For me the samples are in Vlc.DotNet\src\Samples\
And yes, I get that Exception too, seems to be a bug in the library.

**Comment by yosualie8** [comment]
Wow okay then.. its better for me to find another vlc library for .Net..  
I already found one but it only work with vlc 1.1.1 player.. And it seems a little buggy when streaming rtsp from multiple ip cameras.. Please tell me if you found another stable library for vlc 2.x player coczero because i really need it. Thanks for your help..

**Comment by sepehr1014** [comment]
I highly recommend https://github.com/higankanshi/xZune.Vlc

**Comment by yosualie8** [comment]
Hi Sepehr1014 thank you for your suggestion 

Now im testing the stability of higankashi xzune.vlc wrapper library. Im using it for streaming 9 IP cameras simultaneously at 720P 25 FPS settings with 800ms network cache and so far it seems good and stable, there's no hopping and stuttering when i stream those cameras for about 3 hours. We'll see after the app running for one week.

**Comment by PureIso** [comment]
If you are getting the error below:

An unhandled exception of type 'System.ArgumentException' occurred in Vlc.DotNet.Core.Interops.dll
Additional information: Media player instance is not initialized.

I fixed it with:

if (mediaPlayerInstance == IntPtr.Zero) return false;
return GetInteropDelegate<IsPlaying>().Invoke(mediaPlayerInstance) == 1;

I might do a pull request when I get home.

**Comment by jeremyVignelles** [comment]
This repository now has a Getting Started wiki
