### ISSUE TITLE
Record stream into multiple small files

### ISSUE THREAD

**Issue by anupamanadig** [ZeBobo5/Vlc.DotNet#105]
I can record the stream in to a file with the fallowing command

mediaOptions = ":sout=#std{access=file,mux=mp4, dst='test.mp4'}";
myVlcControl.MediaPlayer.Play(new Uri(uri), mediaOptions);

but i need to save multiple small files instead of one big file.
How can i do this?

**Comment by jeremyVignelles** [comment]
Are you able to do this from command line with VLC? If yes, you can pass the arguments as you said.

Closing this as this is not a Vlc.DotNet issue but a VLC usage question.

**Comment by jeremyVignelles** [comment]
Note for future readers : there is the `cycle` plugin that can split the output into several destinations
