### ISSUE TITLE
mouse event not working while playing video

### ISSUE THREAD

**Issue by jasver** [ZeBobo5/Vlc.DotNet#107]
VlcControl add on WinForm, There is no any mouse event fire while playing video

**Comment by sepehr1014** [comment]
You'll need to use: https://github.com/higankanshi/xZune.Vlc

**Comment by friman** [comment]
I notice that https://github.com/higankanshi/xZune.Vlc is only for wpf, no for WinForm. Any solution to this issue?

**Comment by AyraStark** [comment]
I have the same problem in a WinForm App .It seems that the released vlc lib has not throw the mouse event .You should modify the source code of vlc to make it  response .

**Comment by paurail** [comment]
+1

**Comment by krrrishh** [comment]
Use this VLC control which i have created. It supports clicks, mouseclicks, mouse move, scroll etc and also it has auto cursor hide after 2 seconds just like how it does in actual VLC player. I am creating a video player with this VLC dot net will upload soon. :)
[VlcControlV2.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/1010749/VlcControlV2.zip)

**Comment by jeremyVignelles** [comment]
Mouse events are automatically captured by the Vlc control. We probably could add a way to let events fall through by implementing `libvlc_video_set_mouse_input`

see https://github.com/videolan/vlc/blob/9dce7032797ed9ab54e46f944bb7f800bd69cee8/include/vlc/libvlc_media_player.h#L1098

**Comment by aap4ixx** [comment]
Hi,
Sorry for my inappropriate question,
Last update this issue have "28 Nov 2017". At this moment 16.05.2018.
Do you know ho fixing this issue or find a workaround?

**Comment by jeremyVignelles** [comment]
This still need to be implemented in Vlc.DotNet, either by me or by any volunteer.

As for a workaround, I suppose that you _could_ show an invisible control on top of the Vlc control that would handle the right click. I agree, this is far from perfect.

**Comment by aap4ixx** [comment]
Hi jeremyVignelles.
Sorry but i am very bad developer, and my english is also very bed.
But i found how to create "invisible control" and it is work. [Link](http://qaru.site/questions/281223/making-a-control-transparent)

**Comment by krrrishh** [comment]
Hi @aap4ixx . Did you try using my control?
[https://github.com/ZeBobo5/Vlc.DotNet/files/1010749/VlcControlV2.zip](url)

**Comment by aap4ixx** [comment]
Hi @krrrishh.
No i didn't use you code. Because i found normal code.
Thanks.

**Comment by semonpic** [comment]
@krrrishh  I do use your control,but it don't work, Can you give us  a full demo,thanks

**Comment by Arashz22** [comment]
I've downloaded the new files but still mouse events doesn't work.
is it fixed for you ?

**Comment by jeremyVignelles** [comment]
Did you try the 3.0.0 prerelease?

**Comment by Arashz22** [comment]
yes I use 3.0.0 prerelease,
 according to dear @CrookedFingerGuy's guidence in[ this page](https://github.com/ZeBobo5/Vlc.DotNet/commit/7282f8b9689701e1281a20c5618db5a129873787#commitcomment-30259378)
my mouse and keyboard event handlers are working right now.
```
 public Sample()
        {
            InitializeComponent();
            myVlcControl.Video.IsMouseInputEnabled = false;
            myVlcControl.Video.IsKeyInputEnabled = false;
        }
```
Thanks you all
