### ISSUE TITLE
Playing with buffer?

### ISSUE THREAD

**Issue by bur478** [ZeBobo5/Vlc.DotNet#108]
I want video play with buffer. I receive the video stream with udp connection. But, I want to edit received data, and then I want to play. Because, received data has extra frame header. I can capture frame on udp stream. I can play with file and network stream. How to in my buffer play frame by frame?

**Comment by ZeBobo5** [comment]
This can be done by Vlc options passed to media.
You can find help on the [VideoLAN Forums](https://forum.videolan.org/)
