### ISSUE TITLE
Black or blank output in Winforms on certain computers

### ISSUE THREAD

**Issue by cb88** [ZeBobo5/Vlc.DotNet#109]
I have setup my project to build for x86 and I have 32bit VLC installed I have tested my app with VLC 2.1, 2.2 and 3.0 from September 2015.

On my development computer it works fine, on a friends development computer it works fine. I installed it on a fresh windows 7 Pro 64bit computer and it the app runs however if I use VlcControl and put it in a panel I get a black screen (probably just the back color of the panel) and if I use the VlcMediaPlayer class... and set it to embed in a panel I never see it start up.

Firstly how do i figure out where the log file is if any? I'm building a debug build however I don't see anything like that anywhere I need to set it's path and loglevel. 

The computer it does not work on has VLC 3.0 the same as my development computer currently, and VLC itself can indeed connect to the RTSP stream I am trying to view without problems.

I also tried building my app as targeting .net 2.0 as I thought maybe some libraries were not the same across these machines so I'd just take the lowest common denominator but that had no effect. The RTSP Uri is hardcoded in the app so that isn't getting messed up either through human error.

**Comment by jeremyVignelles** [comment]
Is it still an issue? Could you upgrade the libvlc you are using (see the getting started wiki, you will also get info about increasing verbosity of Vlc.DotNet)
