### ISSUE TITLE
Closing the application jumps exception

### ISSUE THREAD

**Issue by rafaelkan** [ZeBobo5/Vlc.DotNet#115]
In code VlcInteropsManager.cs
```c#
internal T GetInteropDelegate<T>()
        {
            string vlcFunctionName = null;
            try
            {
                var attrs = typeof(T).GetCustomAttributes(typeof(LibVlcFunctionAttribute), false);
                if (attrs.Length == 0)
                    throw new Exception("Could not find the LibVlcFunctionAttribute.");
                var attr = (LibVlcFunctionAttribute)attrs[0];
                vlcFunctionName = attr.FunctionName;
                if (myInteropDelegates.ContainsKey(vlcFunctionName))
                    return (T)Convert.ChangeType(myInteropDelegates[attr.FunctionName], typeof(T), null);
                var procAddress = Win32Interops.GetProcAddress(myLibVlcDllHandle, attr.FunctionName);
                if (procAddress == IntPtr.Zero)
                    throw new Win32Exception();
                var delegateForFunctionPointer = Marshal.GetDelegateForFunctionPointer(procAddress, typeof(T));
                myInteropDelegates[attr.FunctionName] = delegateForFunctionPointer;
                return (T)Convert.ChangeType(delegateForFunctionPointer, typeof(T), null);
            }
            catch (Win32Exception e)
            {
                throw new MissingMethodException(String.Format("The address of the function '{0}' does not exist in libvlc library.", vlcFunctionName), e);
            }
        }
```
On the next line the variable 'proc Address' which comes from 'myLibVlcDllHandle' has already been emptied makes an exception.:
```c#
 if (procAddress == IntPtr.Zero)
                    throw new Win32Exception();
```

Please help!

**Comment by wolf-germany** [comment]
I'm not quit sure what the problem is. Assuming that you have set the VlcLibDirectory correctly, you perhaps using an outdated version of VLC. Version 2.1 (also within the lib path of this repository) works at my site.

What is the name of the function in libvlc the exception returns?

**Comment by rafaelkan** [comment]
Versión VLC -> 2.2.1

### First error
>First exception of type 'System.ComponentModel.Win32Exception' in Vlc.DotNet.Core.Interops.dll
Additional information: The specified process did not find
If a driver for this exception, the program can continue safely.

### Second error
>First exception of type 'System.MissingMethodException' in Vlc.DotNet.Core.Interops.dll
Additional information: The address of the function 'libvlc_event_detach' does not exist in libvlc library.
If a driver for this exception, the program can continue safely.

### Third error
>An unhandled exception of type 'System.MissingMethodException' in Vlc.DotNet.Core.Interops.dll
Additional information: The address of the function 'libvlc_event_detach' does not exist in libvlc library.
If a driver for this exception, the program can continue safely.

**Comment by rafaelkan** [comment]
So far I have solved changing this line:
```c#
if (procAddress == IntPtr.Zero)
                    throw new Win32Exception();
```
For this:
```c#
if (procAddress == IntPtr.Zero)
                    System.Threading.Thread.CurrentThread.Abort();
```
Closing the open thread that should not be, but the solution should be that closing the camera does not work any event.

**Comment by rafaelkan** [comment]
In the end my problem came to call Stop. In another thread solved another problem that in the end everything came through it: [https://github.com/ZeBobo5/Vlc.DotNet/issues/136](url)

`Application.DoEvents();`
`this.vlcControl.Stop();`
