### ISSUE TITLE
WPF sample

### ISSUE THREAD

**Issue by initpronj** [ZeBobo5/Vlc.DotNet#116]
Hello I am not able to use the WPF sample (Vlc.DotNet.Wpf.Samples - CLR 4 - .Net 4.5)
It seems that myVlcMediaPlayer is null after InitializeComponent().

Can someone help
thanks a lot

 public void Play(Uri uri, params string[] options)
        {
            //EndInit();
            if (myVlcMediaPlayer != null)
            {
                myVlcMediaPlayer.SetMedia(uri, options);
                Play();
            }
        }

**Comment by higankanshi** [comment]
You can see my project https://github.com/higankanshi/xZune.Vlc .
It's easy to start and has native WPF control.

see this tips(Chinese and English):
>https://github.com/higankanshi/xZune.Vlc#quick-start
>https://github.com/higankanshi/xZune.Vlc#0715

**Comment by initpronj** [comment]
Hello higankanshi
thanks for your hint, but even I try to build your solution I got a lot of errors.
Does anybody has a hint to use Vlc.Net for WPF?
thanks

**Comment by wolf-germany** [comment]
In WinForms the initialization of the component works differently.
Add some lines to **VlcControl.cs** of Vlc.DotNet.Wpf. Should look like this:

```c#
using System;
using System.Runtime.InteropServices;
using System.Windows.Interop;
using Vlc.DotNet.Core.Interops;
using System.Windows.Forms.Integration;

namespace Vlc.DotNet.Wpf
{
    public class VlcControl : WindowsFormsHost
    {
        public Forms.VlcControl MediaPlayer { get; private set; }

        public VlcControl()
        {
            MediaPlayer = new Forms.VlcControl();
            ((System.ComponentModel.ISupportInitialize)(this.MediaPlayer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.MediaPlayer)).EndInit();
            this.Child = MediaPlayer; 
        }
    }
}
```
or add once **EndInit** before first use.

Hint: *The app will not work if the execute path contains "VisualStudio"*

**Comment by initpronj** [comment]
Hallo Wolf Germany

ich probiers mal auf Deutsch.

folgende Änderungen hab ich in meiner App gemacht und es läuft soweit

_vlcControl.MediaPlayer.BeginInit();
_vlcControl.MediaPlayer.VlcLibDirectoryNeeded += OnVlcControlNeedsLibDirectory;
_vlcControl.MediaPlayer.Playing += MdeMainMediaOpened;
_vlcControl.MediaPlayer.EndReached += MdeMainMediaEnded;
_vlcControl.MediaPlayer.EndInit();

danke für die Unterstützung

Mit freundlichen Grüßen
Norbert Jungbauer


Am 09.11.2015 um 10:09 schrieb wolf-germany <notifications@github.com<mailto:notifications@github.com>>:

In WinForms the initialization of the component works differently.
Add some lines to VlcControl.cs of Vlc.DotNet.Wpf. Should look like this:

using System;
using System.Runtime.InteropServices;
using System.Windows.Interop;
using Vlc.DotNet.Core.Interops;
using System.Windows.Forms.Integration;



namespace Vlc.DotNet.Wpf

{

public class VlcControl : WindowsFormsHost

    {

public Forms.VlcControl MediaPlayer { get; private set
; }


public VlcControl
()
        {
            MediaPlayer =
new
 Forms.VlcControl();
            ((System.ComponentModel.ISupportInitialize)(
this
.MediaPlayer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(
this
.MediaPlayer)).EndInit();

this
.Child = MediaPlayer;
        }
    }
}

or add once EndInit before first use.

Hint: The app will not work if the execute path contains "VisualStudio"

**Comment by jeremyVignelles** [comment]
This repository now has a Getting started wiki
