### ISSUE TITLE
System.AccessViolationException in Vlc.DotNet.Core.Interops.dll when dispose applicate

### ISSUE THREAD

**Issue by soapgu** [ZeBobo5/Vlc.DotNet#117]
I install package  Vlc.DotNet.Wpf 2.1.62  in nuget.

but when i close the wpf applicate. It throw a System.AccessViolationException in Vlc.DotNet.Core.Interops.dll.

If I was missed some code for dispose the vlc control?
Can anyone help me ?

**Comment by wolf-germany** [comment]
The nuget packages are "very" old (March or so). Therefore many bugs still within the packages. The source code is much more stable.
Maybe @ZeBobo5 should update the nuget packages.

**Comment by ZeBobo5** [comment]
Close with latest nuget packages
