### ISSUE TITLE
AllowsTransparency= "True"

### ISSUE THREAD

**Issue by 19871010** [ZeBobo5/Vlc.DotNet#119]
If the window is added 

AllowsTransparency= "True"
"WindowStyle= None" 

when playing can not see the screen

**Comment by FJS01** [comment]
I have the same issue. Audio however is played.

**Comment by higankanshi** [comment]
You can see my project https://github.com/higankanshi/xZune.Vlc .

This has no airspace issue, because we provide a native WPF control, not a HwndHost.

**Comment by FJS01** [comment]
I think it's a VlcDotNet problem because the problem does not exist with 'Vlc.DotNet-2.0-Twoflower' (same Vlc player , same wpf-aplication).

**Comment by jeremyVignelles** [comment]
This is a known effect of the famous Airspace issue #296 . I have implemented a native Wpf control that will not suffer from that restriction. See #365

**Comment by jeremyVignelles** [comment]
You can now try with 3.0.0-develop250, which should not suffer from this issue 😉
