### ISSUE TITLE
WPF video is always on top

### ISSUE THREAD

**Issue by pagefault** [ZeBobo5/Vlc.DotNet#12]
Hi,
I tried to place a button on top of the WPF control but it is not visible because the VLC control always seems to be on top. How can I create video player controls like in Windows Media Player where the play/pause button is on top of the video?

**Comment by Itzalive** [comment]
I just came across this issue in the new version here, I have used the WPF control in the old version for quite a while. I'm not familiar with the new version but it looks like a complete rewrite so I expect it will come in time. Although the old project (http://vlcdotnet.codeplex.com/) has some issues the WPF control does not have the 'airspace' issues the new project now has. I recommend giving it a go while the new one is still being developed.

**Comment by ayezutov** [comment]
@ZeBobo5 this is an issue for me as well. And apparently, HwndControl will always be drawn that way:
["A hosted Windows Forms control is drawn in a separate HWND, so it is always drawn on top of WPF elements"](https://msdn.microsoft.com/en-us/library/ms744952.aspx)).

Do you have any other ideas, how to use it in WPF? I might help you out with this one.

**Comment by gen3ric** [comment]
I must say, this airspace issue makes this control absolutely unusable in almost every scenario. I knwo this is a core design issue but is there any way to fix this?

**Comment by sepehr1014** [comment]
Actually, the previous version was pretty useless for us. Since just an image object was visible, there was no interaction between user and the player. For instance, DVD menus could not be interacted with.
Unfortunately the airspace issue is know to all of us, but there is currently no stable fix for it.

**Comment by spoiledtechie** [comment]
Issue for me as well.  Looking to see if I can do anything to fix this.

**Comment by sepehr1014** [comment]
We use a simple yet practical workaround for this issue. Place the overlay controls in a child window which moves on the parent's location changed event. We have the media player control in a window called MediaPlayer which has a transparent child window named MediaPlayerOverlay that has all the required controls. Now you only need to sync these two windows ...

**Comment by asavartsov** [comment]
I'm using airspace workaround from https://microsoftdwayneneed.codeplex.com/ in Redirect mode and it's working fine, I see no major performance degrade. But native DShow/WPF rendering would be much more appropriate though.

**Comment by spoiledtechie** [comment]
@ZeBobo5 Can you please respond to this?  Any future thoughts on fixing this airspace issue or building the control into WPF instead of Win32 component?  If not, have you looked into it and is it possible?  If it is, I will most likely be spending the time to get it completed.  I just need to know if you looked into and thought if its possible to fix?

**Comment by wuzhenda** [comment]
what a pity.could we use MediaElement in wpf,but the background is vlc?

**Comment by Pjanssen** [comment]
I'm experiencing issues with the WPF control as well. It would be great if there was going to be a solution!

**Comment by kkcosmo** [comment]
I am looking also for a good solution for this problem.

**Comment by higankanshi** [comment]
You can see my project xZune.Vlc，this has native WPF Control.
https://github.com/higankanshi/xZune.Vlc

**Comment by wuzhenda** [comment]
I tested @higankanshi 's  solution,it's good. if this project would merge the solution ,we will have a nice wpf vlc.

**Comment by Pjanssen** [comment]
@higankanshi 's solution seems to use C# 6.0, which is a fun, but a bit unpractical at this point in time...

**Comment by kkcosmo** [comment]
This was my problem too @Pjanssen. I created my own fork as a convenient solution for myself. My requirements is .net4 without the new language features of C# 6.0. 
My plan is to stay in sync with @higankanshi 's solution

**Comment by higankanshi** [comment]
Ummm...I only used one features of C# 6.0...

Object?.Method();

You can instead to:

if(Object != null)
{
  Object.Method();
}

**Comment by asavartsov** [comment]
Also nameof expression. Both are minor syntactic sugar so it probably worth
to use old style constructions for compatibility, especially assuming that
VS 2015 is still in RC state.

On Mon, Jun 8, 2015 at 4:46 PM, HIGAN <notifications@github.com> wrote:

> Ummm...I only used one features of C# 6.0...
>
> Object?.Method();
>
> You can instead to:
>
> if(Object != null)
> {
> Object.Method();
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZeBobo5/Vlc.DotNet/issues/12#issuecomment-110001360>.
>



-- 
Sent with <3 by Alexey Savartsov

**Comment by higankanshi** [comment]
Ummm..."nameof"...
You can use the static name String.
Used nameof for avoid the mistake of spelling.

**Comment by higankanshi** [comment]
Ummm...There is a fork with English Comments and .Net4

https://github.com/kkcosmo/xZune.Vlc

**Comment by tombby11** [comment]
@sepehr1014  
can you please elaborate with some code of what you mean ?

**Comment by jeremyVignelles** [comment]
Old issue that is probably covered by #296
