### ISSUE TITLE
Set Audio Output

### ISSUE THREAD

**Issue by Stealth01** [ZeBobo5/Vlc.DotNet#121]
Hi all,
If the pc have more sound cards, how can I set the audio output for a VlcControl?
How can I create a list of all audio output device?
My project is simply a form with a VlcControl. I've added "Vlc.DotNet.Forms.dll" as item of the toolbox and I've set the VlcLibDirectory. I didn't add COM or other references. If I set a media for the VlcControl and play it work and I can hear it on the default audio device, but I don't know how to set a different audio output device.

VB.NET or C# (I use VB.NET but I also understand C#)

Thank you very much :)

**Comment by wrickout** [comment]
I need too! I can play video perfectly, but cant set audio output. Need help SOS!!

**Comment by mlessd** [comment]
I would also like to know if the audio output device can be selected using vlcdotnet...

**Comment by gleda83** [comment]
Any solution?

**Comment by jeremyVignelles** [comment]
I don't have anything to try it out for now. The way of doing this is probably by adding the right options to the vlc control. Are you able to select it from the command line? the option is the same.
Please share your findings

**Comment by gleda83** [comment]
Success!

string[] option = new string[3];
option[0] = "--aout=waveout";
option[1] = "--waveout-audio-device=LG TV-0 (2- NVIDIA High Definit ($1,$64)";
option[2] = "--waveout-volume=1.0";
vlcControl1.VlcMediaplayerOptions = option;
