### ISSUE TITLE
Method's type signature is not PInvoke compatible in VlcInteropsManager

### ISSUE THREAD

**Issue by anhlunnhaque** [ZeBobo5/Vlc.DotNet#125]
Does anybody see the error 'Method's type signature is not PInvoke compatible' in the VlcInteropsManager class?

VlcInteropsManager class
error at this line --> var delegateForFunctionPointer = Marshal.GetDelegateForFunctionPointer(procAddress, typeof(T));

typeof(T) looks right because it's showing libvlc_audio_get_track_description.cs

There's also libvlc_audio_get_track_description_release.cs class in the project as well.

Any help/pointers would be appreciated as I don't know how to fix this error. Is it a bug in the vlcdotnet, or vlc library. The same method 'GetDelegateForFunctionPointer' works for other calls in this vlcdotnet project why not audio_get_track_description.

Thanks.

**Comment by jeremyVignelles** [comment]
Is the issue still present in 2017? If yes, please reopen.
