### ISSUE TITLE
Not playing playlists

### ISSUE THREAD

**Issue by FJS01** [ZeBobo5/Vlc.DotNet#128]
VLC.DotNet Wpf-Sample does not play (stream ?) playlists.

The following stream playlists are not played:
'myControl.MediaPlayer.Play(new Uri("http://mp3-live.swr3.de/swr3_m.m3u"));' and
'myControl.MediaPlayer.Play(new Uri("http://50.7.173.162:2199/tunein/enieopyy.pls"));'

This worked well for TwoFlower.

Playing corresponding stream directly works fine: 'myControl.MediaPlayer.Play(new Uri("http://50.7.173.162:8027/stream"));'

kind regards Franz-Josef

**Comment by FJS01** [comment]
I think it's a VlcDotNet problem because the problem does not exist with 'Vlc.DotNet-2.0-Twoflower' (same Vlc player , same wpf-aplication).

**Comment by jeremyVignelles** [comment]
Closing in favor to #193
