### ISSUE TITLE
how i can get frame from vlc rtsp?

### ISSUE THREAD

**Issue by seekerquoc** [ZeBobo5/Vlc.DotNet#129]
have any function callback for get frame from vlc rtsp?

**Comment by rafaelkan** [comment]
Call VlcControl.TakeSnapshot(fileName)

**Comment by roman-minyaylov** [comment]
I have the same issue. Any ways to check callback to decoded audio and video frames?

**Comment by jeremyVignelles** [comment]
As of Vlc.DotNet 3.0, you can use SetVideoFormatCallbacks and SetVideoCallbacks to get video frame by frame. See an example of implementation in the WPF control.

Feel free to reopen if something else is needed

**Comment by Mamad4D** [comment]
hi jeremy,
i need an **example** for SetVideoCallbacks function in winForm to get video frame by frame.
