### ISSUE TITLE
issue in releasing

### ISSUE THREAD

**Issue by vahidhashemi** [ZeBobo5/Vlc.DotNet#13]
Hi,

I've included this lib into my project (VS2014) and it works fine on local machine (VLC was installed beforehand) when I want to release my app in another computer.

My app gets error and even doesn't run and when I trace it it was because of  "Vlc.DotNet.Core.Interops".

honestly don't know how to fix it!
What should I do? install vlc on every client? (not a good solution)

**Comment by ZeBobo5** [comment]
You must install Vlc or embed vlc libraries with your program. If you don't have Vlc libraries you can't use Vlc.DotNet.
