### ISSUE TITLE
namespace Vlc::DotNet::Core::Medias; has no member "Medias"

### ISSUE THREAD

**Issue by Prakash19921206** [ZeBobo5/Vlc.DotNet#133]
Hello everybody
wanted to try vlc in winforms(c++/cli)
I downloaded Vlc.DotNet and double clicked on "Build.bat"
it created dll's for various version of dot net (from v2 to v4.5)
among them i could only add reference to v2, if i choose any version above 2, it shows error and will not add to reference.
so after choosing v2, i have no issue for 

using namespace  Vlc::DotNet::Core;
using namespace Vlc::DotNet::Core::Interops;
but for 
namespace Vlc::DotNet::Core::Medias;  it shows error for this line
Core has no member "Medias"

any suggestions?

Thanks

with regards
-Prakash

**Comment by rafaelkan** [comment]
Medias??? or Vlc.DotNet.Core.VlcMedia?

**Comment by Prakash19921206** [comment]
Hi rafaelkan,
Thanks for replying.
in tutorials i see Vlc.DotNet.Core.Medias;
but i see error for both 
Vlc.DotNet.Core.Medias;  and Vlc.DotNet.Core.VlcMedia;

may be its available in other .net framework build, but for .net 2.0 i think its not available..
Is ther any work around?
Thanks
with regards

**Comment by rafaelkan** [comment]
If you download the whole project you have a sample with every Framework

**Comment by BuildSoftwareBetter** [comment]
Have you get Vlc.DotNet.Core.Medias?me got this error too.I can not playing RTSP media source.

**Comment by adeellhr786** [comment]
buildsoftwareBetter i have got same both issue you are facing 
1) try running it with x86 solution platform then it will stream RTSP
but it doesnt runs on x64 :/
please fix this

**Comment by jeremyVignelles** [comment]
I think that the tutorial was made for an older version of Vlc.DotNet that has been replaced by this one.

Since this is an old issue, I'm closing this, but feel free to reopen if you still need assistance.
