### ISSUE TITLE
Win32Exception when path to vlc-dlls contains special characters

### ISSUE THREAD

**Issue by ps-mzamette** [ZeBobo5/Vlc.DotNet#134]
We encountered a Win32Exception when loading the libvlc dlls (at Vlc.DotNet.Core.Interops.VlcInteropsManager..ctor) in case the path to the dlls contains any special character like `&-äöüâ^°汉语`.

To fix this issue, we added the `CharSet = CharSet.Unicode` property to the `[DllImport]` Attribute of the LoadLibraryFunction (at Vlc.DotNet.Core.Interops.Win32Interops). Now it looks like this:

``` csharp
[DllImport("kernel32", SetLastError = true, CharSet = CharSet.Unicode)]  
public static extern IntPtr LoadLibrary(string lpFileName);
```

I think its a good idea in general to add this property to the DllImport. At least in case the arguments could contain special characters. What do you think?

Thanks

**Comment by ZeBobo5** [comment]
Charset Will set to Ansi

**Comment by jeremyVignelles** [comment]
Is this still an issue? If yes, could you make a PR?

**Comment by jeremyVignelles** [comment]
Closing this for now, feel free to reopen if this is still an issue.
