### ISSUE TITLE
Bug VLC with mouse

### ISSUE THREAD

**Issue by rafaelkan** [ZeBobo5/Vlc.DotNet#136]
Hi all, I have the following problem:

I'm developing a .NET application for Windows, specifically a video wall and when I have the mouse on one of the video controls and stops via a Timer lets me working.

I returned the following error: The CLR has been unable to transition from COM context 0x826c08 COM 0x826d78 context for 60 seconds.

Important: If I do not have the mouse over the video it works perfectly.

I'm sorry for my English

**Comment by 7ASecond** [comment]
This means you are not or the control is not allowing messages to flow properly... try using a Application.DoEvents(); in your timer or whilst you are stopping the video.
That may help to pump the messages again.

**Comment by rafaelkan** [comment]
Thank you put it before the stop and perfect:

`Application.DoEvents();`
`this.vlcControl.Stop();`

**Comment by 7ASecond** [comment]
You are welcome.
