### ISSUE TITLE
how to select device (webcam) for directshow

### ISSUE THREAD

**Issue by jjr-amit** [ZeBobo5/Vlc.DotNet#139]
Hi,

when I am using the following code, I always get the output from the first device and not from the the selected cam. I have tested the option in VLC and it works.

```
var camoptions = new string[] { string.Format(" :dshow-vdev=\"{0}\"", "Microsoft® LifeCam HD-3000") };
myControl.MediaPlayer.Play(new Uri("dshow://"), camoptions);

```

PLEASE HELP !!!! Its urgent that I achieve this functionality.

Everything else works fine,

Thanks in advance.

**Comment by ZeBobo5** [comment]
Your problem is not a Vlc.Dotnet one but about VLC options syntax. You can find help on the [VideoLAN Forums](https://forum.videolan.org/)
