### ISSUE TITLE
Application using Vlc.Net crashes on exit

### ISSUE THREAD

**Issue by asavartsov** [ZeBobo5/Vlc.DotNet#14]
I'm using Vlc.Net for 2.1 and it runs fine but when I exit application I get exception about is_playing function not found (apparently exception caused by Dispose method which is checking for media playing and stopping it). I tried to debug it and seems that interops manager really doesn't have this method to the time of dispose. Maybe Dispose called twice or some disposing race is occuring.

**Comment by ZeBobo5** [comment]
Yes, I know it on all versions, but I don't have time to correct it soon. If you have correction, I'll be happy to add this :)

**Comment by asavartsov** [comment]
Thanks! I did not come with anything better than random try-catches, I'm glad you fixed this!

**Comment by ayezutov** [comment]
Guys,

I still see the same exception coming from `ReleaseMediaPlayer` method.

Is it possible that the following code actually throws and exception?

     finally
     {
           mediaPlayerInstance.Pointer = IntPtr.Zero;
     }

Or another idea... the code is not marked as `unsafe`. Might it be the case, that some pointers were actually moved around?

**Comment by spsmfd** [comment]
I solved the problem with adding an HandleProcessCorruptedStateExceptions attribute
[System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptions]
        public void ReleaseMediaPlayer(VlcMediaPlayerInstance mediaPlayerInstance)
        {
            if (mediaPlayerInstance == IntPtr.Zero)
                return;
            try
            {
                GetInteropDelegate<ReleaseMediaPlayer>().Invoke(mediaPlayerInstance);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debugger.Log(0, "Exception", "Vlc.DotNet.Core.Interops.VlcManager.ReleaseMediaPlayer threw an Exception: " + ex.Message + Environment.NewLine);
            }
            finally
            {
                mediaPlayerInstance.Pointer = IntPtr.Zero;
            }
        }
