### ISSUE TITLE
Get VideoSource from VlcControl

### ISSUE THREAD

**Issue by anhlunnhaque** [ZeBobo5/Vlc.DotNet#140]
Does this new/re-write have a way to get the VideoSource like the old project? I use the below in the old project.

VlcControl _vlcControl = new VlcControl();
ImageSource imgSrc = _vlcControl.VideoSource;

Thanks.

**Comment by higankanshi** [comment]
VLC.DotNet is using HWND to display media, so you can't get VideoSource.  
But if you using WPF, you can see my project [xZune.Vlc](https://github.com/higankanshi/xzune.vlc).

**Comment by jeremyVignelles** [comment]
There is no way to get the VideoSource, since the video is rendered directly. I'm closing this since this is an old issue, feel free to open a new issue if you have any other question
