### ISSUE TITLE
Set audio track/streams

### ISSUE THREAD

**Issue by anhlunnhaque** [ZeBobo5/Vlc.DotNet#141]
Hi,

Is there a way to set/toggle the audio track/streams where the file have multiple audio tracks? Ex: a movie with Track 1 is Spanish and Track 2 is English. I want to set to Track 2.

I've tried:
myControl.MediaPlayer.Audio.Tracks = 2 <-- this error 'Vlc.DotNet.Core.IAudioOutputsManagement.Tracks has no setter'

Thanks.

**Comment by ZeroHackeR** [comment]
+1

`player.Audio.Tracks` is where we can get tracks information only.
 
There is already a low level function for doing this. I still couldn't find a way to call it from control.

https://github.com/ZeBobo5/Vlc.DotNet/blob/master/src/Vlc.DotNet.Core.Interops/VlcManager.SetAudioTrack.cs

**Comment by ZeroHackeR** [comment]
player.Audio.Tracks.Current is where you got to set the track

**Comment by jeremyVignelles** [comment]
Closing this as a solution has been provided. Feel free to reopen if more help is needed.
