### ISSUE TITLE
Working with Xamarin

### ISSUE THREAD

**Issue by Firlefanz** [ZeBobo5/Vlc.DotNet#142]
Hello,

I want to develop a Streaming Player for Xamarin. 
Does Vlc.DotNet work with Xamarin?
Is there a Control for it? I just saw the WPF sample...

Thanks a lot,

Firlefanz

**Comment by jeremyVignelles** [comment]
Short answer: not yet.
Long answer:  Current plans include migrating the core libraries to netstandard. Then, new video output components can be added, like Xamarin. Feel free to contribute or join the gitter discussion : https://gitter.im/Vlc-DotNet/Lobby
