### ISSUE TITLE
VlcControl is always on the top of my window

### ISSUE THREAD

**Issue by Sergey-Maystrenko** [ZeBobo5/Vlc.DotNet#143]
Hi 

I hosted WinfForm VlcControl in wpf app, and used for WindowsFormsHost it. 
I have one problem, VlcControl is always on the top of my window, but I need to move it to the background 

How can I do this? 
Thanks in advance.

**Comment by higankanshi** [comment]
This is airspace issue of the HwndHost and WindowsFormsHost.
If you using WPF, I recommend my project [xZune.Vlc](https://github.com/higankanshi/xZune.Vlc).
It provide a "Native" WPF control and noairspace issue .

**Comment by Evilpaule** [comment]
Is there a plan to fix this issue?

**Comment by jeremyVignelles** [comment]
Yes, there is now a plan to fix this issue: #296
