### ISSUE TITLE
VLC Direct3D Output Window came out

### ISSUE THREAD

**Issue by ZeroHackeR** [ZeBobo5/Vlc.DotNet#145]
VLC Direct3D Output Window came out randomly 

Vlc.DotNet.Core Version: 2.1.115.0

![20160220_190019](https://cloud.githubusercontent.com/assets/3157700/13276663/0b82a718-daf0-11e5-8d4a-3c1c02c91c18.jpg)

**Comment by jeremyVignelles** [comment]
Please retry with a newer version of libvlc (don't remove any plugins). I don't think this is specific to Vlc.DotNet
