### ISSUE TITLE
ProjectM Visualization presets wont load

### ISSUE THREAD

**Issue by spektor56** [ZeBobo5/Vlc.DotNet#146]
The following command line arguments work from the command prompt:

--projectm-preset-path="C:\Program Files\VideoLAN\VLC\visualizations\presets_milkdrop" --audio-visual=projectm

When the arguments are used in windows forms, the correct visualization is loaded but the presets are not.

**Comment by spektor56** [comment]
Nevermind, got it working with a path without spaces.  It seems this property doesn't like quotes being in the option...  It's still broken for paths with spaces in them though.  Will leave this here for anyone running into the same problem...

**Comment by jeremyVignelles** [comment]
Can you launch vlc from the cli and have your expected output? I'd recommend that you open your own issue or that you come on gitter so that we don't forget to help you
