### ISSUE TITLE
How I can set subtitles

### ISSUE THREAD

**Issue by Excalib65** [ZeBobo5/Vlc.DotNet#147]
Hi,
I'm trying to enable the a subtitle track with the Winform Control.
I can count the number of subtitle tracks by using;

```
        int numSbtitles = myVlcControl.SubTitles.Count;
```

but I cannot set the first track by using:

```
        myVlcControl.SubTitles.Current = myVlcControl.SubTitles.All.First();
```

I obtain an error even if I try to read the ID property (or the Name property) of one of the subtitles track.
Someone could help me?

**Comment by boom1492** [comment]
try it below.
 myVlcControl.SubTitles.Current = myVlcControl.SubTitles.All.First(o=>o.ID == YOUR_SUB_ID);

**Comment by jeremyVignelles** [comment]
Closing as this is an old issue, feel free to reopen if needed
