### ISSUE TITLE
Setting the audio output to specific card?

### ISSUE THREAD

**Issue by JackRyder** [ZeBobo5/Vlc.DotNet#152]
Hi!

I've just learnt of this and am interested in using it to play youtube videos, but I can't figure out where I can set the output device and I can't find the documentation. If you could point me in the right direction I should hopefully be able to get it from there!

Thanks,

**Comment by jeremyVignelles** [comment]
Did you manage to do this with vlc in command line? If yes, just pass the same arguments to your vlc control before it has finished being initialized.
