### ISSUE TITLE
Error Playing an RTSP stream with 64 bit VLC Libs

### ISSUE THREAD

**Issue by nathanhanson** [ZeBobo5/Vlc.DotNet#153]
Apologies if this is a dup. I searched before submitting but didn't see anything similar.

I've created a 64 bit test app very similar to the one that ships with the Vlc.DotNet source. However, when I set the path to my VLC libs in my VlcControlNeedsLibDirectory and then call Play with the URL to my RTSP stream, I get an EncounteredError event.

This does not happen when I create a 32 bit test app and use 32 bit VLC libs. I'm able to work around this for now because VLC can open the stream when I place the libs and the plugins folders directly into the app's working directory. It's just when I place the dlls and plugins elsewhere and try to set the path that I see the error. Might be worth looking into.

As an aside, I'm not able to see what type of error I'm getting because EncounteredError gives me an args object with no properties on it. Hopefully, this will be fixed in a future version too. Thanks!

**Comment by adeellhr786** [comment]
yes there is a bug with using 64 bit architecture and 64 lib 
while playing RTSP stream 
i simply gave path of RTSP stream according to my network (  myVlcControl.Play(new Uri("rtsp://admin:123456@192.168.1.100:7070"));),
when i play it as 32 bit it goes fine
but when i select 64 bit it does not
there is a bug please Fix it

**Comment by jayson8121** [comment]
update 64bit vlclib to newest。 can play RTSP stream with 64 bit.
i tested.

http://mirror.lstn.net/videolan/vlc/2.2.3/win64/vlc-2.2.3-win64.7z
