### ISSUE TITLE
Unable to capture mouse events on Vlc.DotNet.Wpf.VlcControl

### ISSUE THREAD

**Issue by tombby11** [ZeBobo5/Vlc.DotNet#154]
I am trying to capture mouse events on the control "Vlc.DotNet.Wpf.VlcControl"  but i was not able to do so. 
I have also noticed that nothing can come on top of this control. As I have tried to have an transparent stackpanel , but then I have discovered that the panel always come below the VLC control

**Comment by SkinnySackboy** [comment]
I've got exactly the same problem, which also means context menus do not work. Did you ever find a workaround for this problem?

**Comment by tombby11** [comment]
Well I used another repository for VLC  , and I pasted the problem there and i got an answer  
https://github.com/higankanshi/Meta.Vlc/issues/104
check it out :)

**Comment by SkinnySackboy** [comment]
Nice, thanks, I think I'll switch too.

**Comment by jeremyVignelles** [comment]
A possible workaround for the Airspace issue : https://stackoverflow.com/questions/5978917/render-wpf-control-on-top-of-windowsformshost/23662410#23662410

You can follow the status of this project about airspace issue in #296 . I'm closing this, feel free to reopen if needed.

**Comment by mfkl** [comment]
That link is an issue from another project. Open a new issue with a repository reproducing the problem.
