### ISSUE TITLE
Calling "Stop" to load another video freezes

### ISSUE THREAD

**Issue by pinndulum** [ZeBobo5/Vlc.DotNet#155]
Freeze occurs at Vlc.DotNet.Core.Interops\VlcManager.Stop.cs GetInteropDelegate<Stop>().Invoke(mediaPlayerInstance)

I have been testing with Vlc.DotNet.Wpf.Samples - CLR 4 - .Net 4.5

To get Vlc to freeze:
1- Modify `OnPlayButtonClick` method to load file path from an OpenFileDialog box.

``` c#
private void OnPlayButtonClick(object sender, RoutedEventArgs e)
{
     var fd = new Microsoft.Win32.OpenFileDialog { Filter = "Video Files|*.mpg;*.mp4;*.m4v;*.avi" };
     var result = fd.ShowDialog(this) ?? false;
     if (!result)
          return;
     var filePath = fd.FileName;
     if (myControl.MediaPlayer.State == Core.Interops.Signatures.MediaStates.Playing)
          myControl.MediaPlayer.Stop(); // causes deadlock!
     myControl.MediaPlayer.Play(new FileInfo(filePath));
}
```

2- Start Wpf application and click "Play" button, choose a local file and click "Open"
3- After the video begins to play click the "Play" button again to choose another local file and click "Open"
4- The video screen will freeze on the initial file and the subsequent file does not start.

**Comment by pinndulum** [comment]
Also: If the video is stopped before showing the OpenFileDialog loading the next file operates as expected.

**Comment by tombby11** [comment]
I feel it is kind of natural to stop the player before switching the source, but you are right , probably this should be embedded in Play method

**Comment by pinndulum** [comment]
There are a myriad of contradictory and inconclusive search results for "libvlc_media_player_stop deadlock". I believe that this is the root problem.

Media loading completes as expected when the following code block within `OnPlayButtonClick` is replaced with a thread that calls the Stop method.

replace:
```c#
if (myControl.MediaPlayer.State == Core.Interops.Signatures.MediaStates.Playing)
{
     myControl.MediaPlayer.Stop(); // causes deadlock!
}
```

with:
```c#
if (myControl.MediaPlayer.State == Core.Interops.Signatures.MediaStates.Playing)
{
     var thread = new System.Threading.Thread(delegate() { myControl.MediaPlayer.Stop(); });
     thread.Start();
}
```

Actually there is another issue #4 that addresses a similar problem, and has the same solution.

However this doesn't help me within my actual code. It makes no difference if I make a call from another thread started from an event callback, or on the Main\Dispatcher thread, or anywhere else I can think of. I always get a deadlock when calling Stop! For this reason, I have been forced to abandon this project in favor of Vlc's active x control.

**Comment by Insire** [comment]
Removing the OpenFileDialog from the Event should fix the issue. Try selecting the new file outside that click event. Maybe add another button.  The reason why you get that issues is most likely the dialog blocking your synchonous operation, which most likely the playback is part of aswell.

**Comment by jeremyVignelles** [comment]
This is an old issue and I am closing this because a lot of work has been done since then.

As a general rule of thumb, don't attempt to call Vlc methods from the vlc callback thread. Use `ThreadPool.QueueUserWorkItem` or `Task.Run()`
