### ISSUE TITLE
How to enable deinterlacing?

### ISSUE THREAD

**Issue by moson-mo** [ZeBobo5/Vlc.DotNet#156]
Hi,

I'm trying to enable deinterlacing with yadif2x.

I tried things like this:

> string[] options = new string[]
>             {
>                 "--video-filter=deinterlace",
>                 "--deinterlace-mode=yadif2x"
>             };
>             vlcControl1.Play(new Uri("..."), options);

But it doesn't work.

Can anyone tell me which options I need to set to get deinterlacing working?

thanks,
moson

**Comment by jlamitie** [comment]
This worked for me...
                string[] _strMediaOptions = new string[] { "--video-filter=deinterlace" };
                Vlc.DotNet.Forms.VlcControl vlcMovie = new Vlc.DotNet.Forms.VlcControl();
                vlcMovie.VlcMediaplayerOptions = _strMediaOptions;
