### ISSUE TITLE
VlcControl doesn't play youtubevideos

### ISSUE THREAD

**Issue by Insire** [ZeBobo5/Vlc.DotNet#157]
I got the local playback working, but i couldn't figure out what to submit to playback youtube videos. I tried the following: [download url](https://r18---sn-5hne6nl7.googlevideo.com/videoplayback?mime=audio/webm&key=yt6&sver=3&dur=432.029&clen=6502519&nh=IgpwcjAzLmFtczE2KgkxMjcuMC4wLjE&fexp=9416126,9416891,9417828,9420452,9422596,9423329,9423640,9423662,9425281,9425956,9427902,9428399,9428661,9431711,9432135,9432684,9433302&ipbits=0&sparams=clen,dur,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,nh,pl,requiressl,source,upn,expire&lmt=1401685874347652&keepalive=yes&source=youtube&initcwndbps=1581250&requiressl=yes&gir=yes&itag=171&pl=18&ip=91.7.201.183&mm=31&mn=sn-5hne6nl7&ms=au&mt=1459693003&mv=m&upn=o8WdzygW5eI&id=o-AAihW7a2SJ7Kum54DcCnWvR8nPXk80QEkWxGdH5bdeKR&signature=C5383E9833B7123EFECD7208615391BE878ED471.AA45AFA056D9F83BCCA0E345C9034BF9DEA1943B&expire=1459714817&ratebypass=yes
) and [normal url](https://www.youtube.com/watch?v=0ypeOKp0x3k). 

Did i miss anything? You can check my code @[github.com](https://github.com/Insire/InsireBot-V2) Should work right out the box, when you have a local copy of vlc installed.

**Comment by Evilpaule** [comment]
Try this one : https://github.com/flagbug/YoutubeExtractor for getting the complete uri

**Comment by Insire** [comment]
In fact i used exactly that to get the download url after using the normal url didnt work out for me. Sadly the result wasnt any different.

But i saw a pull request, handling something similar, being merged earlier today. So i gonna check that out later today and report back.

**Comment by Insire** [comment]
Just figured out how to get VlcDotNet to playback youtube videos. 

As Evilpaule suggested you need flagbug to get the mrl of the youtubevideo. Not exactly sure why that is, since an earlier version of VlcDotNet could parse an url of a video on youtube. Also making the sample use a current version of Vlc, instead of the libraries provided in the lib folder seems to be crucial aswell. Since i could only download an x86 build from videolan.org i had to switch the architecture of the wpf sample app to x86 too.
