### ISSUE TITLE
Capture video and/or stream

### ISSUE THREAD

**Issue by LightbringerX** [ZeBobo5/Vlc.DotNet#158]
Hi there

Currently I'm doing some testing stuff with vlc.dotnet. In the past i've used vlc directly to do some video streaming plus capturing the shown videostream to harddisk. As far as i've seen its possible to capture a screenshot while playing a video. is it possible to capture a running video to harddisk while watching it?

**Comment by CliffConway** [comment]
Could I clarify that i understand your issue.
You said that in the past you have managed to use vlc directly to stream and capture to harddisk.
And your question is I presume trying to determine if it is possible using vlc.dotnet to do the same thing.
Is my assumption correct?
I am new to vlc.dotnet and I am trying to achieve what I presume your are trying to achieve. I have just started my testing and I must admit that the lack of documentation and examples is really frustrating. Maybe we could collaborate to achieve this goal. Let me know if you are interested.

**Comment by LightbringerX** [comment]
Thats exactly what I inteded to say.
the point is that im new to vlcdotnet AND programming in general thus i may not be able to help alot in this situation :/

**Comment by jeremyVignelles** [comment]
Please try opening VLC from command line and play with that option : 
`--sout="#duplicate{dst=std{access=file,mux=ts,dst='test.avi'},dst=display}"`

Once you're satisfied with the result, take the sample code in this repository and add this as an argument. That should do the same.
