### ISSUE TITLE
Moving Forward

### ISSUE THREAD

**Issue by spoiledtechie** [ZeBobo5/Vlc.DotNet#16]
Hey ZeBobo5,

Im working on a application that will be using this wrapper.  Its a great piece of code by the way.  I was wondering what your doing moving forward?  As I would like to push pull requests your way, but you declined mine.  So I am wondering whats going on?

Can I help push this wrapper?

**Comment by ZeBobo5** [comment]
I just minimize the repository. Audio & video samples was added and branch architecture was not optimal to update code.

Now, you've got the master branch as the current version of Vlc libraries, and a branch by old version of it.

Sorry for the inconvenience. I'm not 100% on this project and I need help for contribution and I'm happy for yours.
