### ISSUE TITLE
Right down to the Frame

### ISSUE THREAD

**Issue by spoiledtechie** [ZeBobo5/Vlc.DotNet#161]
I have been using this player in our application for almost a year.  A new requirement was to be able to get the position to send the position back every frame.

Right now, the player from what I can gather only sends an updated position every 1/5 second.  Instead, I need it to send back ever 1/30th second. Is this doable or is this outside the bounds of VLC entirely?

Thanks!

**Comment by jeremyVignelles** [comment]
To be checked, but I think this is an expected limitation of libvlc.

**Comment by mfkl** [comment]
Yeah, not sure about this. Maybe you can hack around the API ([for example](https://stackoverflow.com/questions/11236432/how-do-i-get-libvlc-media-player-get-time-to-return-a-more-accurate-result)). Probably not accurate but maybe accurate enough for your use case? Let us know.

**Comment by jeremyVignelles** [comment]
Thanks for the workaround, I'm closing this for now, please let us know if anything else is needed.
