### ISSUE TITLE
VlcControl Time version 2.

### ISSUE THREAD

**Issue by antferr** [ZeBobo5/Vlc.DotNet#162]
In version 1.x Vlc.DotNet.Forms.VlcControl had **Time** property where Time was a Timestamp. 
In the 2.x version it is a long. 
It has changed the meaning of the property? 
What is the Time property expressed as long?

**Comment by lzinga** [comment]
Thought it had to do with ticks because you can do TimeSpan.FromTicks(long) but that doesn't even seem to be the case.

Even when looking at the Duration of the current media element doesn't actually seem like anything that could relate to something.

**Comment by ne0ge0** [comment]
I set the position in the track using Time from a slider, where the maximum value of the slider is found by:

`sliderPosition.Maximum = vlcControl.GetCurrentMedia().Duration.TotalMilliseconds;`

The position is then set using the value of the slider on the MouseUp event:

`long thePosition = Convert.ToInt64(sliderPosition.Value, CultureInfo.CurrentCulture);`
`vlcControl.Time = thePosition;`

**Comment by lzinga** [comment]
The Duration is no longer a TimeSpan it is a long which doesn't seem to relate to any type of time

**Comment by ne0ge0** [comment]
On inspection, it seems to be populated on or after Play() is called.

**Comment by jeremyVignelles** [comment]
Closing this as this is an old issue, and answers have been provided. Please open a new issue if there are further questions
