### ISSUE TITLE
Choppy video using webcam input

### ISSUE THREAD

**Issue by bbuckwal** [ZeBobo5/Vlc.DotNet#163]
I'm getting some very choppy, low framerate video when I use webcam input. Performance is fine when I stream a video. Also using the same webcam the video performance is fine when using the normal VLC app. Any ideas?

---

string[] camOptions = new string[] { @" :dshow-vdev=Logitech HD Pro Webcam C920 :dshow-adev=Microphone (HD Pro Webcam C920) :dshow-size=320x240 :live-caching=300" };
MediaPlayer.SetMedia(new Uri(@"dshow://"), camOptions);

**Comment by salihkaragoz** [comment]
I faced some problems too. It's near to yours. I didn't start dshow:// in the VLC.DotNet project. I think if I did not add options, the options will be the default. Am I wrong?

**Comment by jeremyVignelles** [comment]
This is an old issue, I'm closing this for now.
If you really want this to be solved, could you try again with libvlc 3.0 and send logs?
