### ISSUE TITLE
Takesnapshot freeses app.

### ISSUE THREAD

**Issue by vwa-software** [ZeBobo5/Vlc.DotNet#166]
Hello,

I want to take a snapshot like this:

```
if (myVlcControl.IsPlaying)
            {
                myVlcControl.Pause();
            }

            myVlcControl.TakeSnapshot(@"F:\Apps\WebCam\foto.jpg");
```

But unfortunately i keep getting this message:`swscaler decrepated pixel format used` , then the application hangs.

I tryed to debug and came to this point in VLCManager.Takesnapshot.cs
`
GetInteropDelegate<TakeSnapshot>().Invoke(mediaPlayerInstance, 0, file.FullName, width, height);
`
It goes into the TakeSnapshot function then does nothing.

Am i doing something wrong, or is this a bug?

Tanks in advance.

ps, despite of the message, the image is saved correctly to the path.

**Comment by vwa-software** [comment]
Note: When i use the sample url : http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi

I get no warning, but the app still freezes

The warning is when i stream from a rtsp url

**Comment by Prakash19921206** [comment]
in winform also its freezing user interface..
myVlcControl.TakeSnapshot("path to image.jpg");
this freezes UI (no app not responding message, no error message in console or visual studio outout) 
anybody solved this issue?

**Comment by ZeBobo5** [comment]
Try to use it in new thread

**Comment by jeremyVignelles** [comment]
probably a deadlock on vlc side if used from the same thread?
I'm closing this since an answer has been provided
