### ISSUE TITLE
VlcControl.Stop() deadlock and freeze application!

### ISSUE THREAD

**Issue by EduardoBicudo** [ZeBobo5/Vlc.DotNet#167]
Hi my Friends!
I need for a HUGE help in my project...

I'm trying to connect in RTSP from IP's cam, vlc.DotNet connect fine, but when system try close the connection with the Cam, the application freeze in Stop() method and app stop to respond.

My Code:
`Private Sub FinalizaForm()`
        `Me.VlcControl1.Pause()`
        `Threading.Thread.Sleep(200)`
        `Me.VlcControl1.Stop()`
        `Me.Dispose()`
    `End` Sub

And sequence play other video from other Cam.... The application freeze in me.VlcControl1.Stop(), but i use more complex code to do it, i believe this is a BUG in VLC, i did try with ActiveX Com, then i catch the same problem...

Tks to Help ;)

**Comment by jeremyVignelles** [comment]
Hi,
I'm sorry that this issue has been unnoticed for such a long time.
I suspect that this code has been called from a Vlc callback. If this is the case, please call this from another thread.

Also, please try with VLC 3.0

I'm closing this for now, feel free to reopen if this is still an issue.

**Comment by lehne** [comment]
I used SetMedia("") before disposing and that seemed to fix it.
