### ISSUE TITLE
inifinite Loop when setting VLCControlMediaPlayer.Time

### ISSUE THREAD

**Issue by etiqmedia** [ZeBobo5/Vlc.DotNet#169]
Hi!

My control enters in an infinite Loop repeating a few seconds of the video when I set the VLCControlMediaPlayer.Time to a position in milliseconds. It happens in a random fashion, most of the time it doesn't happen. 

Someone is having this same problem? Any ideas?

Thanks!

**Comment by mattivaan** [comment]
I think I have encountered the same problem. I noticed it when creating a UI that has a "back" button that seeks back n seconds. 

`vlcControl1.Time = timeMs;`

If this button is clicked quickly it will freeze the program.

Does this issue happen to you only when the media is in state "playing" or also when it is stopped.

**Comment by jeremyVignelles** [comment]
Looks like an issue in libvlc itself. Did you try with latest libvlc 3.0?
I'm closing this for now, feel free to reopen if more help is needed, by providing the version of libvlc you are using.
