### ISSUE TITLE
Get Client point from video point

### ISSUE THREAD

**Issue by sandeepkrs** [ZeBobo5/Vlc.DotNet#171]
Hi. Thanks for your wonderful control.
Is there any method to get Client screen point (the point on vlcControl where a particular video pixel is displayed) by specifying video pixel point.

There are methods available like PointToClient() and PointToScreen()

but I need methods like 
VideoPointToClient()
 and 
PointToVideo()

Is there any way to achieve this?

**Comment by jeremyVignelles** [comment]
These methods cannot be implemented because of the lack of these methods in the underlying `libvlc` API (please reopen if I'm wrong)
