### ISSUE TITLE
Cannot set ContextMenu on VlcControl

### ISSUE THREAD

**Issue by SkinnySackboy** [ZeBobo5/Vlc.DotNet#173]
When using the WPF VLC player (but also the WinForms) version, there appears to be a bug in that you cannot set a context menu.

**Comment by SkinnySackboy** [comment]
When using the WPF VLC player (but also the WinForms) version, there appears to be a bug in that you cannot set a context menu.

**Comment by jeremyVignelles** [comment]
For WPF, this is what is called the "airspace issue" (#296 ). The new 3.0 WPF control does not have this issue.

For winForms, we should implement `libvlc_video_set_mouse_input`, but this is tracked by  #379
