### ISSUE TITLE
Play RTMP Stream

### ISSUE THREAD

**Issue by Bramreiter** [ZeBobo5/Vlc.DotNet#175]
Hey All, 

Is there a Change to Play a RTMP Stream Through VLC.Net 

When i Play normal Video from the Filesystem it works. 
When i put a RTMP Url in VLCONTROL.PLAY(RTMPURL) it doesn't work.

Is that supportet ? What did i wrong

**Comment by jeremyVignelles** [comment]
Is that supported in VLC? Can you do it with the command line? If yes, then feel free to reopen this issue with the command you invoke to make VLC play that.
