### ISSUE TITLE
How to set change various filters ?

### ISSUE THREAD

**Issue by rmorejon** [ZeBobo5/Vlc.DotNet#179]
I set VlcMediaplayerOptions :

```
this.vlcControl1.VlcMediaplayerOptions = new string[]
                                        {
                                                    "--video-filter=adjust",
                                        }; 
```

then it allows me:
            this.vlcControl1.Video.Adjustments.Brightness = (float)1.5;
            this.vlcControl1.Video.Adjustments.Contrast = (float)1.5;

But if I want to rotate the video played:

```
        this.vlcControl1.VlcMediaplayerOptions = new string[]
                                                  {
                                                    "--quiet",
                                                    "--video-filter=transform",
                                                    "--transform-type=90"
                                                  };
```

no working VlcMediaplayerOptions once initialized control,  I can change filters with the video playing ??

**Comment by jeremyVignelles** [comment]
You can't change the VlcMediaPlayerOptions after the component has been initialized. Maybe an API is missing on our side.

If you really want something to be implemented, please reopen.

**Comment by TPWomed** [comment]
I would also need the ability to set multiple filters (adjust, transform). Can you add this feature?

**Comment by jeremyVignelles** [comment]
You should already be able to set multiple filters, as you would do in the VLC command line. This issue was about modifying options after the video has started.

Is there something that you feel is missing?

**Comment by TPWomed** [comment]
Thanks for Your answer. You are right, I can set several filters (as in the command line of VLC). Is there a way to turn or flip the live video (during playback)? This option would be very interesting for me.
Thank you in advance.
