### ISSUE TITLE
VlcControl cant set audio output device

### ISSUE THREAD

**Issue by wrickout** [ZeBobo5/Vlc.DotNet#180]
Is there an options to set audio device to my prefered device?
If there is a documentation or sample program, i sos need that!
Thanks!

**Comment by wrickout** [comment]
param as  stringcollection
param.Add("--aout=directsound")
param.Add("--directx-audio-device=" + DAudioList.Item(ComboBox3.SelectedIndex).deviceID)
// with debug.print it shows the right option in param

VlcControl1.SetMedia(New IO.FileInfo("c:\Documents\test.avi"), New String() {param(0), param(1)})
VlcControl1.Play()

if i put these two param directly to vlcmediaplayeroption property in design view then it works.
What i did wrong?

**Comment by jeremyVignelles** [comment]
You need to pass the parameters as VlcMediaPlayerOptions (not media options), before the component has finished being initialized.
