### ISSUE TITLE
Volume Change Halts Execution

### ISSUE THREAD

**Issue by ne0ge0** [ZeBobo5/Vlc.DotNet#181]
After Play() is called, and during the PositionChanged event on the VlcControl, attempting to change the volume causes the application to halt, without error, during debug:

```
private void vlcControl1_PositionChanged(object sender, VlcMediaPlayerPositionChangedEventArgs e)
{
    ...
    vlcControl1.Audio.Volume = 100; // Execution halts after this point
    ...
}
```

Any advice greatly appreciated.
- Vlc.DotNet version: 2.1.126.0
- .NET Framework versions tried: 4, 4.5, 4.6, 4.6.1
- VLC version: 2.2.4
- Visual Studio 2015, update 3
- Windows 10 Professional

**Comment by jeremyVignelles** [comment]
Did you try to change the volume in another thread?

Something like:
```
ThreadPool.QueueUserWorkItem(() => vlcControl1.Audio.Volume = 100);
```

**Comment by jeremyVignelles** [comment]
Closing this since an answer has been provided and one year and a half has passed.
