### ISSUE TITLE
DVB-T over network

### ISSUE THREAD

**Issue by lordbarba** [ZeBobo5/Vlc.DotNet#182]
Hi All, 
i've read documentation and made some tests, but i didn't figure out:
- how can i set a dvbt source (and change its setting)
- how to stream my playing session (something like the commandline 
  `:sout=#transcode{vcodec=h264,acodec=mpga,ab=128,channels=2,samplerate=44100}:http{mux=ffmpeg{mux=flv},dst=:8080/} :sout-keep`

Thank u all
Leonardo

**Comment by ZeBobo5** [comment]
Your problem is not a Vlc.Dotnet one but about VLC options syntax. You can find help on the [VideoLAN Forums](https://forum.videolan.org/)
