### ISSUE TITLE
 you give me the vlc build configure?

### ISSUE THREAD

**Issue by luoqi123** [ZeBobo5/Vlc.DotNet#184]
i want build vlc by myself.
so can you give me the vlc build configure(that you used to build).
like this:

```
../configure --host=i686-w64-mingw32 \
--disable-ffmpeg \
--disable-live555 \
```

**Comment by jeremyVignelles** [comment]
you're on the wrong repository for that, please check https://wiki.videolan.org/Category:Building/ and the videolan IRC channel
