### ISSUE TITLE
Is possible overlay a message on VlcControl?

### ISSUE THREAD

**Issue by wuzuxing** [ZeBobo5/Vlc.DotNet#185]
Recently, I got a problem when I am using Vlc.Dotnet.Wpf. I try to display some message when the video was playing, so I using an extra control to flow over the VlcControl. In the design mode, I could see the message correctly, but when the application was running, the message was gone.
So my question is: Is possible overlay a message on VlcControl in WPF project. Thank you for your time, I hope receive your response soon.

**Comment by jeremyVignelles** [comment]
This is the famous "airspace issue", that is now tracked by #296 . In short : you should be able to do this in the future, but not at the time being
