### ISSUE TITLE
set playback speed in winforms

### ISSUE THREAD

**Issue by Prakash19921206** [ZeBobo5/Vlc.DotNet#187]
i am using vlcControl in winforms. its working fine, but the problem is that its playing faster.
i have videos recorded at 10fps. i think vlcControl is playing at 30fps, that's why video are playing faster. Referred this, but it didn't help. i couldn't find any function like `set_play_back_speed` function under vlcControl1.Video
I thought vlcControl would automatically figure out fps & play accordingly.
if i open the same video from vlc media player installed on my windows pc, it plays at proper rate. any clue how to fix this?
Thanks & Regards

P.S: if i open any video recorded at 29.97fps, vlcControl in winforms is playing it at proper speed.

**Comment by jeremyVignelles** [comment]
Which versions of Vlc.DotNet and libvlc are you using? If you still experience this issue after updating both, could you send us a link where we can download a sample video?

**Comment by Prakash19921206** [comment]
This was very old post. we can set speed using `vlcControl1.Rate` . Thanks for your reply..
