### ISSUE TITLE
New here, trying to use wiki, but using pages not opening

### ISSUE THREAD

**Issue by RYG81** [ZeBobo5/Vlc.DotNet#19]
Hi,
I am new here and want use vlc.net in my project.
I am trying to use wiki help, but not able to go ahead here- 

```
Using Vlc.DotNet in WinForms
Using Vlc.DotNet in WPF
```

Both the page links are not opening.

**Comment by ZeBobo5** [comment]
Documentation is not available yet. Repository contains samples projects.

**Comment by RYG81** [comment]
OK
Thanks you very much.
Any other resource to start sir?

**Comment by ZeBobo5** [comment]
No for the moment. I need help to do it :)

**Comment by jeremyVignelles** [comment]
There is now a quite good "Getting started" : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started (humble mode off)
