### ISSUE TITLE
Can't Set VLCLibDirectory

### ISSUE THREAD

**Issue by CaptRR** [ZeBobo5/Vlc.DotNet#190]
I'm running into an odd problem in VB.  I can set the VLCLibDirectory in the control properties in the IDE.  This is great on my development machine and x64 machines, since the VLC directory path is the same.  The problem is on other machines where the path is different.  I tried leaving the VLCLibDirectory blank in the IDE and adding the code below

```
Private Sub Vlc2_VlcLibDirectoryNeeded(sender As Object, e As VlcLibDirectoryNeededEventArgs) Handles Vlc2.VlcLibDirectoryNeeded
    Vlc2.VlcLibDirectory = New IO.DirectoryInfo("C:\Program Files (x86)\VideoLAN\VLC")


End Sub
```

However enven though the sub does run, and writes the Directory into the Vlc2 control, I get the error 

> An exception of type 'System.Exception' occurred in Vlc.DotNet.Forms.dll but was not handled in user code
> Additional information: 'VlcLibDirectory' must be set.

I am kind of scratching my head, it seems I either put the path in the control properties (and then other computers can never have the VLC install directory anywhere else) or it won't run.

Thanks

**Comment by jeremyVignelles** [comment]
As of 2017, we provide a sample code for loading libraries for the right process architecture:
https://github.com/ZeBobo5/Vlc.DotNet/blob/80b9fb5fab8ce4433e4efdcb9a1406b73ac9e240/src/Samples/Vlc.DotNet.Wpf.Samples/MainWindow.xaml.cs#L32-L35

This assumes you are redistributing libvlc with your application (even if it's a little heavy, I'd recommand that way, especially #288). That way, you could redistribute the version of libvlc that you tested on your machine and avoid several issues. Users also won't need to have VLC installed to use your app.

You could also try to detect the OS architecture and go your way.
