### ISSUE TITLE
WPF Sample project works in debug but exe file isn't working

### ISSUE THREAD

**Issue by itaihu** [ZeBobo5/Vlc.DotNet#191]
when I run the WPF sample in debug/release from visual studio (both x64 and x84 compilations) the example works perfectly but when I'm opening the exe file nothing happens..

any idea what's causing it?

Thanks, Itai.

**Comment by jeremyVignelles** [comment]
Could you try it again with latest version? Maybe a wrong library path specified? I'm closing this for now on, please reopen if more help is needed
