### ISSUE TITLE
Possibility to connect to an existing instance of VLC?

### ISSUE THREAD

**Issue by XceSx6** [ZeBobo5/Vlc.DotNet#192]
Is it possible to use this library to connect to an already running VLC Instance?
I'd like to just pass the window or process handle to it and subscribe to events, send play/pause/stop etc commands.
Is it possible with this Library? If so how? So far I've found only examples on how to embed VLC functionality into your own application..
What i want to do is control the already running instance of VLC with this beautiful library.

**Comment by danielwgrech** [comment]
I also have this requirement.  I need to be able to trigger events on certain positions of a video being played in a VLC instance.

**Comment by jeremyVignelles** [comment]
I don't think this is possible with this library. The point of it is to create a new media player to be embedded in an application. You want to connect to an existing instance of VLC. For that, it looks more like a "remote control", and maybe some plugins are available for that. If not, you will probably need to create your own plugin (in C/C++) or create an application with Vlc.DotNet that will expose what you need to your other application.
