### ISSUE TITLE
directx audio device

### ISSUE THREAD

**Issue by karimbusoli** [ZeBobo5/Vlc.DotNet#194]
Hello,
I need to change the output for play the audio of my video.
With the command-line, work if I write:
vlc.exe --directx-audio-device={8D1A226F-07F9-4301-B84A-658A74B017E5} "C:\Users\Public\Videos\Sample Videos\Wildlife.wmv"

how can I make the same behavior with vlc dotnet?

thanks a lot
Karim

**Comment by jeremyVignelles** [comment]
Did you try with `VlcMediaPlayerOptions`?
