### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by raul2015** [ZeBobo5/Vlc.DotNet#197]
An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in Vlc.DotNet.Core.Interops.dll

Additional information: %1 no es una aplicación Win32 válida

**Comment by panchosoft** [comment]
I also have the same problem and I noticed that this started to happen when using VLC Player version 2.2.3 or higher. It doesn't happen in VLC 2.2.1.

**Comment by panchosoft** [comment]
In order to solve this problem, you have to install the 64-bit version of VLC:

http://download.videolan.org/pub/videolan/vlc/2.2.4/win64

And your project should target that platform too.

**Comment by raul2015** [comment]
Even following those leads I get an error: 
{"No se puede cargar el archivo o ensamblado 'Vlc.DotNet.Forms, Version=2.1.126.0, Culture=neutral, PublicKeyToken=84529da31f4eb963' ni una de sus dependencias. Se ha intentado cargar un programa con un formato incorrecto."} 


De: "Francisco I. Leyva" <notifications@github.com> 
Para: "ZeBobo5/Vlc.DotNet" <Vlc.DotNet@noreply.github.com> 
CC: "Raul Perez" <raul2015@zoho.com>, "Author" <author@noreply.github.com> 
Enviados: Sábado, 22 de Octubre 2016 10:45:43 
Asunto: Re: [ZeBobo5/Vlc.DotNet] Getting this error (#197) 



In order to solve this problem, you have to install the 64-bit version of VLC: 

[ http://download.videolan.org/pub/videolan/vlc/2.2.4/win64 | http://download.videolan.org/pub/videolan/vlc/2.2.4/win64 ] 

And your project should target that platform too.

**Comment by jeremyVignelles** [comment]
Please try again with new version of Vlc.DotNet, and following the Getting started wiki. Feel free to reopen if needed
