### ISSUE TITLE
Skip time

### ISSUE THREAD

**Issue by raul2015** [ZeBobo5/Vlc.DotNet#198]
How do I skip the payback to a certain poin, I mean I want to move backward and forward in the video.

**Comment by Hultan** [comment]
I do not know if this is the best or correct way to skip time, but I do it this way :

`videoPlayer.Position += 0.01f;`

You can of course increase 0.01f to a larger number if you want to make a larger skip...I don't remember if 0.01f represents a 1% skip or how it worked, but I do remember looking for a way to skip for example 10 seconds ahead, but I don't think I managed to find a way to do that, and I just settled for the solution above. It was good enough for me at that time anyway...

**Comment by Prakash19921206** [comment]
@Hultan, can we skip to specific time? like 03 min 32 sec  ?

**Comment by Hultan** [comment]
Hi @Prakash19921206 ,

You can do that with this method, yes, but if it is the best (easiest) way I don't know. The Length property contains the length of the video in milliseconds. Use that to calculate how much of the video you want to skip in percent (number between 0 and 1) and set Position to that number.

Example:

Length = 150 000   (video is 2 min 30 secs long)
If you want to skip to, lets say, 1:00 into that video, you will need to calculate the number of milliseconds for 1:00, which is 60 000. Then divide 60 000 / 150 000 and you will get 0,4 which will be your new position, so:

player.Position = 0.4;

/Per

**Comment by Prakash19921206** [comment]
@Hultan, Thanks for your reply.
another quick question. how to skip 1 frame forward & 1 frame backward?
i don't think there is any inbuilt function for this.

**Comment by Hultan** [comment]
I don't know of any funtion that can do that unfortunately.../Per

**Comment by SkinnySackboy** [comment]
There might be a way to do with with VlcManager, but not quite sure how to use it (as per here http://stackoverflow.com/questions/30028851/using-vlcmanager-with-last-version-of-vlc-dotnet)

**Comment by Prakash19921206** [comment]
@SkinnySackboy , thanks for your reply. i had visited that question long time ago (saw my upvote!)
one work around to skip single frame is by calculating total time then time for 1 frame..

I had 1 more issue in .net
I used .net component `track bar `to skip time. i registered with mouse wheel event. the only issue here is that if i scroll mouse twice, only then video will skip, if i scroll once then track bar will jump but it will immediately revert to previous position..i think its to do with code.. below is my code
```
private: System::Void colorSlider1_Wheel(System.Object sender, System.Windows.Forms.MouseEventArgs  e)
{
	vlcControl1.Pause(); //pause 
	double progressPercent = (double)trackBar1.Value / (double)trackBar1.Maximum;
	if (progressPercent >= 1)
		vlcControl1->Stop();
	else vlcControl1.Position = (double)progressPercent;
	vlcControl1->Pause(); //resume
}
```
mouse click event works fine without any issue.
@Hultan , any suggestion to above code?
Thanks

**Comment by Hultan** [comment]
@Prakash19921206 I don't know, but it might be the settings in ControlPanel\Hardware and Sound\Devices and Printers\Mouse and then the wheel tab. I think the default value for the settings there is 3 and maybe it will work better if that is 1? I have no idea, but it is something to try :-)

**Comment by SkinnySackboy** [comment]
Thanks for your reply! So, this is precisely what I tried (or equivalent), trying to figure out how long one frame would take. Unfortunately I also wasn't able to find a way to determine the frame rate programmatically, so this was a bit tricky. Regardless however, if I compensate for the precise fixed frame rate, skipping by this amount sometimes results in nothing happening, i.e. I can adjust the position a few times, then one time in say 5, it appears to do nothing. I wonder whether this is dependent on where the video happens to be when you pause it and begin to skip forward frame by frame. It does appear though that there is a class called VlcManager which should in theory be able to do this, but I cannot figure out how to use it.

**Comment by Prakash19921206** [comment]
@Hultan , i think like @SkinnySackboy suggested we have to use `VlcManager`, because changing `ControlPanel\Hardware and Sound\Devices and Printers\Mouse and then the wheel tab` setting doesn't help - with same settings VLC media player works fine.

i didn't find any example code for using `VlcManager `in latest Vlc.DotNet

**Comment by Prakash19921206** [comment]
@ZeBobo5 if possible,can you share any example code for C# or point to any documentation ?
i'm trying in winform.
this issue is open from long time.

Thanks
with regards
Prakash

**Comment by jeremyVignelles** [comment]
@Prakash19921206 I don't really understand your issue, but the original question has been answered, and I'm closing this.
If you need more help, feel free to open your own issue, or to join the conversation on gitter.
