### ISSUE TITLE
Associating a vlcManager with a vlcControl

### ISSUE THREAD

**Issue by PhilSargeant** [ZeBobo5/Vlc.DotNet#199]
I have downloaded vlc.dotnet 2.1.126 and used (1) the Control (vlcControl) and (2) the MediaPlayer (vlcMediaPlayer), from the Core, VERY successfully.

I would like to associate a Manager (vlcManager), from the Interopts, with the Control so that I could use a Manager with the Control.

I believe a similar question was raised a year or so ago but I did not get to see a response or resolution.

In an earlier version of vlc.dotnet  you could do thus:
vlcControl.Manager=vlcManager

This appears to have disappeared.  Could I ask how a Manager can be associated with a particular Control?

**Comment by ChillyGuy** [comment]
any luck? I have the same exact problem.
looks like in new version its not possible ...

**Comment by PhilSargeant** [comment]
Hello Reziramez (ChillyGuy).
I received no responses/comments other than yours.

After a week or so trying many things I eventually stumbled on a solution. I’m a retired computer analyst and write programs simply for my own fun and enjoyment. I write my programs in C# and VB. I used VB for this project.

I have no idea why the “vlcControl.Manager=vlcManager” capability was taken away.

I knew very little about reflection but, after some study, was able to use reflection to solve my problem. 

You have to first open a video file so that VLC can initialize a number of pointers/controls, etc. 

As you know the VlcControl1 control contains a lot of information about the video file; included was a field called “Video” (i.e.  VlcControl1.Video) that contained information about the video management. It also contained some Non-public members, one being myManager. The problem was that I could, not at first, access the pointer.

After a lot of trial and error and reading about reflection I was able to get myself a pointer to the manager. 

The piece of VB code I used to gain access to the manager was:

        Dim VlcControl1VideoObject As Object
        Dim ManagerPropertyName As String
        Dim MediaPlayerPropertyName As String
        Dim VlcControl1VideoType As Type

        VlcControl1VideoObject = VlcControl1.Video()
        ManagerPropertyName = "myManager"
        VlcControl1VideoType = VlcControl1VideoObject.[GetType]()

        Dim myManagerField As FieldInfo = Nothing
        While myManagerField Is Nothing AndAlso VlcControl1VideoType IsNot Nothing
            myManagerField = VlcControl1VideoType.GetField(ManagerPropertyName, BindingFlags.[Public] Or BindingFlags.NonPublic Or BindingFlags.Instance)
            VlcControl1VideoType = VlcControl1VideoType.BaseType
        End While
        If myManagerField Is Nothing Then
            Throw New ArgumentOutOfRangeException("Property Name ", String.Format("Field {0} was not found in Type {1}", ManagerPropertyName, VlcControl1VideoObject.[GetType]().FullName))
        End If

        myManager = myManagerField.GetValue(VlcControl1VideoObject)

Once I had access to the manager I could then use things such as:

myManager.NextFrame(myMediaPlayerInstance)
myManager.TakeSnapshot(myMediaPlayerInstance, ExtractedFile, VideoWidth, VideoHeight)

I hope this helps.
Cheers
Phil Sargeant
(phillipsargeant@hotmail.com)

**Comment by PhilSargeant** [comment]
Hello Reziramez (ChillyGuy).

I received no responses other than yours.

After a couple of weeks trying many things I eventually stumbled on a solution. I’m a retired computer analyst and write programs simply for my own fun and enjoyment. I write my programs in C# and VB. I used VB for this project.

I have no idea why the “vlcControl.Manager=vlcManager” capability was taken away.

I knew very little about reflection but, after some study, was able to use reflection to solve my problem.

You have to first open a video file so that VLC can initialize a number of pointers/controls, etc.

As you know the VlcControl1 control contains a lot of information about the video file, included was a field called “Video” (i.e.  VlcControl1.Video) that contained information about the video management. It also contained some Non-public members, one being myManager. The problem was that I could not at first access the pointer.

After a lot of trial and error and reading about reflection I was able to get myself a pointer to the manager.

The piece of VB code I used to gain access to the manager was:

        Dim VlcControl1VideoObject As Object
        Dim ManagerPropertyName As String
        Dim MediaPlayerPropertyName As String
        Dim VlcControl1VideoType As Type

        VlcControl1VideoObject = VlcControl1.Video()
        ManagerPropertyName = "myManager"
        VlcControl1VideoType = VlcControl1VideoObject.[GetType]()

        Dim myManagerField As FieldInfo = Nothing
        While myManagerField Is Nothing AndAlso VlcControl1VideoType IsNot Nothing
            myManagerField = VlcControl1VideoType.GetField(ManagerPropertyName, BindingFlags.[Public] Or BindingFlags.NonPublic Or BindingFlags.Instance)
            VlcControl1VideoType = VlcControl1VideoType.BaseType
        End While
        If myManagerField Is Nothing Then
            Throw New ArgumentOutOfRangeException("Property Name ", String.Format("Field {0} was not found in Type {1}", ManagerPropertyName, VlcControl1VideoObject.[GetType]().FullName))
        End If

        myManager = myManagerField.GetValue(VlcControl1VideoObject)

Once I had access to the manager I could then use things such as:

myManager.NextFrame(myMediaPlayerInstance)
myManager.TakeSnapshot(myMediaPlayerInstance, ExtractedFile, VideoWidth, VideoHeight)

I hope this helps.
Cheers
Phil Sargeant
Phillipsargeant@hotmail.com<mailto:Phillipsargeant@hotmail.com>

**Comment by tim-lukacik** [comment]
FYI - It's easier to get to the manager than that as of now
myPlayer.VlcMediaPlayer.Manager

Still not seeing any way to set the manager
