### ISSUE TITLE
VlcMedia contains no data

### ISSUE THREAD

**Issue by reliak** [ZeBobo5/Vlc.DotNet#20]
Hi,

im using your library to play audio files.
After starting an audio track I try to determine its metadata, but except for the duration no metadata seems to be availabe (sometimes the title contains some weird characters).

```
VlcMediaPlayer m = ...;
// load track and play (not shown here)
var media = m.GetMedia();
var nowPlaying = media.NowPlaying; // is null
```

Am I doing something wrong or is this a bug?

**Comment by jeremyVignelles** [comment]
Could you point me to a sample video showing the issue?
I'm closing since this is an old issue. Feel free to reopen if this is still an issue with latest versions of Vlc.DotNet and libvlc
