### ISSUE TITLE
VLC Option

### ISSUE THREAD

**Issue by matteozoni** [ZeBobo5/Vlc.DotNet#200]
Hi, I'm trying to use VLC Option but it seems not work.

I tried both

`vlcControl1.VlcMediaplayerOptions = new string[]{"--sepia-intensity=125"};`

that

`vlcControl1.Play(new Uri("rtsp://" + IPRead + ":554/cam0_0"), new string[] { "--sepia-intensity=125" });`

but in both cases they do not work.

How can I fix?

Thanks in advance.

**Comment by yohanes-wisdompos** [comment]
i think you should change "--sepia-intensity=125" to ":sepia-intensity=125"

**Comment by ZeBobo5** [comment]
Your problem is not a Vlc.Dotnet one but about VLC options syntax. You can find help on the [VideoLAN Forums](https://forum.videolan.org/)
