### ISSUE TITLE
Cannot play RTSP in x64 but in x86

### ISSUE THREAD

**Issue by ThaiwanLannister** [ZeBobo5/Vlc.DotNet#201]
It looks like issue [153](https://github.com/ZeBobo5/Vlc.DotNet/issues/153) has appeared again.  I ran my solution if x86 and it works fine.  Compiled in x64 and I get a blank screen.

**Comment by jeremyVignelles** [comment]
Please try with latest version of Vlc.DotNet and reopen if needed
