### ISSUE TITLE
VLC Low latency Options

### ISSUE THREAD

**Issue by CaptRR** [ZeBobo5/Vlc.DotNet#202]
Love the application, this has been a great system for us, and I want to thank everyone who has contributed.

I do have a little bit of a problem however.  When using regular VLC, one of the applications I use it for is low latency RTP stream.  To do this I would go into the VLC settings and change the http caching value to  0.

My questions is how would I do this with VLc.DotNet?  I din't see any way to adjust the settings area in code.  Is it just not possible?

Thanks

Rob

**Comment by jeremyVignelles** [comment]
Hi,
In case you are still looking for an answer (or if anyone else comes to this post), please try this:

```
VlcControl.MediaPlayer.VlcMediaplayerOptions = new[] { "--network-caching=200" };
```

Be careful however, in some of the recent versions of VLC, setting too low values breaks the stream.
