### ISSUE TITLE
Missing FPS property on VlcControl?

### ISSUE THREAD

**Issue by toby11** [ZeBobo5/Vlc.DotNet#206]
Hi,

Using Vlc.DotNet.Forms, is there a way to get the frames per second of the current video playing?

I see reference to a property FPS in this issue below but this no longer seems to exist?

https://github.com/ZeBobo5/Vlc.DotNet/issues/7

Is there another way to do it?

thanks
Toby

**Comment by ZeBobo5** [comment]
Implementing it to the librairy :smile: 
Sorry but I don't have any time to perform this librairy. I just need some help to improve it.

**Comment by mfkl** [comment]
The MediaPlayer has this API exposed https://github.com/ZeBobo5/Vlc.DotNet/blob/0b48ffc13b2787e9263ff58340cd66a5fd89a178/src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs#L299 I guess this issue can be closed?

**Comment by jeremyVignelles** [comment]
OK for me, thanks for pointing this out, @mfkl !
