### ISSUE TITLE
How to use the srt file?

### ISSUE THREAD

**Issue by Liucuiqiang** [ZeBobo5/Vlc.DotNet#209]
Hello, when I played the mkv file in Vlc.DotNet component, I wanted to load a srt file as the subtitle.
How can I do it? Thank you.

**Comment by RealxDay** [comment]
i have the same question, but there's no answer :(

**Comment by jeremyVignelles** [comment]
How would you do with VLC command line? https://github.com/ZeBobo5/Vlc.DotNet/wiki/Is-Vlc.DotNet-able-to-do-this%3F
Feel free to reopen if more help is needed
