### ISSUE TITLE
Video scaling support

### ISSUE THREAD

**Issue by Past9** [ZeBobo5/Vlc.DotNet#212]
I've added video scaling support at my fork here: https://github.com/Past9/Vlc.DotNet

It's only in the .NET 3.5 project at the moment because that's what I need, but I will add it to the others and submit a pull request in a few days if you're interested.

Initial changes: https://github.com/Past9/Vlc.DotNet/commit/cfa42e0be9b2dc1309fbdd46bc0b50ce9715c4db

**Comment by Past9** [comment]
Scaling appears to still render the entire frame "behind the scenes", leading to performance issues at high zoom. CropGeometry turned out to be a better solution for dynamically zooming a video, so I'm closing this issue.

**Comment by VanKurt** [comment]
Could you elaborate a little on how you did that? I'm currently trying to zoom/shift a video without success...

**Comment by Past9** [comment]
The `CropGeometry` property needs to be set to a string representing the rectangle you want to display. The VLC wiki documents this syntax as:

`"{Width}x{Height}+{X}+{Y}"`

...except that the `Width` and `Height` are not the width and height of the rectangle, but actually the X and Y coordinates of the bottom-right corner of the rectangle. So to turn a rectangle into a `CropGeometry` string, you need to do something like this:

`myVlc.Video.CropGeometry = $"{rect.Width + rect.X}x{rect.Height + rect.Y}+{rect.X}+{rect.Y}";`

The cropped rectangle will be stretched to fill the `VlcControl`.

The `CropGeometry` rectangle should be a section of the actual video, not the display rectangle of the VLC control, so if the video resolution is 1920x1080 but you're displaying it inside a 800x450 `VlcControl`, the `CropGeometry` rectange should be a section of 1920x1080. You can get the video resolution from the `VlcMedia` object like so:

```
var vidWidth = myVlcMedia.TracksInformations[index].Video.Width;
var vidHeight = myVlcMedia.TracksInformations[index].Video.Height;
```

**Comment by VanKurt** [comment]
This helps a lot. Thank you for the detailed explanation.
Using the CropGeometry string I am now able to zoom/scroll my video.

**Comment by acpt** [comment]
Really hard to get to this post and clarify how to do a pan and zoom with VLC lib - Cropping!
Thank you

**Comment by acpt** [comment]
Since this was an old post and I'm using LibVLCSharp 3.6:

To get Width and Height use:
_mediaplayer.Size(0, ref vidWidth , ref vidHeight );

The x,y are the top left position of the window for the Crop string
_mediaplayer.CropGeometry = (rect.Width + rect.X)+ " x" + (rect.Height + rect.Y) + "+" + rect.X  + "+" + rect.Y;
