### ISSUE TITLE
System.AccessViolationException occured in Vlc.DotNet.Core.Interop.dll

### ISSUE THREAD

**Issue by caichat** [ZeBobo5/Vlc.DotNet#214]
First of all, I want to say, that the example project (Forms sample application) works.
But when I try to include the VLC to my own WinForms application, an exception occurs.

> An unhandled exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll
> 
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The error happes in class VlcManager in the method CreateMediaPlayer. The command that cannot be executed is the INVOKATION of the InteropDelegate.
(I've modified the code here during debugging - but I just separeted the commands.)
`

    public sealed partial class VlcManager

    {

        [HandleProcessCorruptedStateExceptions]

        public VlcMediaPlayerInstance CreateMediaPlayer()

        {

            var del= GetInteropDelegate<CreateMediaPlayer>();

            var inv=del.Invoke(myVlcInstance); //ERROR HAPPENS HERE

            return new VlcMediaPlayerInstance(this,inv);

        }

    }
`
Are there any special settings for the compiler, that should be set?

Regards, Christian

**Comment by jeremyVignelles** [comment]
maybe using x86 library in a x64 project or the other way around?
Feel free to reopen if needed, this is a pretty old issue.
