### ISSUE TITLE
Flipping/Rotating a running video

### ISSUE THREAD

**Issue by VanKurt** [ZeBobo5/Vlc.DotNet#216]
When playing a video in VLC Player I can flip/rotate it via the settings menu.
Now I'm trying to replicate something similar using Vlc.DotNet.

So far the only way I found is doing this when creating the player:
```
string[] initOptions =
      {
        // VFlip
         "--video-filter=adjust:transform",
         "--transform-type=vflip",
      };

      VlcMediaplayerOptions = initOptions;
      EndInit();
```

But once the video is running, these settings can't be changed right?
Is there a way to use flip/rotate on a running player?

**Comment by deca90** [comment]
Can you insert the player in a panel and rotate the panel?

**Comment by GieltjE** [comment]
Pass the initoptions to the play/setmedia call, for some reason it won't work without.

**Comment by jeremyVignelles** [comment]
An answer has been provided, but no answer from original poster. I'm closing this for now, feel free to reopen.
