### ISSUE TITLE
.NET add VLC Control programmatically, but nullreferenceexception on .setmedia

### ISSUE THREAD

**Issue by deca90** [ZeBobo5/Vlc.DotNet#217]
Hello,

Can someone help me with this issue:

I create 5 VLC Controls in the main load and add also one button.
When the user hits the button, there is a loop that fills the setmedia en runs the .play function.

Code button:

`

        For Each player As Vlc.DotNet.Forms.VlcControl In Panel1.Controls

            player.SetMedia(New IO.FileInfo("c:\test.mpg"))
            player.Play()

        Next

`

Each time I get an Nullreferenceexception on the .setmedia line.
Can someone help me with this?

**Comment by jeremyVignelles** [comment]
not an expert of WinForms/VB but it looks like you are enumerating all controls of Panel1 and trying to interpret them as a "VlcControl". Items that are not VlcControls will then be null.
