### ISSUE TITLE
How to catch timestamp of RTSP?

### ISSUE THREAD

**Issue by lapaINH** [ZeBobo5/Vlc.DotNet#218]
Good evening! I really need help in getting the timestamp of the RTP response. I tried to write the log to a file, but failed. The logs do not have RTSP messages. Any ideas?

string uri = "rtsp://.....";
var options = new string[] { 
                        "-vvv", "--extraintf=logger", "--verbose=2",
                        "--logfile=" + Environment.CurrentDirectory + @"\img\Logs.log",
                        "--logmode=text", "--file-logging", "--save-config"
 };
var player = new Vlc.DotNet.Core.VlcMediaPlayer(VlcCore.GetLibDirectory(),options);

P.S  - I am sorry that no formatting

**Comment by ZeBobo5** [comment]
You must play media to have informations about it. This is a VLC problem.
