### ISSUE TITLE
Does VLC (or something else) need to be installed to use Vlc.DotNet? 

### ISSUE THREAD

**Issue by crumrine** [ZeBobo5/Vlc.DotNet#219]
I did see and I am using the code from this solution, https://github.com/ZeBobo5/Vlc.DotNet/issues/56  but I am still having a problem. 

I have a couple Win7 machines that run the application perfectly, but they do have VLC installed.  I had two Windows 10 machines I was testing with this morning, neither worked with my application (WPF if that matters), all I got was a blank screen, but I would see network traffic from the video on the machine (I am doing UDP streaming) - no errors in the log, nor the normal chatter I see in the vlc log from the videos playing.  I installed VLC on one of them and everything started working.

The version of VLC I installed was 2.2 where the libraries I am using are 2.1 - so maybe something like a codec needs to be configured that the VLC installer does, but I am not doing with my application install.  Thoughts?  

Thanks,
Brian

**Comment by cb88** [comment]
You have to have VLC installed or at least unzipped somewhere... otherwise how would  vlc = New VlcMediaPlayer(dirInfo) work? I bet if you put a try catch around there it is throwing an exception.
