### ISSUE TITLE
Instance creation behaviour of VlcManager

### ISSUE THREAD

**Issue by marcomeyer** [ZeBobo5/Vlc.DotNet#222]
Question:
Is it intended that different instances of VlcManagers are created when the requests are performed with different DirectoryInfo instances of exactly the same DirectoryInfo?

I am asking this because I currently am analyzing the memory allocation behaviour. And if you do not dispose the created VlcManagers, they(or at least parts of them) will stay in memory.

Here an example:

2 different instances of DirectoryInfo lead to 2 instances of VlcManager:
```c#
var manager1 = VlcManager.GetInstance(new DirectoryInfo(@"C:\temp\VLC"));
var manager2 = VlcManager.GetInstance(new DirectoryInfo(@"C:\temp\VLC"));

bool sameManager = manager1 == manager2;    // false
```

This is because the internal comparison of DirectoryInfo evaluates to false as well:
```c#
var di1 = new DirectoryInfo(@"C:\temp\VLC");
var di2 = new DirectoryInfo(@"C:\temp\VLC");

bool sameDi = di1 == di2;              // false
```

If you request VlcManagers with the same DirectoryInfo instance, you get the same instance of VlcManager:
```c#
var di = new DirectoryInfo(@"C:\temp\VLC");
var manager1 = VlcManager.GetInstance(di);
var manager2 = VlcManager.GetInstance(di);

bool sameManager = manager1 == manager2;    // true
```

**Comment by jeremyVignelles** [comment]
I don't think this is "intended". This is caused by DirectoryInfo instances being different. We could compare paths and check if they are equal, but does it worth it?

Thanks for sharing your findings anyway.

If you really feel something should be done, please reopen this issue
