### ISSUE TITLE
How can i start a audio stream ? 

### ISSUE THREAD

**Issue by salihkaragoz** [ZeBobo5/Vlc.DotNet#223]
I'm working on VLC Audio Stream over RTP. 

My main problem is I can stream with command line and VLC.exe that code. 
cd ///// vlc
(C:\Users\Casper\Downloads\emergency011.mp3 :sout=#rtp{dst=192.168.1.7,port=16400,sdp=sap} :sout-keep --qt-start-minimized vlc://quit )

But but I cannot make with VlcControl class and AxAXVLC.AxVLCPlugin2. and i dont know how can i make it.

string[] Voption = { ":sout=#rtp{dst=192.168.1.7,port=16400,sdp=sap} :sout-keep},dst=display}" };
 axVLCPlugin21.playlist.add(@"file:///C:/Users/Casper/Downloads/emergency011.mp3", "Merhaba",Voption);
   
it cant streaming.

Please please help me..
Thanks in advance.

**Comment by salihkaragoz** [comment]
`myVlcControl.myVlcMediaPlayer.SetMedia("file:///C:/Users/Casper/Downloads/sting.mp3",":sout=#rtp{dst=192.168.1.7,port=16400}");`

I have solved that problems. It was about at syntax. But I can't do capture sound from microphone.

**Comment by ZeBobo5** [comment]
Your problem is not a Vlc.Dotnet one but about VLC options syntax. You can find help on the [VideoLAN Forums](https://forum.videolan.org/)
