### ISSUE TITLE
USB multi-webcamera

### ISSUE THREAD

**Issue by binaryshamy** [ZeBobo5/Vlc.DotNet#226]
Hello,

I am trying to play a video from a usb webcamera and it works.
I am using a vlc syntax as input for the video path, but when I am trying to switch to another camera it plays the first one.

I have 2 webcams
- Logitech HD Pro Webcam C920
- Logitech QuickCam Express/Go

When I have both connected and use `dshow:// :dshow-vdev="Logitech HD Pro Webcam C920"` as input it runs the first camera, but when I switch to `dshow:// :dshow-vdev="Logitech QuickCam Express/Go"` it still plays the first camera. When I try to run the cameras from vlc application or command line, they both work correctly.

Am I doing something wrong?

PS. I am using Vlc.DotNet.Wpf with C#

**Comment by ZeBobo5** [comment]
Have you create a new media for the second camera?

**Comment by binaryshamy** [comment]
No, I have the VlcControl in a wpf control and when I play a video I use something like this:
`videoControl.MediaPlayer.Play(videoPath);`

After seeing your reply I tried with:
`videoControl.MediaPlayer.SetMedia(videoPath);
videoControl.MediaPlayer.Play();`
But it's the same.

**Comment by ZeBobo5** [comment]
Could you try to load media by:
`videoControl.MediaPlayer.Play("ddshow://", ":dshow-vdev=\"Logitech HD Pro Webcam C920\");`
and
`videoControl.MediaPlayer.Play("ddshow://", ":dshow-vdev=\"Logitech QuickCam Express/Go\");`

**Comment by binaryshamy** [comment]
Now it doesn't work anymore, getting a black screen and the IsPlaying flag is true (I waited for a while and tried with both cameras)

**Comment by binaryshamy** [comment]
I solved the issue, I used the solution you gave me in your last post but I had to remove the quotation marks around the camera names (Logitech HD Pro Webcam C920 instead of \"Logitech HD Pro Webcam C920\")

Thank you for your time and solution

**Comment by salihkaragoz** [comment]
binaryshamy  " can you show your syntax code for Direct show. I faced same problem too. How can i add dshow:// to the software. 1. new Uri(dshow://) 2. "dshow://" 3. File info ????? 


Please Help me 
Thanks in advance.

**Comment by binaryshamy** [comment]
like this:

`vlcControl.MediaPlayer.Play("dshow://", ":dshow-vdev=Logitech QuickCam Express/Go");`

**Comment by salihkaragoz** [comment]
Thank you so much. But it doesn't work on my software. I just download VLC.Dotnet and only changed the "dshow://" on Play function.   I started the program,  and nothing changed.   I don't know what I missed?

**Comment by binaryshamy** [comment]
If you use only "dshow://" it will open the first web camera it finds.
Try checking the following:
1) that you have all the necessary vlc libraries in the folder you specified for VlcLibDirectoryNeeded event. You need: axvlc.dll, libvlc.dll, libvlccore.dll, npvlc.dll and the plugins folder.
2) check if the camera is used by another application, if it is in use, vlc will not tell you it will just get stuck with a black screen.
3) not sure about this one, but try to have VLC player installed on the developers system (try vlc for both x64 and x86)

**Comment by salihkaragoz** [comment]
Thank you so much. I solved. The problem is about compiling with x64. When I change the to x86, it works.

**Comment by Prakash19921206** [comment]
hi all
i tried 
`vlcControl.MediaPlayer.Play("dshow://", ":dshow-vdev=my camera name");`
it opens my webcam but it displays only 1 frame.
in console i see `vlcControl1.IsPlaying ` to be `True`
in `vlc-log.txt `i see 

> core warning: clock gap, unexpected stream discontinuity
> core warning: feeding synchro with a new reference point trying to recover from clock gap
> core debug: Buffering 0%
> core debug: Buffering 16%
> core warning: clock gap, unexpected stream discontinuity
> core warning: feeding synchro with a new reference point trying to recover from clock gap
> core debug: Buffering 0%

you can see read details from vlc-log.txt [here ](https://pastebin.com/23QDse6j)

What could be the issue?
Thanks
