### ISSUE TITLE
MediaplayerOptions inconsistency

### ISSUE THREAD

**Issue by thephez** [ZeBobo5/Vlc.DotNet#227]
I am loading options from a file so I can change them without modifying my application.  Some of the options were not working and I initially thought it was a syntax issue, but after some debugging here is what I found:

If I construct the options array using a Split as shown below, only the first option in the array will work (in spite of the string array being the correct size and containing both items).

    string[] vlcMediaOptions = "--network-caching=200, --rtsp-frame-buffer-size=300000".Split(',');
    myVlcControl.VlcMediaplayerOptions = vlcMediaOptions;

If I instead create the options array as shown below, all options are applied as expected.

    string[] vlcMediaOptions = { "--network-caching=200", "--rtsp-frame-buffer-size=300000" };
    myVlcControl.VlcMediaplayerOptions = vlcMediaOptions;

In either case, I do not see a difference in the contents of the vlcMediaOptions array or in what the control's VlcMediaplayerOptions shows, but the first case does not work and the second does.

I am using VS2015 Express, Windows 7 (64-bit) and Vlc.DotNet 2.1.130.

**Comment by marcomeyer** [comment]
There is a difference. With your first option, there is a space at the beginning of the second setting.

Not sure if this is a problem, but try trimming the individual settings after the Split().

**Comment by thephez** [comment]
@marcomeyer Thanks for the feedback.  I was afraid it was going to be something like that, but could not spot it for some reason.  Trimming did the trick.
