### ISSUE TITLE
VlcMediaplayerOptions cannot work

### ISSUE THREAD

**Issue by LGinC** [ZeBobo5/Vlc.DotNet#228]
`this.vlcControl1.VlcMediaplayerOptions = new[] { "--no-audio" };`
this is in function InitallizeComponent(). it do not work.

and I add a button, and add Options to the button's click event, When the VLCplayer was playing , I press that, but it didn't work.

**Comment by LGinC** [comment]
OK,I should add the code before the function EndInit().
But I want to know how to control the player runtime.

**Comment by jeremyVignelles** [comment]
You can control the volume using :
`vlcControl1.Audio.Volume = 50;` or `vlcControl1.Audio.IsMute = true;`
