### ISSUE TITLE
VlcContext.StartupOptions missing

### ISSUE THREAD

**Issue by DominikPalo** [ZeBobo5/Vlc.DotNet#23]
How can I change StartupOptions of VLC control? In one of my projects I'm using older version of Vlc.DotNet library to play video on multiple screens (windows) by wall filter:

```
VlcContext.StartupOptions.AddOption("--vout-filter=wall");
VlcContext.StartupOptions.AddOption("--wall-cols=2");
VlcContext.StartupOptions.AddOption("--wall-rows=2");
```

How can I achieve this behaviour now? Is there any method to set StartupOptions???

**Comment by goobering** [comment]
+1 for this. It's a nightmare trying to debug my option strings without the logging console.

**Comment by gaitanivan** [comment]
When I use Play method, the second parameter is string array for Options, I use ":" instead "--". eg: ":start-time=10", ":vout-filter=wall"...

**Comment by jeremyVignelles** [comment]
You need to initialize `VlcMediaPlayerOptions` before the initialization of your control. Play() 's second option is made for passing options that are specific to the media.
