### ISSUE TITLE
How to add and apply external HLSL filter files?

### ISSUE THREAD

**Issue by hosamhany** [ZeBobo5/Vlc.DotNet#230]
I am trying to add an external filter file to be applied when a video is played, is that possible? If yes, how?

**Comment by jeremyVignelles** [comment]
Is vlc able to do this? If yes, how? https://github.com/ZeBobo5/Vlc.DotNet/wiki/Is-Vlc.DotNet-able-to-do-this%3F
Feel free to reopen if more help is needed
