### ISSUE TITLE
Unable to Play Internet Radio or Youtube

### ISSUE THREAD

**Issue by RichieRogers** [ZeBobo5/Vlc.DotNet#232]
Hi,
I'm using VS 2015 and installed VLC.dotnet via Nuget as per https://github.com/ZeBobo5/Vlc.DotNet/wiki/Using-Vlc.DotNet-in-WinForms
I have added the Net45 x86 control to the form and am successfully able to play local files (eg a wmv file).
However, any online, streaming, internet radio feeds, youtube videos do NOT work (just blank screen).
The files all successfully work when played directly in VLC.

Tried all of the below and only the first one works:
vlcControl1.Play(New IO.FileInfo("M:\Video\Miscellaneous Videos\WizardsofWinter.wmv"))
vlcControl1.Play(New Uri("https://www.youtube.com/watch?v=svnAD0TApb8"))
vlcControl1.Play(New Uri("http://yp.shoutcast.com/sbin/tunein-station.pls?id=930399"))

The VLCLibDirectory for the control is also pointing to "C:\Program Files (x86)\VideoLAN\VLC"

Does this just not work with VLC.DotNet (even though it works with "full" VLC) or am I missing something?

Thanks,
Richie

**Comment by yiatz** [comment]
Bump

I'm having the same issue, specifically with youtube. From the logs it looks like it finds the stream correctly, grabs all the info, then throws a general "EncounteredError" exception without any info. The log shows the video info, then starts removing modules. No error message. Log is attached.
[vlc-log.txt](https://github.com/ZeBobo5/Vlc.DotNet/files/965322/vlc-log.txt)

**Comment by jeremyVignelles** [comment]
Could you try with a newer version of libvlc, like 3.0.0 nightly builds? (see "getting started" wiki)

**Comment by yiatz** [comment]
Why am I cc’d on this? What’s going on?

 

Preston May

**Comment by mfkl** [comment]
What is going on is that you commented on this GitHub issue last April, so you get emails when new comments are posted (just like the email you received says at the bottom). You probably wanna reply through GitHub Issues though, not directly through email.

**Comment by jeremyVignelles** [comment]
No answer received, closing this. If this issue is still present, feel free to reopen with more info.
