### ISSUE TITLE
VLC.DotNet Direct Show

### ISSUE THREAD

**Issue by salihkaragoz** [ZeBobo5/Vlc.DotNet#234]
**First Question: Does VLC.DotNet support the dshow:// stream with mp3 codec ????**

Hello everyone, 

I can not start the direct show. This is my codes.

`myVlcControl.Play("dshow://");`
`myVlcControl.Play(new Uri("dshow://"));`

I added the only dshow:// because I think the other options will be the default. Is there anyone who succeed the direct show with VLC.dotnet project? 

I think my problem is about Vlc.dotnet options. not about  VLC options syntax. Please do not close my issue.
If you close my issue, please say it is possible with Vlc.dotnet. 

Please, Please, Please help me? Thanks in advance. 

**I think It takes not too much time for experts. Please write a little comment about that issue.**

**Comment by salihkaragoz** [comment]
Hello everyone, As soon as I've solved the problem. The problem is compiling with x64 architectural.  When I was compiled with x86 architectural, The problem solved. 

I don't know this is a bug or not.

**Comment by mahdi87gh** [comment]
@salihkaragoz Please share your code, I keep getting this error: Media instance is not initialized.'

`            vlc.Play(@"dshow://  :dshow-adev=""Desktop Microphone(Microsoft® LifeCam Studio(TM))"" :dshow-vdev=""Microsoft® LifeCam Studio(TM)""  :live-caching=500");
`

**Comment by salihkaragoz** [comment]
Same as above.

**Comment by mahdi87gh** [comment]
If I set to x86 I get error. If x64 there is no error but nothing is playing.

**Comment by salihkaragoz** [comment]
(Vlc.DotNet.XXX 2.1.15. which is current) I think you've downloaded from github repo. Its old. Arc type has been updated. You should use Nuget for getting package. In the new version of Vlc.dotnet there is no architectural. Only "Any Cpu" and it works both architectural.  #288

**Comment by mahdi87gh** [comment]
Thanks man, Now I'm getting %1 is not a valid Win32 application error. nuget will have a copy of lib directory? should I reference it to vlc installation directory?

**Comment by jeremyVignelles** [comment]
Hi, please have a look at the wiki : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started
Please note that the manual download is likely to change, because we need a way to get the libraries through NuGet.
If you want to know more about the ongoing discussion, have a look at #288

**Comment by mahdi87gh** [comment]
@jeremyVignelles I created a fresh windows forms application project, followed the wiki, but still the same problem. I check if I set target to x64, it works fine. can play "http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov"
but cannot play dshow devices. I am on windows 10 x64 - vs2017, can you confirm it's working for you.

**Comment by jeremyVignelles** [comment]
@mahdi87gh I don't have access to a computer right now. I was just answering to your issue with x86/x64 ("...is not a valid win32 application") if you build your application with x86 or Any CPU "prefer 32 bits" or Any CPU that is run on a 32bits os, then you will need a x86 VLC (all your libvlc dlls should be x86)
The lib directory in this repository should not be used for production. use the dll from the official VLC distribution.
I didn't look at your issue closely, but it looks like you are passing arguments as the stream url, rather than passing them as stream options.

**Comment by mahdi87gh** [comment]
@jeremyVignelles I took dlls from vlc ftp, as I told you it can play streams well. my problem is I want to stream usb webcam to my rtsp server. Right now I can't even open webcam in vlcControl. Can you help me?

**Comment by jeremyVignelles** [comment]
If your code is the one above, you need to split between the stream url ("dshow://") and the stream parameters ":option" that you can pass as an array to some method (don't remember which, maybe the Play() method itself)

**Comment by mahdi87gh** [comment]
@jeremyVignelles unfortunately it doesn't work. I can open vlc.exe by command and get connected to usb webcam fine. but with vlcControl it doesn't work. Can you make a sample code?

**Comment by salihkaragoz** [comment]
vlc.Play(":dshow://", ":dshow-vdev=Microsoft® LifeCam Studio(TM)");  please try this and say if it is ok.

**Comment by mahdi87gh** [comment]
@salihkaragoz It doesn't work.
