### ISSUE TITLE
VlcLibDirectory

### ISSUE THREAD

**Issue by Fcases** [ZeBobo5/Vlc.DotNet#236]
hey all , im working on a test wpf c# project, and it seems i cant use this

   ```
 VlcControl control = new VlcControl(VlcLibDirectory =  new DirectoryInfo(ConfigurationManager.AppSettings["VlcFolder"]), Tag = i);
               _vlcControls[i - 1] = control;
```
VlcLibdirectory is gone ? 
is there a new way to assign ?

**Comment by jeremyVignelles** [comment]
Hi,
Did you try with the `control.MediaPlayer.VlcLibDirectoryNeeded` event?
