### ISSUE TITLE
Question about using VlcManager

### ISSUE THREAD

**Issue by SkinnySackboy** [ZeBobo5/Vlc.DotNet#239]
Hi,

We are using the WPF version but I cannot for the life of me figure out how to instantiate and use a VlcManager to skip video frame by frame (I would like to call the NextFrame method). This method requires a VlcMediaInstance but I cannot see how to get one of these from the WPF VlcControl.

Is anyone able to point me in the right direction please, as a cursory search has only yielded results of people posing the same question on StackOverflow without any answer?

Many thanks,

Mark

**Comment by jeremyVignelles** [comment]
See
https://github.com/ZeBobo5/Vlc.DotNet/blob/80b9fb5fab8ce4433e4efdcb9a1406b73ac9e240/src/Vlc.DotNet.Forms/VlcControl.cs#L14
https://github.com/ZeBobo5/Vlc.DotNet/blob/80b9fb5fab8ce4433e4efdcb9a1406b73ac9e240/src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs#L14

In short : these are private fields, so you can't do that here.

Two options here:
- Implement a high-level specific option for what you are doing
- Expose those fields through a public property. (my vote goes for this one)

Both options would require some work on our side (or a pull request).
Please tell me what you want, and feel free to join the discussions at https://gitter.im/Vlc-DotNet/Lobby

**Comment by jeremyVignelles** [comment]
Starting with the latest prerelease, you are able to get the `VlcManager` from the Media player. That way, you will be able to apply the workaround.

**Comment by edwardchuajh** [comment]
Hi, I am able to get the VlcManager now, but is still unable to get the  `VlcMediaPlayerInstance` for use in the Manager's method, for e.g. `SetVideoAspectRatio` do we know how I can get that?

Example:
`
private VlcControl vlcElement1 = new VlcControl();
vlcElement1.MediaPlayer.VlcMediaPlayer.Manager.SetVideoAspectRatio(**??**, "16:9");`

**Comment by jeremyVignelles** [comment]
Use `vlcElement1.MediaPlayer.VlcMediaPlayer.AspectRatio = "16:9";` instead. You should only use `Manager` in cases where there is no alternatives.
