### ISSUE TITLE
VlcControl crashes the designer when nested

### ISSUE THREAD

**Issue by ddobrev** [ZeBobo5/Vlc.DotNet#24]
Add a VlcControl to a UserControl, then add the UserControl to a Form and open the Form in the designer - it crashes. The reason is this bug in Visual Studio: http://stackoverflow.com/questions/34664/designmode-with-controls/708594 .

Patch at https://gist.github.com/ddobrev/a9a1990e56fd12097873 .

**Comment by ddobrev** [comment]
Hello, any thoughts on this one? Should I make a pull request with my patch?

**Comment by ZeBobo5** [comment]
Yes you could :)

**Comment by ddobrev** [comment]
There you go: https://github.com/ZeBobo5/Vlc.DotNet/pull/25 .
A NuGet update with the fix will be appreciated. :)
