### ISSUE TITLE
Cannot figure out how to use the .VlcMediaPlayerOptions property...

### ISSUE THREAD

**Issue by Videstra** [ZeBobo5/Vlc.DotNet#241]
Based on the documentation available here: 
[VLC Doc](https://wiki.videolan.org/Documentation:Command_line/#Miscellaneous_options)
I would think I could set options as a string array using the settings outlined in the documentation above - but I haven't been able to get any of them to work.   
**For example:**
```
With VlcPlayer
     .VlcMediaplayerOptions = {"--fullscreen"}
    .SetMedia("http://video3.earthcam.com/fecnetwork/7382.flv/playlist.m3u8")
    .Play()
End With
```
Doesn't appear to do anything...
I've tried to set up a toggle for fullscreen as follows (hopefully I'm doing it right)
```
Private Sub btnFullScreen_Click(sender As Object, e As EventArgs) Handles btnFullScreen.Click
Static bFullScreen as Boolean = False
      If bFullScreen then
            VlcPlayer.VlcMediaplayerOptions = Nothing
            bFullScreen = False
      Else
            VlcPlayer.VlcMediaplayerOptions = {"--fullscreen"}
            bFullScreen = True
      End if
End Sub
```
I've tried other options based on the documentation such as **--grayscale** and **-f** (another way to specify fullscreen) and they appear to just be ignored.   I am wondering if the _.VlcMediaplayerOptions_ property is just broken?
I see another post talking about fullscreen being broken - perhaps this is the reason?   In my application I really need fullscreen to work (I need to be able to toggle in and out of full screen).  I'd also like grayscale to work, but it's not critical...

**Comment by Videstra** [comment]
For the fullscreen option I am an idiot.  I think it's probably not all that practical to rely on the internal fullscreen option built into VLC.   Instead I found it makes more sense to code your own.  I use VB and this is what I did

```
#Region "Fullscreen"

    Private Structure OriginalGeometry_Struct
        Dim FormSize As Size
        Dim VlcSize As Size
        Dim FormLoc As Point
        Dim VlcLoc As Point
        Dim VlcParent As Object
    End Structure

    Private bFullscreen As Boolean = False

    Private OriginalFormGeometry As OriginalGeometry_Struct

    Private Sub btnFullScreen_Click(sender As Object, e As EventArgs) Handles btnFullScreen.Click
        If Me.PreviewAuthorizationMode = False Then
            DoFullscreen()
        Else
            MsgBox("Not Authorized!")
        End If
    End Sub

    Private Sub DoFullscreen()
        Me.SuspendLayout()
        With OriginalFormGeometry
            .FormSize = Me.Size
            .FormLoc = Me.Location
            .VlcSize = vlcPreview.Size
            .VlcLoc = vlcPreview.Location
            .VlcParent = vlcPreview.Parent
        End With
        vlcPreview.Parent = Me
        Me.Size = Screen.FromControl(Me).WorkingArea.Size
        Me.Location = New Point(0, 0)
        vlcPreview.Size = Me.Size
        vlcPreview.Location = Me.Location
        vlcPreview.BringToFront()
        Me.ResumeLayout()
        bFullscreen = True
        Me.Refresh()
        MsgBox("Press Esc to Exit Fullscreen")
    End Sub

    Private Sub DoOriginalGeometry()
        SuspendLayout()
        With OriginalFormGeometry
            vlcPreview.Parent = .VlcParent
            Me.Size = .FormSize
            vlcPreview.Size = .VlcSize
            Me.Location = .FormLoc
            vlcPreview.Location = .VlcLoc
        End With
        Me.ResumeLayout()
        bFullscreen = False
        Me.Refresh()
    End Sub

    Private Sub frmChaserPreview_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.Escape Then
            If bFullscreen Then
                DoOriginalGeometry()
            End If
        End If
    End Sub

#End Region

```
This gave me everything I required to toggle in and out of full screen

**Comment by Videstra** [comment]
This still doesn't give me the grayscale - but that's not critical.

**Comment by jeremyVignelles** [comment]
does the `--grayscale` option work with the `vlc` command line? I don't think this is specific to Vlc.DotNet. If it is and you still want this to be fixed, please reopen this issue.
