### ISSUE TITLE
Streaming audio to Icecast Server

### ISSUE THREAD

**Issue by bostjannagode** [ZeBobo5/Vlc.DotNet#247]
Dear, 

i'm trying but.. I want to stream audio to icecast server, it works from VLC 2.2.1 on windows 10, but with VLCdotnet dont want. If someone can take a look if syntax is correct? it's Visual Basic.net  2015...

 arguments(0) = ":sout=#transcode{vcodec=none,acodec=mp3,ab=192,channels=1}:duplicate{dst=std{access=shout,mux=ogg,dst=source:hackme@192.168.1.75:8000/radio1},{dst=display}}"

On VLC is all ok, but on Vlcdotnet Icecast server says:
Notification: This doesnt look like a Speex file
thanks in advance
Bostjan

**Comment by salihkaragoz** [comment]
I think your problem about at compile platform. maybe you can try with x86 or x64 architectural. 
#234  like here

**Comment by bostjannagode** [comment]
And i have tried all release and debug versions, x86 and x64. Is there anyone that can say that it should work?
Best, Bostjan

**Comment by bostjannagode** [comment]
Anyone that can help, please?

Best, Bostjan

**Comment by jeremyVignelles** [comment]
Which version of libvlc are you using? Is it 2.2.1 like your vlc?
You could also try with libvlc 3.0 nightly builds.

Please also share the command line that you are using to launch vlc to do the same thing.

**Comment by jeremyVignelles** [comment]
Feel free to reopen if needed
