### ISSUE TITLE
Catch RTMP/RTSP stream stop

### ISSUE THREAD

**Issue by JeremiSharkboy** [ZeBobo5/Vlc.DotNet#250]
`myControl.MediaPlayer.Play(new Uri($"rtmp://{Host}:1935/{ServerApplication}/{Imei}"));
`
i want to catch exception when my stream(rtsp/rtmp) is stopped. is it possible?

**Comment by jeremyVignelles** [comment]
Isn't the `Stopped` event made for that? Did you try it?
