### ISSUE TITLE
How to auto re-connect rtsp stream 

### ISSUE THREAD

**Issue by chiecla** [ZeBobo5/Vlc.DotNet#251]
I have a rtsp stream, i use code below to view play and save it to file, 

var opts2 = new string[] { ":sout=#duplicate{dst=std{access=file,mux=mp4,dst='" +path+ "'},dst=display}" };
vlcControl.Play( "rtsp:/123.123.123.123", opts2);

but when I lose the internet connection in some second, It cann't be auto reconnect to play and save continues, please help me to do this. Many thanks

**Comment by jeremyVignelles** [comment]
I don't think that this issue is related to Vlc.DotNet. Did you try with the VLC executable and give it those options? Does it show the same behavior?

Also, please try to upgrade the libvlc version to the latest nightly build and see if there is any improvement.
