### ISSUE TITLE
Where am I supposed to 'get' libgcc_s_seh-1.dll?

### ISSUE THREAD

**Issue by Jeb135** [ZeBobo5/Vlc.DotNet#252]
I'm making a wpf application with an embedded vlc player to play a RTSP stream, and cannot get an implementation of the basics working in my application. I continue to get the Win32 exception "%1 is not a valid win32 application" which I believe to be coming from the fact that I don't have libgcc_s_seh-1.dll anywhere on my computer. Is this dll supposed to be packaged with a vlc install? My code as it stands right now is below. I am using windows 10 on a 64-bit processor, if that helps at all.

`public MainWindow()
        {
            InitializeComponent();
            ROVStream.MediaPlayer.VlcLibDirectory = new DirectoryInfo(@"C:\Program Files\VideoLAN\VLC");
            ROVStream.MediaPlayer.EndInit();
            ViewModel = new ROVControlsViewModel(/*ROVStream*/);
            this.DataContext = ViewModel;
        }`

**Comment by Jeb135** [comment]
After finding a copy of the dll on the internet, it still does not solve the win32 exception issue.

**Comment by jeremyVignelles** [comment]
This exception sounds like the VLC installation is corrupted, or maybe your windows installation? Could you try on another computer?
