### ISSUE TITLE
Hardware Acceleration Not Working

### ISSUE THREAD

**Issue by VanKurt** [ZeBobo5/Vlc.DotNet#253]
I need to play several h264 video files (e.g. 4) in parallel on different screens. My machine is pretty much high end (Win10 x64, Core i7 with 4*2 cores, 32GB RAM and two NVIDIA Geforce GTX1080), so this should be no problem ;-)

For a first test I used the VLC 2.2.4 standalone application. All videos run totally smooth.

Then I created my application with LibVlc DotNet and played the same video files as before. Strangely the videos stutter from time to time. CPU load is very high (60 - 90%), GPU load is rather low.

So I guess there is a problem with hardware acceleration of the video decoding.
Is there a way to check what LibVlc DotNet is doing here? If it is using the hardware properly?
Can I enable/force hardware decoding?

**Comment by jeremyVignelles** [comment]
Hi,
I don't see any reason for that to happen, but I'm not an expert...
You could try enabling verbose logs by passing "-vv" to VlcMediaplayerOptions and check if Hardware acceleration is getting enabled.

Basically, forcing the use of a specific decoder is made exactly the same way as in vlc command line.

You could also try replacing the libvlc with the latest version of libvlc nighly build and see if there is any improvements.
