### ISSUE TITLE
Demux Plugin

### ISSUE THREAD

**Issue by KRobinson-SAY** [ZeBobo5/Vlc.DotNet#254]
I was using an older version of VLC.DotNet and I was able to include a custom demux dll in the plugins directory to play back a custom file format. I have been looking into using the latest version, however this doesn't seem to work anymore. Is there anything I need to do to register the plugin?

**Comment by jeremyVignelles** [comment]
Just saw this in VLC documentation:

> Recent versions of VLC require that the modules follow a specific naming convention or they will not be loaded. Modules must be named in the following format: libmodule_name_plugin.ext where module_name should be the name of your module in lower case, and ext is the system's shared library extension. For example, the http access module is named libaccess_http_plugin.dll on a Windows machine.

Did you follow the naming convention?

Source : https://wiki.videolan.org/Documentation:VLC_Modules_Loading/
