### ISSUE TITLE
How to add a seekbar in vlc dot net forms in C# windows forms application

### ISSUE THREAD

**Issue by premingiet** [ZeBobo5/Vlc.DotNet#255]
**I need to add a custom seekbar / trackbar** as you may say in c# windows forms. But the issue is there is almost no documentation on vlc dot net forms library. I need to know how to add a **custom seekbar in windows forms application**.

**remember, i am not using vlc activeX plugin**. Rather **i am using nuget package of dot net library of vlc** and everything is working fine. I have added toggle play and pause button, stop button, able to get current time, able to get total time and everything else. But i have no idea _how to add a seekbar so that when i seek, the video moves to that position_. Please help me with full code.

**Comment by TheRDavid** [comment]
Not going to provide you with [code ](https://www.youtube.com/watch?v=6gLMSf4afzo), but you can just use the Position-property of your vlcControl (value between 0 and 1 I think)

**Comment by salihkaragoz** [comment]
https://stackoverflow.com/a/44157848/6106129
This is the solution....

**Comment by jeremyVignelles** [comment]
Closing as a solution has been provided on stackoverflow

**Comment by xyz0835** [comment]
Wow, so polite.
