### ISSUE TITLE
Vlc.DotNet in x64 application not working

### ISSUE THREAD

**Issue by TobiasSpatt** [ZeBobo5/Vlc.DotNet#256]
Hello,

Is there any solution to get this framework working in an x64 application?
The application displays a webcam with rtsp.
I use Vlc.DotNet.Core, Vlc.DotNet.Core.Interops and Vlc.DotNetForms from the x64 build and set the VlcLibDirectory to the correct x64 directory.
The VlcControl shows only a black screen. When i build the application in x86 it works well.
I need to get this working fast.

Thank you and best regards

**Comment by marcomeyer** [comment]
Not sure if it is needed but in our application, we also changed the vlc binaries to x64. Did you do this as well ?

**Comment by TobiasSpatt** [comment]
Thanks for your answere. I have already changed the path to the x64 vlc binaries, but it's still not working

**Comment by marcomeyer** [comment]
Do videos work?
