### ISSUE TITLE
MouseWheelEvent

### ISSUE THREAD

**Issue by jldm231** [ZeBobo5/Vlc.DotNet#257]
I find no way to capture mouse wheel event once i have started playing video.
If someone could help me at this point i will be really grateful.
I'm using WPF control.

**Comment by catholic** [comment]
You mean you need to handle mouse wheel event over VlcControl?
To do this in WPF style you need to render WPF control on top of WinForm VLC control
[Check this link](https://stackoverflow.com/a/23662410) for example

**Comment by jldm231** [comment]
I tried what you say without success. I'll  check your link this weekend
and if it works I will be really thankful.
Thanks for your answer

**Comment by jeffreychen567** [comment]
I have the same problem.When the video is playing, it is impossible to use the mouse double-click to achieve full-screen play.Right-click the mouse to show the right menu.

**Comment by pinewoodranger** [comment]
I don't think mouse events work when the video is playing. I got around this by docking the vlcControl inside a new form and I clip another form (overlay) over it with 0.01 opacity. All mouse events are then handled by the overlay form. Implemented double click fullscreen like this and I'm guessing any other mouse/keyboard events would work just as well for this.

**Comment by jeffreychen567** [comment]
Thank you very much，I will give it a try。I have another question，When I use it to play the media on the network, I also want to record it at the same time。What should I do?

**Comment by jeffreychen567** [comment]
It's better to give me some  code.

**Comment by jldm231** [comment]
you can pass some options to vlc in order to save video whereas playing it.
overlay form must be in Won Form, i didn't manage to do this in WPF

**Comment by jeremyVignelles** [comment]
Did you try the airspace overlay as proposed earlyier? i.e.having a control on that airspace overlay to handle your events. see also #296. Feel free to reopen if more help is needed
