### ISSUE TITLE
How to start streaming(out)

### ISSUE THREAD

**Issue by SheetalRaj** [ZeBobo5/Vlc.DotNet#258]
Hi Guys, 

I have been trying to stream (out) an audio file but i can't get it working.
----------------------------------
Code :
vlcControl1.SetMedia("file:///C:/Users/Raj/Music/test.mp3", new string[] { ":sout=#transcode{vcodec=h264,acodec=mpga,ab=128,channels=2,samplerate=44100}", ":rtp{sdp=rtsp://:133/ct2}", ":sout-keep" });

vlcControl1.Play();
--------------------------------
Things I have tried :
1. When i use 2 VLC player for stream (out) & steam (in) it worked fine.
2. Stream (out) from VLC player and receive in c# app it works.
3. Stream (out - using code above) and receive in VLC player doesn't work.
----------------------------------
Log VLC:
core warning: connection timed out
access_realrtsp debug: could not connect to: localhost:133/ct2
core debug: no access modules matched
core error: open of `rtsp://localhost:133/ct2' failed
core debug: finished input
core debug: dead input
core debug: changing item without a request (current 1/2)
core debug: nothing to play
qt4 debug: IM: Deleting the input
----------------------------------
Have already check issue : #165, #203 , #223, #247 
I'm using sample "Vlc.DotNet.Forms.Samples - CLR 4 - .Net 4.5" ,solution configuration is set to x86
----------------------------------
Dose anyone know how to get it working ?
Thanks in advance :)

**Comment by salihkaragoz** [comment]
":rtp{sdp=rtsp://:133/ct2}" What is a different Rtp address :-D are u sure its correct

**Comment by SheetalRaj** [comment]
It should be correct , have copied them from vlc player 
--------------------------------
Sender
![sender 1](https://cloud.githubusercontent.com/assets/29145340/26728506/5afed148-47a2-11e7-9864-1567919ef501.PNG)
![sender 2](https://cloud.githubusercontent.com/assets/29145340/26728504/5afd8fc2-47a2-11e7-8fe7-0be678c8cba0.PNG)
![sender 3](https://cloud.githubusercontent.com/assets/29145340/26728505/5afdbf60-47a2-11e7-9a13-86964d49f731.PNG)
--------------------------------
Reseiver
![receiving end](https://cloud.githubusercontent.com/assets/29145340/26728503/5af9b2b2-47a2-11e7-93fb-203e9bc29d56.PNG)
--------------------------------
Can you spot the my mistake or do you know how to get it working ?
Thanks

**Comment by SheetalRaj** [comment]
Just in case someone struggling to get this working , that's how i got it working 
                string[] test = new string[]
                {
                    ":dshow-vdev=PC Camera", 
                    ":dshow-adev=Microphone (2- Magic Sound)",
                    ":live-caching=100",
                  "sout=#transcode{vcodec=h264,acodec=vorb,ab=128,channels=2,samplerate=44100}:rtp{sdp=rtsp://"+IPAddress:Port/ID+"}"
                };
vlcServer.Play("dshow://", test);
vlcServer = vlc contrlol object.
