### ISSUE TITLE
got 403 forbbiden 

### ISSUE THREAD

**Issue by SomeOneMore** [ZeBobo5/Vlc.DotNet#260]
hi
i got 403 forbbiden error when i try to play youtube videos.
an sample uri is:
https://r2---sn-4g5ednle.googlevideo.com/videoplayback?clen=371058229&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,expire&initcwndbps=1043750&ipbits=0&beids=[9466593]&ei=v6w8WcLzJdLdc57OheAF&ms=au&mt=1497148535&mv=m&pl=23&ip=81.44.102.80&keepalive=yes&mime=video/mp4&id=o-AG74lop-0djauV5iJH9uIaaqggaq9NA0CnawwKz0jGz_&mm=31&mn=sn-4g5ednle&itag=135&expire=1497170207&lmt=1416844123302192&source=youtube&dur=2827.291&requiressl=yes&gir=yes&signature=BA59FF7F53E3BF5CC3FEEB9F29BCAE997BF83D86.D6124C14C64313981C0E21A7CAB47852D9E7CA71&key=yt6&ratebypass=yes

i can only run a few videos
any idea?
thanks in advance

**Comment by jeremyVignelles** [comment]
This is the same for VLC, so this is not the right place to ask.

Moreover, it looks like an URL you are not supposed to play in a VLC player, so google is probably blocking what you are trying to do.

**Comment by SomeOneMore** [comment]
It's a referer question.
if you run this from a internet server, all is ok.
if you run it from your PC, the error appears.
How to pass referer?

**Comment by jeremyVignelles** [comment]
Why don't you pass the youtube URL directly to the player?

**Comment by SomeOneMore** [comment]
to the vlc?
Because it's very very unstable!
It's impossible to have any stable thing or have more than an few videos run without a hang...

**Comment by SomeOneMore** [comment]
With this, i got a stable solution, but the problem, as i read, is about referers.
And i dont know how to manage them.
any help will be appreciated

**Comment by jeremyVignelles** [comment]
Closed as not specific to Vlc.DotNet
