### ISSUE TITLE
How to reduce delay in straming

### ISSUE THREAD

**Issue by SheetalRaj** [ZeBobo5/Vlc.DotNet#261]
Hi there, 

Dose anyone know reduce the delay in RTSP stream, I'm using h264 & mpga for video and audio.
Currently the delay is about 3 - 5 second, I'm trying to get it down to < 1 sec.
Have tried setting live caching and and network caching but it doesn't help.

If you have any solution or idea please share.

Thanks

**Comment by jeffreychen567** [comment]
hello friend，i cannot find mediaplayer in vlccontrol.why?

**Comment by jeremyVignelles** [comment]
The example above assumed that you were using Vlc.DotNet.Wpf. If you are using Vlc.DotNet.Forms, you can remove the `MediaPlayer` in the middle, that is used in WPF to get access to the `Forms.VlcControl` instance.

```
VlcControl.VlcMediaplayerOptions = new[] { "--network-caching=200" };
```

**Comment by jeffreychen567** [comment]
Thank you, my friend.I am using the C#.There is another question. Can you help me?I want to record the video that is playing.rtsp vedio. What should I do?vlcControl1.Play(@"rtsp://admin:admin@192.168.114.111:554/h264/ch1/main/av_stream",@":sout=#duplicate{dst=std{access=file,mux=mp4,dst='[c:\cjf.mp4]'},dst=display}");

this not work

**Comment by jeremyVignelles** [comment]
Closed as your second question is off-topic. Please open a separate issue if needed

**Comment by morl0048** [comment]
What's the `network-caching` doing when you drop it low/climb it high? Is there a ratio to keep in mind?
I'm currently having latency of ~15 seconds...

**Comment by jeremyVignelles** [comment]
network caching is the delay in milliseconds of buffering.
Lower value means lower latency.
In vlc 2.x, you could set it to any value without damage. Starting with vlc 3, setting it to very low values can break your stream. you will need to make some tests to adjust to the value you need
