### ISSUE TITLE
how to wait for vlcplayer to play a seconds before capture screen 

### ISSUE THREAD

**Issue by hoyeunglee** [ZeBobo5/Vlc.DotNet#264]
this may not be an issue,

originally vlccontrol can show black screen when tv channel no signal at the first month running

i did not change this part of code and only remove process call which send udp message at the end of loop

but do not know why when it play the tv channel which no signal , it show the previous channel screen which is static screen

no black screen to show correct current tv channel status, 

is it threading problem? how to show screen correctly?

update

after post this 

and prepare to add

Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Normal, new Action(() => {
                Thread.Sleep(10000);
            }));

after tried Dispatcher.CurrentDispatcher, it make vlc player can not play tv channel

it seems Dispatcher.CurrentDispatcher is not correct, which method can solve this problem?

public void Waitit()
        {
            Thread.Sleep(10000);
        }
main(){
...
vlcControl1.SetMedia(line);
                                    vlcControl1.Play();
                                    Thread newThread = new Thread(Waitit);
                                    newThread.IsBackground = true;
                                    newThread.Start();
                                    newThread.Join();

**Comment by jeremyVignelles** [comment]
.Join() waits for the thread to finish. In your case, this is the same as putting Thread.Sleep directly in place. Try using `System.Threading.Timer`
