### ISSUE TITLE
How to get buffer pointer position in bytes for playing media file?

### ISSUE THREAD

**Issue by catholic** [ZeBobo5/Vlc.DotNet#265]
While media file is playing, we have Time and Position attributes to get or set file play position. 
But how to get buffer pointer position in bytes (need to do this in a player) to send it to the source (server etc) to mark that we want to start download media file only from this position?

Also if anyone knows how to do this in pure C# or using external libraries please contribute

**Comment by jeremyVignelles** [comment]
Hey, now that #315 has just been merged, maybe you can solve your issue : You can download the media from your source and handle your stream as you like.
Could you please give it a try with the latest VLC.DotNet prerelease package and a nightly build of libvlc?
Please keep us updated.

**Comment by jeremyVignelles** [comment]
Closing for now, feel free to reopen if there is still an issue.
