### ISSUE TITLE
Many RTSP connections

### ISSUE THREAD

**Issue by TobiasSpatt** [ZeBobo5/Vlc.DotNet#268]
Hello,

I want to display many VlcControls with the same rtsp connection. The creation of the controls works perfectly, but when i want to play all created controls some of them keep the black color. It is always different which controls are playing.
I got a copy of my Vlc api logs:

-- logger module started --
main debug: VLC media player - 2.1.5 Rincewind
main debug: Copyright © 1996-2014 the VideoLAN team
main debug: revision 2.1.5-9-gb3fd0af
main debug: configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-twolame' '--enable-quicktime' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-mpc' '--enable-libass' '--enable-x264' '--enable-schroedinger' '--enable-realrtsp' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--disable-sdl' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--disable-dirac' '--host=i686-w64-mingw32' 'host_alias=i686-w64-mingw32'
main debug: using interface module "logger"
main debug: Creating an input for 'rtsp://IP'
main debug: using timeshift granularity of 50 MiB, in path 'C:\Users\spt\AppData\Local\Temp'
main debug: `rtsp://IP' gives access `rtsp' demux `' path `IP'
main debug: creating demux: access='rtsp' demux='' location='IP' file='\\IP'
main debug: looking for access_demux module matching "rtsp": 12 candidates
live555 debug: version 2014.05.27
live555 debug: connection timeout
live555 error: Failed to connect with rtsp://IP
main debug: no access_demux modules matched
main debug: creating access 'rtsp' location='IP', path='\\IP'
main debug: looking for access module matching "rtsp": 20 candidates
main debug: net: connecting to IP port 554
main debug: connection succeeded (socket = 2924)
access_realrtsp debug: rtsp connected
access_realrtsp warning: only real/helix rtsp servers supported for now
main debug: no access modules matched
main error: open of `rtsp://IP' failed
main error: Your input can't be opened
main error: VLC is unable to open the MRL 'rtsp://IP'. Check the log for details.

Thank you and best regards

**Comment by jeremyVignelles** [comment]
> live555 debug: connection timeout

Looks like your camera doesn't support that many streams at one time. maybe you could have any improvement by using RTP multicast, but I can't guarantee anything. Otherwise, you should probably avoid displaying the same stream on several controls, or try to find hacking Vlc.DotNet to make the Vlc instance display on several HWND handles (don't know if that would even work...)
