### ISSUE TITLE
Arghhh - cannot get past "Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

### ISSUE THREAD

**Issue by Videstra** [ZeBobo5/Vlc.DotNet#269]
I have copied EVERY x86 file, set the project to x86 and cannot get past this persistent problem! I've followed every instruction on the FAQ - how can I get past this issue - please!  My project is vb.net, using 4.6.1 framework.

**Comment by jeremyVignelles** [comment]
Are you sure your issue is related to Vlc.Net? This library does not have any dependency on CefSharp, as far as I know. CefSharp is about displaying a chrome web view inside your application.
