### ISSUE TITLE
Need help for record stream

### ISSUE THREAD

**Issue by kapitaneo** [ZeBobo5/Vlc.DotNet#272]
Hello Friends. I'm beginner in c# and in my wpf app i try create button for record stream and stop record when click. May be some one have answer on my qustion? I try change option but it does not work. When i set play() with option second time start record but app load new stream and it wrong.
Thank you all for help.

**Comment by TobiasSpatt** [comment]
Hello kapitaneo,

Try to use the following media option when calling the Play().
":sout=#duplicate{dst=std{access=file,mux=mp4,dst='[FileDestination]'},dst=display}"

Regards Tobias

**Comment by jeremyVignelles** [comment]
An answer has been provided, no reply, closing.

**Comment by Srinivasan-TA** [comment]
I want to add a record start/stop toggle button event for both rtsp and vlcplayer  recording feature.how to achieve this....

**Comment by jeremyVignelles** [comment]
I don't think this is possible with vlc to add/remove stream output at runtime.
With the latest beta version (with PR #313) you can set a DisplayVideoCallback (with SetVideoCallbacks) when a picture is ready to be displayed.
Maybe you could have some luck with that by saving pictures one by one by yourself. There are probably other solutions out there, but I can't help very much here.

However, don't expect anything that works out of the box without any work.
