### ISSUE TITLE
How can I select a video track in WPF C#?

### ISSUE THREAD

**Issue by ruffoa** [ZeBobo5/Vlc.DotNet#273]
I have a video file with 4 video tracks recorded from security cameras.  How would I select a track to view within a WPF application?

**Comment by jeremyVignelles** [comment]
How would you do this with VLC command line? If you managed to find the correct option with VLC command line, you could add that to either VlcMediaplayerOptions or as the second argument to the `Play()`  method (don't know which) and that should do the trick.
