### ISSUE TITLE
How to record the video and snap the screen

### ISSUE THREAD

**Issue by jeffreychen567** [ZeBobo5/Vlc.DotNet#279]
I only found some of the way to play it.How to achieve, at the same time, record to Local hard disk, or the Cut screen.I was using the remote monitoring Video.And record the video.Can it be realized? Can you teach me?

**Comment by jeffreychen567** [comment]
I am a Chinese, English is a little bad, I hope you understand what I mean.

**Comment by jeremyVignelles** [comment]
I suppose that the question that you wrote in #261 was related to this.

To be clear, I don't really know how to do this, but you should be able to do it with VlcMediaplayerOptions, with the same options you are giving to vlc. Also try with higher verbosity ("-vv" option) to see if there is any error messages.
Good luck

**Comment by jeffreychen567** [comment]
Thank you, my friend.I am using the C#.There is another question. Can you help me?I want to record the video that is playing.rtsp vedio. What should I do?vlcControl1.Play(@"rtsp://admin:admin@192.168.114.111:554/h264/ch1/main/av_stream",@":sout=#duplicate{dst=std{access=file,mux=mp4,dst='[c:\cjf.mp4]'},dst=display}");

**Comment by jeffreychen567** [comment]
its does not work. I want to record the files while watching the Stream media .

**Comment by jldmatwork** [comment]
Use transcode option, lookup for that.
The only problem is that i have two instances, one for saveing and one for watching, maybe i can try using just one.

**Comment by jeremyVignelles** [comment]
Closing since this is an old issue. Feel free to reopen if more help is needed.
