### ISSUE TITLE
takesnapshot is doesn't work

### ISSUE THREAD

**Issue by jeffreychen567** [ZeBobo5/Vlc.DotNet#280]
vlcControl1.TakeSnapshot(@"d:\aa.jpg");

This doesn't work.why?

**Comment by jeremyVignelles** [comment]
Please be more precise. Does it show any error message? Any crash?

**Comment by jeffreychen567** [comment]
no err message，The file is not generated in the specified directory.

**Comment by jeffreychen567** [comment]
Running normal.

**Comment by jeremyVignelles** [comment]
Closing as I cannot reproduce. If this is still an issue, please reopen and provide a sample code and more details about what you are trying to do.

I tried reproducing by adding a Snapshot button to the WPF interface linked to this click handler:
```
        private void Snapshot_Click(object sender, RoutedEventArgs e)
        {
            myControl.MediaPlayer.TakeSnapshot(@"d:\aa.jpg");
        }
```
