### ISSUE TITLE
How add folder "lib" to my project 

### ISSUE THREAD

**Issue by kapitaneo** [ZeBobo5/Vlc.DotNet#285]
Hello frieds. May be my question will be stupid but, how can i add folder "Lib" with VLC libriaries to my project and when i do publish they will be package in project? And i could setup project on other pc and all works. 
Thansk

**Comment by jeremyVignelles** [comment]
I added a "Getting started" topic in the wiki just yesterday. Maybe you will find some useful advices.
Afterwards, you will need to publish that lib folder, but that's out of the scope of that documentation.

**Comment by kapitaneo** [comment]
Thanks all. Our need in solution explorer click show all files. Click on folder an inject in project. All files must be have properties Build Action - Content. And in our code need take path.
