### ISSUE TITLE
Slow Memory Leak and Crashing

### ISSUE THREAD

**Issue by pimpmypc89** [ZeBobo5/Vlc.DotNet#286]
Is anyone else experiencing a problem where the number of Vlc.DotNet.Core.Interops.Signatures.EventCallback objects grows continuously consuming an ever growing amount of resources until an exception is thrown when what I assume is garbage collection wiping out resources being used. The exception being thrown is something along the lines of a callback on garbage collected delegate (I can replicate the problem for more details).

I have 4 VlcControl instances on one window playing RTSP streams which makes the problem happen 4x as fast. The Forms sample included shows the same problem, just never crashes. Also to note, stopping a video stream and playing either the same stream or a different one causes the EventCallback objects to continue to grow without them ever being cleared.

Digging around I found and "repaired" the steadily increasing leak, at which point the number of EventCallback objects barely grew over the course of 10 hours of running other than switching (calling Play() on a different URL) gains noted above, but then I got a "System.AccessViolationException, Attempted to read or write protected memory. This is often an indication that other memory is corrupt." in VlcManager.GetMediaDuration when the GetMediaDuration method attempted to return GetInteropDelegate<GetMediaDuration>().Invoke(mediaInstance); where mediaInstance.Pointer had a value of 0x00000000 and mediaInstance.myIsDisposing had a value of true.

**Comment by iHimiko** [comment]
That's the way it's supposed to be, just look how VLC makes the video output to the HWND.

**Comment by iHimiko** [comment]
U can use vmem

**Comment by jeremyVignelles** [comment]
Can you try with 2.2.0-develop181 ? Does the issue still appear? If yes, could you share a sample code so that I can reproduce the issue?

**Comment by jeremyVignelles** [comment]
Please try again with latest versions of Vlc.DotNet and vlc-3.0.0 and tell me if that's better
