### ISSUE TITLE
Why this controk will have an order window?

### ISSUE THREAD

**Issue by jeffreychen567** [ZeBobo5/Vlc.DotNet#287]
I don't want to see this, order window.What should I do?

**Comment by jeremyVignelles** [comment]
What do you call an "order window"? I don't understand your question.

**Comment by jeffreychen567** [comment]
when my  program start,a command window jump up，like cmd command .i donnt want it

**Comment by jeremyVignelles** [comment]
Duplicate of #248 and #267
