### ISSUE TITLE
Provide a better way to install libvlc

### ISSUE THREAD

**Issue by jeremyVignelles** [ZeBobo5/Vlc.DotNet#288]
I don't think there should be a `lib` folder in this repository.

Here are a few reasons :
## Not up-to-date
New versions of VLC are out quite often, and keeping the repository up-to-date is time consuming

## The Size of the repository
Including binary files, especially VLC DLL files, are making the repository heavy. If you want to keep up-to-date, the files will be included several times and the size will increase rapidly.

## Confusing for users
I have seen at least two issues report (#36 and #283) from user that are using the files in the library rather than downloading the version they want from the official VLC website

## Independence of the version of libvlc you are using
This library is independant of the version of VLC you are using, and providing a version would make people think that this is the only compatible version.

# My proposal
- Create two NuGet packages (.x86 and .x64) that allows yo install libVLC in a folder next to the executable. The version should be pulled directly from the official website.
- Remove the `lib` folder
- Add a reference to that packge in the sample projects
- Do not add a reference to that package in Vlc.DotNet, so that the user will be free to use any version he wants, including versions he builds himself.
- Document that in the wiki so that user knows that installing this is just a matter of installing 2-3 libraries

What do you think about this?

Edit : added the Independance point, and changed my proposal

**Comment by ZeBobo5** [comment]
Would you like to be contributor ? I don't have time to work on project now

**Comment by jeremyVignelles** [comment]
Great, thanks a lot for your invite! I'll merge that soon

**Comment by jeremyVignelles** [comment]
I've got news from Martin Finkel, from VideoLan. He doesn't seem against the idea of a VideoLan's official NuGet package for LibVlc. To be continued...

**Comment by Kelsinga** [comment]
Any update on this?

**Comment by jeremyVignelles** [comment]
Hi,
Some attempts have been made ( https://github.com/mfkl/libvlc-nuget available at https://www.myget.org/feed/libvlc-x64/package/nuget/VideoLAN.LibVLC.Win.x64 ) but nothing ready for production yet. The discussion is still going on to integrate this packaging in the vlc building workflow, on VideoLAN's side.
I think this will give something nice and officially supported by VideoLAN, but we still need to be patient...

**Comment by Kelsinga** [comment]
Thanks for the quick reply. 
Good to know it's being worked on.

**Comment by jeremyVignelles** [comment]
A new package has been published by VideoLAN on NuGet, let's start using it!
https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/3.0.0-alpha2

**Comment by Altiano** [comment]
So, On "How To Use" Guide,
Should we just install the nuget as the replacement for step #2?

**Comment by jeremyVignelles** [comment]
Yeah, sure, can you make the PR for that (with commit message starting with `[skip ci]` so that we don't publish a new package)?

**Comment by jeremyVignelles** [comment]
Nevermind, I updated the readme.

https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/ now has 3.0.4 for those who are interested in this topic 🙂
