### ISSUE TITLE
Not supporting events?

### ISSUE THREAD

**Issue by lrsitod** [ZeBobo5/Vlc.DotNet#289]
VlcControl vlc = sender as VlcControl;
vlc.PreviewMouseDown += vlc_PreviewMouseDown;           
vlc.MediaPlayer.AllowDrop = true;
vlc.MediaPlayer.DragDrop += MediaPlayer_DragDrop;
vlc.MediaPlayer.Click += MediaPlayer_Click;

None of these events can be triggered

**Comment by iHimiko** [comment]
Yes, it doesn't work, because in Vlccontrol video rendered the Directx tools

**Comment by lrsitod** [comment]
Is there any way to solve this problem?

**Comment by jeremyVignelles** [comment]
maybe you could try putting an overlay window over the player, but that could be hard to do. see #296 for info about the airspace issue and a possible workaround of it. I can't think about another alternative right now, and I didn't test that solution either

**Comment by jeremyVignelles** [comment]
This answer presents a workaround for the airspace issue : https://stackoverflow.com/questions/5978917/render-wpf-control-on-top-of-windowsformshost/23662410#23662410

Please reopen if you need something else.
