### ISSUE TITLE
Vlc.DotNet.Wpf is not WPF, it's Winforms in WindowsFormsHost

### ISSUE THREAD

**Issue by kolorowezworki** [ZeBobo5/Vlc.DotNet#291]
I've come here to check how WPF control will work, but it's already Winforms control with airspace effect, so it shouldn't be named WPF control. Original ActiveX VLC plugin is working the same way.  

Reference:
https://msdn.microsoft.com/pl-pl/library/aa970688(v=vs.85).aspx

**Comment by jeremyVignelles** [comment]
Discussion is already started to improve this, see #249 and #296
