### ISSUE TITLE
Multiple video filters adjustment not working.

### ISSUE THREAD

**Issue by sysroad** [ZeBobo5/Vlc.DotNet#293]
for example code below is not working correctly.
second filter ignored.

`var player = new VlcControl() {
    VlcMediaplayerOptions = new string[]
    {
        "--video-filter=transform,sepia",
        "--sepia-intensity=100",
        "--transform-type=180"
    }
}`

**Comment by remy33** [comment]
Try to use filters inside the Sout

**Comment by sysroad** [comment]
Changing filter separator ',' to ':' works.

**Comment by remy33** [comment]
XD,that's a possibility.
You can simply create logs and see what's the problem is.
