### ISSUE TITLE
Get video information before playing

### ISSUE THREAD

**Issue by Fergo** [ZeBobo5/Vlc.DotNet#294]
Hey there!

Is there any option to grab the video information before using the Play() method? 

I tried using SetMedia() and adding a MediaChanged event handler, but even inside the event handler, I don't seem to be able to call the GetCurrentMedia() method in order to get the media information (it says it's not available in the current context).

At the moment, I'm just calling Play() and Stop(), so it actually loads the media and allows me to call the GetCurrentMedia() method.

Any ideas?

**Comment by remy33** [comment]
If I remember currect, SetMedia() return a VlcMedia object in which you can grab info.

**Comment by Fergo** [comment]
> If I remember currect, SetMedia() return a VlcMedia object in which you can grab info.

Unfortunately, it returns void. SetMedia() seems to do basically the same thing as Play(), but it doesn't start playing right away (but doesn't allow me to call GetCurrentMedia() too).

**Comment by jeremyVignelles** [comment]
There is an option in libvlc to start "parsing" the media before it plays. it just need to be made available to vlc.dotnet

**Comment by RolandoKRC** [comment]
This way I was able to get the data before playing it:

myVlcMediaInstance = myVlcManager.CreateNewMediaFromPath(openFileDialog.FileName);
//get metadata
Parse();
TxtTitle.Text = GetMetaData(MediaMetadatas.Title);

I hope you find it useful

**Comment by jeremyVignelles** [comment]
Thanks @RolandoKRC ! It looks like there is the Parse() method on the `VlcMedia` object. Can this issue be closed then?

**Comment by RolandoKRC** [comment]
I'm sorry, I forgot to directly specify the method my parse () function calls, the method it calls is myVlcManager.ParseMedia (myVlcMediaInstance);
I estimate that with this solution it can be closed.
regards

**Comment by jeremyVignelles** [comment]
OK, closing this issue then. Feel free to reopen if you feel something is missing

**Comment by wantRP** [comment]
> 
> 
> This way I was able to get the data before playing it:
> 
> myVlcMediaInstance = myVlcManager.CreateNewMediaFromPath(openFileDialog.FileName);
> //get metadata
> Parse();
> TxtTitle.Text = GetMetaData(MediaMetadatas.Title);
> 
> I hope you find it useful

Can you make it clearly?I tried
```
VlcControl vcontrol = new VlcControl();
vcontrol.SourceProvider.CreatePlayer(this.vlcLibDirectory);
vcontrol.SourceProvider.MediaPlayer.SetMedia(myuri);
VlcMediaPlayer vlcMediaPlayer = vcontrol.SourceProvider.MediaPlayer;
VlcManager vlcManager= vlcMediaPlayer.Manager;
vlcManager.CreateNewMediaFromPath(myptah);
VlcMediaInstance myVlcMediaInstance = vlcManager.CreateNewMediaFromPath(myptah);
Console.WriteLine( vlcManager.GetMediaDuration(myVlcMediaInstance));
```
then it appears exception.

**Comment by wantRP** [comment]
now i found a way.
```
VlcControl vcontrol = new VlcControl();
vcontrol.SourceProvider.CreatePlayer(this.vlcLibDirectory);
vcontrol.SourceProvider.MediaPlayer.SetMedia(new Uri("XXX"));
VlcMediaPlayer vlcMediaPlayer = vcontrol.SourceProvider.MediaPlayer;
VlcMedia media = vlcMediaPlayer.GetMedia();
media.Parse();
Console.WriteLine(media.Duration);
```

**Comment by Yuri-Belkasoft** [comment]
I tried the last piece of code but got zero duration - though the file is being played OK with the same player. What can be a reason of zero duration?

**Comment by Yuri-Belkasoft** [comment]
I was able to get correct duration using ParseAsync + ParsedChanged event. Strange that sync method does not work.
