### ISSUE TITLE
`.MediaPlayer.Time` doesn't seem to update properly

### ISSUE THREAD

**Issue by Reyth3** [ZeBobo5/Vlc.DotNet#298]
I wanted to add a `TextBlock` showing the current time for testing purposes, so I added the following inside the `.TimeChanged` event handler:

    tb.Text = TimeSpan.FromMiliseconds(vlc.MediaPlayer.Time);

That's when I noticed that something isn't right. I created a simple dispatcher timer with an interval of 500ms and started logging the `Time` property. Here are the results:

    0
    0
    0
    0
    2937
    2937
    2937
    2937
    2937
    5107
    5107
    6440
    6440
    6440
    6440
    6440
    6440
    6440
    6440
    6440
    6440
    11366

As you can see, at first it takes ~2s to update the property, then a bit longer after that, then shorter, and then finally ~5 seconds, which is just plain unacceptable.

I'm not yet sure if that changes depending on the file, quality, compression etc, since I don't have any files on hand to test that.

Am I doing something wrong or missing something here?

***Edit:*** Seems to break only with Matroska container, than again the problem might be entirely on my end.

**Comment by jeremyVignelles** [comment]
Do you experience that kind of behaviour when launching this in VLC? which version of libvlc?

**Comment by Reyth3** [comment]
Just downloaded the latest version of VLC and it works perfectly.

Previously I was using the libraries from this repo.

Thanks!

**Comment by jeremyVignelles** [comment]
good to know, thanks!
