### ISSUE TITLE
WinForms draw text over video playing

### ISSUE THREAD

**Issue by evo744** [ZeBobo5/Vlc.DotNet#301]
I tried using VlcMediaplayerOptions with --sub-source="marq{marquee=testccvvc,color=16776960}" but it did nothing. Anything I can do?

**Comment by jeremyVignelles** [comment]
Could you try removing the quotes around the parameter value? like the example I gave in #205

**Comment by evo744** [comment]
I did, tried again just now and still nothing happens. I also updated to 2.1.154 with no change

**Comment by jeremyVignelles** [comment]
Which version of libvlc? could you try with latest nightly?

**Comment by evo744** [comment]
it works with the latest lib but you can't change it or remove it once the player is loaded.

**Comment by jeremyVignelles** [comment]
You're right. I think I have seen another plugin than marq that allows to change that programmatically with libvlc, but I don't think that would work with Vlc.DotNet without modification

**Comment by evo744** [comment]
so currently there is no way to do it without modifications?

**Comment by jeremyVignelles** [comment]
I don't think so. Maybe you would have more chance in WinForms than in WPF for displaying labels above the video, but really without warranty. in any case, please post updates of your findings.

If you want to implement the functions for the plugin that is mentioned above for Vlc.DotNet, then please make a PR, thank you.

**Comment by evo744** [comment]
I'm using WinForms. I'll try some things and update if find anything

**Comment by jeremyVignelles** [comment]
Closing since a workaround has been found. Feel free to reopen if you need something else.
