### ISSUE TITLE
Video not starting with space in url

### ISSUE THREAD

**Issue by SheppeR** [ZeBobo5/Vlc.DotNet#31]
Hi, 

I have a issue with space in url when i try to play a video hosted on a web server.

Example:
http://example.com/prev 01.mp4        -> will never start
http://example.com/prev%2001.mp4  -> will never start
http://example.com/prev01.mp4         -> will start without problems

Best regards

**Comment by jeremyVignelles** [comment]
Which version of libvlc? Can you share a sample code? Did you try to upgrade libvlc version?

I'm closing since this is an old issue, please reopen if you are still interested.
