### ISSUE TITLE
Last version (2.2.0-develop193) huge memory leak

### ISSUE THREAD

**Issue by evo744** [ZeBobo5/Vlc.DotNet#318]
# Generic information

- **Vlc.DotNet version** : 2.2.0-develop193
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 64-bit | https://nightlies.videolan.org/
- **.net version** : 4.5
- **Project language** : vb.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 64-bit

# Summary

Every time I stop and play the memory usage increases. it gets to about 600-700 mb used after 10 stop-play

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Thanks for your bugreport. I hope to have a look at it in the next few days.
If you want me to spare some time, could you try a few thing for me?
1. Are you able to reproduce the bug with one / all of the samples (modified if needed)?
2. Are you able to reproduce with latest stable version?

**Comment by jeremyVignelles** [comment]
might be related to #286

**Comment by evo744** [comment]
The problem only seems to occur with the **visual studio debugger**. If normally opened there is no problem... Never had this before. Sorry about this, I should of checked

**Comment by jeremyVignelles** [comment]
Maybe VS is tracing the memory as it is used and consumes a lot. Thanks for the feedback anyway, you're welcome 👍
