### ISSUE TITLE
Video playback and audio issues playing HLS streams

### ISSUE THREAD

**Issue by SenalPereraAMG** [ZeBobo5/Vlc.DotNet#322]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.1.154
- **Vlc.DotNet project used** : WPF
- **libvlc version** :  Tried with 2.1.6 and 2.1.1 + got from videolan
- **.net version** : 4.6.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64

# Summary

I have trouble playing some .m3u8 links. A few links play perfectly while some links have broken audio and most don't play at all. All streams were tested on VLC player and they work perfectly.
I receive the following error:
access_mms access error: error: HTTP/1.0 400 Bad Request
main stream error: no suitable access module for "url"
**Note:** Unfortunately I'm not allowed to share the url.

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
I can't see how this could be related to Vlc.DotNet. please upgrade your libvlc version. 2.1 is not supported anymore. I'd recommend using libvlc -3.0.0 nightlies

**Comment by SenalPereraAMG** [comment]
Thank you for the quick response. I tried using 3.0.0 nightlies and 2.2.6 vlc libraries. Unfortunately it has no affect on the audio but the video quality seems to have improved.

**Comment by jeremyVignelles** [comment]
And using the VLC.exe that you downloaded with the nightlies, does it have the same issue? Can you share some logs? (Pass the options: `"-vv", "--extraintf=logger", "--logfile=Logs.log"`, remove any sensitive data and share it with us)

**Comment by SenalPereraAMG** [comment]
Hi, My sincere apologies for the late response. I have been communicating with our development head to try and get you a working link. If you can send me an IP address we can enable that IP to work with our links. Please email me "senal@asiamediaglobal.org".

**Comment by jeremyVignelles** [comment]
Hi,
This project is run by volunteers on their free times, including myself. I don't have much time to have a look at it, and thus I can't really help with that.

However, I can give you a few pointers:
- Could you try with libvlc or libvlcpp directly, in a C/C++ project?
- Could you check the load of the CPU when playing those links?
- Is that possible that you are doing some action in one of the Vlc.DotNet callback without switching thread? That could delay the normal work of libvlc and lead to what you are seeing.

**Comment by jeremyVignelles** [comment]
Did you manage to find a solution? Shall we close this?

**Comment by SenalPereraAMG** [comment]
Hi, 
Thank you for you help. However the project was put on hold by my company hence I haven't been working on it. I apologize for the late response.

**Comment by jeremyVignelles** [comment]
Then, closing this for now, reopen if needed.
