### ISSUE TITLE
Defualt Video Conrols (play, stop, seek bar, etc...)

### ISSUE THREAD

**Issue by B0R1K** [ZeBobo5/Vlc.DotNet#331]
Hi,

Is there a way to display default video controls play, stop, seek bar, etc...)?

I am suing C# WPF, .net 46.

Thank you,

Basically what i want to accomplish is full functionality of VLC, but it would stop every 2 min ask a user a question, if answered correctly it will continue... 

Thank you.

**Comment by jeremyVignelles** [comment]
Hi,
Unfortunately, it's out of the scope of this library, which is designed to give access to libvlc through .net code.
The controls that you mention are part of vlc itself and is written in c++/Qt, so there is no easy way to do that.
You have to write your own controls around that.
Sorry.
