### ISSUE TITLE
How do I get the length of the audio being played?

### ISSUE THREAD

**Issue by SwaroopSomanna** [ZeBobo5/Vlc.DotNet#333]
I have an issue with getting the length/duration of an audio file that has been loaded with the setMedia method. 

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Winforms
- **libvlc version** : 2.2.5.1 x86 I got it from the installation directory of VLC Media Player
- **.net version** : 4.5.2
- **Project language** : VB. Net
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 8.1 x64

# Summary

I want to make a trackbar behave as a progress bar for the audio file
So I need to set the maximum value of the trackbar to the duration/length of the audio track
For that I tried using;
p.Length
p.GetMedia.Duration
p.GetMedia.Duration.TotalSeconds
p.GetMedia.Duration.TotalMilliseconds
Where p is a VlcMediaPlayer variable

Whenever those codes are executed they produce values such as -1, -1.0000, 0.001 etc but not the actual duration of the audio track

Those codes are executed as soon as I click on the play button

Below is the code of the play button
p.Play
TrackBar1.Maximum = p.GetMedia.Duration.Milliseconds
The exception is "0 is not valid for value. Value should be between minimum and maximum"

The value of TrackBar1.minimum is set to 0 during design time. 

The trackbar progresses with the following codes:

Private Sub....... Handles Timer1.Tick
TrackBar1.Value = p.Time
' Timer interval is set to 1 millisecond

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Those data are only available after the media has started playing. Did it start in your case?

There is another method in libvlc, called "parse" (if I remember correctly) that make those data available without playing, but it is not yet implemented in LibVlc.DotNet.

**Comment by TheGeka** [comment]
i have done the same with this event `"this.vlcControl1.Playing += new System.EventHandler<Vlc.DotNet.Core.VlcMediaPlayerPlayingEventArgs>(this.SetProgresMax);` it fires when you start the Playback of your File this the Called Method 

**SetProgesMax** :
`private void SetProgresMax(object sender, VlcMediaPlayerPlayingEventArgs e)
        {
            Invoke(new Action(() =>
            {
                var vlc = (VlcControl)sender;
                trackBar1.Maximum = (int)vlc.Length;
            }));
        } `

I hope this will help :)

**Comment by jeremyVignelles** [comment]
Getting media info before playing is already tracked by #294. Closing this issue
