### ISSUE TITLE
--program command doesn't  work

### ISSUE THREAD

**Issue by JUSTHassan** [ZeBobo5/Vlc.DotNet#336]
# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WPF 
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU 
- **Operating system** : Windows 7 x64

# Summary

I've tried  `--program`  as an option in the command line to start a specific program from my `MPEG-TS ` stream file.
`vlc --program 906 hotbird.mpeg`  it worked fine, but when I'm trying to use this option in VLC.dotnet in `setMedia()` function it didn't work and starts the default stream.

I've tried this ways
1-
`vlcControl.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program=906");`

`vlcControl_Copy.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program=905");`

`vlcControl_Copy1.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program=904");`

`vlcControl_Copy2.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program=903");`

2-
`vlcControl.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program 906");`

`vlcControl_Copy.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program 905");`

`vlcControl_Copy1.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program 904");`

`vlcControl_Copy2.MediaPlayer.SetMedia(new Uri(String.Format("hotbird.mpeg")), ":--program 903");`

where is the problem ?? 

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Before the call to EndInit, you should be able to do this, if I remember correctly:
```
vlcControl.MediaPlayer.VlcMediaplayerOptions = new {
    "--program",
    "906"
};
```

**Comment by JUSTHassan** [comment]
thanks jeremyVignelles it works missing ```string []```  
```
vlcControl.MediaPlayer.VlcMediaplayerOptions = new string[]{
    "--program",
    "906"
};
```

**Comment by jeremyVignelles** [comment]
`string` is useless, but `[]` is indeed required.
Glad it helped, feel free to ask if you need something else 😉
