### ISSUE TITLE
Youtube video can not be played

### ISSUE THREAD

**Issue by jonijm** [ZeBobo5/Vlc.DotNet#345]
Hi! 

I am trying in "myControl.MediaPlayer.Play(new Uri("https://www.youtube.com/watch?v=GMFewiplIbw")), but it doesn't work;", it's strange...anybody can help me?

This is the trace:
libVlc : Debug Name: Becky G, Bad Bunny - Mayores (Official Video) ft. Bad Bunny @ lua
libVlc : Debug meta-URL: https://www.youtube.com/watch?v=GMFewiplIbw @ lua
libVlc : Debug removing module "lua" @ core
libVlc : Debug ArtURL: https://i.ytimg.com/vi/GMFewiplIbw/maxresdefault.jpg @ lua
libVlc : Debug removing module "http" @ core
libVlc : Debug removing module "record" @ core
El subproceso 0xc18 terminó con código 0 (0x0).
El subproceso 0xc9c terminó con código 0 (0x0).
El subproceso 0xd28 terminó con código 0 (0x0).
El subproceso 0xf54 terminó con código 0 (0x0).

Vlc.DotNet version : 2.2.1
Vlc.DotNet project used : WinWpf
libvlc version : x86, 2.2.6 and 3.0.0
.net version : 4.0
Project language : Visual C#
Project build architecture : x86
Operating system : Windows 7 x64

Thanks!

**Comment by ebalmol** [comment]
Did you finally get it? I have the same problem :(

Thanks!

**Comment by jeremyVignelles** [comment]
There has been work made on the youtube lua script recently, but I don't know if this is related. did you try the latest nightly build?

**Comment by jeremyVignelles** [comment]
Please also confirm that your issue don't show up with vlc.exe

**Comment by ebalmol** [comment]
With vlc.exe it works fine. 
I have tested it with Vlc.DotNet 2.2.1, I'll try it with 2.2.2.

Thanks,

**Comment by jeremyVignelles** [comment]
Please also try with vlc-3.0.0 nightly from nightlies.videolan.org

**Comment by ebalmol** [comment]
With vlc-3.0.0 nightly from nightlies.videolan.org it works (x86 and x64 are ok).

**Comment by ebalmol** [comment]
Hi again,

I've been working on this and It's possible that playing youtube videos is only supported under playlist feature (https://stackoverflow.com/questions/11436864/vlc-python-doesnt-play-youtube-video).

If you look for youtube lua it is under Playlist folder.

I have been looking for playing Playlist with vlcdotnet and I think it is still not possible, isn't it? Does anyone know if it will be developed in the near future?

Thanks,

**Comment by jeremyVignelles** [comment]
@ebalmol : Thanks for your finding. Indeed, playlists are not (yet?) supported by Vlc.DotNet. This is tracked by #193 . It is not currently planned to add playlist support in Vlc.DotNet, but I welcome contributions :) If you want to contribute and need help to implement it, feel free to join the gitter discussion.

**Comment by yewnok** [comment]
Can it be a solution?
https://stackoverflow.com/questions/40264207/how-can-i-play-youtube-videos-with-vlc-dotnet-library-in-wpf/40278491#40278491

**Comment by jeremyVignelles** [comment]
It might be a solution. I did not test and do not guarantee that this will work.

I think that youtube streaming URL is purposefully opaque so that you use their player or their website. This means that whatever the way you try to reach it, it is a hack and you're not sure it will still work in the future...

**Comment by MachDemon** [comment]
I can play youtube video using YouTubeExplode [https://github.com/Tyrrrz/YoutubeExplode]
My code snippet - I am passing a string like https://youtu.be/hI3GaXL96Ws

` private async void PlayYouTubeVideoAsync(string youtubeVidId)
        {
            var yt = new YoutubeClient();
            var video = await yt.GetVideoMediaStreamInfosAsync(youtubeVidId);
            var muxed = video.Muxed.WithHighestVideoQuality();

            vlcControl.SetMedia(new Uri(muxed.Url));
            vlcControl.Play();
            vlcControl.Visible = true;
        }`

**Comment by jeremyVignelles** [comment]
This looks nice, thanks for sharing your findings @MachDemon ;-)

**Comment by jeremyVignelles** [comment]
Since there's no answer from the original poster, I'm going to close that, because several options have been provided.

**Comment by nekinci** [comment]
>  var url = "https://youtu.be/PbGDH_JOM9w";
>             var youtubeVidId = YoutubeClient.ParseVideoId(url);
>             var yt = new YoutubeClient();
>             var video = await yt.GetVideoMediaStreamInfosAsync(youtubeVidId);
>             var muxed = video.Muxed.WithHighestVideoQuality();
> 
>             vlcControl.SetMedia(new Uri(muxed.Url));
>             vlcControl.Play();

Thank you very much.
