### ISSUE TITLE
question rtsp server based on vlc.dotnet

### ISSUE THREAD

**Issue by Stakhmi4** [ZeBobo5/Vlc.DotNet#349]
I have a a question about Vlc.DotNet.

i have camera (not ip), which connect to computer using plate. i recive byte array from the plate. and i want create rtsp server: send recived bytes.

    string libDirectory = @"C:\Program Files\VideoLAN\VLC"; // installed vlc 3.0.0-20171112-0458
    var mediaPlayer = new Vlc.DotNet.Core.VlcMediaPlayer(new DirectoryInfo(libDirectory));
    var mediaOptions = new string[]
            {
                @":sout=#rtp{sdp=rtsp://:14789/test,proto=tcp}",
                ":sout-keep"
            };
    MemoryStream ms = new MemoryStream();
    var vlcMedia = mediaPlayer.SetMedia(ms, mediaOptions);
    mediaPlayer.EndReached += (sender, e) =>
            {
                playFinished = true;
            };
    /*
    i dont know what do here
    i try 
                byte[] data = packet.Data;
                ms.Write(data, 0, data.Length);
    but mediaPlayer finished player very fast, and i cannot streaming new byte array
    */
    mediaPlayer.Play();

# Generic information

- **Vlc.DotNet version** : (Please fill)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (x64) - install vlc player 3.0.0-20171112-0458
- **.net version** : (4.6.1)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows 10 x64)

# Summary

**Comment by jeremyVignelles** [comment]
Hi,
I don't know "plate" so it won't be easy to help. Could you send me a link?
I think you were right when you were using `ms.Write(...)`, but you will need to identify the type of data you are giving as input. Is that a picture, with decoded bytes? is that a mpeg stream?...

Please keep in mind that RTSP streaming in VLC is not very stable, and I wouldn't use it for production.

**Comment by medzik1993** [comment]
Hi, 
I have similar problem. Simply i want to convert C# stream to file.
My code look like this 
`
            var libDirectory = @"C:\Temp\libvlc";

            var options = new string[]
            {
                "--demux=h264",
            };

            var mediaPlayer = new VlcMediaPlayer(new DirectoryInfo(libDirectory),options);
            mediaPlayer.Log += Log;

            var mediaOptions = new string[]
            {
                @":sout=#file{dst=C:\Temp\test.mp4}",
            };
            using (FileStream stream = File.OpenRead(fileName))
            {
                mediaPlayer.Play(stream, mediaOptions);
            }
`
In feature I would switch FileStream for some stream come form api.  
I successfully convert my test file using normal FileInfo (mediaPlayer.Play(new FIleInfo(fileName), mediaOptions);). but this now with stream a have big problem. 
I read here : `https://stackoverflow.com/questions/31250640/using-vlc-imem-to-play-an-h264-video-file-from-memory-but-receiving-error-main` that new 3.0.0 api should be available to do this. 

this is how my log looks like: 
`main Debug VLC media player - 3.0.0-rc7 Vetinari
main Debug Copyright © 1996-2018 the VideoLAN team
main Debug set config option: sout-standard-dst to C:\Temp\test.mp4
stream_out_standard Debug using `file/mp4://C:\Temp\test.mp4'
main Debug looking for sout access module matching "file": zd candidates
main Debug using sout stream module "stream_out_standard"
main Debug revision 3.0.0-rc6-2-ged5177c851
main Debug using sout access module "file"
main Debug `imem://' gives access `imem' demux `h264' path `'
main Debug looking for sout mux module matching "mp4": zd candidates
main Debug looking for sout stream module matching "file": zd candidates
main Debug Creating an input for 'imem://'
main Debug using sout mux module "mp4"
main Debug looking for access module matching "imem": zd candidates
main Debug using access module "imem_access"
main Debug looking for stream_filter module matching "prefetch,cache_read": zd candidates
main Debug configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-twolame' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-mpc' '--enable-libass' '--enable-x264' '--enable-schroedinger' '--enable-realrtsp' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--host=i686-w64-mingw32' '--enable-debug' 'host_alias=i686-w64-mingw32' 'PKG_CONFIG_LIBDIR=/home/jenkins/workspace/vlc-nightly/vlc-3.0-nightly-win32-x86/contrib/i686-w64-mingw32/lib/pkgconfig'
main Debug stream=`file'
file Debug file access output opened (C:\Temp\test.mp4)
imem_access Error read error
prefetch Debug end of stream
playlist Debug not enough data
lua Debug Trying Lua scripts in C:\Users\Rico\AppData\Roaming\vlc\lua\playlist
lua Debug Trying Lua scripts in C:\Temp\libvlc\lua\playlist
main Debug no stream_filter modules matched
main Debug looking for stream_directory module matching "any": zd candidates
main Debug no stream_directory modules matched
main Debug attachment of directory-extractor failed for imem://
main Debug looking for stream_filter module matching "record": zd candidates
main Debug using stream_filter module "record"
mp4 Debug Mp4 muxer opened
main Debug using timeshift granularity of 50 MiB
main Debug using sout chain=`file{dst=C:\Temp\test.mp4}'
main Debug using timeshift path: C:\Users\Rico\AppData\Local\Temp
main Debug using packetizer module "h264"
main Debug using demux module "h26x"
main Debug starting in sync mode
main Debug no access_demux modules matched
imem Error Invalid get/release function pointers
main Debug looking for packetizer module matching "any": zd candidates
main Debug looking for access_demux module matching "imem": zd candidates
main Debug creating access: imem://
main Debug creating demux: access='imem' demux='h264' location='' file='(null)'
main Debug looking for stream_filter module matching "any": zd candidates
main Debug using stream_filter module "prefetch"
main Debug no meta reader modules matched
prefetch Debug using zu bytes buffer, zu bytes read
main Debug EOF reached
main Debug removing module "h26x"
main Debug removing module "h264"
main Debug removing module "record"
main Debug removing module "prefetch"
main Debug creating demux: access='imem' demux='h264' location='' file='(null)'
main Debug `imem://' successfully opened
main Debug looking for demux module matching "h264": zd candidates
h26x Error this doesn't look like a h264 ES stream, continuing anyway
lua Debug Trying Lua scripts in C:\Users\Rico\AppData\Roaming\vlc\lua\meta\reader
lua Debug Trying Lua scripts in C:\Temp\libvlc\lua\meta\reader
main Debug removing module "imem_access"
main Debug looking for meta reader module matching "any": zd candidates
`

Any ideas ? 

Thanks for help

**Comment by jeremyVignelles** [comment]
@medzik1993 : Please open your own issue, these are two separate things.

Please also be careful of the formatting of your message, it's unreadable, and paste your logs as an attachment rather than in the message body.

Regarding this issue, I have no answer from original poster for a very long time, so I'm closing this in the meantime. Feel free to reopen if needed.
