### ISSUE TITLE
Replace the x64 binaries in the NuGet package with AnyCPU ones

### ISSUE THREAD

**Issue by ddobrev** [ZeBobo5/Vlc.DotNet#35]
The WinForms designer crashes with x64 ones.

**Comment by sepehr1014** [comment]
Have you seen this one? https://github.com/ZeBobo5/Vlc.DotNet/issues/24

**Comment by MaitreDede** [comment]
Hi,

I would like to see this too.

The Vlc.DotNet references added to my project are x86, but I have to run it on both x86 and x64. So AnyCPU will do the trick.

**Comment by jeremyVignelles** [comment]
Fixed in recent versions
