### ISSUE TITLE
Interactive Zoom

### ISSUE THREAD

**Issue by SkinnySackboy** [ZeBobo5/Vlc.DotNet#351]
Hi,

Is anyone aware of a way to enable interactive zoom just as you can in the standalone VLC player, to allow users to dynamically change which zoomed portion of the video they would like to be viewing?

Thanks,

Mark

**Comment by jeremyVignelles** [comment]
In the Wpf component, you will soon be able to do that with an ImageBrush (I guess) in 3.0.0. See #365

**Comment by jeremyVignelles** [comment]
As of Vlc.DotNet 3.0.0-develop250, you should probably be able to implement that, but that requires some work on your side. You have an ImageSource, so you can do whatever you want with that 😃 

Good luck, and feel free to join the gitter discussion if you need help.
