### ISSUE TITLE
Problems with VLC 2.2.6 and 3.0.0 while playing HLS (.M3U8)

### ISSUE THREAD

**Issue by jonijm** [ZeBobo5/Vlc.DotNet#352]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 and x64
- **.net version** : 4.0
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 7 Professional (x64) in VirtualBox

# Summary

I'm doing tests with HLS (.M3U8) and the following is happening to me (these are some examples):

HLS v3 "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8" (NO AUDIO in VLC 2.2.6 and sometimes fails, OK in 3.0.0).
HLS v1 "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8" (HAS NO AUDIO in VLC 2.2.6 and sometimes fails, OK in 3.0.0)
HLS v3 "https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8" (OK in 2.2.6, in 3.0.0 saturates memory and does not play)
HLS v5 "http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8" (Does NOT work in 2.2.6, OK in 3.0.0)
HLS v3 "http://www.streambox.fr/playlists/test_001/stream.m3u8" (OK in 2.2.6, in 3.0.0 saturates memory and does not play)

In the cases where I write "sometimes fails", the error is always "The program '[844] X.exe' ended with code -1073741819 (0xc0000005) 'Access violation'." What is curious is that with the version of VLC 3.0.0 in the desktop program, the cases where I write "saturates memory and does not play" work perfectly. I understand that these problems are due to the wrapper, but I can not find an explanation. Remember that I am using Visual Studio 2017. Is anyone else experiencing these problems?

Log output is here: https://pastebin.com/9bdmmGtQ. Someone can try the "https://github.com/ZeBobo5/Vlc.DotNet/tree/develop/src/Samples/Vlc.DotNet.Wpf.Samples" with the sample HLS "http://www.streambox.fr/playlists/test_001/stream.m3u8", Vlc.DotNet 2.2.1 and VLC 3.0.0? It would be good for me to know if it is a problem of mine or of the library itself (with the "Vlc.DotNet.Wpf.Samples" the memory is also saturated and no image of the video is shown).

Thanks!!!

**Comment by jeremyVignelles** [comment]
Hi,
I tried with VLC 3.0.0 (not libvlc but the media player) with the stream : http://www.streambox.fr/playlists/test_001/stream.m3u8 
It turns out that the stream stops after 3s, the memory increases and then after a while, VLC gives up.

Could you try again and confirm that your issue only happen in Vlc.DotNet and not in VLC itself on your side?

**Comment by jeremyVignelles** [comment]
No answer for a long time, please reopen if this is still an issue.
