### ISSUE TITLE
Adding a Shadereffect to the VLC MediaElement

### ISSUE THREAD

**Issue by TomTomB** [ZeBobo5/Vlc.DotNet#353]
# Generic information

- **Vlc.DotNet version** : Current one
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86/x64 2.2.6 - from official FTP
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 Pro x64

# Summary

I would like to add a pixelshader effect to the media element.
Is there any way of doing something like this:
`MyPlayer.MediaPlayer.Effect = new MySuperEffect();`

Cheers

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
I don't know if this is currently possible.

Do you want something dynamic? If the answer is no, then you probably can pass a flag at initialization, as you would have done with the vlc command line.

**Comment by TomTomB** [comment]
Hi,

I don´t know what you actually mean with "something dynamic".
Sorry, I am quiet a newbie to vlc/vlc.dotnet.

So, let´s say I have a classic "DeepColor" effect:
```c#
public class DeepColorEffect : ShaderEffect
{
        public static DependencyProperty InputProperty =
            RegisterPixelShaderSamplerProperty("Input", typeof(DeepColorEffect), 0);

        public DeepColorEffect()
        {
            var u = new Uri(@"" + GlobalVars.ExecutePath + "Effects/DeeperColor.ps");
            PixelShader = new PixelShader {UriSource = u};
            UpdateShaderValue(InputProperty);
        }
}
```
Is there a way to add this effect to the vlc media element like:
`MyPlayer.MediaPlayer.Effect = new DeepColorEffect();`

If it´s possible it would be really nice if you could provide a small code snippet to get me going.

Thanks for your time

**Comment by jeremyVignelles** [comment]
Oh, I think I misunderstood your request. Are you trying to use https://msdn.microsoft.com/fr-fr/library/system.windows.media.effects.shadereffect(v=vs.110).aspx ?

If yes, unfortunately, It is not possible with the current version of Vlc.DotNet, because the Wpf component is not a "native Wpf component" but rather is using the WinForms component under the hood. That causes many issues, because a window is rendered on top of the Wpf controls and can't be styled "The Wpf Way"

**Comment by TomTomB** [comment]
Sadly, yes that´s what I wanted to use. And I guess there are no plans on creating a proper Wpf control because it would be pretty hard to do?

**Comment by jeremyVignelles** [comment]
We do have a plan to rewrite an VideoLan-supported .net wrapper around libvlc. It is currently an early stage and yet doesn't work. There is no WPF control either yet.

We are planning to create a Wpf control that is based on DirectX, but that would require using the winRT builds of LibVlc. I still don't know yet how that would work.

As for making that breaking change in this library, I don't think I will have time to do that on my own.

If you are looking at a more "Wpf-ish" control, I know about https://github.com/higankanshi/Meta.Vlc, I don't know about perfs, but at least it's WPF.

Other options include "creating your own filter plugin in C/C++ and build it with your own VLC". The amount of work is really bigger, but perfs and cusomizations will probably be at their best.

**Comment by TomTomB** [comment]
I´ve already tried Meta.Vlc and don´t really like it. Of cause it´s a Wpf control, but it comes with many other problems - and it seems like the developer stopped working on it. 
My C/C++ skills are... well pretty limited I would say so writing my own plugin is not an option. 

Anyways thanks for taking your time
I think we can close this one now.

**Comment by jeremyVignelles** [comment]
Ok, keep an eye on what's going on on this repository and mfkl's work 😉
