### ISSUE TITLE
[question]Trying too play raw H.264 video using .NET 4.0 WinForms sample project

### ISSUE THREAD

**Issue by redxar** [ZeBobo5/Vlc.DotNet#354]
Hi all,

I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : Latest stable 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : vlc-2.2.6-win64 ->  http://download.videolan.org/pub/videolan/vlc/
- **.net version** : 4.0
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** :  Windows 7 Enterprise x64
-        [x ] I confirm that my issue doesn't happen in VLC itself.

# Summary
[output.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/1514958/output.zip)

(What happens, when, how? Steps to reproduce (with sample codes))

I have two questions so I will post them as two separate “bugs”.  The problem I am encountering is most likely my lack of knowledge or inability to find good examples on how to set the vlc options, so this is not a bug report per se, more of a request for help.  The first issue is that the file I am working with plays on the vlc command line but does not play in the sample project.

I am trying to use Vlc.DotNet to play raw (ie not in a container) H.264 video recorded at a rate of 5 frames per second.  The file I am trying to play is attached to this bug report ("output.zip").   

I am able to play this file from the vlc command line just fine.  I am using the following command:  vlc --h264-fps=5.0 C:\\KBData\ output.h264.  
I also noted that the video played without the command line option as well:
vlc  C:\\KBData\output.h264
![resultofrawh264file](https://user-images.githubusercontent.com/3177768/33391399-c9a45284-d4ed-11e7-95eb-64148f939cc1.PNG)

I went through the getting started guide:  
https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started 

and downloaded the sample project: 
https://github.com/ZeBobo5/Vlc.DotNet/tree/master/src/Samples/Vlc.DotNet.Forms.Samples

I downloaded the sample video pointed to by the project and it played just fine in the sample project player:
      private void OnButtonPlayClicked(object sender, EventArgs e)
      {
         myVlcControl.Play(new FileInfo(@"C:\\KBData\big_buck_bunny_480p_h264.mov"));
      }

Then I try to play the raw H.264 file:
      private void OnButtonPlayClicked(object sender, EventArgs e)
      {
         string[] options = new string[] { "--h264-fps=5.0" };
         myVlcControl.Play(new FileInfo(@"C:\\KBData\output.h264"), options);
      }

And it looks like it recognizes the video as h.264 as the “Video Informations” field is filled in:
Codec:  h264
Height: 720
Width: 1280

But no video plays in the player. It remains a black screen.  See attached PNG file.  

  I try using myVlcControl.Play without the options field as well with the same result:  
myVlcControl.Play(new FileInfo(@"C:\\KBData\output.h264"));

I also use the following line to set the options before I call play with same result: 
myVlcControl.VlcMediaplayerOptions = options;

Does anyone have any advice or suggestions as to what I might try to get this video to play?  I noticed in the vlc debug output:

libVlc : Debug `file:///C:/KBData/output.h264' gives access `file' demux `' path `/C:/KBData/output.h264' @ main
libVlc : Debug looking for access_demux module matching "file": zd candidates @ main
libVlc : Debug no access_demux modules matched @ main
libVlc : Debug creating demux: access='file' demux='' location='/C:/KBData/output.h264'
a few lines later:  libVlc : Debug using demux module "avcodec" @ main

So it looks like it is not seeing the option that I provided as demux is blank at first and it defaults to avcodec.  

So maybe it is not seeing my option field?  Or I am incorrectly setting up the demux?

Any help is appreciated.

Thanks,
-	Chuck

**Comment by jeremyVignelles** [comment]
Hi, welcome to Vlc.DotNet. feel free to come on gitter for such questions.
Passing your option to "Play" is indeed wrong. we need to improve the documentation on How to pass parameters, but this one is for the per media options, like applying filters...
VlcMediaPlayerOptions is the way to go, but you need to do that before your component is initialized. Since you are using WinForms, the easiest way to do that is to click on the component in the designer and find the VlcMediaPlayerOptions parameter in the "properties" window

**Comment by redxar** [comment]
Jeremy, 

Thanks for the quick response.  gitter is something I have not used before - I have now installed it and will use in future....

I will try your suggestion as soon as I get the solution working again.  I am getting a few weird build errors where the build fails because certain files are locked by another process - and the second error:  "The type or namespace shell does not exist in the namespace 'System.Windows'" what is weird is they occur in the unmodified dot net sample solution which has been working perfectly prior to today...

**Comment by jeremyVignelles** [comment]
When you are having issues of files locked when building, it might be because the process is still running somewhere. using the windows task manager might help to find what's going on. When Visual Studio is unable to build, it can start behaving weird. in those case, if the error doesn't disappear after building successfully, I generally restart Visual Studio and the error often magically disappear
