### ISSUE TITLE
cmdline run standvlc is ok but using vlc.dotnet broken

### ISSUE THREAD

**Issue by fingerx** [ZeBobo5/Vlc.DotNet#355]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (dev)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x64-v2.6.6) 
- **.net version** : (4.5)
- **Project lang/VB.netuage** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Wix86ndows ...) (x64)

# Summary

using  install vlc run commond line is ok(client connect success,and synced):
`C:\Program Files\VideoLAN\VLC\vlc.exe F:\Video\01\001.mp4 --sout"duplicate{dst=std{access=http,mux=ts,dst=192.168.1.103:1234}}"` 

but using cmdline in Vlc.DotNet.Forms.Samples - CLR 4 - .Net 4.5  modify code in sample.cs

 `myVlcControl.SetMedia(new FileInfo(@"F:\Video\01\001.mp4"),new string[]{"--sout=#duplicate{std={access=http,mux=ts,dst=192.168.1.103:1234}}"});`

 `myVlcControl.Play();`

build is ok but run nothing(not sync video,client connect error), i have copy plugins and core dll to bin folder.

can anyone help me ? thanks .

 I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
Please have a look at this answer : https://github.com/ZeBobo5/Vlc.DotNet/issues/272#issuecomment-317422391
If you still have issues making it work, you can come to gitter so that I can help you more.

**Comment by fingerx** [comment]
@jeremyVignelles  thanks but using answer alway run error:
  myVlcControl.SetMedia(new FileInfo(@"F:\Video\01\001.mp4"), new string[] { ":sout=#duplicate{std={access=http,mux=ts,dst=192.168.1.103:1234},dst=display}" });
            myVlcControl.Play();

log(some):
libVlc : Debug Copyright © 1996-2014 the VideoLAN team @ main
libVlc : Debug VLC media player - 2.1.5 Rincewind @ main
libVlc : Debug revision 2.1.5-9-gb3fd0af @ main
libVlc : Debug configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-twolame' '--enable-quicktime' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-mpc' '--enable-libass' '--enable-x264' '--enable-schroedinger' '--enable-realrtsp' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--disable-sdl' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--disable-dirac' '--host=i686-w64-mingw32' 'host_alias=i686-w64-mingw32' @ main
libVlc : Debug Creating an input for '001.mp4' @ main
libVlc : Debug using sout chain=`duplicate{std={access=http,mux=ts,dst=192.168.1.103:1234},dst=display}' @ main
libVlc : Debug stream=`duplicate' @ main
libVlc : Debug  * adding `display' @ stream_out_duplicate
libVlc : Debug looking for sout stream module matching "duplicate": zd candidates @ main
libVlc : Debug stream=`display' @ main
libVlc : Debug using timeshift granularity of 50 MiB, in path 'C:\Users\ADMINI~1\AppData\Local\Temp' @ main
libVlc : Debug looking for sout stream module matching "display": zd candidates @ main
libVlc : Debug using sout stream module "stream_out_display" @ main
libVlc : Error  * ignore unknown option `std' @ stream_out_duplicate
libVlc : Debug using sout stream module "stream_out_duplicate" @ main
libVlc : Debug `file:///F:/Video/01/001.mp4' gives access `file' demux `' path `/F:/Video/01/001.mp4' @ main
libVlc : Debug creating demux: access='file' demux='' location='/F:/Video/01/001.mp4' file='F:\Video\01\001.mp4' @ main
libVlc : Debug creating 'duplicate' @ stream_out_duplicate
libVlc : Debug no access_demux modules matched @ main
libVlc : Debug looking for access module matching "file": zd candidates @ main
libVlc : Debug Using stream method for AStream* @ main
libVlc : Debug using access module "filesystem" @ main
libVlc : Debug pre-buffering done 1024 bytes in 0s - 1000000 KiB/s @ main
libVlc : Debug starting pre-buffering @ main
libVlc : Debug looking for stream_filter module matching "any": zd candidates @ main
libVlc : Debug looking for stream_filter module matching "record": zd candidates @ main
libVlc : Debug looking for access_demux module matching "file": zd candidates @ main
libVlc : Debug received first data after 0 ms @ main
libVlc : Debug creating access 'file' location='/F:/Video/01/001.mp4', path='F:\Video\01\001.mp4' @ main
libVlc : Debug opening file `F:\Video\01\001.mp4' @ filesystem

**Comment by jeremyVignelles** [comment]
Is that normal that you are not using the same syntax as what you did in the vlc command line?
you were using `dst=std` whereas you are now using `std=`

**Comment by fingerx** [comment]
@jeremyVignelles  thanks .My own mistakes. all is ok! thanks again.
