### ISSUE TITLE
Hello, is there any way to deal with the gray screen when VLC just started playing? I want him to show nothing, or to display a picture or a paragraph of text

### ISSUE THREAD

**Issue by lrsitod** [ZeBobo5/Vlc.DotNet#356]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.1.149.0)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (2.2.6.0) (x86) + how did you get it? Official website to download
- **.net version** : (4.0)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows ...) (x86/x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi, did you try with vlc 3.0.0 nightlies (or RC1)?
The screen is now black at the beginning.
If you want, you can print something at the top of the video until IsPlaying is called. For that, you will need to use one of the way described in #296

**Comment by lrsitod** [comment]
Thank you very much, I solved the problem with vlc 3.0.0, The screen is now black at the beginning.
