### ISSUE TITLE
Can you please update vlc libraries to 2.2.0?

### ISSUE THREAD

**Issue by Krakean** [ZeBobo5/Vlc.DotNet#36]
Can you please update vlc libraries to 2.2.0?

**Comment by LinoBarreca** [comment]
what do you mean?

**Comment by Krakean** [comment]
Well, I mean that vlc libraries in lib\x64 has version 2.1.3, so I suggest may be you update them to newly released 2.2.1 and (if required) API too?

**Comment by LinoBarreca** [comment]
Why don't you just take them yourself from a vlc folder?

**Comment by qzzf1w** [comment]
Is it just as simple as downloading the VLC.Dotnet source and swapping out the VLC folder and recompiling the dotnet?

**Comment by PureIso** [comment]
should this even be an issue?

**Comment by jeremyVignelles** [comment]
Closed, see #288
