### ISSUE TITLE
System.AccessViolationException when creating MediaPlayer

### ISSUE THREAD

**Issue by bpev21** [ZeBobo5/Vlc.DotNet#361]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Core
- **libvlc version** : x86 and x64, from the VLC homepage
- **Project language** : C#
- **Project build architecture** : x86 and x64
- **Operating system** : Windows 10 x64

# Summary

When compiling my UWP project I get the following Exception:

> Exception thrown: 'System.AccessViolationException' in Vlc.DotNet.Core.Interops.dll
> An exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll but was not handled in user code
> Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I'm creating the MediaPlayer like this:
```
string vlcLibDir;
if (IntPtr.Size == 4) // x86
{
    vlcLibDir = Path.Combine(Directory.GetCurrentDirectory(), "vlc_x86");
}
else // x64
{
    vlcLibDir = Path.Combine(Directory.GetCurrentDirectory(), "vlc_x64");
}

m_MediaPlayer = new VlcMediaPlayer(new DirectoryInfo(vlcLibDir));
```

Is there any solution to this issuse? Am I doing something wrong?

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
UWP is not officially supported by Vlc.DotNet. However, Vlc.DotNet.Core "should" work, but I'd rather try with a "winrt" build of libvlc. See : http://nightlies.videolan.org/build/ in folders `winrt-i686/` and `winrt-x86_64/`

**Comment by jeremyVignelles** [comment]
https://github.com/videolan/libvlcsharp supports UWP natively, you should give it a try ;)
