### ISSUE TITLE
System.AccessViolationException playing videos with a title in the metadata

### ISSUE THREAD

**Issue by woolersj** [ZeBobo5/Vlc.DotNet#362]
# Generic information

- **Vlc.DotNet version** : 2.2.1 and develop241
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 2.2.8 x64 downloaded from http://download.videolan.org/pub/videolan/vlc/2.2.8/
- **.net version** : .NET4.5
- **Project language** :C#
- **Project build architecture** : AnyCPU
- **Operating system** : (Windows ...) x64

# Summary
I have an issue with Vlc.DotNet playing certain files with a title in the metadata.
I get a System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

**CallStack**

Vlc.DotNet.Core.Interops.dll!Vlc.DotNet.Core.Interops.Utf8InteropStringConverter.Utf8InteropToString(System.IntPtr ptr) Line 26
Vlc.DotNet.Core.dll!Vlc.DotNet.Core.VlcMediaPlayer.OnMediaPlayerTitleChangedInternal(System.IntPtr ptr) Line 20

I am using the latest develop code and have updated the WPF sample as follows:

1. Changed the VlcLibDirectory to point to 
`this.control.MediaPlayer.VlcLibDirectory = new DirectoryInfo(@"C:\Downloads\vlc-2.2.8-win64\vlc-2.2.8");`
2.Updated the file to play 
`control.MediaPlayer.Play(new FileInfo(@"C:\Temp\output.mkv"));`

The file was created with **ffmpeg** and has the following **ffprobe** output

`Input #0, matroska,webm, from 'c:\Temp\output.mkv':
  Metadata:
    title           : Siqura stream
    encoder         : Lavf
  Duration: 00:00:05.48, start: 0.000000, bitrate: 242 kb/s
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      DURATION        : 00:00:05.480000000`

The same file works fine using the x86 version of 2.2.8.

- [ X] I confirm that my issue doesn't happen in VLC itself.
The Video file I am playing works fine in VLC 2.2.6 and VLC 2.2.8 both x64.

**Comment by woolersj** [comment]
Additional Info.
When I edit the source file Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.Events.TitleChanged.cs
And replace
var fileName = Utf8InteropStringConverter.Utf8InteropToString(args.eventArgsUnion.MediaPlayerTitleChanged.NewTitle);

With filename = "";

The video plays without error.

**Comment by jeremyVignelles** [comment]
Indeed, it works, because there is an issue in the method call you removed. Since you already managed to use the source code of the library, could you have a look at the memory window and look if the NewTitle pointer is valid?

**Comment by jeremyVignelles** [comment]
Wow, no need for that. There is a huge logic flaw in this method...
NewTitle is an integer that represents the index of the "Title" being played. It is used as a string...

Could you submit a patch that removes the string conversion and that considers the NewTitle property as an int, as it should be?

**Comment by jeremyVignelles** [comment]
Also, please change https://github.com/ZeBobo5/Vlc.DotNet/blob/153af2aff488a71e3ed38741c3ccb160eddd66fa/src/Vlc.DotNet.Core.Interops/Signatures/libvlc_events.h/libvlc_event_t.cs#L167 . As an answer to this, I'd say that this is not OK :smile: .

**Comment by woolersj** [comment]
That makes sense, thanks.
Will try and submit a patch.

**Comment by jeremyVignelles** [comment]
Fixed by #364 in version 2.2.2-develop243
