### ISSUE TITLE
vs2017  do not can open

### ISSUE THREAD

**Issue by windsOne** [ZeBobo5/Vlc.DotNet#363]
![image](https://user-images.githubusercontent.com/14890297/34282419-2491b050-e700-11e7-99a4-cbe7cd69e065.png)

**Comment by jeremyVignelles** [comment]
Do you have .net core SDK installed on your computer?

**Comment by windsOne** [comment]
yes  i Have   you can open it??

**Comment by jeremyVignelles** [comment]
Yes, I am using VS 2017 for everything. something seems broken on your VS installation

**Comment by biancheng1000** [comment]
I can open it by vs2017.Eevery thing  is ok.

**Comment by jeremyVignelles** [comment]
cool! ☺️
