### ISSUE TITLE
setting tunnel rtsp and rtp over http

### ISSUE THREAD

**Issue by Davutcsmc** [ZeBobo5/Vlc.DotNet#367]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : v2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : v2.2.8 (x86) + downloaded from http://download.videolan.org/pub/videolan/vlc/
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 Enterprise x64

# Summary

When I want to set tunnel rtsp and rtp over http (vlc player advanced options), It seems doesn't work, 

the related code part : 

string[] strar_vlcMediaplayerOptions = { "--rtsp-http", "--rtsp-http-port=50334" };
myVlcControl.VlcMediaplayerOptions = strar_vlcMediaplayerOptions;
myVlcControl.BeginInit();
myVlcControl.EndInit();
myVlcControl.VlcMediaPlayer.SetMedia(new Uri(uriString), strar_vlcMediaplayerOptions);
myVlcControl.Play();

- this issue doesn't happen in VLC itself ( vlc.exe --rtsp-http --rtsp-http-port=50334 rtsp:\\username:password@ip_address:port)

**Comment by Davutcsmc** [comment]
Finally managed to configure "rtsp over http" or this kind of configurations. However, I had to re-create "myVlcControl" for each configuration request, for example brightness/contrast or invert configurations or etc..

**Comment by jeremyVignelles** [comment]
Yes, it should be possible with those functions : https://github.com/ZeBobo5/Vlc.DotNet/blob/153af2aff488a71e3ed38741c3ccb160eddd66fa/src/Vlc.DotNet.Core.Interops/VlcManager.SetVideoAdjust.cs

Closing this as you solved your issue. Please open separate issues for other unrelated problems.
