### ISSUE TITLE
Can  Vlc.DotNet can play 3d format video?

### ISSUE THREAD

**Issue by biancheng1000** [ZeBobo5/Vlc.DotNet#369]
I have  a question about Vlc.DotNet.
I want to play 3d format video by vlc player.I found some ways to play 3d format video by vlc media player.But I don't know if vlc.DotNet can do it.

**Comment by jeremyVignelles** [comment]
Hi,
You might find this useful : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Is-Vlc.DotNet-able-to-do-this

In short : if you can do it with the vlc command line, chances are that you can do it with vlc.dotNet too 😄 

If you manage to do that, please share your findings here 😉

**Comment by biancheng1000** [comment]
Thank you 😉

**Comment by jeremyVignelles** [comment]
So, can VLC do that?
I'm closing this issue since nothing has been said for a long time.
