### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by goobering** [ZeBobo5/Vlc.DotNet#37]
I tried to drop you a line using the 'Contact' section from here: http://zebobo5.github.io/Vlc.DotNet, but unfortunately all I'm getting is a 405 error. 

I'm likely to come into a little free time shortly and might be interested in putting together some documentation/examples to help ease the learning curve for the new library a little. Do you have any high level requirements/preferred formats for documentation?

**Comment by RexGrammer** [comment]
I've did the documentation for the previous version. You can see that here: https://rexgrammer.github.io/Vlc.DotNet-Deprecated/doc/index.html

It's made with [Sandcastle Help File Builder] (https://shfb.codeplex.com/). It features a MSDN-style documentation style that's readable and easily maintainable. The main thing that should be done is commenting the code and adding XML comments, which SHFB will automatically convert into a class reference documentation library. You can comment the code, add xml comments submit a PR, then generate the class reference and submit a PR to the gh-pages branch with it added.

The next thing in order is to create wiki articles about using the library. For starters one 'quickstart' style article about using the library in WinForms and one for WPF would be really good.

**Comment by goobering** [comment]
I've used SandCastle on my own projects before, so that shouldn't present
too much of a problem.

I'm fluent in WPF, but it's been a *long* time since I did much in
WinForms. I'll maybe see about putting together an introductory walkthrough
for WPF first, then look into converting that to WinForms. I'll mail over
anything I put together for discussion and you can let me know if it's what
you're looking for.


Cheers

Dale

**Comment by RYG81** [comment]
Yes Documentation - tutorials are really needed for new comers.
Please spend some time on it.

**Comment by jeremyVignelles** [comment]
Closing this old issue to clean up the "issues" page. A "Getting started" wiki page has now been written. Feel free to create a new  issue if more doc is needed
