### ISSUE TITLE
save another file while vlc is running.

### ISSUE THREAD

**Issue by faithmaker** [ZeBobo5/Vlc.DotNet#370]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : v2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (2.2.8) (x86/x64) + nuget
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows ...) (x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

...
  private Vlc.DotNet.Forms.VlcControl VlcDisp;

  sRtsp = "rtsp://admin:admin@192.168.0.45:10554/tcp/av0_1"; // 640*480
  string[] acPara = new string[] {
    ":sout=#std{access=file, mux=mp4, dst='1.mp4'}"
  };
  VlcDisp.SetMedia(new Uri(sRtsp), acPara);

  VlcDisp.Play(); // OK
...
// I Want chage save file.(cycle 10 minute)
...
  VlcDisp.VlcMediaplayerOptions = new string[] {
    ":sout=#std{access=file, mux=mp4, dst='minute_xx.mp4'}"
  }; // Don't effect.
...

*. How can i save continue file?

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
you can't : media player options are only for init.
Is the cycle plugin what you are looking for?

**Comment by faithmaker** [comment]
Is the cycle plugin what you are looking for?
=> Yes. I would like to save the stream file in 10 minutes without loss.
I'm considering making nvr via vlc..ffmpeg...

**Comment by jeremyVignelles** [comment]
I also need that. according to videoLAN's developpers the way to go could be mpeg-TS, which supports splitting the file anywhere (so that you can concat two files and still have a valid file) and supports encryption.

**Comment by faithmaker** [comment]
Is it possible to use ffmpeg?
Find out the way through ffmpeg. I will write.

**Comment by jeremyVignelles** [comment]
Most probably, but linking your project to ffmpeg will require you to disclose the source code of your application. If this is not desired, you could wrap ffmpeg.exe calls in your app

**Comment by jeremyVignelles** [comment]
Your question seems answered, closing this. Feel free to reopen if needed.
