### ISSUE TITLE
Subtitles and Audio Tracks

### ISSUE THREAD

**Issue by TheMeq** [ZeBobo5/Vlc.DotNet#372]
# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 2.2.5.1 - Installed VLC as Media Player
- **.net version** : .NET Framework 4.6.1
- **Project language** : VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 Pro

Please can someone provide information on how to set Audio Track and Subtitle for video in vb.net. Everything I am trying says that I can't cast to a TrackDescription, but I don't know how to create a TrackDescription from a selected Name or ID.

**Comment by jeremyVignelles** [comment]
Hi,
Enumerate tracks in `AudioTracksManagement.All`, and set one of those objects to `Current`

**Comment by TheMeq** [comment]
Are you able to provide some code, i've never Enumerated anything before. It would be appreciated.

**Comment by jeremyVignelles** [comment]
I'm not a VB.net developper, sorry. Have a look at "How to use IEnumerable in VB.net"

**Comment by TheMeq** [comment]
Thanks for your help 👍
