### ISSUE TITLE
Problem withstreaming form memoryStream to file.

### ISSUE THREAD

**Issue by medzik1993** [ZeBobo5/Vlc.DotNet#374]
Hello,

At first I will explain what we want to do in out project. 
We receive from api some byte[] which is raw h264 format . We don't want to store that data in any file 
 temp file, so we using memoryStream. Out gool is to create m3u8 and ts file form that stream. Code in out opinion should look something like this:

> 

          MemoryStream ms = new MemoryStream();
            var libDirectory = @"C:\Temp\libvlc";
            var options = new string[]
            {
                "--demux=h264",
            };
            var mediaPlayer = new VlcMediaPlayer(new DirectoryInfo(libDirectory), options);
            var mediaOptions = new string[]
            {
                ":sout=#std{access=livehttp{seglen=5,delsegs=true,numsegs=10, index=C:\\Temp\\stream.m3u8,index-url=./test-########.ts},mux=ts{use-key-frames},dst=C:\\Temp\\test-########.ts}",
            }
            mediaPlayer.Play(ms, mediaOptions)
            while (true)
            {
                // here append new data to memorystream
            }

For testing we simplified code and use FileStream instead of MemoryStream. In log we get some errors 

main Debug VLC media player - 3.0.0-rc7 Vetinari
main Debug Copyright © 1996-2018 the VideoLAN team
main Debug configured with ../extras/package/win32/../../../configure  "--enable-update-check" "--enable-lua" "--enable-faad" "--enable-flac" "--enable-theora" "--enable-twolame" "--enable-avcodec" "--enable-merge-ffmpeg" "--enable-dca" "--enable-mpc" "--enable-libass" "--enable-x264" "--enable-schroedinger" "--enable-realrtsp" "--enable-live555" "--enable-dvdread" "--enable-shout" "--enable-goom" "--enable-caca" "--enable-qt" "--enable-skins2" "--enable-sse" "--enable-mmx" "--enable-libcddb" "--enable-zvbi" "--disable-telx" "--enable-nls" "--host=i686-w64-mingw32" "--enable-debug" "host_alias=i686-w64-mingw32" "PKG_CONFIG_LIBDIR=/home/jenkins/workspace/vlc-nightly/vlc-3.0-nightly-win32-x86/contrib/i686-w64-mingw32/lib/pkgconfig"
main Debug revision 3.0.0-rc6-2-ged5177c851
main Debug Creating an input for "imem://"
main Debug stream="file"
mp4 Debug Mp4 muxer opened
main Debug set config option: sout-standard-dst to C:\Temp\test.mp4
stream_out_standard Debug using "file/mp4://C:\Temp\test.mp4"
main Debug using sout chain="file{dst=C:\Temp\test.mp4}"
main Debug using timeshift granularity of 50 MiB
main Debug using timeshift path: C:\Users\Rico\AppData\Local\Temp
main Debug "imem://" gives access "imem" demux "h264" path ""
main Debug creating demux: access="imem" demux="h264" location="" file="(null)"
main Debug looking for access_demux module matching "imem": zd candidates
main Debug looking for sout access module matching "file": zd candidates
main Debug using sout access module "file"
main Debug creating access: imem://
file Debug file access output opened (C:\Temp\test.mp4)
main Debug using access module "imem_access"
main Debug looking for stream_filter module matching "prefetch,cache_read": zd candidates
main Debug using sout mux module "mp4"
main Debug using stream_filter module "prefetch"
main Debug looking for stream_filter module matching "any": zd candidates
imem_access Error read error
prefetch Debug end of stream
main Debug looking for sout stream module matching "file": zd candidates
main Debug looking for sout mux module matching "mp4": zd candidates
main Debug using sout stream module "stream_out_standard"
main Debug no stream_filter modules matched
main Debug looking for stream_directory module matching "any": zd candidates
main Debug no stream_directory modules matched
main Debug attachment of directory-extractor failed for imem://
main Debug looking for stream_filter module matching "record": zd candidates
main Debug using stream_filter module "record"
imem Error Invalid get/release function pointers
main Debug looking for demux module matching "h264": zd candidates
main Debug no access_demux modules matched
main Debug looking for packetizer module matching "any": zd candidates
main Debug using packetizer module "h264"
playlist Debug not enough data
main Debug starting in sync mode
main Debug looking for access module matching "imem": zd candidates
lua Debug Trying Lua scripts in C:\Users\Rico\AppData\Roaming\vlc\lua\meta\reader
prefetch Debug using zu bytes buffer, zu bytes read
main Debug no meta reader modules matched
main Debug "imem://" successfully opened
main Debug using demux module "h26x"
main Debug removing module "h26x"
main Debug removing module "record"
main Debug removing module "prefetch"
main Debug removing module "imem_access"
lua Debug Trying Lua scripts in C:\Temp\libvlc\lua\meta\reader
lua Debug Trying Lua scripts in C:\Users\Rico\AppData\Roaming\vlc\lua\playlist
lua Debug Trying Lua scripts in C:\Temp\libvlc\lua\playlist
h26x Error this doesn"t look like a h264 ES stream, continuing anyway
main Debug EOF reached
main Debug creating demux: access="imem" demux="h264" location="" file="(null)"
main Debug looking for meta reader module matching "any": zd candidates
main Debug removing module "h264"

But when we change file stream for new FileInfo(filepath) everything works nice. I read here :https://stackoverflow.com/questions/31250640/using-vlc-imem-to-play-an-h264-video-file-from-memory-but-receiving-error-main` that new 3.0.0 api should deal with it.

Any ideas 

Thanks for help

**Comment by jeremyVignelles** [comment]
`libvlc_media_new_callbacks` is already used by your code, because this is what we use when reading a stream.

It seems like the end of stream is reached (you don't have an infinite file), that could be why you see some things like that.

To be honnest, I don't really understand what you are trying to do, and what doesn't work. 

Please also use the issue template when submitting, which version of what are you using?

**Comment by medzik1993** [comment]
We are using Vlc.DotNet.Core and Vlc.DotNet.Core.Interops nuget packages in version 3.0.0-develop252. 
We are trying to display IP camera's image in any browser. This is why we need m3u8 and ts chunks. Live stream is by rtsp. We deal with it. It works. Now we need to handle timeshift. When user want to play some video form past, api don't provide for as another rtsp url, but we receive byte[]. Too handle this we need to use the same logic, as rtsp does and return m3u8 and ts chunks.
For last 2hours a most problems. :) There is only one problem to solve now. VlcPlayer read bytes form my memoryStream very quick and fire EndReached event while the data form api stream are still append

> 

            var options = new string[]
            {
                "--demux=h264"
            };

            var mediaPlayer = new VlcMediaPlayer(new DirectoryInfo(libDirectory), options);
            mediaPlayer.Log += Log;
            mediaPlayer.EndReached += EndReached;
            var mediaOptions = new string[]
            {
                ":sout=#std{access=livehttp{seglen=5,delsegs=true,numsegs=10, index=C:\\Temp\\TempChunks\\test.m3u8,index-url=./test-########.ts},mux=ts{use-key-frames},dst=C:\\Temp\\TempChunks\\test-########.ts}",
                ":sout-keep"
            };

            MemoryStream ms = new MemoryStream();
            FileStream fm = File.OpenRead(fileName);

            Task.Run(async () =>
            {
                await Task.Delay(1000);
                mediaPlayer.Play(ms, mediaOptions);

            });


            byte[] buffer = new byte[8 * 1024];
            int read;
            while ((read = fm.Read(buffer, 0, buffer.Length)) > 0)
            {
                Console.WriteLine($"Write {buffer} {read}");
                ms.Write(buffer, 0, read);
                ms.Flush();
                Task.WaitAll(Task.Delay(100)); // here I simulate the delay of receiving data from the api
            }

is there any flag in vlc that prevent player form firing EndReached event and wait for stream ?

**Comment by jeremyVignelles** [comment]
Ok, I don't think there is. Maybe @ananjev-a-v or @qmfrederik can help with that?

**Comment by medzik1993** [comment]
I would be very grateful for help!

**Comment by jeremyVignelles** [comment]
Did you manage to find a solution, can we close this?
