### ISSUE TITLE
How to remove buffering?

### ISSUE THREAD

**Issue by mateuszbyczkowski** [ZeBobo5/Vlc.DotNet#376]
I have a question.
When i pause real time video (in RSTP) in my WinForms app, video stopps.
And then i click start and video resumes, and it's ok. 
But how can i achieve that when i resume video it's playing realtime. 
How to remove that buffer (gap) between paused and present video stream?

My 1st idea is to remove that buffer, 2nd is to forward (skip) video to actual time.
There is any other way to do this?

Thanks in advance for help or any code snippet.
Greetings!

**Comment by jeremyVignelles** [comment]
I don't think this is possible. stopping and restarting the stream might be your best option. This sounds more like a libvlc usage question, so you might have a better chance in videolan's forum.

**Comment by mateuszbyczkowski** [comment]
Thanks for response, but stopping and restarting is quite long and removes .ts files. 
And i want to avoid it ;)

**Comment by jeremyVignelles** [comment]
A dirty hack could be to let the video play in the background, and present the user with a screenshot on top of the video?

**Comment by mateuszbyczkowski** [comment]
i prefer to avoid dirty hacks

**Comment by 9Arca9** [comment]
unfortunately stop unloads, so when you play a stopped video it reloads, but reloads to the correct time.

pause keeps the position in the buffer, loading information into it, when played resumes from the same state.

Have you tried using seek to position the playback as close to real time as possible? Might have to record how long the user was paused for then seek to the duration of the paused.

**Comment by jeremyVignelles** [comment]
The dirty hack is not *that* bad, you have an option to take a snapshot of the video, which can be used to be displayed on top of the video. As long as you don't need to seek, there's no issue in doing that, plus you have an immediate "return to live".

I don't have any other options. Stopping and restarting a stream is very expansive...
