### ISSUE TITLE
Position/Time update very infrequently for MKV files

### ISSUE THREAD

**Issue by guytaylor** [ZeBobo5/Vlc.DotNet#377]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : vlc-2.1.5 + downloaded from FTP site
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64

# Summary

I am running a hello world app just playing an MKV file (1080p H264 codec) and have a timer set to 500ms to read out the Time and Position properties. I also have an event for the position changed.
The time/position seem to update very infrequently (below is the log, reading it every 500ms as well as pos changed event)

pos = 1.207957E-07   Time = 1
pos = 1.207957E-07   Time = 1
Newpos = 0.001127587
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
pos = 0.001127587   Time = 9344
Newpos = 0.001709482
Newpos = 0.001739892
pos = 0.001739892   Time = 14418
Newpos = 0.00177163
Newpos = 0.001812901
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
pos = 0.001812901   Time = 15023
Newpos = 0.002263139
Newpos = 0.002293429
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
pos = 0.002293429   Time = 19005
Newpos = 0.003284774
pos = 0.003284774   Time = 27220
pos = 0.003284774   Time = 27220
pos = 0.003284774   Time = 27220

Playing an AVI (codec XVid) seems to work fine. Her is the log by comparison:

pos = 0   Time = 0
Newpos = 7.148531E-05
pos = 7.148531E-05   Time = 90
Newpos = 0.0002779984
Newpos = 0.0004964257
pos = 0.0004964257   Time = 625
Newpos = 0.0007148531
Newpos = 0.0009332804
pos = 0.0009332804   Time = 1175
Newpos = 0.001151708
Newpos = 0.001370135
pos = 0.001370135   Time = 1725
Newpos = 0.001588562
pos = 0.001588562   Time = 2000
Newpos = 0.00180699
Newpos = 0.002025417
pos = 0.002025417   Time = 2550
Newpos = 0.002243844
Newpos = 0.002462272
pos = 0.002462272   Time = 3100
Newpos = 0.002680699
Newpos = 0.002899126
pos = 0.002899126   Time = 3650
Newpos = 0.003117554
Newpos = 0.003335981
pos = 0.003335981   Time = 4200
Newpos = 0.003554408
Newpos = 0.003772835
pos = 0.003772835   Time = 4750
Newpos = 0.003991263
pos = 0.003991263   Time = 5025
Newpos = 0.00420969
Newpos = 0.004428118
pos = 0.004428118   Time = 5575
Newpos = 0.004646545
Newpos = 0.004864972
pos = 0.004864972   Time = 6125
Newpos = 0.005083399
Newpos = 0.005301827
pos = 0.005301827   Time = 6675
Newpos = 0.005520254
Newpos = 0.005738682

- [ ] I confirm that my issue doesn't happen in VLC itself.
Yes - the timer on the VLC ticks over ever second

**Comment by jeremyVignelles** [comment]
Hi,
You also have an event "TimeChanged" to detect changes in time, rather than calling that from a timer.

I don't think this is an issue with Vlc.DotNet but rather with libvlc itself. By the way, did you try with vlc 2.1.5 to see if there is the same issue?

Could you try with the latest rc of libvlc3.0?

I don't think this is an issue with Vlc.DotNet

**Comment by guytaylor** [comment]
Hi,
The TimeChanged event fires at exactly the same time as the positionChanged event, so that didn't help.

I was previously trying with vlc version 2.1.5. (I had misread the docs, thinking i had to use 2.1.x)

I couldn't find RC libvlc3.0 but I tried it with vlc-2.2.8 and that seemed to fix the issue!

Thanks :)

**Comment by jeremyVignelles** [comment]
3.0 rc can be found at http://nightlies.videolan.org/ . I'm glad it helped to solve your issue
