### ISSUE TITLE
Event .MouseMove not working during playback

### ISSUE THREAD

**Issue by 01001001** [ZeBobo5/Vlc.DotNet#379]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 2.2.5.1 x86 (FTP download)
- **.net version** : 4.5
- **Project language** : VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 Ent. x64

# Summary

I added a VlcControl element to a form and it works fine, also events like .MouseMove will be correctly triggered, but as soon Playback starts no event will be triggered.
In my case I want to show a Information when Player is in Fullscreen as soon mouse will be moved.
But it works only in Stopped status.

- [X ] I confirm that my issue doesn't happen in VLC itself.

Regards,
Chris

**Comment by jeremyVignelles** [comment]
We should probably expose `libvlc_video_set_mouse_input` for that to work...

**Comment by 01001001** [comment]
Agree, but it seems that not only mouse events are affected, I tried also to use KeyDown event but it is also not working.
It seems that during playback no event is working...

**Comment by jeremyVignelles** [comment]
We need to expose `libvlc_video_set_key_input` too. Vlc is handling keyboard and mouse inputs so that you can navigate in a DVD menu for example, but if you want to have that in your app, you must explicitely tell it not to handle those events with those functions, which are currently not implemented in Vlc.DotNet.

**Comment by CrookedFingerGuy** [comment]
I'm new to the project.

I have just created a pull request for this issue. I implemented the delegates for libvlc_video_set_key_input and libvlc_video_set_mouse_input 

I had them default to false for the vlcControl. I'm not sure if that is the best way to do it.
