### ISSUE TITLE
Take snapshot without showing the movie?

### ISSUE THREAD

**Issue by BergChristian** [ZeBobo5/Vlc.DotNet#383]
Hi,

Does anyone know if it is possible to grab screenshots without having to actually show the file to the user? Have been looking everywhere and trying out some ideas, but don't get it to work.

Anyone can point me in the right direction?

Thanks
Christian

**Comment by honfika** [comment]
I'm just curious why don't you use simply ffmpeg if you only want to decode a video file to bitmaps? VLC is much much more.

**Comment by BergChristian** [comment]
I still need VLC to view the videos but would like to get a picture from the video so I was hoping VLC.dotnet could do that as well.  Will look into FFMPEG.

**Comment by honfika** [comment]
In that case please ignore my answer. I thought that you need the frame bitmaps only. It is better to use only 1 dependency, since both VLC and FFMpeg are quite big :)

**Comment by jeremyVignelles** [comment]
Does it work with `--no-video` at initialization?

Another solution could be to hide the control if you're using the WinForms control.

With the new WPF control, you could just instanciaite a `VlcVideoSourceProvider` without the control.

Is any of those solution acceptable?

**Comment by mfkl** [comment]
@BergChristian Here is one implementation of a thumbnailer (in C++/CX) using the libvlc API: https://code.videolan.org/videolan/vlc-winrt/blob/50b659c3375d67956be6f137c1ee4de40493fc0f/modules/libVLCX/Thumbnailer.cpp#L184

Maybe this can help you implement your own.

**Comment by jeremyVignelles** [comment]
A thumbnailer sample has been written : https://github.com/ZeBobo5/Vlc.DotNet/tree/develop/src/Samples/Samples.Core.Thumbnailer
