### ISSUE TITLE
Need to capture a frame to memory - oVLC.MediaPlayer.DrawToBitmap() returns black block

### ISSUE THREAD

**Issue by tpcarmen** [ZeBobo5/Vlc.DotNet#39]
I'm not sure if this is a bug or I'm just doing something wrong.

All I need to do is pause the player and grab the current frame, but can't seem to  find a way to do it. 

I've been beating on this for days and any help would be really appreciated.

Thanks.

Code:

dim bm As New Bitmap(CInt(oVLC.ActualWidth), CInt(oVLC.ActualHeight))

oVLC.MediaPlayer.DrawToBitmap(bm, b)

At this point, bm appears as a black block.

**Comment by adrians75** [comment]
Hi Carmen,
Try this. I have not tested yet, but I think it should go.


private void btPictCapture_ItemClick(object sender, ItemClickEventArgs e)
{
	if (vlcControl.IsPlaying)
    {
	vlcControl.Pause();
	string fileImg = TakeAPicture();
	Thread.Sleep(500);
	BitmapImage image1 = LoadImageToMemory(fileImg);
	vlcControl.Play();
	}
	else
		ShowTempMessage("Can't capture, because no stream is played!", 10);
}
	
private string TakeAPicture()
{
	if (string.IsNullOrWhiteSpace(Properties.Settings.Default.PictCaptFolder))
		Properties.Settings.Default.PictCaptFolder = Environment.GetFolderPath(System.Environment.SpecialFolder.MyPictures);

	string imgfile = Properties.Settings.Default.PictCaptFolder + @"\" + vlcControl.GetCurrentMedia().Title + "_" + DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss") + "." + Properties.Settings.Default.PictCaptFormat;
	//Size size = vlcControl.Video.Size;
	//vlcControl.TakeSnapshot(imgfile, (uint)size.Width, (uint)size.Height);
	vlcControl.OnSnapshotTaken(imgfile);
	return imgfile;
}

private BitmapImage LoadImageToMemory(string fileImg)
{
        BitmapImage image = new BitmapImage();

        try
        {
            image.BeginInit();
            image.CacheOption = BitmapCacheOption.OnLoad;
            System.IO.Stream stream = System.IO.File.Open(fileImg, System.IO.FileMode.Open);
            image.StreamSource = new System.IO.MemoryStream();
            stream.CopyTo(image.StreamSource);
            image.EndInit();

            stream.Close();
            stream.Dispose();
            image.StreamSource.Close();
            image.StreamSource.Dispose();
        }
        catch { throw; }
       return image;
}

**Comment by tpcarmen** [comment]
Thanks,

Terry


On a more general note,
