### ISSUE TITLE
Output to VLC NDI Plugin?

### ISSUE THREAD

**Issue by joedemax** [ZeBobo5/Vlc.DotNet#396]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : v2.0.50727
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : Included with Vlc.DotNet
- **.net version** : 4.5
- **Project language** : (C#/VB.net) C#
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits)) AnyCPU
- **Operating system** : (Windows ...) (x86/x64) Windows X64

# Summary

Trying to use the NewTek NDI output plugin using --vout=NDI. Works fine with VLC in command line. I have copied the libndi_plugin.dll to the library's plugin folder in the video out folder but no such luck. Any ideas?

- [X ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Do not use the libvlc in the source control, see #288 .
Use the same version of libvlc that was compiled with your plugin.

**Comment by joedemax** [comment]
Hi Jeremy,

How can I find out which version of libvlc the NDI plugin was compiled with?

Joe

**Comment by jeremyVignelles** [comment]
If it's not the exact same version, you can already try with the version you tested on your computer. maybe 3.0.1 will work as well, but the version in this repository is waaaay too old

**Comment by joedemax** [comment]
Running VLC 2.2.4 on here and it outputs fine to the NDI plugin.  What version is in the repo?

**Comment by joedemax** [comment]
Did it! Copied and paste libvlc.dll, libvlccore.dll and the plugins directory from my VLC install and I can now pass in --vout=ndi and see the output in Studio Monitor.

**Comment by jeremyVignelles** [comment]
cool. I don't know which version is here (2.1.? If i remember correctly), but it's way too old.
Issue solved anyway, closing
