### ISSUE TITLE
Global sout stopped work

### ISSUE THREAD

**Issue by remy33** [ZeBobo5/Vlc.DotNet#398]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (I don't remember, I last updated about 9 months ago)
- **Vlc.DotNet project used** : Core
- **libvlc version** : 3.0.1 x64 + how did you get it? That's the same as VLC GUI install
- **.net version** : 4.6.1
- **Project language** : C#, mvc.net
- **Project build architecture** : AnyCPU (64)
- **Operating system** : Windows 10 x64

# Summary

I have a working code, but3 after upgrade VLC version from 2.2.6 and VLC.NET core to the latest beta all global sout ("--sout{...}") stopped working but don't raise any error and I had to convert them to internal (":sout{...}"), But in the regular GUI VLC they work as expected.
Example this cmd:
"C:\Program Files\VideoLan\VLC\vlc.exe" "x.mp4" --sout=#std{access=file,dst=y.mp4,mux=mp4}
Will stream the file into file.
But the equal:
new VlcMediaPlayer(dir, "--sout=#gather:std{access=file,dst=" + destVid + ",mux=mp4}");
Doesn't work anymore even though it was work in the the last version.

My workaround was to convert into internal ":sout".

I writing this mostly if someone else will struggle with that.

**Comment by jeremyVignelles** [comment]
Is that normal that the option you set in Vlc.DotNet (`#gather:std`) is not the same as the one from the command line? (`#std`)
Does it behave the same with the same command?

I don't see what can cause this issue on Vlc.DotNet side, could you please confirm that the issue also happens with an old version of libvlc?

One more question : did you only update Vlc.DotNet.Core or all the Vlc.DotNet projects? Please check that you have matching version of Vlc.DotNet libraries.

**Comment by remy33** [comment]
I looked into the source and I didn't find the cause of the problem.
It's just the same command and it is on a prod machine.
After I update everything it stopped working.
Tbh, I don't have a clue why and how to solve it, but I opened so other
people won't pull thirs too like I did.

**Comment by remy33** [comment]
I forgot, I used exactly the same options, I just deleted it by mistake, I
used gather on both.
