### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by BergChristian** [ZeBobo5/Vlc.DotNet#399]
I have an issue / a question (pick one) about Vlc.DotNet.

Trying to open a FullHD movie using vlc.DotNet. It works flawlessy for smaller videos but when trying two different FullHD movies it crashes with the error message of:

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

I cannot catch it so it brings the whole application down. Any ideas of where to start look? I am compiling in x64.

Regards,
Christian

# Generic information

- **Vlc.DotNet version** : (Please fill)
- **Vlc.DotNet project used** : (WinForms/WPF/Core)
- **libvlc version** : (Please fill) (x86/x64) + how did you get it?
- **.net version** : (Please fill)
- **Project language** : (C#/VB.net)
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows ...) (x86/x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by remy33** [comment]
Hello!
https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started
Scroll down to " how to debug " section and look what's inside the log.
Also it was helping if you were actually fill up the generic information.

**Comment by BergChristian** [comment]
Thank you very much for pointing out the debug. I upgraded my VLC installation from 2.2.8 to 4.0 and after that it just worked. I found an issue where Title was set as integer (and title is off course a string) which caused this. I have no idea if these are aligned but it is now working using the latest build from VLC.

**Comment by jeremyVignelles** [comment]
I'm glad it works, closing.

Thanks @remy33 for answering 👍
