### ISSUE TITLE
Set new media after end reached freez aplication

### ISSUE THREAD

**Issue by kamprog** [ZeBobo5/Vlc.DotNet#4]
In this version is still the same bug.
If the player reached end of movie and we try load a new movie it freeze application. It quite important to have a possibility to load new media file after old is ended. Here is simple example:
private void VlcOdtwarzacz_EndReached(object sender, VlcMediaPlayerEndReachedEventArgs e)
        {
            Console.WriteLine("END");
            this.VlcOdtwarzacz.Play(new Uri(@"c:\movie.mkv", UriKind.Absolute)); //freeze here
        }

**Comment by jfgbaker** [comment]
+1, I really need this as well - any work around?

**Comment by jfgbaker** [comment]
Ok - figured out a work around - in VlcMediaPlayer.cs (in Core) simply wrap the methods in a new thread. It must be a thread deadlock. i.e.:
        public void Play()
        {
            Thread thread = new Thread(delegate() { Manager.Play(myMediaPlayer); });
            thread.Start();
        }

i voided setmedia as well, didnt need the return.        

        public void SetMedia(VlcMedia media)
        {
            Thread thread = new Thread(delegate() { Manager.SetMediaToMediaPlayer(myMediaPlayer, media.MediaInstance); });
            thread.Start();
        }
...

hope this helps...

**Comment by wolf-germany** [comment]
Maybe same issue as in #81. EndReached event (temporary) unregister all events and "reset" the media player core instance.

**Comment by jeremyVignelles** [comment]
Deadlocks will appear if you call Vlc methods from vlc callbacks. You should call that from another thread, as jfgbaker suggested, or with `ThreadPool.QueueUserWorkItem()` or `Task.Run`.

Closing this as a solution has been provided, feel free to reopen if needed.

**Comment by Arashz22** [comment]
Hi every body
I’m using the latest version and I’m not calling Vlc methods from vlc callbacks
But my application freezes when I want to set another media from my play list.
I should mention that my application should play stream not video file.
I also tried these :

`   vlcControl.Play(currStream);
`

And

```
new System.Threading.Thread(()=>
{
    vlcControl.Play(currStream);
}).Start();
```
And

```
new System.Threading.Tasks.Task(() =>
{
    vlcControl.Play(currStream);
}).Start();
```
And

```
System.Threading.ThreadPool.QueueUserWorkItem((a) =>
{
    vlcControl.Play(currStream);
});
```

but still freeze.

**Comment by jeremyVignelles** [comment]
The deadlock you are experiencing does not seem to be related to this issue. You might have a deadlock elsewhere in your code. Can you create a minimal project to reproduce that and send that on github so that we can have a look?

**Comment by Arashz22** [comment]
Yes as you said my issue was not related to this thread.
When I was creating a minimal project I realized that my problem was related to this part of code : 

```
private void vlcControl_LengthChanged(object sender,
Vlc.DotNet.Core.VlcMediaPlayerLengthChangedEventArgs e)
        {
                if (this.InvokeRequired)
                    this.Invoke(new Action(() =>
                    {
                        label2.Text = TimeSpan.FromMilliseconds(vlcControl.Length).ToString("hh\\:mm\\:ss");
                    }));
                else
                    label2.Text = TimeSpan.FromMilliseconds(vlcControl.Length).ToString("hh\\:mm\\:ss");
        }
```
I was calling calling Vlc methods from vlc callback.
I changed my code to this :

```
private void vlcControl_LengthChanged(object sender, Vlc.DotNet.Core.VlcMediaPlayerLengthChangedEventArgs e)
        {
            new Task(() =>
            {
                if (this.InvokeRequired)
                    this.Invoke(new Action(() =>
                    {
                        label2.Text = TimeSpan.FromMilliseconds(vlcControl.Length).ToString("hh\\:mm\\:ss");
                    }));
                else
                    label2.Text = TimeSpan.FromMilliseconds(vlcControl.Length).ToString("hh\\:mm\\:ss");
            }).Start();
        }
```
		
And my problem is solved now.
Thanks alot and apologize my spam

**Comment by jeremyVignelles** [comment]
Any reason you don't use the Length from your `e` parameter? that would save a call to libvlc

**Comment by Arashz22** [comment]
do you mean  this ?

> e.NewLength

I will try it.
Thanks for your suggestion.

**Comment by Arashz22** [comment]
> Any reason you don't use the Length from your `e` parameter? that would save a call to libvlc
why e.NewLength is float but vlcControl.Length is long ?

**Comment by Arashz22** [comment]
why 

> e.NewLength

 is float but 

> vlcControl.Length

 is long ?

**Comment by Arashz22** [comment]
> Can you make a PR for that?

I will do it with pleasure!.
