### ISSUE TITLE
System.AccessViolationException while following WPF sample

### ISSUE THREAD

**Issue by jordanbee1992** [ZeBobo5/Vlc.DotNet#404]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop273
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 & x64 versions both from official repository
- **.net version** : v4.6.1
- **Project language** : C#
- **Project build architecture** : x86 & x64 (tried both)
- **Operating system** : Windows 10 Education
# Summary

Trying to follow the WPF sample from the Wiki:
``` csharp
        private void BootstrapVLC()
        {
            DirectoryInfo vlcLibDirectory;
            if (IntPtr.Size == 4)
            {
                // Use 32 bits library
                vlcLibDirectory = new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, "libvlc_x86"));
            }
            else
            {
                // Use 64 bits library
                vlcLibDirectory = new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, "libvlc_x64"));
            }

            var options = new string[]
            {
                "-vvv --extraintf=logger --verbose=2 --logfile=Logs.log"
                // VLC options can be given here. Please refer to the VLC command line documentation.
            };

            this.MyControl.SourceProvider.CreatePlayer(vlcLibDirectory, options);

            // Load libvlc libraries and initializes stuff. It is important that the options (if you want to pass any) and lib directory are given before calling this method.
            this.MyControl.SourceProvider.MediaPlayer.Play(@"http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov");
        }
```

The only thing I changed from the sample is the sample had vlcLibDirectory declared as a string, where as current version of CreatePlayer method seems to take a DirectoryInfo (which is what is being passed anyway).

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Did you manage to solve your issue? Do you have a stack trace of the exception?

**Comment by jeremyVignelles** [comment]
No answer, closing. Please reopen if you still need help.
