### ISSUE TITLE
Know the status of RTMP streaming from webcam

### ISSUE THREAD

**Issue by saiprasadb** [ZeBobo5/Vlc.DotNet#407]
I have  a question about Vlc.DotNet.

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 2.2.5.1
- **.net version** : 4.0
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 64bit

Am using VLC.DotNet and streaming webcam video using RTMP which works fine, but some times in negatives may be network issue or any other issue, I can not identify in the program whether the streaming is working or not below is the command am using 

string[] streamingaArguments = new string[]
                    {
                    ":dshow-vdev=Integrated Webcam",
                    ":dshow-size=640*480", // Webcam supportted resolution.
                    ":dshow-adev= ",
                    ":live-caching=10",
                    ":dshow-adev=",
                    "sout=#duplicate{dst=display," +
                    "dst=transcode{vcodec=h264,scale=Auto,width=480,height=360,vb=300,acodec=libvo_aacenc,ab=48,samplerate=22050,channels=2,deinterlace}}" +
                    ":std{access=rtmp,mux=ffmpeg{mux=flv}," +
                    "dst=rtmp://rtmpfullpath}"
                    };

            this.previewControl.MediaPlayer.Play(@"dshow://", streamingaArguments);

I want to know is there any event which triggers when it gets failed to perform operation.

Please help me to achieve this.

**Comment by jeremyVignelles** [comment]
is `MediaPlayer.EncounteredError` the event you are looking for?

**Comment by jeremyVignelles** [comment]
Closing this since you didn't answer for over a month. Feel free to reopen if help is still needed
