### ISSUE TITLE
Text Overlay with background image vlc.dotnet

### ISSUE THREAD

**Issue by rawat123** [ZeBobo5/Vlc.DotNet#408]
I want to show some text on top of the player something like overlay and a background image so that always my text will be visible, I have tried that on vlc media player and its working but I want to implement it in my winform application.   
# Generic information

- **Vlc.DotNet version** : (2.2.1)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x64)
- **.net version** : (4.0)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows ...) (x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by rawat123** [comment]
In vlc player under tools --> effects and filters

**Comment by jeremyVignelles** [comment]
OK, the next step for you is to find the corresponding command line that displays the same thing. once you're done, include those command line options in Vlc.DotNet

**Comment by rawat123** [comment]
ok, how can I find what command is being executed and how can I include those command in Vlc.DotNet

I tried opening View -> add interface -> Console   in vlc player
and then I again started overlay but no command executed in console

**Comment by jeremyVignelles** [comment]
Please have a look at the documentations:
https://wiki.videolan.org/VLC_HowTo/Add_a_logo/
https://wiki.videolan.org/Documentation:Modules/logo/
https://wiki.videolan.org/Documentation:Modules/marq/

Try to launch VLC with your command line, using those parameters.

**Comment by jeremyVignelles** [comment]
Position 0 means Center:
See : https://wiki.videolan.org/Documentation:Modules/marq/

Basically, you need to align on the side you want, and offset with X/Y

**Comment by rawat123** [comment]
ok thanks I got it and I think position and X Y positon are similar like you have to use one at a time?

and some questions- 
can I use multiple Marquees?
and multiple logo?
can I set logo behind the marquee?

**Comment by rawat123** [comment]
hi jeremyVignelles I kinda solve it I created a png image as a frame with middle part transparent and marquee text I used \n\t  for multiple lines. 
 thanks for your help, thank u very much.

**Comment by jeremyVignelles** [comment]
Great!
