### ISSUE TITLE
Record stream video with bitrate option

### ISSUE THREAD

**Issue by rawat123** [ZeBobo5/Vlc.DotNet#409]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x64) 
- **.net version** : (4.0)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows 10) (x64)

# Summary

I want to record stream video, I tried with VLC media player and I can record but I don't know how to record with the library in c#, please help me.
and while recording with vlc player my file size is too much I am using camera FCB EV7520 
I tried recording with some other application where I can manage the bitrate and filesize reduced with that. how can I also manage bitrate in Vlc.DotNet.Core in c#
- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Please see here for an example of video recording : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#vlcdotnetcore

As for the bitrate, please look in the vlc wiki

**Comment by rawat123** [comment]
hi @jeremyVignelles I tried the application start with streaming on form load 
```
var mediaOptions = new string[]
           {
                ":dshow-vdev=Aivion-603-IF"
                ,":live-caching=0"
                
           };
            vlcControl1.SetMedia("dshow://", mediaOptions);
            vlcControl1.Play();
```
streaming is working
and I added a button to start recording, on click event I added the below code
     
```
vlcControl1.Stop();
            Thread.Sleep(1000);
            var mediaOptions = new string[]
            {
                ":dshow-vdev=Aivion-603-IF"
                 ,":live-caching=0"
                ,":sout=#transcode{vcodec=XVID, vb=1024}"
                 ,":sout=#file{dst="+Path.Combine(Environment.CurrentDirectory, "output.mp4")+"}"
                ,":sout-keep"
            };
            vlcControl1.SetMedia("dshow://", mediaOptions);

            vlcControl1.Video.AspectRatio = "16:9";
            vlcControl1.Play();
```
and on stop recording I am just calling `vlcControl1.Stop();` 
but my video is recording in YUY2 codec and unable to play with vlc media player 
I tried with vcodec =  h264, mp4v  and HEVC but nothing works video still records in YUY2 codec

**Comment by jeremyVignelles** [comment]
I'm not a recording expert, but the fact that you have two `sout` looks suspiscious to me. What I understand is that you transcode an do nothing with that, and you take the original stream to save it to the disk.
Try merging the two, but if you really have troubles, write the same thing for the command line, and try until you find something that fits you need. if you don't manage to do that, please ask VideoLan

**Comment by jeremyVignelles** [comment]
Did you manage to do what you want?

**Comment by rawat123** [comment]
no, still struggling.

**Comment by morl0048** [comment]
Do you only need to set the mediaOptions of the vlcControl with different parameters to start recording? I also see that you stop your stream before you start recording. Can you still play the stream while recording it?

Thanks for the quick answer as always!

**Comment by rawat123** [comment]
actually when program starts video streams live  and recording is manual so i used to stop stream and start with stream and recording when recording required.

**Comment by morl0048** [comment]
I tought that if you wanted to record a stream, you needed to change the mediaOptions of the vlcController (which is right), but I also tought, for some reasons, that changing/adding those `sout` options were going to stop the vlcController from displaying an image on the windows form...(I was wrong) Anyways... Thanks for the help!

**Comment by jeremyVignelles** [comment]
closing this since there's nothing we can really do in Vlc.DotNet. Feel free to reopen if more help is needed
