### ISSUE TITLE
Wpf VlcControl seems to ignore ZIndex

### ISSUE THREAD

**Issue by dracool** [ZeBobo5/Vlc.DotNet#41]
I tried to draw a semi-transparent overlay (Grid + Semi-Transparent Rectangle) over the vlc control and it is invisible.
I then tried to show it partly over the vlc control and partly over the form and it was visible over the form, but invisible over the VlcControl.

Markup Code:

``` xaml
<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Wpf="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf" x:Class="LivestreamViewer.MainWindow"
        Title="MainWindow" Height="449" Width="753">
    <Grid>
        <Wpf:VlcControl x:Name="vlc" Margin="0,0,0,13" Panel.ZIndex="-1"/>
        <Grid x:Name="overlayGrid" HorizontalAlignment="Stretch" Height="25" Margin="0,0,0,0" VerticalAlignment="Bottom" Panel.ZIndex="1">
            <Rectangle Fill="Black" HorizontalAlignment="Stretch" Margin="0,0,0,0" Stroke="Black" VerticalAlignment="Stretch" IsHitTestVisible="False" Opacity="0.5"/>
        </Grid>
    </Grid>
</Window>
```

Screenshot of the result:
![ae12c35861](https://cloud.githubusercontent.com/assets/1708357/7118402/4620cfd4-e1ff-11e4-9344-cbabf86317b7.png)

**Comment by dracool** [comment]
Checking the source code and WPF Interop problems reveals that this happens because the WPF VlcControl is just a HwndHost displaying the WinForms VlcControl. Rules for when problems occur can be found [here](https://msdn.microsoft.com/en-us/library/aa970688.aspx?f=255&MSPPError=-2147217396)
At the moment there does not seem to be a fix available.

A possible workaround would be to use the [`video_set_callbacks`](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#ga612605f2e5c638d9f4ed59021d714bf0) function from libvlc and some kind of custom rendering method. The [nVLC](http://www.codeproject.com/Articles/109639/nVLC) project seems to have such a custom renderer using a D3DImage surface. Sadly it looks abandoned.

**Comment by wuzhenda** [comment]
yes,that's helpful

**Comment by kjeremy** [comment]
Any general guidance on how to create a pure wpf control with vlc?  I can take a stab at it...

**Comment by kjeremy** [comment]
Specifically: how does the rendering happen and where would I use the `video_set_callbacks` (as an alternative to an existing call?) to alter the behavior?

**Comment by wuzhenda** [comment]
see this issue:
https://github.com/ZeBobo5/Vlc.DotNet/issues/12
and reference the repo:
https://github.com/higankanshi/xZune.Vlc

**Comment by jeremyVignelles** [comment]
Thanks for the great bug report, I've just created an issue to gather all issues related to this : #296
