### ISSUE TITLE
Local Vidoes are not playing... 

### ISSUE THREAD

**Issue by B0R1K** [ZeBobo5/Vlc.DotNet#410]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop275
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (3.0.1) (x64) + DL from FTP
- **.net version** : (4.6.1)
- **Project language** : (C#)
- **Project build architecture** : (nyCPU)
- **Operating system** : (Windows ...) (x86/x64)

# Summary
Hi, when i try to run basic example i get following error, but sample video still plays... 
![image](https://user-images.githubusercontent.com/2473977/38910235-60b04c80-4296-11e8-897c-2239a887a9d8.png)
i did check that path does exist and accessible...

Bigger problem, that i can't play any of the local videos, control just remains blank...

Thank you.

**Comment by B0R1K** [comment]
Hi Jeremy, 

Installed libvlc from Nuget and error went away, but local video still not playing.

using WPF example:
`<Vlc:VlcControl xmlns:Vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf" x:Name="MyControl" />`


```var vlcLibDirectory = new DirectoryInfo("C:\VS Projects\VLCLearner\packages\VideoLAN.LibVLC.Windows.3.0.0-alpha2\build\x64");

    var options = new string[]
    {
        // VLC options can be given here. Please refer to the VLC command line documentation.
    };

    this.MyControl.SourceProvider.CreatePlayer(vlcLibDirectory, options);

    //this.MyControl.SourceProvider.MediaPlayer.Play("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov");
    this.MyControl.SourceProvider.MediaPlayer.Play(@"C:\0\qq.mkv");```

Please let me know if I missed something...

Thank you.

**Comment by jeremyVignelles** [comment]
When playing local files, you must either use the FileInfo overload, or set the MRL to a valid URL-like value, like `file:///C:/0/qq.mkv`

**Comment by B0R1K** [comment]
wow, thank you, that was to easy !

**Comment by horseyhorsey** [comment]
@jeremyVignelles 

Please add your answer to the Getting started.  I just spent a good half hour trying every sample with black screens. 

Seems the online versions eg. "http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi" don't work at all.

Please also add where the logs are produced because you're "still pulling hairs" even though you add the params with no logs.

**Comment by horseyhorsey** [comment]
Sure, no problem. I have been playing with it for a couple of hours now so I'll keep some notes for some extra snippets.
