### ISSUE TITLE
WPF - Slow Application Closing

### ISSUE THREAD

**Issue by Sep95** [ZeBobo5/Vlc.DotNet#411]
First of all, many thanks for the new WPF UI-Element! It has a much more fluent response than the old one. One issue apperared to me.

# Generic information

- **Vlc.DotNet version** : 3.0.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 - manual download via Nuget
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 (x64)

# Summary

When I embed the new WPF UI Element like stated in the [Getting Started Wiki](https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started), everything works fine, even playing a video file. But if I close the Window, it takes more than 5 seconds until the WPF Application shuts down.
I've already tried to Stop the Video in the WPF Window Closing event. But it just slows down the Closing process. Any idea, what the problem could be?

I confirm that my issue doesn't happen in VLC itself.

**Comment by Sep95** [comment]
Using VLC directly, I do not have this problem. So it may be the interop between VLC and the WPF application. The issue also happens when using the release version of the WPF application (without Visual Studio). The window closes fast, but the executable remains more than 5 seconds visible in the task manager. 

Disposing the control in the `Window_Closing()` event works fine. Maybe the Dispose() method is just in code of the new control without being derived from `IDisposable` interface?

**Comment by jeremyVignelles** [comment]
By "not WPF-specific", I meant "could also produce in Vlc.DotNet.WinForms"

Do you mean that Disposing the control solves your issue and you can close the window immediately? In that case, this is great and we can close this issue.

By the way, the new control IS implementing `IDisposable` : https://github.com/ZeBobo5/Vlc.DotNet/blob/0f115710fe4ec0efc14064672d2195f6c458f011/src/Vlc.DotNet.Wpf/VlcControl.cs#L12

**Comment by Sep95** [comment]
Yes, Disposing the control explicitely in the `Window_Closing()` event solves my problem. But I don't know, why this explicit `Dispose()` call is reqired.
