### ISSUE TITLE
screen:// only 1fps

### ISSUE THREAD

**Issue by catzy007** [ZeBobo5/Vlc.DotNet#412]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2011.11.29.0)
- **Vlc.DotNet project used** : (WinForms+WPF+Core)
- **libvlc version** : (x64)
- **.net version** : (2.0)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows 10) (x64)

# Summary

i'm currently trying to modify VRPlayer so it can capture screen and project it as barrel projection.
in simple command line i just type "vlc screen:// :screen-fps=120 :live-caching=0" and it just working properly 120fps and no delay. 

now when i do same thing on vlcdotnet using this code

try
            {
                ClearPlaylist();
                var screen = "screen:// :screen-fps=60 :live-caching=0";
                _player.Media = new LocationMedia(screen.ToString());
                _player.Play();
                IsPlaying = true;
                HasChapters = true;
            }

i'm getting 1 frame/second whatever i do. can you help me or i do some mistake.. anything appreciated

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Vlc.DotNet 2011 looks like an old version that I never met and that is therefore not supported anymore. Are you really using .net framework 2.0? How could you be using WPF then? You didn't mention the version of libvlc you are using. is it a 3.0.1?

That being said, it sounds weird to me that you pass the media options in the same string as `screen://` . In newer versions of Vlc.DotNet, you have a Play method that takes two arguments : the media (`screen://`) and the media options (the array of the two options). Could you try that? In case it doesn't exist, could you upgrade to latest version of Vlc.DotNet? We still support 2.0 for now, but I'm not sure it will stay like that in the future.

**Comment by jeremyVignelles** [comment]
No update for a long time. I'm closing this. Please reopen if help is still wanted.
