### ISSUE TITLE
Marshaling string .net as UTF8 byte array?

### ISSUE THREAD

**Issue by isyami** [ZeBobo5/Vlc.DotNet#414]
I have an  a question about Vlc.DotNet.

Why don't you Marshal a .net string as an array of UTF8 bytes by setting the marshaling type as
```[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
private delegate IntPtr LibVlcMediaNewPath(IntPtr instancePtr,
                           [MarshalAs(UnmanagedType.LPArray)] byte[] location);
```

I did that, and everything worked fine.:

```
public static IntPtr libvlc_media_new_path(IntPtr instancePtr, string path)
{
    return GetAddress<LibVlcMediaNewPath>("libvlc_media_new_path")
        .Invoke(instancePtr, Encoding.UTF8.GetBytes(path));
}
```

**Comment by jeremyVignelles** [comment]
It could have been done this way, you are right.
Here are a few arguments:
-Semantics : A byte array? what should I pass there? a "string handle" is clearer in my mind
- Symmetry: a converter converts a string from and to a IntPtr
- Why not? it works well like that, unless you show me a benchmark that shows a huge perf improvement doing like that, I don't really see the point.

**Comment by isyami** [comment]
Yes, I looked at your implementation of copying the data string. This option came to my mind, but I'm not sure that it is pretty nimble =)
