### ISSUE TITLE
The PositionChanged event in the VlcMediaPlayer class has bug.

### ISSUE THREAD

**Issue by tianxin8206** [ZeBobo5/Vlc.DotNet#418]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (3.0.0-alpha3) (x64) nuget
- **.net version** : (4.6.2)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows) (x64)

# Summary
The video length is 72 seconds.But position stopped to change at 58 seconds.
![qq 20180514144635](https://user-images.githubusercontent.com/32237514/39984110-a933eee8-578c-11e8-8ffb-78287a326da2.png)

The event binding method not executed at 58 seconds.

**Comment by jeremyVignelles** [comment]
Please use the issue template.
Does that happen in vlc itself?

**Comment by tianxin8206** [comment]
It has been modified.

**Comment by jeremyVignelles** [comment]
Please try with VLC itself. My guess is that VLC cannot read your file correctly. (try with the same version as the libvlc ypu are using)

**Comment by tianxin8206** [comment]
Really?My video is in the server.😵

**Comment by jeremyVignelles** [comment]
but you can play it with the sample, so why can't you play it with vlc?

**Comment by tianxin8206** [comment]
Let me try.Thank you.

**Comment by jeremyVignelles** [comment]
Any update on this?

**Comment by jeremyVignelles** [comment]
My guess is that something is wrong with the video, or there is a bug in vlc. Since I do not have any evidence that this is related to Vlc.DotNet, I'm closing this. Feel free to reopen if more help is needed.
