### ISSUE TITLE
Get video device list

### ISSUE THREAD

**Issue by aap4ixx** [ZeBobo5/Vlc.DotNet#419]
I have a question.
How i can take video capture device list?

# Generic information
- **Vlc.DotNet version** : (2.2.5)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (2.2.8) (x86) + how did you get it?
Take from official side.
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10) (x64)

**Comment by jeremyVignelles** [comment]
I don't think there is any API for that in libvlc itself. The better option I can think of is to get that info from the Windows API by yourself.
