### ISSUE TITLE
Smooth Streaming (VLC 3.x)

### ISSUE THREAD

**Issue by cpritchard** [ZeBobo5/Vlc.DotNet#42]
I have been looking for solutions for implementing smooth streaming in WPF and came across this project. However VLC 2.X smooth streaming is pretty much unusable, and it isn't an issue simply with the project but with VLC 2.X in general that also effects that standalone VLC player. 

https://trac.videolan.org/vlc/ticket/11426

Based on that ticket I tried one of the 3.X nightly builds with great success in playing smooth streaming sources. It would be amazing to see a 3.X branch become availiable.

**Comment by wuzhenda** [comment]
tks.it's usefull. but can we simply replace the vlc lib  in this project?

**Comment by jeremyVignelles** [comment]
The version number of this repository is misleading. You can use 3.0 libraries with this project. You can follow the getting started wiki to know how to download the libvlc version you want
