### ISSUE TITLE
Record and display RTSP stream

### ISSUE THREAD

**Issue by saM21785** [ZeBobo5/Vlc.DotNet#420]
# Generic information

- **Vlc.DotNet version** : 3.0.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.0-alpha3 x86
- **.net version** : 4.5.2
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows x64

Hello everyone,

I'm able to record and display video stream like this one : 

http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov

With this command line : 
:sout=#duplicate{dst=display,dst=std{access=file,mux=mp4,dst=d:\\record\\12345.mp4}}

With a rtsp video stream, the record option works but the image is no more displayed.  I use the same command line and here is the link of the rtsp stream : 
rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

Can someone help please? I'm really stuck on this. 

Thx

# Some code
```C#
vlcControl.SourceProvider.MediaPlayer.SetMedia(new Uri("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov"), 
new string[] { ":sout=#duplicate{dst=display,dst=std{access=file,mux=mp4,dst=d:\\record\\12345.mp4}}" });

**Comment by jeremyVignelles** [comment]
Are you able to record and play with VLC media player?
On my side, I'm unable to record correctly any RTSP stream with VLC 3 (file does not grow until I close the window). See https://trac.videolan.org/vlc/ticket/18940

**Comment by saM21785** [comment]
I'm not able to..  Made some tests, everything works fine until version 3 :/

**Comment by jeremyVignelles** [comment]
Then unfortunately, it is out of the scope of Vlc.DotNet, so I'm closing this. Feel free to comment on the trac ticket linked above.

**Comment by saM21785** [comment]
I'm agree.  Using an old library doesn't make me happy but that do the thrick for the moment.  I'll contribute to this ticket.
