### ISSUE TITLE
RTMP delay too much

### ISSUE THREAD

**Issue by tranvyhor** [ZeBobo5/Vlc.DotNet#425]
I have a question about Vlc.DotNet. Is there any way to stop/close buffer (such as adding '-fflags nobuffer' param for ffplay) to reduce delay for RTMP playing?

# Generic information

- **Vlc.DotNet version** : (2.2.1)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (2.2.1) (x86)  nuget
- **.net version** : (4.5.1)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows 10) (x86)

# Summary

VLC at least delays 5 seconds for playing RTMP stream(720P).

**Comment by jeremyVignelles** [comment]
did you try with`--network-caching=<value in ms>`? too low values may cause stuttering

**Comment by jeremyVignelles** [comment]
Also please fill the issue template

**Comment by tranvyhor** [comment]
Yes, I tried.

**Comment by jeremyVignelles** [comment]
And? does it have any effect? You said that you are using libvlc 2.2.1 from NuGet? how is that possible? we started packaging libvlc in nuget starting from 3.0.0. If you're not already using it, use libvlc 3.0.0

**Comment by tranvyhor** [comment]
Ok, I have a try with libvlc 3.0.0.

**Comment by remy33** [comment]
As jeremy said, it's probably the VLC. 
Open regular client of VLC and choose stream, after the dialog you will be able to see the parameter VLC itself uses.

**Comment by jeremyVignelles** [comment]
Closing this as there's probably nothing I can do (please reopen if this is the case)
