### ISSUE TITLE
How can i add subtitle to media 

### ISSUE THREAD

**Issue by PhantomCloak** [ZeBobo5/Vlc.DotNet#426]
I have an issue about vlc dotnet how can i add subtitle to player 

# Generic information

- **Vlc.DotNet version** : (2.2.1)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (3.0.2.0) (x86) 
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows 10) (x64)

# Summary

How can i add subtitle to my video im spent lots of time to find documentation and i found nothing is there any documantation or sample about adding subtitle to player

**Comment by jeremyVignelles** [comment]
subtitles? Do you have a subtitle file? Are you able to do that in the VLC media player ?

**Comment by PhantomCloak** [comment]
yes i have and yes it does but i dont know how can i add subtitle file to embedded player

**Comment by jeremyVignelles** [comment]
Are you able to do that from the VLC command line? I'm sorry, but I've never done that before, I'm just giving you the general steps to get started.

Once you have the command line, you have the options to pass to Vlc.DotNet

**Comment by PhantomCloak** [comment]
oh thanks i solved with vlc command line

`myVlcControl.SetMedia(@"file:///E:\movies\watchman.mp4",new string[] { @"--sub-file=E:\movies\watchman.srt" });`
