### ISSUE TITLE
How to set deinterlace Mode

### ISSUE THREAD

**Issue by Alphagen2901** [ZeBobo5/Vlc.DotNet#428]
# Generic information
- **Vlc.DotNet version** : 2.2.6
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64, installed vial vlc installer
- **.net version** : 4.6.1
- **Project language** : (C#
- **Operating system** : Windows 10 x64

Im having stripes in my videos if i play them via vlc.DotNet.
In VLC itself i turned on deinterlace and used yadif to solve this problem.

in C# i tryed the following:

`string[] streamingaArguments = new string[] {`
`"--sout-deinterlace-mode=yadif --sout='#transcode{deinterlace}};`
`FileInfo fi = new FileInfo(motiv.pfad);`
`vlc.Play(fi, streamingaArguments);`

Can someone tell me how i can use yadif in deinterlaced mode?

**Comment by jeremyVignelles** [comment]
Please set only one parameter per argument string.

```
var streamingArguments = new string[] {
   "--sout-deinterlace-mode=yadif",
   "--sout='#transcode{deinterlace}'"
};
```

This is the first step, I don't know if this will fix anything, but that's the way it's supposed to be.
Please also check your syntax, I'm not sure if you copy/pasted your real code here...

Once you've done that, you will be very close from the solution. If you are still having issues, try writing the command line that does what you want and paste it here.

**Comment by Alphagen2901** [comment]
Thanks for your fast answer. I've tryed your answer with one parameter per argument string but it didnt  change anything. :-/ Still having this stripes in the video. 
The complete method looks like this:


```
public void setMotiv(Motiv m) {
   MethodInvoker vis = delegate () {
      vlc.Visible = true;
      FileInfo fi = new FileInfo(motiv.pfad);
      vlc.SetMedia(fi);
      vlc.EndReached += vidEndReached;
      vlc.Playing += vidStarted;

      var streamingArguments = new string[] {
          "--sout-deinterlace-mode=yadif",
          "--sout='#transcode{deinterlace}'"
        };

        vlc.Play(fi, streamingArguments);
    };
    Invoke(vis);
}
```

**Comment by jeremyVignelles** [comment]
I don't know if those options can be set with play(), and I don't think the syntax is the same here.
Can you try providing the options in VlcMediaPlayerOptions in the media player option at initialization? (see wiki for samples)

**Comment by Alphagen2901** [comment]
Sorry but i can't find an working example. Can you link it to me maybe?

**Comment by jeremyVignelles** [comment]
great!
