### ISSUE TITLE
Vlc Control error

### ISSUE THREAD

**Issue by Gabee8** [ZeBobo5/Vlc.DotNet#43]
Hello!
I use vlc control in c# 2010 (winform).
I build or save project show this messange:
"Code genetation for property 'Time' failed. Error was: 'Property accessor 'Time' on object 'myVlcControl' threw the following exception: 'Object reference not set to an instance of an object.'"
How to fix a problem? (sorry my bad english)
Thanks G.

**Comment by vlkam** [comment]
I had this problem too. I just ignored this and closed Form Disigner Window. After that an error message don't appeared again.
And also I can't change audio track 
At the moment I migrate to NVLC library.

**Comment by Gabee8** [comment]
Nvlc one problem dotnet 4 minimum :( I use dotnet 3.5! Thx answer

**Comment by vlkam** [comment]
Hi!
Do you solved this problem ?

**Comment by Gabee8** [comment]
Hi!
Solved this:

Vlc.DotNet.Core.VlcMediaPlayer vmpl;
DirectoryInfo VlcLibDirectory = new DirectoryInfo(Path.Combine(currentDirectory, @".\Vlc\"));
vmpl = new Vlc.DotNet.Core.VlcMediaPlayer(VlcLibDirectory);
vmpl.VideoHostControlHandle = panel1.Handle;
Button click event:
FileInfo file = new FileInfo(fileName);
vmpl.SetMedia(file);
vmpl.Play();

**Comment by vlkam** [comment]
Thanks, it's a very interesting solution

**Comment by umarcpt** [comment]
@Gabee8 what is currentDirectory? kindly explain
