### ISSUE TITLE
Access violation exception after long time of playing video

### ISSUE THREAD

**Issue by max619** [ZeBobo5/Vlc.DotNet#431]
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in TestVideoPrj.exe: 0xC0000005: Access violation reading location 0x0000000000000028

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x64 (3.0.0-alpha3 Nuget package) 
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Win 10 x64

# Summary

When video playing for a long time >90 mins (even if it same video started with input-repeat) libvlc throws Access violation exception and crushes application without any information.

Also i changed VlcVideoSourceProvider to not allocate memory for every video to remove empty images between videos when changing them from one to another. Every video have same resolution and same buffer size.

And i noticed strange behaviour when new video openning in VlcVideoSourceProvider.
When new video starts opening first allocates buffer for frame with resolution 1650x960, then allocates new buffer for frame with resolution 1650x962 (video has resolution 1650x960) and then starts invalidating for every frame.

Debug output:
```

avcodec decoder debug: available hardware decoder output format 119 (cuda)
avcodec decoder debug: available hardware decoder output format 53 (dxva2_vld)
avcodec decoder debug: available hardware decoder output format 118 (d3d11va_vld)
avcodec decoder debug: available hardware decoder output format 174 (d3d11)
avcodec decoder debug: available software decoder output format 0 (yuv420p)
avcodec decoder debug: reusing decoder output format 0
main input debug: Buffering 83%
main input debug: Stream buffering done (500 ms in 2 ms)
main decoder debug: Received first picture
main input debug: Decoder wait done in 10 ms
main vout display debug: VoutDisplayEvent 'window state' 0
main generic debug: reusing provided vout
main vout display debug: VoutDisplayEvent 'window state' 0
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x2fa8 has exited with code 0 (0x0).
main audio output warning: playback way too late (1609079000): flushing buffers
main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)
main audio output warning: buffer too late (-1608613000 us): dropped
main audio output warning: buffer too late (-1608592667 us): dropped
main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: ES_OUT_RESET_PCR called
main input debug: ES_OUT_RESET_PCR called
main audio output warning: buffer too late (-1609969334 us): dropped
main input debug: Buffering 0%
ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)
The thread 0x5cc8 has exited with code 0 (0x0).
The thread 0x4624 has exited with code 0 (0x0).
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 8%
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)
main input debug: Buffering 0%
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 16%
The thread 0x49cc has exited with code 0 (0x0).
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 24%
main input debug: Buffering 32%
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x48b8 has exited with code 0 (0x0).
main input debug: Buffering 40%
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 83%
main input debug: Buffering 48%
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 56%
main input debug: Buffering 64%
main input debug: Buffering 72%
main input debug: Buffering 80%
main input debug: Stream buffering done (500 ms in 3911 ms)
main input debug: Buffering 88%
main input debug: Buffering 96%
main input debug: Stream buffering done (312 ms in 5332 ms)
main input debug: Decoder wait done in 0 ms
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 5020 ms)
main audio output warning: buffer too late (-1763000 us): dropped
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main audio output warning: buffer too late (-2384000 us): dropped
main input debug: ES_OUT_RESET_PCR called
ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 5020 ms)
main audio output warning: buffer too late (-2360000 us): dropped
main vout display debug: VoutDisplayEvent 'resize' 1536x960
main audio output warning: buffer too late (-2337000 us): dropped
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 0%
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x3130 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 1%
main input debug: Buffering 2%
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x22a4 has exited with code 0 (0x0).
main video output warning: picture is too late to be displayed (missing 1656716 ms)
main video output warning: picture is too late to be displayed (missing 1656677 ms)
main video output warning: picture is too late to be displayed (missing 1656637 ms)
main video output warning: picture is too late to be displayed (missing 1656597 ms)
main input debug: Buffering 3%
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x1410 has exited with code 0 (0x0).
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x4b6c has exited with code 0 (0x0).
The thread 0x6024 has exited with code 0 (0x0).
The thread 0x35b4 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x3fcc has exited with code 0 (0x0).
The thread 0x62e8 has exited with code 0 (0x0).
main input debug: Buffering 4%
main input debug: Buffering 5%
main input debug: Buffering 6%
main input debug: Buffering 7%
main input debug: Buffering 8%
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x1878 has exited with code 0 (0x0).
main input debug: Buffering 9%
main input debug: Buffering 10%
main input debug: Buffering 11%
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

main input debug: Buffering 12%
Unhandled exception at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

The thread 0x37f0 has exited with code 0 (0x0).
Exception thrown at 0x00007FFB18AE5C46 (libvlccore.dll) in VideoTestProj.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

```

I can make a prediction that it can happen because of old frame buffer, however if same video playing looping, buffer should not be reallocated.

**Comment by max619** [comment]
`00007FFB18AE5C46  mov         rax,qword ptr [rcx+28h]`
line of dissasembled code where exception is thrown,
and rcx is 0, and i dont think that it shold be equal to 0

**Comment by jeremyVignelles** [comment]
I am currently in vacation until june, the 22nd, and I won't probably be very helpful in the meantime.
Disassembly won't probably be helpful, but if you really want to help with that, you can probably start with a debug version of libvlc (i.e. build your own vlc). This will be long and painful...

This can really be many things :
-A bug in a vlc plugin
-A bug in the libvlc core
-A bug in Vlc.DotNet
-Your changes in VlcSourceProvider introduced a bug (like a race condition)

A few things you can try:
-Does it happen with videos I can find on internet, like "big buck bunny" or "caminandes"?
-Does it happen independently of the codec used?

If you want a quick way to solve that, use the WinForms contol in a WinFormsHost (see the readme for the comparison).

As for the buffer size, I'm not surprised that the buffer is bigger than the video. To make operations faster, vlc aligns its buffer to fixed values and then displays fewer pixels rows or columns.

**Comment by max619** [comment]
@jeremyVignelles  Thank you for operative reply, i'm going to do a little research and neither i solve this problem or not, i'm going to report here.

**Comment by max619** [comment]
So, this problem keep appears with different versions of libvlc and different codecs.

However, with version 3.0.4 another exception i thrown: 
`Unhandled exception at 0x00007FFB7B4AF218 (KernelBase.dll) in VideoTestProj.exe: 0xC0020001: The string binding is invalid (parameters: 0xFFFFFFFF8007042B).`

and after this i got this message:

```
[00000256ffa6d0b0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[00000256f3691430] mmdevice audio output error: cannot initialize COM (error 0x80010106)
Assertion failed!

File: ../../extras/package/win32/../../../src/input/decoder.c, Line 555

Expression: p_owner->p_vout
```

**Comment by max619** [comment]
I have tested my video with WPF Sample, still got the same exception after playing for 90 to 200 minutes with `input-repeat=65535` param.
Also tested with Big Bucks Bunny, it works OK, but it is pretty long video. The video i'm playing is short, about 3 seconds.

WinForms sample works fine. And i noticed, that in winforms appears one more message, that i have never seen in WPF one:
`[h264 @ 00000181c5153340] Reinit context to 1536x976, pix_fmt: d3d11va_vld`

May it be the case, that when video source provider is called to reinit context, it just does not support this action? But this debug message comes not from VlcDotNet code base, but from libvlc itself because i cant find any `Debug.WriteLine()` in code? except ones that wrote in sample, also it got no `libVlc : ` prefix, that is added before log messages.

**Comment by jeremyVignelles** [comment]
sorry, I just noticed I didn't answer the last message:
It is normal that WinForms and WPF does not display the same messages, because they have different `vout`, that is, they print their video in different places, in different formats. WPF renders the video in a buffer, that is then displayed by WPF, whereas WinForms renders that directly to the screen using DirectX.

Yes, logs come from libvlc itself. You can disable them, or you can even get them by listening to the ` Log` event, as done in the sample project (that's why the format is different)

Can we close this issue?

**Comment by max619** [comment]
Actually it looks like this is a bug in libvlc itself, if i would have enough time to find that bug, i would create an issue in libvlc repository.

That is why we can close the issue. Thank you for your time.
