### ISSUE TITLE
How to play multiple DirectShow devices

### ISSUE THREAD

**Issue by DonaldReynolds** [ZeBobo5/Vlc.DotNet#434]
I have an a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64 + Nuget package
- **.net version** : 4.5.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : (Windows 10) (x64)

# Summary

The following code will not select the device specified in the options. vclControl1 will play HD USB Camera (first that enumerated) and vclControl2 does not play either devices. vclControl2 will play a media file when set.  

            string mrl = "dshow:// ";

            string[] options1 = new string[] { " :dshow-vdev=\"Logitech BRIO\"" };
            vlcControl1.SetMedia(mrl , options1);
            vlcControl1.Play();

            //            vlcControl2.SetMedia(new FileInfo(@"C:\TASR0013.mp4"));
            string[] options2 = new string[] { " :dshow-vdev=\"HD USB Camera\"" };
            vlcControl2.SetMedia(mrl, options2);
            vlcControl2.Play();

- [X ] I confirm that my issue doesn't happen in VLC itself.

I can select and play either device in VLC.

**Comment by jeremyVignelles** [comment]
Can you select your device with the vlc command line?
Please also remove the space at the beginning of the strings

**Comment by jeremyVignelles** [comment]
Did you manage to get it work?

Please reopen if you're still facing issues.
If you managed to find a solution, please share it! :slightly_smiling_face:
