### ISSUE TITLE
Getting the WPF control from a player

### ISSUE THREAD

**Issue by miyakoj** [ZeBobo5/Vlc.DotNet#435]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop289
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.0-alpha3 x86 (NuGet)
- **.net version** : 4.6.2
- **Project language** : C#
- **Project build architecture** : AnyCPU - prefer 32bits
- **Operating system** : Windows 7 x64

# Summary

Is there a way to get a reference to the VLC control from a player? I'm using this for a video wall project and I want to log messages to files in events that are specific to a video and I need access to the name of the control. Or is there a way to name the video? Thanks in advance.

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
There isn't, since the Player is from the Vlc.DotNet.Core, which has no knowledge of the WPF control.

Where do you want to do that? Is there any way you could pass other data with your player reference?

**Comment by jeremyVignelles** [comment]
Why not something like this? (pseudo code, did not test)

``` CS
var controlName = "ThisIsMyControl";
player.Log += (s,e) => {
    LogSomething(e, controlName);
};
```

**Comment by miyakoj** [comment]
I ended up passing a unique filename to the VLC options as I create each player because all of the messages were getting mixed up in the files using your suggestion. I was hoping to use the Vlc.DotNet logger since I could include a timestamp with each message, but this works well enough. Thank you for your help.
