### ISSUE TITLE
ONVIF + rtsp how to change stream 

### ISSUE THREAD

**Issue by maciejkaiser** [ZeBobo5/Vlc.DotNet#436]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0 -dev289
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x64
- **.net version** : 4.6.2
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows x64

# Summary

I'm using a Panasonic IP camera and I have a problem with getting not-default stream from it. In config I can select 4 streams and set values like resolution or image quality but I don't have any idea how to use it with Vlc.DotNet.

Code that works and displays first stream (default): 
` myControl.SourceProvider.MediaPlayer.Play(new Uri("rtsp://" + IpAddress + "/ONVIF/MediaInput?profile=def_profile1"));`

Camera config:
![ipcamera](https://user-images.githubusercontent.com/12011503/42129319-0edb9714-7cc2-11e8-8b4e-f56cb8b600a1.PNG)

Also I don't know where to find documentation that describe those parameters after MediaInput value. Any ideas how to extort using i.e. Stream(2)?

**Comment by jeremyVignelles** [comment]
Libvlc is not yet able to read onvif directly. This means that you must feed it with a rtsp URL to get it work. However RTSP URLs are constructor-specific and I don't know them for your case.

What you can try is to use a software like "ONVIF Device Manager" to read the stream profiles from the camera. However, I don't know if you could get the rtsp url directly that way.

**Comment by jeremyVignelles** [comment]
Please try Onvif Device Manager and try to play thelive stream. From there, there should be the URL at the bottom of the screen.

It is possible (by resizing your control, Ratio doesn't work for the WPF control, see another issue) but it is a bad idea : your stream will be stretched for nothing, while the purpose of the stream profiles is to get the right resolution from the camera.

**Comment by maciejkaiser** [comment]
The reason why I'm asking is that when my app need to display 8-16 streams at once - then performance dramatically goes down :( I think that trick with changing resolution / ratio may be help with that. Thanks for your answer, I'll try that approach.

**Comment by jeremyVignelles** [comment]
If you have perf issues with the new WPF control, use the WinForms control in a WinFormsHost. See the readme and the WPF sample using WinForms.
Changing resolution on Vlc side won't make your app faster : it needs to decode the stream at full resolution anyway, and then scale it

**Comment by maciejkaiser** [comment]
But the camera have stream profile with lower resolution and framerate. This won't work that way?

**Comment by jeremyVignelles** [comment]
Setting video options on VLC side won't affect the stream provided by the camera, but only what gets displayed by vlc. Internally, it needs to make a convertion between what the stream provides and what you asked.

If you want a specific stream profile, you must pass it to the rtsp URL

**Comment by maciejkaiser** [comment]
That's way I want to use stream profile, but it didn't work with profile other than default. Now I'm dealing with ONVIF Device Manager that you suggest and it's looking like it works ! :) Thank you for help.

**Comment by maciejkaiser** [comment]
An issu was about stream encoding format - H.265 instead of H.264.

**Comment by maciejkaiser** [comment]
Sure : 

`myControl.SourceProvider.MediaPlayer.Play(new Uri("rtsp://user:password@" + IpAddress + "/ONVIF/MediaInput?profile=def_profile4"));`

i.e.
`myControl.SourceProvider.MediaPlayer.Play(new Uri("rtsp://user:password@192.168.88.252/ONVIF/MediaInput?profile=def_profile4"));`

You can also use url without user login (depends on camera settings)

`myControl.SourceProvider.MediaPlayer.Play(new Uri("rtsp://" + IpAddress + "/ONVIF/MediaInput?profile=def_profile4"));`

**Comment by jeremyVignelles** [comment]
Thanks for sharing. VLC should be able to decode H.265... which version of libvlc are you using?

Please also note that in libvlc,using user:pass in URL is deprecated. You should use the Dialog API instead (there is a sample in this repository)

**Comment by maciejkaiser** [comment]
It's 2.1.3.0 for 64bit version

**Comment by jeremyVignelles** [comment]
It's a pretty old version, and the dialog API wasn't there at that time if I remember correctly. I'd recommend that you use the libvlc 3 from NuGet

**Comment by jeremyVignelles** [comment]
And that could explain why H.265 is not supported...

**Comment by maciejkaiser** [comment]
Ok I'll use that version. Thanks for you mention that
