### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by aborrelli87** [ZeBobo5/Vlc.DotNet#437]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 and x64 from https://download.videolan.org/pub/videolan/vlc/3.0.3/
- **.net version** : 4.7.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows x64

# Summary

I would like to know how to use the plugins during playing a movie, such as rotate or transform.

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Did you have a look at the wiki? If I remember correctly, it shows the generic steps to answer the question "How to do that in Vlc.DotNet"

**Comment by aborrelli87** [comment]
I found two similar post: https://github.com/ZeBobo5/Vlc.DotNet/issues/216 https://github.com/ZeBobo5/Vlc.DotNet/issues/86 but both don't have a valid solution, because they use VlcMediaplayerOptions (with command line options) before the EndInit and before the SetMedia, not during playing...
 
I was thinking of something like this:

```
using System;
using System.Runtime.InteropServices;

namespace Vlc.DotNet.Core.Interops.Signatures
{
    /// <summary>
    /// Returns a list of video filters that are available.
    /// </summary>
    [LibVlcFunction("video_format_TransformTo")]
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void VideoFormatTransformTo(IntPtr fmt, VideoOrientation orientation);    
}
```

**Comment by jeremyVignelles** [comment]
I'm not sure libvlc provides this kind of feature... vlc can do that because it uses a privileged way to access the lower-level API

**Comment by jeremyVignelles** [comment]
I have the confirmation of what I thought : Here is a long-standing bug to apply filters on-the-fly : https://trac.videolan.org/vlc/ticket/5603 .
Until this issue is resolved, there's nothing we can do on our side.
