### ISSUE TITLE
Options :sout duplicate

### ISSUE THREAD

**Issue by 44simon** [ZeBobo5/Vlc.DotNet#438]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop289
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.3.0 - downloaded from official site
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Win10 x64

# Summary

First of all I would like to thank you for your hard work. On the stable version and meta.vlc I had a problem with forcing options, only one option worked. On Vlc.DotNet 3.0 the options seem to work fine, although I have problem with recording the video. The same command in the vlc works and the file is created in directory. Here the file is not created. Maybe I' doing something wrong, below is just a scratch of what I'm using:

            String[] Video_options_line = new String[] {
                ":dshow-vdev=" + video_device,
                ":dshow-adev=" + audio_device,
                ":sout=#duplicate{dst=std{access=file,,mux=mp4, dst='V:\recorder\test.avi'},dst=display}"

            };

            this.vlc.SourceProvider.CreatePlayer(libDirectory, options);
            this.vlc.SourceProvider.MediaPlayer.Play("dshow://", Video_options_line);

BR,
Simon

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
I suppose you need to double the backslashes `\`, because `\r` and `\t`have special meanings. or, you can use the verbatim string form : `@""` to avoid the wrong escape

**Comment by 44simon** [comment]
Man, thank you for enlightening me, I totally forgot about it. I was pretty sure it was something stupid this time... I'm deeply sorry. The file was created. :)
