### ISSUE TITLE
Is there any way to applied Overlay functionality in Vlc.DotNet?

### ISSUE THREAD

**Issue by anirudhagupta** [ZeBobo5/Vlc.DotNet#440]
I am trying to apply overlay on my video. I have a frame and a video.  What I am looking for is setting frame on video.

**Comment by jeremyVignelles** [comment]
Please use the issue template to help understand your specific question.

How would you do that with libvlc itself ? Would you use the `marq` plugin?
Try to do that from VLC command line. Once it's done, you have the parameters to give to Vlc.DotNet
