### ISSUE TITLE
No hardware acceleration for video decoding

### ISSUE THREAD

**Issue by Sep95** [ZeBobo5/Vlc.DotNet#441]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.3.0 x86 via official VideoLAN homepage 
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary
When opening an MP4 file directly with VLC, hardware acceleration for video decoding is active by default. This can be confirmed by taking a look at the Windows 10 Task Manager in the GPU Column. When opening the same file with the VlcControl in my WPF application, no hardware acceleration for video decoding is used. This results in a huge CPU workload. Is there a way, to force libvlc to use hardware acceleration?

 I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
See the readme : use the WinForms control if you need performance
