### ISSUE TITLE
how to reopen/restart stream after EndReached/Freeze

### ISSUE THREAD

**Issue by morl0048** [ZeBobo5/Vlc.DotNet#444]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 using this link's instruction -> https://github.com/ZeBobo5/Vlc.DotNet/wiki/Using-Vlc.DotNet-in-WinForms (nuget package manager)
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows10 x64

# Summary
I am displaying a rtsp stream using a VlcControl in a windows form.

This stream is from an ONVIF conformant ip camera.

When I play the stream, I always encounter the EndReached flag of the VlcControl when the stream has been playing for a bit.

So, it looks like the display of the stream just freezes, because my VlcControl thinks there's no more images to show...

I have to repress my play button every time my stream freezes, so my application can't really run by itself...

**I want my stream to restart by itself when it freezes.**

I tried using the `EndReached` flag : 
`private void myVlcControl_EndReached(object sender, Vlc.DotNet.Core.VlcMediaPlayerEndReachedEventArgs e)`
`{`

`(sender as VlcControl).Play(MyStream.URL);`

`}`

But, when I do so, my stream won't restart...

What's the best way to do what I'm trying to achieve?

**Comment by jeremyVignelles** [comment]
Please read the wiki, there is a page for this kind of freezes

**Comment by morl0048** [comment]
oh god, I feel stupid, it's right there! hahah

Thank allot!

[Wiki link](https://github.com/ZeBobo5/Vlc.DotNet/wiki/Vlc.DotNet-freezes-(don't-call-Vlc.DotNet-from-a-Vlc.DotNet-callback))
