### ISSUE TITLE
Remap Audio Filter

### ISSUE THREAD

**Issue by lcbpdev** [ZeBobo5/Vlc.DotNet#446]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop294
- **Vlc.DotNet project used** : Core
- **libvlc version** : x86 from the VLC Homepage
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits))
- **Operating system** : Windows 10 x64

# Summary

I want to use the remap audio filter to choose from which speaker to play.
When I pass the following options from the command-line to the vlc.exe it works perfectly.
When I pass them as options to the Vlc.DotNet it's like the filter is ignored.
Am I doing something wrong?

`"--audio-resampler=any",
"--stereo-mode=5",
"--force-dolby-surround=1",
"--audio-filter=remap",
"--aout-remap-channel-left=0",
"--aout-remap-channel-center=0",
"--aout-remap-channel-right=0",
"--aout-remap-channel-rearleft=0",
"--aout-remap-channel-rearcenter=0",
"--aout-remap-channel-rearright=0",
"--aout-remap-channel-middleleft=0",
"--aout-remap-channel-lfe=0",
"--aout-remap-normalize"`

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Can you share a sample code ? How can I test that ?

**Comment by lcbpdev** [comment]
I start the VLC-Player from the command-line with the following command:
`vlc --vout=any --audio-resampler=any --audio-filter=remap --aout=any --stereo-mode=5 --force-dolby-surround=1 --aout-remap-channel-left=7 --aout-remap-channel-center=7 --aout-remap-channel-right=7 --aout-remap-channel-rearleft=7 --aout-remap-channel-rearcenter=7 --aout-remap-channel-rearright=7 --aout-remap-channel-middleleft=7 --aout-remap-channel-lfe=7 --mmdevice-audio-device={0.0.0.00000000}.{.....}`

Then I start to listen to music and it does what it should, it plays out of the right surround speaker.
The audio device is configured in windows-settings as 7.1 surround.

In my code I create the VLC player with the following code:
```
string[] options = {
	"--vout=any",
	"--audio-resampler=any",
	"--audio-filter=remap",
	"--aout=any",

	"--stereo-mode=5",
	"--force-dolby-surround=7",
	"--aout-remap-channel-left=7",
	"--aout-remap-channel-center=7",
	"--aout-remap-channel-right=7",
	"--aout-remap-channel-rearleft=7",
	"--aout-remap-channel-rearcenter=7",
	"--aout-remap-channel-rearright=7",
	"--aout-remap-channel-middleleft=7",
	"--aout-remap-channel-lfe=7",
	"--mmdevice-audio-device={0.0.0.00000000}.{.....}"
};
mediaPlayer = new VlcMediaPlayer(new DirectoryInfo(libDirectory), options);
```

Later, from another thread, I start playing music like this:

```
string[] options = {};
mediaPlayer.SetMedia(url, options);
mediaPlayer.Play();
```

This music always comes from the front speakers, no matter which channel i map it to.

Here you can find the log file:
[log.txt](https://github.com/ZeBobo5/Vlc.DotNet/files/2205608/log.txt)

**Comment by jeremyVignelles** [comment]
I noticed this line:

> wasapi generic error: cannot initialize audio client (error 0x8889000a)

A quick search brought me to : https://forum.videohelp.com/threads/388189-ffplay-WASAPI-can-t-initialize-audio-client-error

Can you please try to set the `SDL_AUDIODRIVER` environment variable to `directsound` ?

Anyway, it looks like a bug in vlc or one of its plugins. You will probably get more useful help from there.

**Comment by jeremyVignelles** [comment]
did you manage to solve your issue?
I'm closing this, since It's been a long time and I have no evidence that this is a bug in Vlc.DotNet itself. Please reopen if you still need help.
