### ISSUE TITLE
Issue with EndReached event

### ISSUE THREAD

**Issue by Sep95** [ZeBobo5/Vlc.DotNet#450]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.3.0 x86 via official VideoLAN homepage
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 (x64)

# Summary

The EndReached event is somehow unusable. If I access a GUI element in the belonging event handler, it throws an InvalidOperationException. If I syncronize the access [like shown here](https://stackoverflow.com/a/1792156) it throws an internal .Net Framework exception.
I only tried it with video files (*.mp4, *.mov).

I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Did you try with `Dispatcher.BeginInvoke()` instead of `Invoke()` ? `Invoke` is synchronous and locks the VLC thread, whereas `BeginInvoke()` is more "fire and forget"

**Comment by Sep95** [comment]
`BeginInvoke()` does not fire an exception, but the whole program freezes.

**Comment by jeremyVignelles** [comment]
What are you doing in the `BeginInvoke()`? Are you only doing some UI-related things? or VLC things?

For vlc-related fonction, you will probably need to wrap them in `ThreadPool.QueueUserWorkItem`, as described in https://github.com/ZeBobo5/Vlc.DotNet/wiki/Vlc.DotNet-freezes-(don't-call-Vlc.DotNet-from-a-Vlc.DotNet-callback)

**Comment by Sep95** [comment]
I'm only doing one UI related operation: Changing the Source of an Image placed on the UI: `imgPlayPause.Source = playerIcons[0];`
I'm also doing the same thing with the WPF MediaPlayer `MediaEnded` event. There I have no problems.

**Comment by jeremyVignelles** [comment]
That's super weird. 

- What kind of media are you trying to play?
- What if you remove your UI call and replace it by a Console.WriteLine? Does it still freeze?
- Does it also freeze if you call a MessageBox.Show() ?
- Is there any log that can help ?
- Can you send a sample code? Can you reproduce in the sample project?

**Comment by Sep95** [comment]
While creating a demo application for reproducing the issue I found the problem. It was a wrong delegate parameter of `BeginInvoke` which results in an runtime error.
