### ISSUE TITLE
Using VLC commands in VLCDotnet app

### ISSUE THREAD

**Issue by Boheminsan** [ZeBobo5/Vlc.DotNet#453]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64 + how did you get it?
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 Pro x64

# Summary
Hi to all. I am trying to make VLC media player in WinForms.
My problem is about VlcMediaPlayerOptions.
I want to use vlc command line parameters and commands in my app.
As i search, its possible with VlcMediaPlayerOptions property.
But some of commands are working; some are not.
For example "--no-video" works, "--aspect-ratio=4:3" doesnt work.

My main goal is show (or hide) video title.
Any of these commands are not working for me.
"--no-video-title", "--video-title-show", "--video-title-timeout=4000", "--osd"

Here is my code which i put commands into it.

           public Form1()
        {
            InitializeComponent();
            var VlcLibDirectory = new DirectoryInfo(@"..\..\..\lib\x64\");
            vlcControl1.BeginInit();
            vlcControl1.VlcLibDirectory = VlcLibDirectory;
            vlcControl1.VlcMediaplayerOptions = new string[] { "--video-title-show" };
            vlcControl1.EndInit();
        }

And play part is looks like this:

public void PlayMedia(string dosya, float rate)
        {
            this.vlcControl1.SetMedia(new Uri(dosya), vlcControl1.VlcMediaplayerOptions);
            vlcControl1.Rate = rate;
            this.vlcControl1.Play();
            timer1.Start();
        }

even i tried ":" instead of "--" in commands, its still same.

- [ X ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
I thought you managed to find a solution yesterday.
I don't know what's wrong with your code, because when some option works and some other don't, it's more likely an issue with vlc itself.
Anyway:

- Don't pass VlcMediaPlayerOptions in SetMedia. That's two different things.
- Which version of libvlc are you using? it's really important to know since the results can be affected by the version.

**Comment by Boheminsan** [comment]
Yes you helped me to find where i should write commands. And now, some commands like "--no-video" works well properly. others doesnt work which i declared in question. 

"Don't pass VlcMediaPlayerOptions in SetMedia. That's two different things."
You mean like that? 

this.vlcControl1.SetMedia(new Uri(dosya));
"I don't know what's wrong with your code, because when some option works and some other don't, it's more likely an issue with vlc itself."
I started to think like that also. 
Thanks for all your efforts anyway.

**Comment by Boheminsan** [comment]
If you want to take a look to my code, I added to my github.
https://github.com/Boheminsan/VLCApp

**Comment by morl0048** [comment]
I personally went on the events' section of my vclControl and double click on the `VlcLibDirectoryNeeded` event and added ::

```
/// <summary>
/// Looks for the vlc directory on the opening of the app.
/// Opens a dialog if the libvlc folder is not found for the user to pick the good one.
/// Folder for 32bits should be "libvlc\win-x86\" and "libvlc\win-x64\" for 64 bits.
/// </summary>
/// <param name="sender"></param>
/// <param name="e"></param>
private void vlcRecorder_VlcLibDirectoryNeeded(object sender, VlcLibDirectoryNeededEventArgs e)
{
    var currentAssembly = Assembly.GetEntryAssembly();
    var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;

    if (currentDirectory == null)
        return;
    if (IntPtr.Size == 4)
        e.VlcLibDirectory = new DirectoryInfo(Path.GetFullPath(@".\libvlc\win-x86\"));
    else
        e.VlcLibDirectory = new DirectoryInfo(Path.GetFullPath(@".\libvlc\win-x64\"));

    if (!e.VlcLibDirectory.Exists)
    {
        var folderBrowserDialog = new System.Windows.Forms.FolderBrowserDialog();
        folderBrowserDialog.Description = "Select Vlc libraries folder.";
        folderBrowserDialog.RootFolder = Environment.SpecialFolder.Desktop;
        folderBrowserDialog.ShowNewFolderButton = true;
        if (folderBrowserDialog.ShowDialog() == DialogResult.OK)
        {
            e.VlcLibDirectory = new DirectoryInfo(folderBrowserDialog.SelectedPath);
        }
    }
}
```

If a dialog shows up to let you select a directory, your reference to the vlc dir isn't good.

**Comment by jeremyVignelles** [comment]
After testing : `--aspect-ratio` doesn't work in libvlc. Use `this.vlcControl1.Video.AspectRatio = "4:3";` instead.

`--video-title` does not seem to work either. You can mimick that behavior using the `marq` plugin, for example with :
`--sub-source=marq{marquee=Hello,timeout=500,position=4}`
See documentation here : https://wiki.videolan.org/Documentation:Modules/marq/

Some remarks with your project:
- exclude the `packages` folder in your .gitignore, as described here https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
- You don't need to reference AXVLC
- You can use the VideoLAN.LibVLC.Windows NuGet package (still in preview) to install libvlc.
- Don't use beginInit/endInit and all the code in-between if you put your control in the designer. You can't initialize your control twice. Either put the parameters in the designer, or create the control in the constructor  `new VlcControl(...)`.

**Comment by Boheminsan** [comment]
I will try all. Thanks for your patient and help. 👍
