### ISSUE TITLE
how to run a normal vlc command line with Vlc.DotNet?

### ISSUE THREAD

**Issue by csurn** [ZeBobo5/Vlc.DotNet#455]
I have an a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** :2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86/x64 
- **.net version** : .net framework 4.0
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64

# Summary

I want to run the command: "vlc file1.ps file2.ps file3.ps --sout "#gather:std{access=file,mux=ts,dst=all.ts}" --sout-keep" with Vlc.DotNet.How should I do?

**Comment by jeremyVignelles** [comment]
I'm not sure it is possible. I can see some things you can try:
- specify your options in VlcMediaPlayerOptions (without the input files), and then play the files one by one (Play, OnEndReached, Play) but be careful of the deadlocks (see wiki)
- Can MPEG-PS files be embedded in m3u8 like mpeg-ts does? if so, you can create a playlist and play it
- Call the vlc.exe without vlc.DotNet, using the Process command

**Comment by csurn** [comment]
Thanks!
