### ISSUE TITLE
Win32 exception in Vlc.DotNet.Core.Interops.dll

### ISSUE THREAD

**Issue by metalglove** [ZeBobo5/Vlc.DotNet#456]
I have an issue about Vlc.DotNet.

**Summary**:
**What**:
http://prntscr.com/ke9xdf
**Error in text:**
Exception thrown: 'System.ComponentModel.Win32Exception' in Vlc.DotNet.Core.Interops.dll
An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in Vlc.DotNet.Core.Interops.dll
%1 is not a valid Win32 application

**When**:
The moment this line is called the application breaks.
vlcControl.MediaPlayer.EndInit();

**How**:
To reproduce the error, i will upload the full code to my github.
https://github.com/metalglove/AnimeSync

using the example code from this:
https://github.com/ZeBobo5/Vlc.DotNet/blob/master/src/Samples/Vlc.DotNet.Wpf.Samples/MainWindow.xaml.cs

# Generic information

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : http://download.videolan.org/pub/videolan/vlc/last/win64/
- **.net version** : v4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10

**Comment by jeremyVignelles** [comment]
In the Project properties, in the Build tab, is the "prefer 32 bits" box checked?
Does it work with a x86 libvlc?

By the way, don't commit libvlc in a folder, it's really huge. I'd recommend that you get it as described here : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#with-nuget-

**Comment by metalglove** [comment]
The prefer 32 bits box is checked.
Upon trying 32 i get a other error.
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

And yeah i should of made a ignore file for that.

**Comment by metalglove** [comment]
Alright, i have got it working.
But how do i know what the required plugins are for this to work?

**Comment by jeremyVignelles** [comment]
It depends of what you are trying to do with your application. For example, if you are just playing files, you don't have to redistribute the plugins that reads media from http, rtsp and other protocols.

**Comment by metalglove** [comment]
What would i need if i were to only do it from http?

**Comment by jeremyVignelles** [comment]
I wouldn't touch the codec folder too much, but you can probably remove most of the access plugins except http, also keep directx for hardware acceleration.
For other folders, try to delete plugins and see if it's broken. it's the easiest way to know for sure

**Comment by metalglove** [comment]
Okay, thanks for your help!
i hereby close this issue as it is resolved.

**Comment by TooLoose** [comment]
"Alright, i have got it working." Wonderful. How?

**Comment by jeremyVignelles** [comment]
Probably by following the wiki /samples and not trying to load a x86/x64 version in the other type of process.
