### ISSUE TITLE
Vlc.DotNet.WPF Property

### ISSUE THREAD

**Issue by ermanuruk** [ZeBobo5/Vlc.DotNet#457]
I have a question  about Vlc.DotNet.
 
- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 + From FTP Server
- **.net version** : 4.7.1
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 8.1 x64)

I can't get `this.MyControl._SourceProvider_ `property when i code behind.
I get Mycontrol.Mediplayer but it doesn't have method `CreatePlayer`. I dig down and found 
`MyControl.Mediaplyer.VlcMediaPlayer.Manager.CreatePlayer()` option but it turned Object reference null exception. What i do wrong ? Please support.

**Comment by jeremyVignelles** [comment]
The documentation that you are reading is for 3.0.0, please use the prerelease version from nuget if you want to try it.
