### ISSUE TITLE
WPF Control throws SEHException/AccessViolationException on Sample App Close after Play

### ISSUE THREAD

**Issue by joncloud** [ZeBobo5/Vlc.DotNet#46]
Thrown from [VlcManager](https://github.com/ZeBobo5/Vlc.DotNet/blob/master/src/Vlc.DotNet.Core.Interops/VlcManager.ReleaseMediaPlayer.cs#L14) on the .Invoke call.

External component has thrown an exception.

Visual Studio also reports an AccessViolationException:
An unhandled exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by DominikPalo** [comment]
#22

**Comment by DominikPalo** [comment]
See #22

**Comment by jeremyVignelles** [comment]
Old issue, please reopen if still experiencing this issue

**Comment by B0R1K** [comment]
i have same issue, on first run... please advise

**Comment by jeremyVignelles** [comment]
please update libvlc dll to latest version and try again. Are you also using the sample project? which language, which .net?

**Comment by B0R1K** [comment]
i use libvlc from 2.2.6, using code from https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started, Vlc.DotNet.Wpf, C#

Sample Project works, also in your libs folders are alot more files then just 2 Dll.

if i copy your lib folders into my folders project works, if i update your 2 dlls with new version it crushes... 

Hope it helps

**Comment by jeremyVignelles** [comment]
your libvlc dlls should have the same version as the plugins. you should update the plugins folder with the dll or nothing.
Could you confirm that there is something wrong after removing the plugins folder and copying the new folder?

**Comment by B0R1K** [comment]
After coping all the DLL and PlugIn Folder Everything is working... Thank you.
