### ISSUE TITLE
Possibly found a bug involving multiple players

### ISSUE THREAD

**Issue by doctorbunhead** [ZeBobo5/Vlc.DotNet#460]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (Please fill) 2.2.1
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (Please fill) (x86/x64) + how did you get it? x86 v3.0.3 from videolan installed on system
- **.net version** : (Please fill) 4.7
- **Project language** : (C#/VB.net) c#
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits)) x86
- **Operating system** : (Windows ...) (x86/x64) x64

# Summary
I've found that running 2 players simultaneously under programmatic control, the volumes can get tied together.

I am initialising 2 music players with this code

`string regPath = (string)Microsoft.Win32.Registry.GetValue("HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\VideoLAN\\VLC", "InstallDir", null);

            vlcMusic1 = new VlcControl();
            vlcMusic1.VlcLibDirectoryNeeded += VlcMusic1_VlcLibDirectoryNeeded;
            vlcMusic1.BeginInit();
            vlcMusic1.VlcLibDirectory = new DirectoryInfo(regPath);
            vlcMusic1.EndInit();
            vlcMusic1.VlcMediaplayerOptions = new string[] { "--no-keyboard-events", "--no-mouse-events" };`

There's an identical player called vlcMusic2

I'm playing these 2 players alongside a windows media player for video and based on the position of the video, one player will fade out while the other player fades in using System.Windows.Forms.Timer's which will increase or decrease the volume of each player by 1 on each tick until they reach a maximum or minimum value.

All is OK until I seek through the video. At this point, all players are stopped, times adjusted and players started where they are supposed to start. 

After seeking, when one player tries to fade out it will fade both simultaneously. Also the fade in will do the same so they sometimes battle against each other with fade out usually winning.

I've gone through the code many times and there are no cross references occuring. I have tried replacing VLC with mplayer and it all works OK but mplayer has some limitations I can't live with (often get mpg123 failed to open stream...).

Here's the fade in timer code

`
private void TmrFadeIn1_Tick(object sender, EventArgs e)

        {

            Debug.WriteLine("tmrFadeIn1 Called - intFadeinAmount1=" + intFadeInAmount1.ToString());
            if (vlcMusic1.Audio.Volume < maxVolume)

            {

                    vlcMusic1.Audio.Volume += 1;

            }

            else

            {

                tmrFadeIn1.Enabled = false;

            }

            Debug.WriteLine("vlcMusic1.Audio.Volume=" + vlcMusic1.Audio.Volume.ToString());

        }
`
Here's an dump of the debug output where you can see tmrFadeOut1 getting called but both volumes are dropping. The volumes are vlcMusic1.Audio.Volume and vlcMusic2.Audio.Volume. As you can see only one timer is enabled but both volumes are falling. Very strange and I've exhausted all tests I can think of.  I have however found a workaround detailed under this debug dump. (Sorry if the debug below appears as one big block. It does in preview)

`
tmrMusCheck - state of Variables  blFading1=True  blFading2=False  Player1Track=3  Player2Track=3  vlcMusic1Playing=True  vlcMusic2Playing=True  finalTrack=False  finalTrackHit=False
tmrFadeIn1.Enabled=False  tmrFadeIn2.Enabled=False  tmrFadeOut1.Enabled=True  tmrFadeOut2.Enabled=False  **vlcMusic1.Audio.Volume=36  vlcMusic2.Audio.Volume=36**
vlcMusic1 position=00:03:02.3140000  vlcMusic2 position=00:01:50.7650000  vlcMusic1 State=Playing  vlcMusic2 State=Playing  gpsIndex=61
gpsStartTime =00:17:38  tmrGpsTick.period303  player1TrackStart =00:14:36  player1TrackEnd =00:17:37  player2TrackStart =00:17:37  player2TrackEnd =00:21:36
maxVolume =100
Current Media -- vlcMusic1=Sasha-Scorchio  -  vlcMusic2=Underworld-Born Slippy
tmrMusCheck Ticked @ 00:17:38.0980000
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=36
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=35
CurrentPosition= 00:17:38.1450000
Time Remaining = 00:42:16.8550000
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=34
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=33
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=32
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=31
tmrMusCheck - state of Variables  blFading1=True  blFading2=False  Player1Track=3  Player2Track=3  vlcMusic1Playing=True  vlcMusic2Playing=True  finalTrack=False  finalTrackHit=False
tmrFadeIn1.Enabled=False  tmrFadeIn2.Enabled=False  tmrFadeOut1.Enabled=True  tmrFadeOut2.Enabled=False  **vlcMusic1.Audio.Volume=30  vlcMusic2.Audio.Volume=30**
vlcMusic1 position=00:03:02.5880000  vlcMusic2 position=00:01:51.0210000  vlcMusic1 State=Playing  vlcMusic2 State=Playing  gpsIndex=62
gpsStartTime =00:21:26  tmrGpsTick.period303  player1TrackStart =00:14:36  player1TrackEnd =00:17:37  player2TrackStart =00:17:37  player2TrackEnd =00:21:36
maxVolume =100
Current Media -- vlcMusic1=Sasha-Scorchio  -  vlcMusic2=Underworld-Born Slippy
tmrMusCheck Ticked @ 00:17:38.1970000
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=30
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=29
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=28
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=27
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=26
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=25
tmrMusCheck - state of Variables  blFading1=True  blFading2=False  Player1Track=3  Player2Track=3  vlcMusic1Playing=True  vlcMusic2Playing=True  finalTrack=False  finalTrackHit=False
tmrFadeIn1.Enabled=False  tmrFadeIn2.Enabled=False  tmrFadeOut1.Enabled=True  tmrFadeOut2.Enabled=False  **vlcMusic1.Audio.Volume=24  vlcMusic2.Audio.Volume=24**
vlcMusic1 position=00:03:02.5880000  vlcMusic2 position=00:01:51.0210000  vlcMusic1 State=Playing  vlcMusic2 State=Playing  gpsIndex=62
gpsStartTime =00:21:26  tmrGpsTick.period303  player1TrackStart =00:14:36  player1TrackEnd =00:17:37  player2TrackStart =00:17:37  player2TrackEnd =00:21:36
maxVolume =100
Current Media -- vlcMusic1=Sasha-Scorchio  -  vlcMusic2=Underworld-Born Slippy
tmrMusCheck Ticked @ 00:17:38.2970000
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=24
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=23
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=22
CurrentPosition= 00:17:38.3420000
Time Remaining = 00:42:16.6580000
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=21
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=20
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=19
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=18
tmrMusCheck - state of Variables  blFading1=True  blFading2=False  Player1Track=3  Player2Track=3  vlcMusic1Playing=True  vlcMusic2Playing=True  finalTrack=False  finalTrackHit=False
tmrFadeIn1.Enabled=False  tmrFadeIn2.Enabled=False  tmrFadeOut1.Enabled=True  tmrFadeOut2.Enabled=False  **vlcMusic1.Audio.Volume=17  vlcMusic2.Audio.Volume=17**
vlcMusic1 position=00:03:02.5880000  vlcMusic2 position=00:01:51.0210000  vlcMusic1 State=Playing  vlcMusic2 State=Playing  gpsIndex=62
gpsStartTime =00:21:26  tmrGpsTick.period303  player1TrackStart =00:14:36  player1TrackEnd =00:17:37  player2TrackStart =00:17:37  player2TrackEnd =00:21:36
maxVolume =100
Current Media -- vlcMusic1=Sasha-Scorchio  -  vlcMusic2=Underworld-Born Slippy
tmrMusCheck Ticked @ 00:17:38.3960000
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=17
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=16
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=15
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=14
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=13
tmrFadeOut1 Called - intFadeOutAmount1=10
vlcMusic1.Audio.Volume=12
`
As a workaround I have found that re-initialising each player before it plays a new track, the problem goes away. I do this by using
 `
                vlcMusic1.VlcLibDirectoryNeeded -= VlcMusic1_VlcLibDirectoryNeeded;

                vlcMusic1 = new VlcControl();

                vlcMusic1.VlcLibDirectoryNeeded += VlcMusic1_VlcLibDirectoryNeeded;

                vlcMusic1.BeginInit();

                vlcMusic1.VlcLibDirectory = new DirectoryInfo(regPath);

                vlcMusic1.EndInit();

                vlcMusic1.VlcMediaplayerOptions = new string[] { "--no-keyboard-events", "--no-mouse-events" };
`

Then everything works perfectly. I have no idea if this behaviour is due to LibVlc or Vlc Dotnet as my programming knowledge doesn't extend to me investigating further.

If I'm doing something horribly wrong, please tell me ( be nice ;) ).

cheers.
- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Can you try with 3.0.0-develop311 ?

**Comment by jeremyVignelles** [comment]
Closing this since 3.0.0 has been around for a while and no answer for a long time. Feel free to reopen if something else is needed
