### ISSUE TITLE
Transperent UI does not show vlc control 

### ISSUE THREAD

**Issue by xXxTheDarkprogramerxXx** [ZeBobo5/Vlc.DotNet#461]
I have an issue with Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** :  V2.2.1
- **Vlc.DotNet project used** : WPF Windows Form Hosted / Custom Control
- **libvlc version** :V3.0.0 (x86/x64)(both) + (Official video Lan FTP)
- **.net version** : .net 4.5.2 
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 Pro x86

# Summary

If I enable a WPF UI with Allow Transparency = True (in Window AllowsTransparency="True")
the VLC Control in either a WindowsFormHost Contorl or a custom control disappears 

I Have Attached 2 screenshots 
image 1 : Without Transparency 
![image](https://user-images.githubusercontent.com/12253240/45140349-c871db00-b1b2-11e8-910f-758b9a5f4fbc.png)

Image 2: with Transparency
![image](https://user-images.githubusercontent.com/12253240/45140429-0a9b1c80-b1b3-11e8-817e-dbff38c37cc7.png)

As you can see here the VLC Control Disappears

Currently you can view code on my Github 
here : https://github.com/xXxTheDarkprogramerxXx/PS3Tools/tree/master/PS4%20PSP%20Classics%20GUI 

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
This is not a bug of Vlc.DotNet but a limitation of the WinFormsHost  : https://stackoverflow.com/questions/4108531/wpf-windowsformshost-is-not-visible-when-allowstransparency-true

**Comment by xXxTheDarkprogramerxXx** [comment]
@jeremyVignelles  just want to say thanks for that link your a legend
