### ISSUE TITLE
reducible delay when moving cursor on vlc

### ISSUE THREAD

**Issue by morl0048** [ZeBobo5/Vlc.DotNet#462]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 using this link's instruction -> https://github.com/ZeBobo5/Vlc.DotNet/wiki/Using-Vlc.DotNet-in-WinForms (nuget package manager)
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : (Windows 10x86/x64)

# Summary
When I start reading a rtmp/rtsp stream with vlc, I start viewing the video with a delay of 20 seconds.

But I can reduce this delay by scrolling the bottom time cursor to the right most a couple of times...

The delay reduce to a point where it only has a 2-3 seconds delay...

I assumed it was a caching problem, I tried adding the following options on the vlc app and it changed nothing : " :network-caching=100 :live-caching=100" .

So my question is... Is there any way to "move the time cursor" with Vlc.DotNet's VlcController?

Let me know if I'm not clear... I know it's a strange question! haha

**Comment by jeremyVignelles** [comment]
Yes, there is. you can set the time, but your workaround should not be needed.
Your issue is indeed weird, but you didn't help either : Does that happen in vlc 3.0.0 itself? what's are you connecting to ? an IP camera? which brand? any log?

**Comment by morl0048** [comment]
I'm sorry I wasn't clear...

My C# app is in vlc 2.2.1 but the test I made were with the lastest version of vlc 3.0.4 .

I'm connecting to a nginx server that takes an rtsp stream comming from a Foscam IP camera and broadcasts it as a rtmp stream (the conversion is made with ffmpeg).

To be clear : IPCamera->RTSP->ffmpeg->nginx->RTMP->vlc

Here's the log I get from when I initialize the connection to the rtmp stream : 

main debug: processing request item: rtmp://192.168.10.170:1935/live, node: Playlist, skip: 0
main debug: rebuilding array of current - root Playlist
main debug: rebuild done - 1 items, index 0
main debug: starting playback of new item
main debug: resyncing on rtmp://192.168.10.170:1935/live
main debug: rtmp://192.168.10.170:1935/live is at 0
main debug: creating new input thread
main debug: Creating an input for 'rtmp://192.168.10.170:1935/live'
main debug: requesting art for new input thread
main debug: using timeshift granularity of 50 MiB
main debug: using timeshift path: C:\Users\MORNEA~1\AppData\Local\Temp
main debug: `rtmp://192.168.10.170:1935/live' gives access `rtmp' demux `any' path `192.168.10.170:1935/live'
main debug: looking for meta fetcher module matching "any": 1 candidates
main debug: creating demux: access='rtmp' demux='any' location='192.168.10.170:1935/live' file='\\192.168.10.170:1935\live'
main debug: looking for access_demux module matching "rtmp": 15 candidates
main debug: no access_demux modules matched
main debug: creating access: rtmp://192.168.10.170:1935/live
main debug: (path: \\192.168.10.170:1935\live)
main debug: looking for access module matching "rtmp": 26 candidates
lua debug: Trying Lua scripts in C:\Users\morneaulo\AppData\Roaming\vlc\lua\meta\fetcher
lua debug: Trying Lua scripts in I:\Utilities\VLC\lua\meta\fetcher
main debug: no meta fetcher modules matched
main debug: looking for art finder module matching "any": 2 candidates
qt debug: IM: Setting an input
avcodec debug: CPU flags: 0x000fd3db
lua debug: Trying Lua scripts in C:\Users\morneaulo\AppData\Roaming\vlc\lua\meta\art
lua debug: Trying Lua scripts in I:\Utilities\VLC\lua\meta\art
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: skipping script (unmatched scope) I:\Utilities\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\01_googleimage.luac
lua debug: skipping script (unmatched scope) I:\Utilities\VLC\lua\meta\art\01_googleimage.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\02_frenchtv.luac
lua debug: skipping script (unmatched scope) I:\Utilities\VLC\lua\meta\art\02_frenchtv.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\03_lastfm.luac
lua debug: skipping script (unmatched scope) I:\Utilities\VLC\lua\meta\art\03_lastfm.luac
main debug: no art finder modules matched
main debug: looking for meta fetcher module matching "any": 1 candidates
lua debug: Trying Lua scripts in C:\Users\morneaulo\AppData\Roaming\vlc\lua\meta\fetcher
lua debug: Trying Lua scripts in I:\Utilities\VLC\lua\meta\fetcher
main debug: no meta fetcher modules matched
main debug: looking for art finder module matching "any": 2 candidates
lua debug: Trying Lua scripts in C:\Users\morneaulo\AppData\Roaming\vlc\lua\meta\art
lua debug: Trying Lua scripts in I:\Utilities\VLC\lua\meta\art
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\01_googleimage.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\02_frenchtv.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\art\03_lastfm.luac
main debug: no art finder modules matched
avcodec debug: seekable, size=-40
main debug: using access module "avcodec"
main debug: looking for stream_filter module matching "prefetch,cache_read": 24 candidates
cache_read debug: Using stream method for AStream*
cache_read debug: starting pre-buffering
cache_read debug: received first data after 40 ms
cache_read debug: pre-buffering done 1024 bytes in 0s - 24 KiB/s
main debug: using stream_filter module "cache_read"
main debug: looking for stream_filter module matching "any": 24 candidates
lua debug: Trying Lua scripts in C:\Users\morneaulo\AppData\Roaming\vlc\lua\playlist
lua debug: Trying Lua scripts in I:\Utilities\VLC\lua\playlist
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\anevia_streams.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\anevia_xml.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\appletrailers.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\bbc_co_uk.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\cue.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\dailymotion.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\jamendo.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\koreus.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\liveleak.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\newgrounds.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\rockbox_fm_presets.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\soundcloud.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\twitch.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\vimeo.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\vocaroo.luac
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\playlist\youtube.luac
main debug: no stream_filter modules matched
main debug: looking for stream_directory module matching "any": 1 candidates
main debug: no stream_directory modules matched
main debug: attachment of directory-extractor failed for rtmp://192.168.10.170:1935/live
main debug: looking for stream_filter module matching "record": 24 candidates
main debug: using stream_filter module "record"
main debug: creating demux: access='rtmp' demux='any' location='192.168.10.170:1935/live' file='\\192.168.10.170:1935\live'
main debug: looking for demux module matching "any": 55 candidates
main debug: looking for xml reader module matching "any": 1 candidates
main debug: using xml reader module "xml"
ts debug: TS module discarded (lost sync)
mod debug: MOD validation failed (ext=170:1935\live)
webvtt debug: subtitle demux discarded
avcodec debug: trying url: \\192.168.10.170:1935\live
avcodec debug: CPU flags: 0x000fd3db
avcodec debug: detected format: flv
main debug: selecting program id=0
avcodec debug: adding es: video codec = FLV1 (21)
avcodec debug: AVFormat(ffmpeg Lavf58.3.100) supported stream
avcodec debug: - format = flv (FLV (Flash Video))
avcodec debug: - start time = 10248762000
avcodec debug: - duration = 0
main debug: using demux module "avcodec"
main debug: looking for video decoder module matching "any": 17 candidates
avcodec debug: using ffmpeg Lavc58.6.103
avcodec debug: CPU flags: 0x000fd3db
avcodec debug: allowing 6 thread(s) for decoding
avcodec debug: available software decoder output format 0 (yuv420p)
avcodec debug: codec (flv) started
main debug: using video decoder module "avcodec"
main debug: looking for meta reader module matching "any": 2 candidates
lua debug: Trying Lua scripts in C:\Users\morneaulo\AppData\Roaming\vlc\lua\meta\reader
lua debug: Trying Lua scripts in I:\Utilities\VLC\lua\meta\reader
lua debug: Trying Lua playlist script I:\Utilities\VLC\lua\meta\reader\filename.luac
main debug: no meta reader modules matched
main debug: `rtmp://192.168.10.170:1935/live' successfully opened
main debug: Buffering 0%
main debug: Buffering 4%
main debug: Buffering 8%
main debug: Buffering 12%
main debug: Buffering 14%
main debug: Buffering 20%
main debug: Buffering 24%
main debug: Buffering 28%
main debug: Buffering 34%
main debug: Buffering 38%
main debug: Buffering 40%
main debug: Buffering 48%
main debug: looking for text renderer module matching "any": 3 candidates
main debug: Buffering 50%
main debug: Buffering 54%
main debug: Buffering 60%
main debug: Buffering 64%
main debug: Buffering 68%
main debug: Buffering 72%
main debug: Buffering 78%
main debug: Buffering 80%
main debug: Buffering 84%
main debug: Buffering 90%
main debug: Buffering 94%
main debug: Buffering 98%
main debug: Stream buffering done (1040 ms in 1 ms)
freetype debug: Using DWrite backend
freetype debug: DWrite_GetFamily(): family name: Arial
freetype debug: DWrite_ParseFamily(): using font at index 0 with weight 400 for bold: 0, italic: 0
freetype debug: DWrite_ParseFamily(): using font at index 1 with weight 700 for bold: 1, italic: 0
freetype debug: DWrite_ParseFamily(): using font at index 2 with weight 400 for bold: 0, italic: 1
freetype debug: DWrite_ParseFamily(): using font at index 3 with weight 700 for bold: 1, italic: 1
main debug: using text renderer module "freetype"
main debug: looking for video converter module matching "any": 24 candidates
swscale debug: 32x32 (32x32) chroma: YUVA -> 16x16 (16x16) chroma: RGBA with scaling using Bicubic (good quality)
main debug: using video converter module "swscale"
main debug: looking for video converter module matching "any": 24 candidates
yuvp debug: YUVP to YUVA converter
main debug: using video converter module "yuvp"
main debug: Deinterlacing available
main debug: deinterlace -1, mode auto, is_needed 0
main debug: looking for vout window module matching "qt,any": 3 candidates
qt debug: requesting video window...
main debug: resized to 527x449
main debug: resized to 1280x720
main debug: using vout window module "qt"
main debug: looking for inhibit module matching "any": 1 candidates
main debug: using inhibit module "inhibit"
main debug: Opening vout display wrapper
main debug: looking for vout display module matching "any": 12 candidates
direct3d11 debug: creating Vout EventThread
direct3d11 debug: Win32VoutCreateWindow
main debug: VoutDisplayEvent 'resize' 1280x720
qt debug: Logical video size: 1280x720
main debug: resized to 1280x720
main debug: VoutDisplayEvent 'resize' 1280x720
direct3d11 debug: inclinometer not found. (hr=0x80070490)
direct3d11 debug: created video sub-window
direct3d11 debug: Vout EventThread running
direct3d11 debug: Created the D3D11 device type 1 level b100.
direct3d11 debug: ATI WDDM driver 22.19.172.769
direct3d11 debug: supports colorspace RGB Rec.709 gamma:22 range:FULL
direct3d11 debug: supports colorspace RGB Rec.709 gamma:22 range:STUDIO
direct3d11 debug: supports colorspace RGB Rec.2020 gamma:22 range:STUDIO
direct3d11 debug: supports colorspace RGB Rec.2020 gamma:22 range:FULL
direct3d11 debug: supports colorspace RGB Rec.2020 gamma:2084 range:FULL
direct3d11 debug: supports colorspace RGB Rec.2020 gamma:2084 range:STUDIO
direct3d11 debug: Output max luminance: 270.0, colorspace RGB Rec.709 gamma:22 range:FULL, bits per pixel 8
direct3d11 debug: using colorspace RGB Rec.709 gamma:22 range:FULL
direct3d11 debug: Using pixel format I420 for chroma I420
main debug: VoutDisplayEvent 'resize' 1296x759
direct3d11 debug: Direct3D11 resources created
direct3d11 debug: Direct3D11 device adapter successfully initialized
direct3d11 debug: Direct3D11 Open Succeeded
main debug: using vout display module "direct3d11"
direct3d11 debug: D3D11 pool succeed with 24 surfaces (1280x736) context 0x00b78d70
main debug: original format sz 1280x736, of (0,0), vsz 1280x720, 4cc I420, sar 1:1, msk r0x0 g0x0 b0x0
main debug: removing module "freetype"
main debug: VoutDisplayEvent 'resize' 1280x720
main debug: looking for text renderer module matching "any": 3 candidates
direct3d11 debug: Detected size change 1280x720
freetype debug: Using DWrite backend
freetype debug: DWrite_GetFamily(): family name: Arial
freetype debug: DWrite_ParseFamily(): using font at index 0 with weight 400 for bold: 0, italic: 0
freetype debug: DWrite_ParseFamily(): using font at index 1 with weight 700 for bold: 1, italic: 0
freetype debug: DWrite_ParseFamily(): using font at index 2 with weight 400 for bold: 0, italic: 1
freetype debug: DWrite_ParseFamily(): using font at index 3 with weight 700 for bold: 1, italic: 1
main debug: using text renderer module "freetype"
avcodec warning: plane 0 not aligned: disabling direct rendering
main debug: Received first picture
qt debug: Logical video size: 1280x720
main debug: Decoder wait done in 349 ms
main debug: resized to 1280x720
main debug: VoutDisplayEvent 'resize' 1280x720
main debug: auto hiding mouse cursor
main warning: picture is too late to be displayed (missing 70 ms)
main warning: picture is too late to be displayed (missing 52 ms)
main warning: picture is too late to be displayed (missing 11 ms)
main debug: auto hiding mouse cursor
main warning: picture is too late to be displayed (missing 68 ms)
main warning: picture is too late to be displayed (missing 47 ms)
main warning: picture is too late to be displayed (missing 17 ms)
main warning: picture is too late to be displayed (missing 17 ms)
main warning: picture is too late to be displayed (missing 78 ms)
main warning: picture is too late to be displayed (missing 39 ms)
main warning: picture is too late to be displayed (missing 19 ms)
main warning: picture is too late to be displayed (missing 83 ms)
main warning: picture is too late to be displayed (missing 49 ms)
main warning: picture is too late to be displayed (missing 85 ms)
main warning: picture is too late to be displayed (missing 61 ms)
main warning: picture is too late to be displayed (missing 6 ms)
main debug: auto hiding mouse cursor
main warning: picture is too late to be displayed (missing 85 ms)
main warning: picture is too late to be displayed (missing 28 ms)
main warning: picture is too late to be displayed (missing 8 ms)
main debug: VoutDisplayEvent 'mouse button' 0 t=8
main debug: VoutDisplayEvent 'mouse button' 0 t=9
main warning: picture is too late to be displayed (missing 10 ms)
main warning: picture is too late to be displayed (missing 10 ms)
main debug: auto hiding mouse cursor
main debug: incoming request - stopping current input
main debug: killing decoder fourcc `FLV1'
main debug: removing module "avcodec"
main debug: saving a free vout
main debug: reusing provided vout
main debug: removing module "avcodec"
main debug: removing module "record"
main debug: removing module "cache_read"
main debug: removing module "avcodec"
main debug: Program doesn't contain anymore ES
main debug: dead input
main debug: nothing to play
main debug: destroying useless vout
main debug: removing module "direct3d11"
qt debug: IM: Deleting the input
direct3d11 debug: Direct3D11 resources destroyed
direct3d11 debug: Direct3D11 device adapter closed
direct3d11 error: SetThumbNailClip failed: 0x800706f4
direct3d11 debug: Win32 Vout EventThread terminating
direct3d11 debug: Win32VoutCloseWindow
direct3d11 debug: WinProc WM_DESTROY
main debug: removing module "inhibit"
qt debug: releasing video...
qt debug: Video is not needed anymore
main debug: removing module "freetype"
main debug: removing module "yuvp"
main debug: removing module "swscale"


I also see that there's a big delay (the logs stop growing/writing for a good 10 seconds) when It reaches the 
avcodec debug: trying url: \\192.168.10.170:1935\live
avcodec debug: CPU flags: 0x000fd3db
avcodec debug: detected format: flv

part.

**Comment by morl0048** [comment]
Ill just post the logs in 2 files one full until the stream plays and another when the delay in logs happens.
[vlcFullLogs.log](https://github.com/ZeBobo5/Vlc.DotNet/files/2358581/vlcFullLogs.log)
[beforeDelayLogs.log](https://github.com/ZeBobo5/Vlc.DotNet/files/2358582/beforeDelayLogs.log)

**Comment by morl0048** [comment]
I was refering to the 3.0.4 version of VLC itself
and there's no code comming from me...

**Comment by morl0048** [comment]
It's hard to explain, I'll try to come up with a better explanation tomorrow! Haha

**Comment by jeremyVignelles** [comment]
If I understand correctly, you are experiencing a deadlock while playing a rtmp stream in vlc and in your app.
If that's the case, it's likely a bug in vlc or in your ffmpeg transmitter.
can ffmpeg play the rtmp stream correctly?

**Comment by jeremyVignelles** [comment]
Probably related : https://trac.videolan.org/vlc/ticket/15597

**Comment by morl0048** [comment]
Even ffmpeg can't play the stream without delay at first... It's so strange... Thanks for your help!
