### ISSUE TITLE
Very slow loading video

### ISSUE THREAD

**Issue by adilsonbatistajr** [ZeBobo5/Vlc.DotNet#463]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** :  2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64 + oficial FTP Site 3.0.0
- **.net version** : 4.6
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64

# Summary

I made a small example to run a video, it works, but it takes too long to load the video, about 30 seconds. The official GitHub example also behaves the same way. What could be happening?

vlcControl1.Play(new FileInfo(@"C:\Users\adils\Videos\sample4.avi"));

**Comment by jeremyVignelles** [comment]
Does that happen at each run or only the first time? Any antivirus software in place?

**Comment by adilsonbatistajr** [comment]
Hi Jeremy! No, it always happens, the first and any other that runs. I only have Windows Defender on the machine ...

**Comment by adilsonbatistajr** [comment]
I downgrade to vlc-2.2.1 its work fine!

**Comment by jeremyVignelles** [comment]
and with vlc 3.0.4?

**Comment by jeremyVignelles** [comment]
Did you try with the actual VLC?

**Comment by adilsonbatistajr** [comment]
I tried with vlc 3.0.4, same problem, it took about 15 seconds to start the video. I seem to be a bug in versions higher than vlc 2.2.1

**Comment by jeremyVignelles** [comment]
If this is a bug in vlc, you should file a bug in vlc's bug tracker.

**Comment by adilsonbatistajr** [comment]
I will do! Thanks Jeremy!
