### ISSUE TITLE
'VlcControl' does not contain a definition for 'SourceProvider' 

### ISSUE THREAD

**Issue by ISmileYouCryYouSmileIDie** [ZeBobo5/Vlc.DotNet#467]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 / official / nuget
- **.net version** : 4.5 , 4.6 , 4.7
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 x64

# Summary

How this library works ?! I did everything in manual and I did everything right but I get this error : 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1061	'VlcControl' does not contain a definition for 'SourceProvider' and no accessible extension method 'SourceProvider' accepting a first argument of type 'VlcControl' could be found (are you missing a using directive or an assembly reference?)	VLCPlay	C:\Users\Tak\Documents\Visual Studio 2017\Projects\VisualStudies\VLCPlay\MainWindow.xaml.cs	36	Active

I can't even build your project , same error !

- There is no SourceProvider
- There is no CreatePlayer!

**I changed CreatePlayer to :**
`    control.MediaPlayer.VlcLibDirectory = vlcLibDirectory;`
**and I changed  control.SourceProvider.MediaPlayer to :** 
```
control.MediaPlayer.Play(new Uri("file:///C:/test/movie.mp4"));
GetLength.Content = control.MediaPlayer.Length + " ms";

```
**that made errors gone but still player dosen't play anything , pure black !**

- [ * ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
The wiki and all the samples you see on the `develop` branch are for 3.0 which is currently in preview.
You will probably need the Vlc.DotNet.WinForms, even if you're doing Wpf
