### ISSUE TITLE
vlcControl.MediaPlayer.EndInit() - System.AccessViolationException

### ISSUE THREAD

**Issue by 4E71-NOP** [ZeBobo5/Vlc.DotNet#468]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 & x64 - intalled with VS nuget manager
- **.net version** :  .NET Framework 4.6.2
- **Project language** : C#
- **Project build architecture** : x86 & x64 & AnyCPU & prefer 32bits or not
- **Operating system** : Windows10 x64

# Summary

Using MyvlcPlayer.MediaPlayer.EndInit();
I systematically get :
Exception levée : **'System.AccessViolationException'** dans **Vlc.DotNet.Core.Interops.dll**
Une exception de type 'System.AccessViolationException' s'est produite dans Vlc.DotNet.Core.Interops.dll mais n'a pas été gérée dans le code utilisateur
Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée.

- [X] I confirm that my issue doesn't happen in VLC itself.

# What's happening ?
If i use the method EndInit() it crashes systematically. I tried different pieces of code available on the net. I got back to the ZeBobo5 example and refined it (https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#getting-libvlc)
If i don't use EndInit() everything behave properly except of course the VlcControl stays black.

THe VlcControl is located in a tab. This tab is in a separate XAML/cs file. I don't know if it is important or not. So far it never the source of problems. 

I tried with 3.0.0 and 3.0.4 VlcLib with the same behavior so far. 

I must be missing something small. Please what should i check in Visual Studio project and such in order to make it run 100% sure. 

The XAML looks fine:
``` xaml
<UserControl  x:Class="Labo_template.ihm.ongletVideoVLC"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf"
      mc:Ignorable="d" 
      d:DesignHeight="450" d:DesignWidth="800">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="80*"/>
            <RowDefinition Height="20*"/>
        </Grid.RowDefinitions>
        <vlc:VlcControl x:Name="vlcPlayer" Grid.Row="0" />
        <Button x:Name="Tab13ButtonA01" Content="Fichier" Grid.Row="1" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="10,10,0,0" MinWidth="128.2" Click="Tab13ButtonA01_Click"/>
        <Button x:Name="Tab13ButtonB01" Content="Lecture" Margin="10,35,0,0" VerticalAlignment="Top" Grid.Row="1" HorizontalAlignment="Left" MinWidth="128" Click="Tab13ButtonB01_Click"/>
        <Button x:Name="Tab13ButtonB02" Content="Stop" Margin="143,35,0,0" VerticalAlignment="Top" Grid.Row="1" MinWidth="128" HorizontalAlignment="Left" Click="Tab13ButtonB02_Click"/>
    </Grid>
</UserControl>
```

The class managing the tab in which the VLC plugin is looks fine too.
Nota Bene : "Msg.Publication" is a logging / statusbar logger.

``` C#
using Labo_template.agents;
using System;
using System.IO;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;

namespace Labo_template.ihm
{
    /// <summary>
    /// Logique d'interaction pour ongletVideoVLC.xaml
    /// </summary>
    public partial class ongletVideoVLC : UserControl
    {

        public ongletVideoVLC()
        {
            InitializeComponent();

            vlcPlayer.MediaPlayer.BeginInit();
            Msg.Publication("Initialisation de l'onglet 'Vidéo'...");

            vlcPlayer.MediaPlayer.VlcLibDirectoryNeeded += OnVlcControlNeedsLibDirectory;
            this.vlcPlayer.MediaPlayer.Log += (sender, args) => { System.Diagnostics.Debug.WriteLine(string.Format("libVlc : {0} {1} @ {2}", args.Level, args.Message, args.Module)); };
            vlcPlayer.MediaPlayer.EndInit();

        }

        private void OnVlcControlNeedsLibDirectory(object sender, Vlc.DotNet.Forms.VlcLibDirectoryNeededEventArgs e)
        {
            var assemblyCourant = Assembly.GetEntryAssembly();
            var repertoireCourantSolution = new FileInfo(assemblyCourant.Location).DirectoryName;
            if (repertoireCourantSolution == null) { return; }
            var version = "3.0.0";
            e.VlcLibDirectory = new DirectoryInfo(Path.Combine(repertoireCourantSolution, "lib", "vlc", version, IntPtr.Size == 4 ? "x86" : "x64"));
            Msg.Publication("Lib choisie: " + e.VlcLibDirectory);
            // -> Lib choisie: U:\Developpement_C_sharp\WPF_Labo_template\Labo_template\bin\Debug\lib\vlc\3.0.0\x86
        }

        private void Tab13ButtonA01_Click(object sender, RoutedEventArgs e)
        {
            var interfaceSelecteurFichier = new Microsoft.Win32.OpenFileDialog();
            var newDestination = Environment.CurrentDirectory;

            if (interfaceSelecteurFichier.ShowDialog() == true)
            {
                try
                {
                    var fichierNomComplet = interfaceSelecteurFichier.FileName;
                    var fichierNom = Path.GetFileName(fichierNomComplet);
                    Msg.Publication("Sélection fichier : " + fichierNom + " (" + fichierNomComplet + ")");

                    var options = new string[] { "-vvv" };
                    Uri fUri = new Uri("file://" + fichierNomComplet);
                    vlcPlayer.MediaPlayer.Play(fUri, options);
                }
                catch (Exception ex)
                {
                    //Msg.Publication("Exception levée : " + ex.Message);
                    Msg.Publication("Exception levée : " + ex);
                }
            }
        }

        private void Tab13ButtonB01_Click(object sender, RoutedEventArgs e)
        {
            vlcPlayer.MediaPlayer.Play();
            Msg.Publication("VLC play");
        }
        private void Tab13ButtonB02_Click(object sender, RoutedEventArgs e)
        {
            vlcPlayer.MediaPlayer.Stop();
            Msg.Publication("VLC Stop");
        }
    }
}
```

I'll let the solution in here if i or we find it. Not like the previous ticker on the matter. 

Thanks in advance.

**Comment by jeremyVignelles** [comment]
That's strange, but I'm sure there's an explanation.

Can you try with Vlc.DotNet.Forms 3.0.0-develop ?

**Comment by jeremyVignelles** [comment]
I'm not sure, but maybe EndInit() is already called by InitializeComponent()... I'd recommend you to add the control to the view programmatically rather than in the XAML so that you have full control over the initalization

**Comment by 4E71-NOP** [comment]
No luck

**I tested :**
**1** VlcControl on XAML vrs 2.2.1
**2** VlcControl on XAML vrs 3.0.0
**3** VlcControl added programmatically vrs 3.0.0
uninstalled nuggets and reinstalled as after the downgrade the compiler was still looking for 3.0.0
**4** VlcControl added programmatically vrs 2.2.1

Same behavior in all 4 cases.
-Using EndInit() = crash
-Not using it = no crash & no error but black rectangle doing nothing.

Care to clone it ? You'll have a better look. 
It's here: https://github.com/4E71-NOP/WPF_Labo_template
I'm convinced i must have forgot something tiny but crucial.

**Comment by jeremyVignelles** [comment]
I didn't clone your repo yet.

 In the meantime, what antivirus software do you have?

Have you kept all plugins inside the plugins folder?

**Comment by 4E71-NOP** [comment]
Hi,
Harrr the plugin folder was removed somehow. 
Egg -> head
Told you...

On the other hand maybe this kind of error (plugin not found) doesn't seems to be thrown and taken care of, leading to the AccessViolationException.


**For those who got here:**
Make sure you :
1 have a VlcControl in you XAML (or programmatically)
2 use <yourPlayerName>.MediaPlayer.BeginInit();
3 set <yourPlayerName>.MediaPlayer.VlcLibDirectory pointing to the accessible lib directory 
4 use <yourPlayerName>.MediaPlayer.EndInit();
5 have all the needed files in the lib directory. 

**Related help:**
Now there's a little issue with that. Shipping the application assuming the target PC do not have VLC installed (yeah; a pity; i know). It means we have to ship the plugins with the application. This is a 111Mo package. One for X86 one for X64... What would be the way to make it lighter ? is there a list somewhere that define the critical "assets" (plugin) to make sure it runs for most case/video encoding etc ??

On the other hand finding VLC programmatically can be tricky depending on the system as described here: https://stackoverflow.com/questions/5698690/check-if-vlc-is-installed

I found this but a little old for W10 user:
https://social.msdn.microsoft.com/Forums/en-US/4f7446dc-7aa9-4b58-b294-9b4dccb50596/how-to-check-vlc-player-and-skype-is-installed-on-a-system-using-c?forum=csharpgeneral

If you know a good (official?) way to find VLC on Win 7/8/10 automatically... I'm all for it. 


Thanks for your time.

**Comment by jeremyVignelles** [comment]
This is not something that is handled by Vlc.DotNet but with libvlc itself.I guess we could check if the plugins folder exist, but that would only solve a part of the issue : what if the plugins are present but none is usable...

I wouldn't recommend relying on the version installed on the user's computer : you don't have the control over which version is installed, and the user can break your app by updating its vlc version.

My recommendation would be to redistribute libvlc with your application, by using this nuget package : https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/3.0.0-alpha3

Additionally, you will find instructions on how to cusomize what is getting copied to your output directory [here](https://github.com/mfkl/libvlc-nuget). We can't tell you a list of what to copy, since it depends on what you need, you have to make tests yourself.

**Comment by Twistt** [comment]
Yup it was the plugins folder! I copied to that to my bin folder from installed VLC folder and I was right as rain. Thanks!

**Comment by jeremyVignelles** [comment]
@Twistt Don't copy that manually, use the nuget package (and if you can, also move to LibVLCSharp)
