### ISSUE TITLE
Difficult migration

### ISSUE THREAD

**Issue by Bukran** [ZeBobo5/Vlc.DotNet#47]
I am working on a WinForms project which occasionally needs to play some videos.

I come from RexGrammer Vlc.DotNet and it was great to know this new version came to life but am having quite serious difficulties migrating when one would expect this task to be almost immediate.

Vlc.DotNet.Core.Interops.dll keeps throwing AccessViolationException when the first MRL is set.
IsPlaying property throws NullReferenceException when no video has been played yet (because myVlcMediaPlayer is still null).

I'm going back to the previous version until this project gets a bit more developed and try to be in touch with this one to see its progress.

**Comment by jeremyVignelles** [comment]
Closing for now because it is an old issue. If you are still having trouble with the latest version, feel free to reopen or join the discussion at https://gitter.im/Vlc-DotNet/Lobby
