### ISSUE TITLE
how can i get the media toltle time 

### ISSUE THREAD

**Issue by liuyuqingenglish** [ZeBobo5/Vlc.DotNet#470]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.2.1)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x64)
- **.net version** : (net 4.5)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows 64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

how can i get the media time  that i played    thanks for reply me

**Comment by jeremyVignelles** [comment]
Are you looking for MediaPlayer.Time?

**Comment by liuyuqingenglish** [comment]
> Are you looking for MediaPlayer.Time?

no  i want to know the media file totle time

**Comment by jeremyVignelles** [comment]
MediaPlayer.Length?

**Comment by liuyuqingenglish** [comment]
> MediaPlayer.Length?

it seem to not work--  MediaPlayer.Length,always show 0

**Comment by jeremyVignelles** [comment]
What kind of video is that? Does a length show up in VLC when playing the same media?

**Comment by jeremyVignelles** [comment]
See also here : https://github.com/ZeBobo5/Vlc.DotNet/blob/421ddef16cab3d12b9a2d22d7bb9374758a26cea/src/Samples/Samples.WinForms.Advanced/Sample.cs#L63

When VLC says that the length is available, we get NewLength and display it

**Comment by chiefmb** [comment]
> > MediaPlayer.Length?
> 
> it seem to not work-- MediaPlayer.Length,always show 0

It is till play starts i thing

**Comment by tim-lukacik** [comment]
Media information seems to not be available until the player has started playing. After that you can use player.GetCurrentMedia().Duration

**Comment by jeremyVignelles** [comment]
Closing for now, feel free to reopen with more info if needed
