### ISSUE TITLE
Log file output location?

### ISSUE THREAD

**Issue by jnieman21** [ZeBobo5/Vlc.DotNet#472]
# Generic information

- **Vlc.DotNet.Core version** :  3.0.0-develop306
- **Vlc.DotNet.Wpfversion** :  3.0.0-develop306
- **Vlc.DotNet project used** : WPF
- **libvlc version** : v3.0.4 (nuget)
- **.net version** : 4.0
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : (Windows ...) x64

# Summary

Hopefully, this is just me not being able to find something easy... 

When running Vlc.DotNet.Wpf, where does the Logs.log end up? I'm starting the player like this, and for the life of me, I can't find the output log file. I've tried running this under the VS debugger and directly via the .exe.

            // Set up the objects
            this.control = new VlcControl();
            this.ControlContainer.Content = this.control;
            var options = new string[]
            {
                "-vvv",
                "--extraintf=logger",
                "--logfile=Logs.log"
            };

Where *should* it be?
Thanks!

**Comment by mfkl** [comment]
> Where should it be? 

Wherever you tell it be. Probably near the exe with your current relative path. Try using an absolute path.

Alternatively, try this `myVlcMediaPlayer.Log += OnLogInternal;`

**Comment by jnieman21** [comment]
I couldn't find anything in the the rel dirs, but I'll try with an absolute path to see how that goes. Thanks!

**Comment by dilandau2001** [comment]
According to Vlc documentation file logging parameters are:

`

       File logger (file)
      --file-logging, --no-file-logging 
                                 Log to file
                                 (default disabled)
          Log all VLC messages to a text file.
      --logfile=<string>         Log filename
          Specify the log filename.
      --logmode={text,html}      Log format
          Specify the logging format.
      --log-verbose={-1 (Default), 0 (Info), 1 (Error), 2 (Warning), 3 (Debug)} 
                                 Verbosity
          Select the logging verbosity or default to use the same verbosity
          given by --verbose.
`

I think you are missing to enable file logging (--file-logging), because default behaviour is not to do it.

**Comment by jnieman21** [comment]
> According to Vlc documentation file logging parameters are:
> 
> `
> 
> ```
>    File logger (file)
>   --file-logging, --no-file-logging 
>                              Log to file
>                              (default disabled)
>       Log all VLC messages to a text file.
>   --logfile=<string>         Log filename
>       Specify the log filename.
>   --logmode={text,html}      Log format
>       Specify the logging format.
>   --log-verbose={-1 (Default), 0 (Info), 1 (Error), 2 (Warning), 3 (Debug)} 
>                              Verbosity
>       Select the logging verbosity or default to use the same verbosity
>       given by --verbose.
> ```
> `
> 
> I think you are missing to enable file logging (--file-logging), because default behaviour is not to do it.

That did it, thanks!

@jeremyVignelles, I recommend updating the getting started page (https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started) to include this:
"--file-logging", "-vvv", "--extraintf=logger", "--logfile=Logs.log"

It currently shows:
"-vvv", "--extraintf=logger", "--logfile=Logs.log"

**Comment by jeremyVignelles** [comment]
Please do it, the wiki is writeable by anyone

**Comment by jnieman21** [comment]
> Please do it, the wiki is writeable by anyone

Thanks, done!
