### ISSUE TITLE
Mouse Events Turned Off When Video Control is Playing and Cannot Be Turned Back On

### ISSUE THREAD

**Issue by JohnKlineKurtz** [ZeBobo5/Vlc.DotNet#473]
When I upgraded to VLC 3.0.4, my app no longer recognized the mouse events. I had been throwing a transparent panel in front of the vlcControl to capture enter and leave in order to bring up my own custom control bar on top of the video. This no longer stays on top. It appears the vlcControl puts itself on top and I can no longer use my mouse over the video.

So I downloaded this project and ran Advanced player project and found that it is also having trouble recognizing mouse down when the video is playing. It recognizes it when the video is stopped.

I am going to try to debug it further and see if I can make a workaround.

# Generic information

- **Vlc.DotNet version** : downloaded develop
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 and x64 from VIDEOLAN website?
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 Pro x64

# Summary

Run Vlc.DotNet with Samples.Winforms.Advanced project as startup. I set a local video. Before I hit play, the control can recognize mouse events like mouse down and up. After I hit play, the mouse is not recognized at all.

WORKAROUND:
Created a class TransparentPanel like this:
    public class TransparentPanel : Panel
    {
        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams cp = base.CreateParams;
                cp.ExStyle |= 0x00000020; // WS_EX_TRANSPARENT
                return cp;
            }
        }
        protected override void OnPaintBackground(PaintEventArgs e)
        {
            //base.OnPaintBackground(e);
        }
    }

Then on my usercontrol that has the vlcControl, I overlay the Transparent Panel above the vlcControl in order to intercept any mouse events. I was adding the panel to the vlcControl in the past, but that is now broken.

**Comment by jeremyVignelles** [comment]
In Develop versions of Vlc.DotNet, there is an option which I don't remember the name `EnableMouseEvents` maybe? this let you control wether vlc intercepts the mouse events (for things like a dvd menu) or not.

**Comment by jeremyVignelles** [comment]
If you manage to do that, you won't need the transparent form anymore

**Comment by JohnKlineKurtz** [comment]
Yes, that is broken with v3.0.4.
Thanks, John

On Saturday, October 20, 2018, Jérémy VIGNELLES <notifications@github.com>
wrote:
> If you manage to do that, you won't need the transparent form anymore
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/CMoNzQmqVUYNu4_BxL0yscrXwsrRyt2RG0XO8XkgN6wkJaAc8Yz-tIAT5GjDWEvi7JBzQN9zmK6dBRk5ehhwdSYy-iG5gGt8gYmFX9MGi5NSAX9f02JWU7LzSGizy4e0a4yRnCgV646iYQQQoPwIN04daH8SjA=s0-d-e1-ft#https://github.com/notifications/beacon/AQOYir_L28HUHP8k2YjIccZMelrj_L7sks5um2BMgaJpZM4XyAfr.gif>

**Comment by jeremyVignelles** [comment]
The naming of the property combined with the lack of comments makes it hard to understand how it works.

IsMouseInputEnabled should be considered from the libvlc point of view. This means that if the parameter is `true`, it tells libvlc that it is responsible for handling mouse input, effectively disabling the mouse events in your application.

Did you try setting that parameter to `false`?

**Comment by dilandau2001** [comment]
I have test it and Jeremy is right.

if you set both:

`

                player.Video.IsMouseInputEnabled = false;
                player.Video.IsKeyInputEnabled = false;
`

before player.Play, then, the event handler works correctly.

![image](https://user-images.githubusercontent.com/12834469/47574165-45ae0680-d93f-11e8-8c02-43586bb342e5.png)

If you leave any of them as true, then the player itself will capture the inputs

![image](https://user-images.githubusercontent.com/12834469/47574023-f9fb5d00-d93e-11e8-8fa8-aba1ca776fd5.png)

**Comment by codirx** [comment]
Any wpf solution for that ?

**Comment by jeremyVignelles** [comment]
Vlc.DotNet.Wpf 3.x will never pass mouse events to vlc since it's just a bitmap that is replaced very quickly. if you need to use your mouse with the vlc control, use the . WinForms control

**Comment by codirx** [comment]
> Vlc.DotNet.Wpf 3.x will never pass mouse events to vlc since it's just a bitmap that is replaced very quickly. if you need to use your mouse with the vlc control, use the . WinForms control

But my project is WPF and I want to add mouse and keyboard controls to my vlcControl 🤔

**Comment by codirx** [comment]
''VlcLibDirectory' must be set.'


          ` vlcControl1.VlcLibDirectory = new DirectoryInfo(@"C:\Program Files (x86)\VideoLAN\VLC");
            vlcControl1.EndInit();
            vlcControl1.VlcMediaPlayer.Play("")
`
What is wrong with this code ?

**Comment by jeremyVignelles** [comment]
What do you mean? you can handle events on the control as in any WPF control, right?
What do you mean by set directory?

**Comment by codirx** [comment]
> What do you mean? you can handle events on the control as in any WPF control, right?
> What do you mean by set directory?

I mean VLC directory I can't find how to set in WPF new version of dll.

**Comment by codirx** [comment]
Finally I made it. Thank you and Thank God      


```
private void UserControl_Loaded(object sender, RoutedEventArgs e)
        {
           VlcControl.SourceProvider.CreatePlayer(new DirectoryInfo(@"C:\Program Files\VideoLAN\VLC"));
            VlcControl.SourceProvider.MediaPlayer.Play("");
            VlcControl.SourceProvider.MediaPlayer.Video.IsKeyInputEnabled = false;
            VlcControl.SourceProvider.MediaPlayer.Video.IsMouseInputEnabled = false;
            


        }


        private void VlcControl_OnMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            VlcControl.SourceProvider.MediaPlayer.Pause();
        }
```
```

**Comment by jeremyVignelles** [comment]
Closing since an answer has been provided. I'm assuming it solved the issue for you.

Feel free to reopen if more help is needed.
