### ISSUE TITLE
Does setting anything in the options field work?

### ISSUE THREAD

**Issue by amiga-500** [ZeBobo5/Vlc.DotNet#478]
Just curious.  When reading through several old issues here i notice it is a hit or miss if the options even work at all.  For me, i have never gotten anything to work in this field.  I've tried setting options (one per line) in the _VlcMediaPlayerOptions_ field in Designer mode (e.g. "**_---file-logging, --logfile=file_**").  I've also tried the same thing in code (using the prefix "--","-" and no dashes) via:

`vlcControl.SetMedia(..., new string[] { "<option 1 here>","<option 2 here>" });`
and 
`vlcPlayer.Play( ..., new string[] { "<option 1 here>", "<option 2 here>" });`

When referring to the vlc docs, i've tried setting different things and so far nothing has worked.  Clearly i must be doing it wrong; or is it that this package is just that buggy and I must just accept that setting options is not possible and i should hunt for workarounds?  I am happy to hunt for workarounds, if that is the case because at least then i don't have to keep wasting more time trying to figure it out.

Thanks very much for demystifying this.

**Comment by jeremyVignelles** [comment]
It does actually work, but we must be clearer about it.
The samples gives pretty good overview of what to do.

In a few words :

- VlcMediaPlayerOptions must be given at initialization and define the options you set for the whole media player (given with `--` in the CLI)
- Media options are set per media, with SetMedia or Play and given to cli with `:`
