### ISSUE TITLE
Overlaying Image onto Playing Video without using Marquee/Logo

### ISSUE THREAD

**Issue by amiga-500** [ZeBobo5/Vlc.DotNet#480]
Greetz from Canada!

I am aware of the marquee and logo options as a way to overlay simple text or an image, respectively, on a vlc playing video, however, i find the amount of features for both a bit lacking and was wondering if there was an alternative way to overlay a PictureBox, Button, or some other control over a playing video without it disappearing?

I figure it would require working with the vlcControl's Paint() event whereby you would wait for a  frame to finish drawing and then use that as the trigger to invalidate the e.g. PictureBox and have it refresh in the location you want.  The problem with that approach is that you will see really bad flickering.   But then, if there was a memory pointer to the frame display buffer and one could monitor each column/row pixel being drawn and it entered the region wihere the PictureBox was then you could then temporarily redirect this pointer to the picture box's display memory pointer for display.  That would stop the flickering.  But then, this isn't C/C++ and i figure hunting through the pInvokes and/or Interop libraries will take ages.

Surely there must be an easier way?  

Regards
Kimberly

**Comment by jeremyVignelles** [comment]
No, you can't use the Paint event of the control itself because it is a window (HWND) that is not handled in WinForms.
The best way to do that is with the options you discovered since it would blend your image into the video, but you can still, as far as I know, overlay controls the same way you would do in any other WinForms app

**Comment by amiga-500** [comment]
Thanks for the info Jeremy!
