### ISSUE TITLE
How to add Subtitles to Streaming Video ? 

### ISSUE THREAD

**Issue by codirx** [ZeBobo5/Vlc.DotNet#481]
Title ?

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x64
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** :/x64
- **Operating system** : (Windows ...) x64)

# Summary

**I have found this but I dont get it or I couldn't apply it. Can you help me ?**

If you just want to stream video and audio then transcode the video (and audio if necessary), and overlay the subtitles using soverlay in the transcode commandline. This way the subtitles will become a part of the output video. For example:

#transcode{vcodec=mp4v,vb=1024,scale=1,soverlay}

A complete commandline example:

vlc eyer5.avi --sub-file=eyer5.txt :sout=#transcode{vcodec=mp4v,vb=1024,scale=1,soverlay}:duplicate{dst=std{access=http,mux=asf,dst=192.168.55.5:1234}}

**Comment by jeremyVignelles** [comment]
Please see the streaming sample for an example of how to use media options in vlc.dotNet. For -- options, you will need VlcMediaPlayerOptions instead. Please share everything you tried so that we can help you more

**Comment by codirx** [comment]
> Please see the streaming sample for an example of how to use media options in vlc.dotNet. For -- options, you will need VlcMediaPlayerOptions instead. Please share everything you tried so that we can help you more

I am using this [https://github.com/mafintosh/peerflix](url). So like that:

           ` sourceProvider.MediaPlayer.Play(new Uri("http://"+uri+":8888/"), new string[] { @"--sub-file=C:\Users\Cumhur X\Desktop\Incredibles.2.2018.720p.BluRay.x264-Felony.srt" });
`

**Comment by jeremyVignelles** [comment]
`--` options must be set VlcMediaPlayerOptions at initialization

**Comment by codirx** [comment]
> `--` options must be set VlcMediaPlayerOptions at initialization

Can you give an example ?

**Comment by codirx** [comment]
Ok I made it thanks
` sourceProvider.CreatePlayer(libDirectory, new string[] { @"--sub-file=C:\Users\Cumhur X\Desktop\Incredibles.2.2018.720p.BluRay.x264-Felony.srt" });`
