### ISSUE TITLE
AccessViolationException during disposing multiple instances

### ISSUE THREAD

**Issue by mat-kul** [ZeBobo5/Vlc.DotNet#482]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Core
- **libvlc version** : _VideoLAN.LibVLC.Windows_ from nuget package (version 3.0.4), machine runs on x64
- **.net version** : 4.7.1
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64

# Summary

In case when multiple instances of `VlcMediaPlayer` are in use, it's not possible to dispose they correctly, because `Dispose()` will throw `System.AccessViolationException` 

# Scenario to reproduce issue:

1. Create more than one instance of `VlcMediaPlayer`. `SetMedia `and `Play` for each of they
2. `Stop()` and `Dispose()` first instance
3. Try to stop and dispose second instance

**Result:** `System.AccessViolationException` was thrown during disposing second instance

**Stacktrace**
```
at Vlc.DotNet.Core.Interops.VlcManager.GetMediaPlayerEventManager(VlcMediaPlayerInstance mediaPlayerInstance)
  at Vlc.DotNet.Core.VlcMediaPlayer.UnregisterEvents()
  at Vlc.DotNet.Core.VlcMediaPlayer.Dispose(Boolean disposing)
  at Vlc.DotNet.Core.VlcMediaPlayer.Dispose()
  at VLCTest.Program.Main(String[] args)
```

# Example code that reproduce issue:

```

static void Main(string[] args)
{
    var currentDirectory = Path.GetDirectoryName(
    System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase);

    currentDirectory = currentDirectory.Substring(6);

    var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

    var destination1 = Path.Combine(currentDirectory, "record1.mp4");
    var destination2 = Path.Combine(currentDirectory, "record2.mp4");

    var mediaPlayer1 = new VlcMediaPlayer(libDirectory);
    var mediaPlayer2 = new VlcMediaPlayer(libDirectory);

    var mediaOptions1 = new[]
    {
		$":sout=#file{{dst={destination1}}}",
		":sout-keep"
    };
    var mediaOptions2 = new[]
    {
		$":sout=#file{{dst={destination2}}}",
		":sout-keep"
    };

    var fileInfo1 = new FileInfo("test1.sdp");
    var fileInfo2 = new FileInfo("test2.sdp");

    mediaPlayer1.SetMedia(fileInfo1, mediaOptions1);
    mediaPlayer2.SetMedia(fileInfo2, mediaOptions2);

    mediaPlayer1.Play();
    mediaPlayer2.Play();

    Console.WriteLine("Press any key to stop");
    Console.ReadKey();

    mediaPlayer1.Stop();
    mediaPlayer2.Stop();

    mediaPlayer1.Dispose();
    mediaPlayer2.Dispose();
}
```

**I found workaround for this issue:** you must create separate folder of `libvlc` libraries for each instance of `VlcMediaPlayer`

**Comment by mat-kul** [comment]
@jeremyVignelles  This issue still exists on 3.0.0-develop311 version

**Comment by jeremyVignelles** [comment]
Based on your workaround, maybe you are hitting the potential race condition I described in #486

**Comment by jeremyVignelles** [comment]
Nevermind, I tried your code and reproduced your issue, even with #486. Sorry about that.

**Comment by dilandau2001** [comment]
I will give a try to his code this afternoon

**Comment by dilandau2001** [comment]
I found the possible reason:

Inside VlcManager

ref 1:
`

        public static VlcManager GetInstance(DirectoryInfo dynamicLinkLibrariesPath)
        {
            if (!MyAllInstance.ContainsKey(dynamicLinkLibrariesPath))
                MyAllInstance[dynamicLinkLibrariesPath] = new VlcManager(dynamicLinkLibrariesPath);
            return MyAllInstance[dynamicLinkLibrariesPath];
        }
`

For the console application, ref1 is returning the same instance of VlcManager for both players.

And given that VlcMediaPlayer Dispose() is disposing the Manager, when the second player calls dispose it has no manager to work with.

ref 2:
`

        private void Dispose(bool disposing)
        {
            if (myMediaPlayerInstance == IntPtr.Zero)
                return;
            UnregisterEvents();
            if (IsPlaying())
                Stop();

            myVlcEventManager.Dispose();
            myCurrentMedia?.Dispose();
            myMediaPlayerInstance.Dispose();
            **Manager.Dispose();**
        }
`

This is not an issue with the Form multiplayer sample because ref1 is returning 2 different manager instances... I am not sure why, maybe access time changed... who knows. The thing is, using a complex data (DirectoryInfo) for a dictionary key is not a good idea.

And my proposal to fix it. As we did for VlcMedia I think we can consider the "VlcManager Manager" to be a common resource among all players so the players do not dispose it on their dispose. Also, I think, the dictionary might not be useful at all, plugins will be loaded once for all possible players and only one "Manager" is necessary to support all VlcMediaPlayers.


For a fast "fix":

Go to VlcMediaPlayer.cs->Dispose method and comment Manager.Dispose as follows:


`

        private void Dispose(bool disposing)
        {
            if (myMediaPlayerInstance == IntPtr.Zero)
                return;
            UnregisterEvents();
            if (IsPlaying())
                Stop();

            myVlcEventManager.Dispose();
            myCurrentMedia?.Dispose();
            myMediaPlayerInstance.Dispose();
            //Manager.Dispose();
        }

`

Open VlcInstance.cs->Dispose and protect myManager.Release to not work when disposing is false, as follows:


`

        protected override void Dispose(bool disposing)
        {
            if (disposing && Pointer != IntPtr.Zero)
            {
                myManager.ReleaseInstance(this);
            }

            base.Dispose(disposing);            
        }

`

And in order to not leak VlcManagers on the Form sample I would change Dictionary key to maybe libVlc full path instead of DirectoryInfo. At least with that we are enforcing only 1 manager per Vlc folder.

**Comment by jeremyVignelles** [comment]
Didn't see that in #486, you're right, we're disposing the Manager instance. Thanks for your investigations we should probably use `libvlc_retain` to keep the code as compatible as possible without leaking. Will try to implement that in #485

**Comment by dilandau2001** [comment]
You can update #486 with the second option of the fix, as the pull is open as is affects the same file;

> The other possible fix would be just to update the ref 1, and always return a new VlcManager, so each player has its own manager. And removing the Dictionary.

`

        public static VlcManager GetInstance(DirectoryInfo dynamicLinkLibrariesPath)
        {
            return new VlcManager(dynamicLinkLibrariesPath);
        }

`

**Comment by jeremyVignelles** [comment]
Yes, but I don't want to load too many times the libraries. I don't know how Windows handles that

**Comment by dilandau2001** [comment]
It would work fine. At least I had no issues in the Multiplayer sample.
Although I agree it would not be very memory efficient.

**Comment by jeremyVignelles** [comment]
@mat-kul : I fixed your issue in #490. You can download the .nupkg at https://ci.appveyor.com/project/ZeBobo5/vlc-dotnet/builds/20498710/artifacts, install them in your project and confirm that it works for you if you have time.

**Comment by jeremyVignelles** [comment]
@mat-kul Did you try the nupkg from appveyor? Did you have any crash with this?

**Comment by samarthshroff** [comment]
@jeremyVignelles Is this merged in master?

**Comment by jeremyVignelles** [comment]
No, this has never been merged. I made another PR after (#490) that replaces this one, and that is merged in develop.

This was really recent, so I'm going to wait a little for feedback brefore releasing a stable version.

**Comment by samarthshroff** [comment]
okay. I will keep an eye on PR #490 then. Thank you.

**Comment by jeremyVignelles** [comment]
@samarthshroff : 490 is done and there won't be any update there. Please keep an eye on the next stable release instead ;)

**Comment by samarthshroff** [comment]
okay thank you 👍

**Comment by mat-kul** [comment]
@jeremyVignelles sorry for long response time, I've just checked version develop323 and it works correctly, thanks!
