### ISSUE TITLE
TakeSnapshot - How to turn off Snaphost Preview's File path?

### ISSUE THREAD

**Issue by amiga-500** [ZeBobo5/Vlc.DotNet#483]
Using the latest vlcdotnet/libvlc via Forms

When i use TakeSnapshot() a snapshot preview and its filepath appears at the top of the screen.  I would like to turn both off.  I have discovered that the only way to turn off the thumbnail preview image is to add "--no-snapshot-preview" in designer mode (aka, before EndInit()).  However when i attempt to use "--no-video-title-show" it has no effect.  The preview save location always shows on screen.

Any idea how to remove this text?

**Comment by mfkl** [comment]
https://forum.videolan.org/viewtopic.php?f=32&t=146793

**Comment by amiga-500** [comment]
Thanks a bunch @mfkl ... the switch: **--osd**  is what solved it.

**Comment by jeremyVignelles** [comment]
Since you're using `--` options, you must set them before EndInit. If you're putting the control on the designer, you must use the designer to set VlcMediaPlayerOptions. since InitializeComponents calls EndInit.

Next time, please the issue template.
