### ISSUE TITLE
Volume Mixer Shows "VLC Media Player (LibVLC 3.0.4)" Instead of My App Name

### ISSUE THREAD

**Issue by amiga-500** [ZeBobo5/Vlc.DotNet#484]
Hi.

When i use my form's app and begin to play a video that has audio i notice the Window's Volume mixer shows my app name as (see the pic below):
![volumemixer](https://user-images.githubusercontent.com/5191497/48304932-57bba780-e4f0-11e8-9f14-daa3d1fcc612.jpg)
Is there a way to change this so it shows my app name instead?

**Comment by amiga-500** [comment]
Ok never mind.  I decided to just use a hex editor to modify the text @ 0x170380 in win-x64's libvlccore.dll file and @ 0x161B70 in win-x86's libvlccore.dll

**Comment by jeremyVignelles** [comment]
I don't think this "fix" respects the license terms of vlc.
The proper fix in my opinion would be to ask the libvlc developers how to fix that.

**Comment by mfkl** [comment]
@jeremyVignelles is right, and it sounds like the wrong way to go anyway.

I'd try `libvlc_set_user_agent` and `libvlc_set_app_id`

**Comment by jeremyVignelles** [comment]
Didn't know those methods existed, reopening so that we can track that

**Comment by jeremyVignelles** [comment]
Added those functions in #485, but this doesn't work.

It seems that the issue doesn't happen if the video is rendered somewhere.

**Comment by mfkl** [comment]
Setting the WindowTitle seems to do the trick. Can you share a small repository displaying the issue? @amiga-500

**Comment by jeremyVignelles** [comment]
Closing since no answer from original poster.
