### ISSUE TITLE
I want to know how to play Rtsp Media

### ISSUE THREAD

**Issue by dandanyouxiang** [ZeBobo5/Vlc.DotNet#49]
I want to know how to play Rtsp Media，Thank you

**Comment by Jhfelectric** [comment]
VlcControl1.Play(New Uri("rtsp://192.168.0.50:8554/unicast")) works for me !
The Uri I use is from a raspberry pi, using http://raspberrypi.stackexchange.com/questions/23182/how-to-stream-video-from-raspberry-pi-camera-and-watch-it-live

**Comment by dandanyouxiang** [comment]
I tried, but no，
this is Demo，
myControl.MediaPlayer.Play(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
But I want to know how to play Rtsp Media

Like this "myControl.MediaPlayer.Play(new Uri("rtsp://192.168.0.16:554/live1.sdp"));" it is can not play

**Comment by RafalNiewinski** [comment]
You should compile your application for x86 architecture not for AnyCPU nor x64.

**Comment by yetmorestuff** [comment]
I have a similar issue. If I try to play a H.264 rtsp stream, such as:

vlc.MediaPlayer.Play(new Uri("rtsp://jblive.videocdn.scaleengine.net/jb-live/play/jblive.stream"));

...I get a System.IO.DirectoryNotFound exception - "Attempted to access a path that is not on the disk."

If instead, I try the code from the sample in my app:

vlc.MediaPlayer.Play(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));

...I get the same exception. Same if I download the avi and try to play locally...

Any ideas what is wrong?

**Comment by RafalNiewinski** [comment]
Check what I wrote for you in #56  and try again :-)

**Comment by dandanyouxiang** [comment]
@RafalNiewinski 
I wondered if he was not supported X64 architecture？Why？

**Comment by cyryl2004** [comment]
It is work for x64 if you copy dlls and plugin folder from vlc site ver win64 to lib/x64 folder.
