### ISSUE TITLE
vlc network stream load long time

### ISSUE THREAD

**Issue by kuangqifu** [ZeBobo5/Vlc.DotNet#495]
I have an issue about Vlc.DotNet, I need to play network rtsp/rtmp video stream.but the video load very slow,about 8-9s,but when I play the video use other ActiveX not vlc, It's very fast.I had changed vlc version,but the same.I don't know where is wrong about this.what can I do about this?

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 + VideoLAN.LibVLC.Windows.3.0.4 nuget
- **.net version** : .net 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows x64

# Summary

VLC itself play also slow,itself reason? or can I change some settings?

**Comment by jeremyVignelles** [comment]
If it's an issue with VLC itself, then it has nothing to do here.

You can change the network buffering setting, but it's hard to tell without any log and without access to the stream

**Comment by kuangqifu** [comment]
thanks.
I set this before EndInit:
```
vlcTest1.VlcMediaplayerOptions = new string[] {
        "--network-caching=300",
        "--realrtsp-caching=300",
        "--tcp-caching=300",
        "--udp-caching=300"};
```

but not work.The options seems to be ignored.
