### ISSUE TITLE
Setting --avcodec-hw=none still uses hardware acceleration

### ISSUE THREAD

**Issue by tim-lukacik** [ZeBobo5/Vlc.DotNet#498]
I have an issue about Vlc.DotNet.

In VLC media player -> Tools ->Preferences -> Input/Codecs -> Hardware-accelerated decoding

When set to "auto" we see the log show a message like
`avcodec decoder: Using D3D11VA (NVIDIA Quadro M1000M, vendor 4318(NVIDIA), device 5041, revision 162) for hardware decoding`
We can also observe in task manager GPU usage
`GPU 0 - Video Decode`
When set to "disabled" this message is absent and `GPU 0 - Video Decode` never shows in task manager. This is expected behavior.

The option being set by VLC media player when disabling hardware acceleration is actually `avcodec-hw=none`. When passing `"--avcodec-hw=none"` to VlcMediaplayerOptions the output
`avcodec decoder: Using D3D11VA (NVIDIA Quadro M1000M, vendor 4318(NVIDIA), device 5041, revision 162) for hardware decoding` is still observed, and task manager still shows `GPU 0 - Video Decode` which is not expected.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64, Nuget
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64

# Summary

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Can you send a sample code ?
Did you try `{"--avcodec-hw", "none"}` ? Can you send logs?

**Comment by tim-lukacik** [comment]
I have tried every combination I can think of without luck. For the attached project it seems libvlc doesn't restore properly so you may have to remove ad re-add it.

[Vlc.DotNet498.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/2669203/Vlc.DotNet498.zip)

**Comment by jeremyVignelles** [comment]
I found your answer : When you are using the WinForms control, you are using this method, which explicitely resets the value of `--avcodec-hw` : 
https://github.com/videolan/vlc-3.0/blob/738da6c2737d2da93b24b7cce47944d45d10d8d3/lib/media_player.c#L1226

I don't know why, but there is certainly a good reason for that. Why would you disable the hardware acceleration?

**Comment by SirePi** [comment]
Sorry to jump in, but I'm in the same situation; in particular, I need to disable hardware acceleration because, due to a hardware incompatibility (old video card with unsupported drivers under Windows 10), if I use hardware acceleration I get half of the screen covered by a green square.

Same thing happens if I run vlc.exe; it works properly (no green square) if I start it with --nooverlay command line parameter, but apparently this is not supported either.

**Comment by jeremyVignelles** [comment]
@SirePi : I guess that the first thing to do is to reach out to VideoLAN with the model of your video card and see if they can blacklist it for you so you can use vlc on your machine without issues.

If you're not using WinForms nor WPF, then the `"--avcodec-hw=none"` method above should work

**Comment by SirePi** [comment]
Thanks for the info, I'll try again with avcodec-hw.. to be clear, I should be doing this, correct?
```csharp
private static DirectoryInfo VLCPATH = new DirectoryInfo(...);
private static string[] VLCOPTIONS = new string[]
{  "--avcodec-hw=none"  };

...

var vlc = new VlcMediaPlayer(VLCPATH, VLCOPTIONS);
```

**Comment by jeremyVignelles** [comment]
Seems correct

**Comment by jeremyVignelles** [comment]
@tim-lukacik : Maybe there's something you can try :
Set `:avcodec-hw=none` as an argument to `Play()` (or `SetMedia()`)

@SirePi : Just answered on your forum thread.

**Comment by SirePi** [comment]
@jeremyVignelles thanks, I also added a further comment on the forum. I hope they can have a better answer but in the worst case I'm prepared to deal with VLC.exe instances directly from code.

**Comment by tim-lukacik** [comment]
My use case was playing up to 8 videos at once which was performing equally poorly on our low end machines and high end workstations. I believe this is due to the generally very limited number of NVDEC chips on Quadros regardless of series.

I got around this by using FFMPEG to convert all the videos to a raw format at video load time. It adds a small delay for the user initially but everything plays and seeks pretty much flawlessly on even our lowest spec'd machines now.
