### ISSUE TITLE
Perfomance when playing multiple videos

### ISSUE THREAD

**Issue by miguelgomezmunoz** [ZeBobo5/Vlc.DotNet#499]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop322
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x64 installed using nupkg
- **.net version** : .4.5.2
- **Project language** : C#
- **Project build architecture** : x64/Any CPU
- **Operating system** : Windows 10 x64

# Summary

I have an application which reproduces 12 videos at the same time. I am using videos with a duration of 1h (around 3GB per video)
If I open 8 videos it works fine but when I try to open 12 the app run very slowly. I am using VS 2015 and it shows that:
With 8 videos: the CPU usage is around 88% and the memory usage is 2GB (goes well).
With 12 videos: the CPU usage is around 98% all the time and the memory usage is 3GB (goes slow).
I am using a NVIDIA GTX 1080 8GB, I could add another one but will this solve my problem? I am kind of newbie in this topic, so I appreciate any help.

**Comment by jeremyVignelles** [comment]
Do not use the WPF project if you need perf/multiple players, as stated in the readme/wiki

**Comment by miguelgomezmunoz** [comment]
I have just realized one thing with 12 videos, if I use version 2.2.1 the CPU usage is just 20% and everything works fine.
However when I use version 3.0.0 CPU usage grows until 90-100%. I used version 3.0.0 because it fixed the airspace issue, is there any workaround for the 2.2.1 version which does not have much impact in the performance?

**Comment by jeremyVignelles** [comment]
Did you read the README? 
https://github.com/ZeBobo5/Vlc.DotNet/#migrating-wpf-control-from-2x

If you really need performance, you can't use that. Please use the .WinForms control in a WinFormsHost, and use one of the hack listed here : #296
