### ISSUE TITLE
Is it possible to set playback position

### ISSUE THREAD

**Issue by christianbrockly** [ZeBobo5/Vlc.DotNet#5]
Hi there,

first of all, thank you for the great work. I am trying to include Vlc.DotNet in my project. Everything is working fine, but I can't find out how to set the playback position to for example 30 seconds. There's no Position property on the VlcControl.

Is there any way to accomplish that?

Thanks,
Christian

**Comment by HubKing** [comment]
Previous version from CodePlex had Position.
After upgrading to the latest version (2014.10.15.0) from GitHub, I cannot find any "Position" or "Tine" property. How am I supposed to change position?

**Comment by ZeBobo5** [comment]
The current version implement them
