### ISSUE TITLE
WPF Control issues

### ISSUE THREAD

**Issue by Pjanssen** [ZeBobo5/Vlc.DotNet#50]
I've been experimenting a bit with the previous version of VLC.DotNet in WPF, which was really nice. Using the videobrush, I was able to draw other controls on top of my video. 
With the current version, I'm unable to do this. I believe this is due to the fact that the VlcControl is actually a HwndHost, which draws on top of all controls. Is there any chance of getting a "native" WPF control?

**Comment by wilbit** [comment]
@Pjanssen, see #12

**Comment by wuzhenda** [comment]
where I can reference the previous version of VLC, how did it use the videobrush?
