### ISSUE TITLE
System.IO.DirectoryNotFoundException when running Samples.WPF.Minimal

### ISSUE THREAD

**Issue by ashelleyPurdue** [ZeBobo5/Vlc.DotNet#500]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : commit  fcb247b
- **Vlc.DotNet project used** : (WinForms/WPF/Core)
- **libvlc version** : 3.0.4 (x86/x64).  The Nuget package referenced by this project.
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10, x64

# Summary

When running the project, it immediately throws a DirectoryNotFoundException.  The folder in question is this:  {E:\Users\Alex\source\repos\Vlc.DotNet\src\Samples\Samples.Wpf.Minimal\bin\Debug\libvlc\win-x64}

To reproduce:

- Make a fresh clone of the repo
- Set Samples.WPF.Minimal as your startup project
- Click "Start"

- [ x ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Which VS version are you using?
Do you have a packages folder next to the solution? Does it contain the VideoLAN.LibVLC.Windows folder? Do this package contain the libvlc.dll files?
Are those files copied to the bin/Debug/libvlc folder?

**Comment by ashelleyPurdue** [comment]
I'm using Visual Studio 2017, 15.9.4.  Yes, I do have a packages folder.  It's located in src/packages.  Yes, it contains the libvlc.dll folder.  No, these files are *not* copied to the Debug folder on build.  Sorry, I should have clarified that when reporting the issue!

Also I did some investigating.  The NuGet package managing widows says that LibVLC *is*, in fact, installed for Samples.WPF.Minimal.

![image](https://user-images.githubusercontent.com/8558767/50046293-6ce7a100-006f-11e9-8ef6-224ea8ac848d.png)

Despite this, however, there is no reference to it in the "references" list.

![image](https://user-images.githubusercontent.com/8558767/50046308-8d176000-006f-11e9-9968-693311054f68.png)

I opened up Samples.Wpf.Minimal.csproj and I found this entry regarding LibVLC:
`<Import Project="..\..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets" Condition="Exists('..\..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>Ce projet fait référence à des packages NuGet qui sont manquants sur cet ordinateur. Utilisez l'option de restauration des packages NuGet pour les télécharger. Pour plus d'informations, consultez http://go.microsoft.com/fwlink/?LinkID=322105. Le fichier manquant est : {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets'))" />
  </Target>`

For comparison: inside my own project which consumes this package successfully, the csproj entry looks like this:
`<Import Project="..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets" Condition="Exists('..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\VideoLAN.LibVLC.Windows.3.0.4\build\VideoLAN.LibVLC.Windows.targets'))" />
  </Target>`

They both appear to be identical, except for the French error message.

I must say, this is very bizzarre.  Everything seems to be correct, and yet it the files don't copy over.

**Comment by jeremyVignelles** [comment]
> Despite this, however, there is no reference to it in the "references" list.
This is expected. This is not a "managed" dependency, but a package that contains native .dll.

I'll try to clean my project and try to reproduce your issue. In the meantime, you can try to remove the package and add it again.

**Comment by tim-lukacik** [comment]
I referenced this behavior when attaching the sample project on my issue. Seems like an issue with VS or the nuget package itself.

[https://github.com/ZeBobo5/Vlc.DotNet/issues/498#issuecomment-446344266](url)

**Comment by mfkl** [comment]
Does checking/unchecking “prefer 32 bits build” change anything? Switch from AnyCPU to something else help?

**Comment by jeremyVignelles** [comment]
@ashelleyPurdue : Did you find a solution?
I'm going to close this, please reopen if you still have an issue
