### ISSUE TITLE
vlc.dotnet.forms play stream url with (user agent protect)

### ISSUE THREAD

**Issue by leooshad** [ZeBobo5/Vlc.DotNet#501]
I have   a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.2.1)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x86)
- **.net version** : (4.0)
- **Project language** : (VB.net)
- **Project build architecture** : (AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows 7) (x86)

# Summary

hello there

I have a question about playing stream url with user agent protection

the url like that:

:http-user-agent= my user agent
http://mywebsite.me/live/67.ts or . m3u8

now if I put thes in file.m3u and played with real vlc media player it works fine

but the question how to played and add the user agent to the url stream in my project of vlc.dotnet.forms

thank you.

**Comment by jeremyVignelles** [comment]
Did you try to set that in the media options, in `Play()` or `SetMedia()`?

**Comment by leooshad** [comment]
yes I tried to add in to (setmedia) but still did not work

**Comment by jeremyVignelles** [comment]
Please send a sample code of what you tried. I guess that if you have spaces or special chars, you will need to embed quotes inside your option string.

**Comment by leooshad** [comment]
this is an example to code:
VlcControl1.SetMedia("http://mywebsite.net:8000/live/me002/me/135.ts", ":http-user-agent=1234")

   VlcControl1.Play()

**Comment by leooshad** [comment]
thanks I found a solution its like that:

 Dim mediaOptions = New String() {":http-user-agent=1234"}

        VlcControl1.SetMedia("http://mywebsite.net:8000/live/me1/me2/135.ts", mediaOptions)
        VlcControl1.Play()

**Comment by jeremyVignelles** [comment]
@mfkl reminds me that I implemented a function one month ago, and I already forgot:

```
VlcControl1.VlcMediaPlayer.SetUserAgent(...)
```

This requires the develop version of Vlc.DotNet 3.
