### ISSUE TITLE
vlc audio visualization doesn't work

### ISSUE THREAD

**Issue by tinywinfun** [ZeBobo5/Vlc.DotNet#502]
I have an issue about Vlc.DotNet.

# Generic information
- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.0.4 (x86) copy from installed directory [D:\Program Files (x86)\VideoLAN\VLC]
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : (Windows 10 x64)

I want to use audio visualization option when play audio file. I run this in command line, it works fine.
D:\Program Files (x86)\VideoLAN\VLC>
 vlc d:\file\30.mp3 --audio-visual=visual --effect-list=spectrum

When I use the options in C# code, the audio file plays OK, but without anything displayed in myVlcControl. I want to see spectrum in myVlcControl. here is my C# code:

myVlcControl.Play(new FileInfo(@"d:/file/jmzcg.mp3"), new string[]{
                ":audio-visual=visual"
                ,":effect-list=spectrum"
            });

I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
: options are not the equivalent of --audio-visual. You can pass the -- options in VlcMediaPlayerOptions (in the designer if you're using it)

**Comment by jeremyVignelles** [comment]
Be careful, as said in the wiki, you need to call VlcMediaPlayerOptions before EndInit to have any effect. The EndInit is called by WinForms in the InitializeComponents method, so if you're using the designer, you're either too early (your control is null) or too late (endinit already called).
In that case, you will want to set the options through the designer properties tab

**Comment by tinywinfun** [comment]
It works! Thank you very much.

**Comment by tigros** [comment]
this was helpful! Please, how can i turn off visualizations for video files? Currently it pops up a new window with the visualization. I managed to close it with some code, but would rather disable creating new popups entirely. I'd do it myself but i've tried compiling vlc years ago, it still gives me nightmares heh. hopefully its improved. unless you have a better idea?

**Comment by jeremyVignelles** [comment]
Maybe you could try to parse the media to know what it is made of, and if it is an audio, pass the option in the media options of SetMedia(). That would parse the file twice, but you could choose whether you show the video or not...

**Comment by tigros** [comment]
hmm that's how i ended up on this page, had to use myVlcControl.VlcMediaplayerOptions as mentioned above which i placed in vlcControl1_VlcLibDirectoryNeeded, SetMedia was having no effect, no visualizations.

**Comment by jeremyVignelles** [comment]
OK, can you open a separate issue for that and send a sample code so that can have a look at it? I'd say you would need two players, one for audio and one for video and have to switch between them unless there is an option on vlc's side

**Comment by tigros** [comment]
That's not a bad idea, having 2 players, i did post a question here https://forum.videolan.org/viewtopic.php?f=14&t=112815&p=488409#p488409 but no response yet.

**Comment by mfkl** [comment]
Don't bump a 6 years old thread... create a new one.

**Comment by subh-kundu** [comment]
Hello,
how to stop visualization --no-visual-peaks & visual-80-bands 
my code not working properly default visualization show only Spectrum

```
mediaOptions = new[] { "--network-caching=8000",
                                   "--directx-use-sysmem",
                                   "--avcodec-hw=none",
                                   "--audio-visual=visual",
                                   ":no-visual-peaks",
                                   "--no-visual-80-bands",
                                   "--video-on-top" };
```
