### ISSUE TITLE
how to change options over video playing

### ISSUE THREAD

**Issue by clark-yang** [ZeBobo5/Vlc.DotNet#504]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : v2.0.50727
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86
- **.net version** : NET3.5 NET4.5
- **Project language** :C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 x64

# Summary
  Hi, I use the following code for video recording,it's working very well.But I need to replay the stream for start or stop recording, It was a bad experience. Is there any other way to chang the options over video playing?Thanks!

   string option = @":sout=#duplicate{dst=display,dst=record{dst-prefix='" + fileName + "'}}";
   vlcPlay.MediaPlayer.Play(streamInfo.sFlvUri, option);

**Comment by jeremyVignelles** [comment]
you can't change options while playing. to change the file destination while playing, you can try the cycle plugin (scripted destinations changes) but it has limitations that made it impractical for me.

Depending on your needs, if it's for a rolling record, you might want to use a vlc.exe process, transcode to mpeg-ts and write to stdout, grab output in your process and split by multiples of 188 bytes. 
That's what I'm doing for a recording software for my company

**Comment by Japollack** [comment]
What about stream display then? Does the recording and display use separate stream from the same source (device) simultaneously?
Could it be optimised so display always plays the stream and recorder is time-to-time reusing the same stream if video recording has been turned on, without doubling the network traffic?

**Comment by jeremyVignelles** [comment]
I don't know of any solution that would be able to do that in vlc. if you don't need to seek but just see live video, maybe you can use VLC.exe to play the stream and "record" to stdout. from your app, you could receive those bytes and write them to files, while feeding a Vlc.DotNet control with the same data.

Seems possible but hard

**Comment by jeremyVignelles** [comment]
Anything else we can do? Closing for now.
