### ISSUE TITLE
Blank screen when trying to play live stream in winform vlccontroller, OutOfMemoryException when running for a few minutes

### ISSUE THREAD

**Issue by Razkan** [ZeBobo5/Vlc.DotNet#509]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : v2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : v3.0.5 (x86), followed the 'Getting started wiki' and downloaded it to my app from nuget.
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 7, x64

# Summary
I have tried to consume a live stream from twitch.tv in the vlccontroller, such as `https://www.twitch.tv/<insertStreamerName>`.  But the vlccontroller will only show a black screen with no video or audio. When I look in the task manager my CPU will be at around 30% when trying to play the stream. When I remove the vlccontroller, it will be at a 0-1% CPU. Having the application running for 5-10 minutes will eventually throw an `OutOfMemoryException`, since the applications memory usage only increase.

```csharp
            var vlcControl1 = new Vlc.DotNet.Forms.VlcControl();
            vlcControl1.BeginInit();

            vlcControl1.BackColor = System.Drawing.Color.Black;
            vlcControl1.Location = new System.Drawing.Point(0, 0);
            vlcControl1.Name = "vlcControl1";
            vlcControl1.Size = new System.Drawing.Size(VLCPanel.Width - 100, VLCPanel.Height);
            vlcControl1.Spu = -1;
            vlcControl1.TabIndex = 1;
            vlcControl1.Text = "vlcControl1";

            vlcControl1.VlcLibDirectory = Configuration.VLCDirectory; // <ProjectPath>\Library\VideoLAN.LibVLC.Windows.3.0.5\build\x86
            vlcControl1.VlcMediaplayerOptions = new[]
            {
                "-vv",
            };

            vlcControl1.Click += (object sender, EventArgs e) => { };
            VLCPanel.Controls.Add(vlcControl1);

            vlcControl1.EndInit();

            vlcControl1.Play(new Uri("https://www.twitch.tv/<specificStream>")); // <specificStream is replaced with an actual streamers name
```

Pastebin to debug log: https://pastebin.com/nd5S3yYD

## With vlccontroller I can:
- [x] Play a local .mp4 clip.
- [x] I can play the 'vlcControl1.Play("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov"));`
- [ ] Play a livestream from example twitch

## With vlc I can:
- [x] Play a local .mp4 clip.
- [x] I can play the 'vlcControl1.Play("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov"));`
- [x] Play a livestream from example twitch
- [x] I confirm that my issue doesn't happen in VLC itself.

## Memory leak?
After like 5-10 minutes (or more) of running, the app's memory (checked through the task manager) will only increase until an 'OutOfMemoryException' is thrown in the application.

**Comment by jeremyVignelles** [comment]
Hi, thanks for the bug report.
Are you using the same verson of VLC that you are using in your project? (3.0.5)
Did you try with another version of the nuget package?

**Comment by Razkan** [comment]
I am using VLC `3.0.4`.

I have tried LibVLC version `3.0.0`, `3.0.4` & `3.0.5`. None of those have worked.

**Comment by Rukhlov** [comment]
You need get a link to channel stream and then play it on vlc
Something like:
-------------
https://video-edge-c2a9ec.fra02.abs.hls.ttvnw.net/v1/segment/Cu8D239k7TksyFw0uUjexrm32hFfsJv4BC1W84sQIQIf5ciDntH5TAFyR6FUB-AVwPZfSblMN8qlSFc02XLsulwWT9i7DnE6X9bp3nDDyf9ve_GB1xikHA1Vf9XXx1M1BgnfjRjHr_3xz1NoIjfDuwgmiO57i0AHg47qvxKwZZnxAPHaSXgspZ3vuJy6sqVlQZiXS7a930t78sjQzgrv4inY3cFYECj3XAzA8dFFWXYD__8D0auiP2JNX78-cKjir6QfmzLmvTlTXipGYn5ECVWuN57g7uKhdsvautE9HlVC_LlgbCOnlC-wiLtBgdcUF8yfykNIVi4mZ_BXjPk0TKs1h_GZoHN5WyCmAA-jHzvA6Lzy_zvksDTs1mIF3YYvhLuQ0EUbjbhECSvjvfx6UEll4YP8W0B3b5Wpo2erLQ2lo4-yX00rdcb_k0iYXAMPdMvg27y_5u1P8-ZvcuC8pxYNAHJ7rse7CzSGB7n85r9m9mgqiMCeUPtx5rhY2f7tr1CFLn_GygnmGLwX7KYk7DH8kwLrCqjTDOm2Mt6JF91IKOt-EcE8sXC5KhSi5zk45WB0V5dt0XSw6o1YHPzANmBO0zHCgMsUtfpbyx0mW4Kwz4F4ccygsn0mrYql6QiAw3fKpOfpIyKvrsnrAadrZC72EhAkcUh7cnwWunr1ZgFfoo4IGgzrFH1Zv-5JriGr_iM.ts

**Comment by Razkan** [comment]
@Rukhlov 

> You need get a link to channel stream and then play it on vlc
> Something like:
> `https://video-edge-c2a9ec.fra02.abs.hls.ttvnw.net/v1/segment/Cu8D239k7TksyFw0uUjexrm32hFfsJv4BC1W84sQIQIf5ciDntH5TAFyR6FUB-AVwPZfSblMN8qlSFc02XLsulwWT9i7DnE6X9bp3nDDyf9ve_GB1xikHA1Vf9XXx1M1BgnfjRjHr_3xz1NoIjfDuwgmiO57i0AHg47qvxKwZZnxAPHaSXgspZ3vuJy6sqVlQZiXS7a930t78sjQzgrv4inY3cFYECj3XAzA8dFFWXYD__8D0auiP2JNX78-cKjir6QfmzLmvTlTXipGYn5ECVWuN57g7uKhdsvautE9HlVC_LlgbCOnlC-wiLtBgdcUF8yfykNIVi4mZ_BXjPk0TKs1h_GZoHN5WyCmAA-jHzvA6Lzy_zvksDTs1mIF3YYvhLuQ0EUbjbhECSvjvfx6UEll4YP8W0B3b5Wpo2erLQ2lo4-yX00rdcb_k0iYXAMPdMvg27y_5u1P8-ZvcuC8pxYNAHJ7rse7CzSGB7n85r9m9mgqiMCeUPtx5rhY2f7tr1CFLn_GygnmGLwX7KYk7DH8kwLrCqjTDOm2Mt6JF91IKOt-EcE8sXC5KhSi5zk45WB0V5dt0XSw6o1YHPzANmBO0zHCgMsUtfpbyx0mW4Kwz4F4ccygsn0mrYql6QiAw3fKpOfpIyKvrsnrAadrZC72EhAkcUh7cnwWunr1ZgFfoo4IGgzrFH1Zv-5JriGr_iM.ts`

I do not really understand what you mean. Could you please elaborate a bit? Also I tried the link you sent and it does not work.

**Comment by jeremyVignelles** [comment]
@Razkan I did not reproduce the memory leak you are experiencing with the latest Vlc.DotNet develop.

However, the video does not play either. I suspect the issue is with libvlc somehow, but it's hard to tell.

I see this in my log:

```
[000001a47f7e1390] main stream debug: no stream_filter modules matched
[000001a47f798690] inflate stream debug: end of stream
```

**Comment by Rukhlov** [comment]
> 
> 
> @Rukhlov
> 
> > You need get a link to channel stream and then play it on vlc
> > Something like:
> > `https://video-edge-c2a9ec.fra02.abs.hls.ttvnw.net/v1/segment/Cu8D239k7TksyFw0uUjexrm32hFfsJv4BC1W84sQIQIf5ciDntH5TAFyR6FUB-AVwPZfSblMN8qlSFc02XLsulwWT9i7DnE6X9bp3nDDyf9ve_GB1xikHA1Vf9XXx1M1BgnfjRjHr_3xz1NoIjfDuwgmiO57i0AHg47qvxKwZZnxAPHaSXgspZ3vuJy6sqVlQZiXS7a930t78sjQzgrv4inY3cFYECj3XAzA8dFFWXYD__8D0auiP2JNX78-cKjir6QfmzLmvTlTXipGYn5ECVWuN57g7uKhdsvautE9HlVC_LlgbCOnlC-wiLtBgdcUF8yfykNIVi4mZ_BXjPk0TKs1h_GZoHN5WyCmAA-jHzvA6Lzy_zvksDTs1mIF3YYvhLuQ0EUbjbhECSvjvfx6UEll4YP8W0B3b5Wpo2erLQ2lo4-yX00rdcb_k0iYXAMPdMvg27y_5u1P8-ZvcuC8pxYNAHJ7rse7CzSGB7n85r9m9mgqiMCeUPtx5rhY2f7tr1CFLn_GygnmGLwX7KYk7DH8kwLrCqjTDOm2Mt6JF91IKOt-EcE8sXC5KhSi5zk45WB0V5dt0XSw6o1YHPzANmBO0zHCgMsUtfpbyx0mW4Kwz4F4ccygsn0mrYql6QiAw3fKpOfpIyKvrsnrAadrZC72EhAkcUh7cnwWunr1ZgFfoo4IGgzrFH1Zv-5JriGr_iM.ts`
> 
> I do not really understand what you mean. Could you please elaborate a bit? Also I tried the link you sent and it does not work.

 Go to https://pwn.sh/tools/getstream.html, get ***.m3u8 file from you twitch stream
and try  `vlcControl1.Play(new FileInfo(" ***.m3u8"));`

**Comment by jeremyVignelles** [comment]
I tried with a direct libvlc implementation ( https://github.com/jeremyVignelles/TestLibvlcNative ) and faced the same blank screen issue.

Then, it's not a Vlc.DotNet issue and you should address your question to vlc directly.

@Rukhlov 's solution worked for me, but instead of "downloading" the .m3u8 file, I just right-click and copy the file's URL. However, this URL is likely to disappear quite quickly and I wouldn't recommend that solution for production.

**Comment by Rukhlov** [comment]
>  's solution worked for me, but instead of "downloading" the .m3u8 file, I just right-click and copy the file's URL. However, this URL is likely to disappear quite quickly and I wouldn't recommend that solution for production.
it's not a solution, it's just a direction for digging ))

**Comment by Razkan** [comment]
@jeremyVignelles @Rukhlov 

I managed to make things work with the help of both your advices.

@jeremyVignelles if you add the following option:

```csharp
            vlcControl1.VlcMediaplayerOptions = new[]
            {
                "--file-caching=3500",
                "--network-caching=3500"
            };
```

The stutter and freeze was removed and I have had it running for 10 min without problems!

**Comment by Razkan** [comment]
If anyone were to stumble upon a similar issue, this is how it was solved for me:

## Pre-requiste:

[Vlc.DotNet 2.2.1](https://github.com/ZeBobo5/Vlc.DotNet)
LibVLC 3.0.5 _(Follow the how to on [Vlc.DotNet](https://github.com/ZeBobo5/Vlc.DotNet) for installation)_

## To get a stream
1. Go to: https://pwn.sh/tools/getstream.html (you can also get streamlink). 
2. Right-click on a desired streamer and quality.
3. Copy the url to your clipboard.

According to the following links: 
[reddit](https://www.reddit.com/r/VLC/comments/7pb9kw/does_vlc_need_both_file_caching_network_caching/)
[howtogeek](https://www.howtogeek.com/howto/windows/fix-for-vlc-skipping-and-lagging-playing-high-def-video-files/)
[vlc.dotnet issue 261](https://github.com/ZeBobo5/Vlc.DotNet/issues/261)

You need to set the network caching (and file caching) for the video not to stutter or freeze.
```
    --file-caching=<ms>
    --network-caching=<ms>
```

The following C# code creates a new windows form, adds it to a panel, set the vlc options and then play the stream.

```csharp 
var vlcControl1 = new Vlc.DotNet.Forms.VlcControl();
vlcControl1.BeginInit();

vlcControl1.BackColor = System.Drawing.Color.Black;
vlcControl1.Location = new System.Drawing.Point(0, 0);
vlcControl1.Name = "vlcControl1";
vlcControl1.Size = new System.Drawing.Size(MediaPanel.Width - 100, MediaPanel.Height);
vlcControl1.Spu = -1;
vlcControl1.TabIndex = 1;
vlcControl1.Text = "vlcControl1";

vlcControl1.VlcLibDirectory = Configuration.VLCDirectory;
vlcControl1.VlcMediaplayerOptions = new[]
{
    "-vv",
    "--file-caching=3500",
    "--network-caching=3500"
};

vlcControl1.Click += (object sender, EventArgs e) => { };
MediaPanel.Controls.Add(vlcControl1);

vlcControl1.EndInit();

// Replace the below stream link with the one in your clipboard
vlcControl1.Play("https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/Cq0DRs3KXFgHNLLqhScxGHLZymbTTueo6rMfm8P22vUY8BKeX16OgrkZjjR-KsQmO0Lh0-9NpN1KxVOZsvlhBSIMbud6wS_YhrbDKRroQx1m--1ObL_SLYh45gxtqDALalfNB5FOx9ApYhSUSwRQzC9dMasAJQraWTgscqOR5-Gb90i1FpfpxWSgZ91C5S-Sdkw1JB6KOislaAiM0or7yXdiMkNVcIfU3V9yS_1lPj2JbCKpFxJklo7QO_N9a4x__-h4Q3h-qQnX7KDdQkpH4ZBjCHu2BhTsGWX4LMiaPaxf29LF8dnx50ME583oji6Tb82IBKGTInGbpkf9rXJKN95p10VAuAZza3Nb5XbGJGqfWdtluswjulnnqCRHOx2yfzFPGzQv5KzcAb3hOiT35_80Yy_IE4YWGwqVTIBz1i1IWicWzCzw_plsJp8z_WEOURjpyMMQAyq_jV2o2lK5uGNGMMiErazHeeQ5zIgOdX6ygDTLYAAsk5Ee6gNo-uibTWXQO30CDS4MzgXpx_cCfavEYahjEKBdn2ZM0iFMaw3d1h9uRkok_UuGide-YO6hEhCs9wMJdG80Yv-IqWMp1h7kGgzzxlagegN0DKAwLEU.m3u8");
```

**Comment by jeremyVignelles** [comment]
From the reddit link you mentioned, the file-caching is useless in your case.

As I said before, the link there is probably there for the duration of the live streaming, and might not be valid in the future. The proper way for this would be for VLC to fix the bug in the core.

**Comment by sutoornan** [comment]
Please Help. I also have a Blank screen when trying to play a video (Windows form )

================================
Form1.Designer.cs code;
================================
namespace WindowsFormsApp3
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.vlcControl1 = new Vlc.DotNet.Forms.VlcControl();
            //((System.ComponentModel.ISupportInitialize)(this.vlcControl1)).BeginInit();
            this.SuspendLayout();
            // 
            // vlcControl1
            // 
            this.vlcControl1.BackColor = System.Drawing.Color.Black;
            this.vlcControl1.Location = new System.Drawing.Point(0, 0);
            this.vlcControl1.Name = "vlcControl1";
            this.vlcControl1.Size = new System.Drawing.Size(285, 262);
            this.vlcControl1.Spu = -1;
            this.vlcControl1.TabIndex = 0;
            this.vlcControl1.Text = "vlcControl1";
            this.vlcControl1.VlcLibDirectory = ((System.IO.DirectoryInfo)(resources.GetObject("vlcControl1.VlcLibDirectory")));
            this.vlcControl1.VlcMediaplayerOptions = new[]
{
    "-vv",
    "--file-caching=3500",
    "--network-caching=3500"
};
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 262);
            

            vlcControl1.Click += (object sender, System.EventArgs e) => { };
            this.Controls.Add(this.vlcControl1);
            this.Name = "Form1";
            this.Text = "Form1";
            //((System.ComponentModel.ISupportInitialize)(this.vlcControl1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Vlc.DotNet.Forms.VlcControl vlcControl1;
        
    }
}


================================
Program.cs code:
================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp3
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }
    }
}
==============================
Form1.cs code:
==============================
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp3
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            //vlcControl1.Play("https://cliptionary.org/hd1/temp/15618_1.mp4");
            vlcControl1.Play(new Uri("https://cliptionary.org/hd1/temp/15618_1.mp4"));
        }
    }
}

Thanks.

**Comment by jeremyVignelles** [comment]
Please open a new issue, use the issue template and paste the code properly (using the markdown syntax). This is unreadable like that...
