### ISSUE TITLE
Unhandled exception in Vlc.DotNet.Wpf.VlcVideoSourceProvider.VideoFormat

### ISSUE THREAD

**Issue by openlisp** [ZeBobo5/Vlc.DotNet#512]
I have an issue/question  about Vlc.DotNet. (both)

# Generic information

- **Vlc.DotNet version** : (3.0.0-develop322)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** :  (x64) 
- **.net version** : (Please fill)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows x64)

# Summary

This sometimes occur on systems with low RAM  (4GB) memory. It causes application crush down.

`System.IO.IOException: The paging file is too small for this operation to complete. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(SafeFileHandle fileHandle, String mapName, HandleInheritability inheritability, MemoryMappedFileSecurity memoryMappedFileSecurity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity) at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, MemoryMappedFileSecurity memoryMappedFileSecurity, HandleInheritability inheritability) at Vlc.DotNet.Wpf.VlcVideoSourceProvider.VideoFormat(IntPtr& userdata, IntPtr chroma, UInt32& width, UInt32& height, UInt32& pitches, UInt32& lines)
`

How it could be handled?

**Comment by jeremyVignelles** [comment]
What is the size of the video you're trying to display?
I'd recommend you use the WinForms control instead, it will likely use less ram

**Comment by jeremyVignelles** [comment]
Closing this for now since you didn't reply.
Feel free to reopen if needed.
