### ISSUE TITLE
Autorotation Metadata is Ignored by Vlc.DotNet

### ISSUE THREAD

**Issue by lucklouis** [ZeBobo5/Vlc.DotNet#513]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 4.0.30319
- **Vlc.DotNet project used** : Winforms
- **libvlc version** : x64 by Nuget
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 Pro

- [x ] I confirm that my issue doesn't happen in VLC itself.

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))
I am having trouble with videos captured in different orientations.  Is there a way to display a video in Vlc.DotNet using the auto-rotation metadata collected by phones and other devices?

The Vlc.DotNet control, by default, does not appear to use autorotation metadata.  For example, a video shot in portrait orientation on a mobile phone may be rotated by 90 degrees when played inside a Vlc.DotNet control.  However, the video plays in the expected portrait orientation in other media players, including VLC, presumably because they are reading the autorotation metadata.

I can set the options in Vlc.DotNet during instantiation using:

VlcMediaplayerOptions = new[]
                {
                    "--video-filter=transform",
                    "--transform-type==90)
                }

However, without knowing whether there is any auto-rotation metadata associated with the video file to begin with, this produces very unpredictable results depending on the video being played inside a Vlc.DotNet control.

I'm guessing there's a VlcMediaplayerOption that I'm not aware of but I'd be most appreciative of any guidance.

THANK YOU for all of the time and effort you put into this project!!

**Comment by jeremyVignelles** [comment]
As far as I remember, the last time I tried the rotation was correct at play without specifying any option, but I had issues with snapshots.
This should work out of the box, and I suggest you to ask VLC directly.

**Comment by jeremyVignelles** [comment]
Also, if you want us to do something, please upload a file somewhere so that we can reproduce the issue.

**Comment by lucklouis** [comment]
Hi, thanks for the quick response.  Please find below a video shot in Portrait mode on my iPhone X.  It plays normally (i.e. portrait mode) in VLC but when played in Vlc.DotNet, it is rotated counterclockwise 90 degrees.  Please note that I haven't set an video options during instantiation of the Vlc.DotNet control at all. 

[IMG_7604.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/2805565/IMG_7604.zip)

**Comment by lucklouis** [comment]
FWIW, the code I'm using in this test is pretty basic...

vlcControl.BeginInit();
vlcControl.VlcLibDirectory = new System.IO.DirectoryInfo(VLCLibraryPath);
vlcControl.EndInit();
vlcControl.SetMedia(new FileInfo(mediaInfo.currentFilePathFull));
vlcControl.Play();

I then add the vlcControl to my WinForm.  The video plays but the only issue is the counterclockwise rotation.

**Comment by jeremyVignelles** [comment]
Orientation is correct for me using this package:
```
<package id="VideoLAN.LibVLC.Windows" version="3.0.4" targetFramework="net471" />
```

and this code:
```
            var currentAssembly = Assembly.GetEntryAssembly();
            var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
            // Default installation path of VideoLAN.LibVLC.Windows
            var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            control.BeginInit();
            control.VlcLibDirectory = libDirectory;
            control.Dock = DockStyle.Fill;
            control.EndInit();
            this.Controls.Add(control);

            control.Play("file:///C:\\Users\\JeremyVignelles\\Videos\\VideoSamples\\IMG_7604.MOV");
```

in Vlc.DotNet 3.0-develop

**Comment by lucklouis** [comment]
Just wanted to say thank you again for your help.  I must have had a corrupted VLC – after reinstalling VLC, it worked.

Hope I didn’t waste your valuable time.

Regards,
Luck



Sent from Mail for Windows 10
