### ISSUE TITLE
What is the difference between Play and SetMedia?

### ISSUE THREAD

**Issue by todatamining** [ZeBobo5/Vlc.DotNet#518]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.2.1.0,)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x86) (x86/x64) + how did you get it?
- **.net version** : (4.0)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (window 10 x64)

# Summary

What is the difference between Play and SetMedia?

1. vlcControl.Play(...)

2. vlcControl.SetMedia(...)

   vlcControl.Play()

Are 1 and 2 exactly the same? If not, in which case should I use SetMedia?

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
It's two ways to do the same thing, because the libvlc API offers the way to do it.
If you want to preload the media before playing, like getting the media length and so on, you should use method 2
