### ISSUE TITLE
Play video start at a specific time?

### ISSUE THREAD

**Issue by todatamining** [ZeBobo5/Vlc.DotNet#519]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information
* **Vlc.DotNet version** : 2.2.1
* **Vlc.DotNet project used** : Winforms
* **libvlc version** : 2.2.5.1 x86 I got it from the installation directory of VLC Media Player
* **.net version** : 4.5.2
* **Project language** : VB. Net
* **Project build architecture** : AnyCPU (prefer 32bits)
* **Operating system** : Windows 8.1 x64

# Summary

Can I specify a time (or percentage, for example %10)  when play a video?

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Yes, `.Position` is the position in the video ([0;1]) and `.Time` is the number of milliseconds since the beginning.

Side note : please use the 3.0 develop version instead of the 2.x . Many bugs have been fixed since that version.

**Comment by todatamining** [comment]
Thanks so much for your help!
