### ISSUE TITLE
Performance issues streaming videos. No problem in VLC itself.

### ISSUE THREAD

**Issue by GustavPS** [ZeBobo5/Vlc.DotNet#520]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop333
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.6 x64 via Nuget
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64

# Summary

Some frames are dropped when streaming a live video, when I stream it directly in VLC
It is perfectly smooth. Atleast I think the problem is that the frames are dropped, every 1-2 seconds I notice some slight lagg.

Code:

         var currentAssembly = Assembly.GetEntryAssembly();
         var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
         var libDirectory = new DirectoryInfo(System.IO.Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));
         var options = new string[] { ":sout-mux-caching=5000", ":network-caching=1000" };
         _video_player.SourceProvider.CreatePlayer(libDirectory, options);
         ThreadPool.QueueUserWorkItem(ThreadProc);

        private void ThreadProc(Object stateInfo)
        {
            _video_player.SourceProvider.MediaPlayer.Play("<STREAM_URL>");
        }

- [ x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Do not use the Wpf control if you need perf. Use the WinForms control in a WinFormsHost. See this sample: https://github.com/ZeBobo5/Vlc.DotNet/tree/develop/src/Samples/Samples.Wpf.Minimal.UsingWinForms
