### ISSUE TITLE
How to get RTSP Video Every Frame In background thread ?

### ISSUE THREAD

**Issue by wangning08115** [ZeBobo5/Vlc.DotNet#521]
How to get RTSP Video Every Frame In background thread ?
And the background thread will Add a watermark to the Frame Bitmap,Then will save all Frame Bitmap to Disk.   
Can you give a demo?
Thanks!

**Comment by jeremyVignelles** [comment]
This will be very slow to do like that, but you can try the callbacks route. See how the Wpf control is implemented.

Another way that should be faster is to add an image over the video, but you will need to look for the syntax on the internet. Then, you can use the record sample to write the video to the disk.

**Comment by wangning08115** [comment]
I know This will be very slow to do like that.   
But this situation has many application scene, Such as Video monitoring, On Video monitoring, system will save all Video Picture to Disk, Then system can do some Picture data analysis .  Suck as face recognition.  

I am an  beginner, It is hard to me to implemented it use Wpf control sample source code.
I will try to do this. 

Very Thank you for your reply.
