### ISSUE TITLE
reducing the number of frame per seconds

### ISSUE THREAD

**Issue by wangning08115** [ZeBobo5/Vlc.DotNet#523]
reducing the number of frame per seconds.

I use below option:
String[] options = {
                "--sout=\"#transcode{vcodec=theo,vb=256,fps=10}\""
                };
            string[] vlcMediaPlayerOptions = options;

But the options not vaild, The MediaPlayer.SetVideoCallbacks Callback function still called 15 times per second.

How can i use option to set VLC to 5 times per second?

**Comment by wangning08115** [comment]
@jeremyVignelles    Can you help me?

**Comment by jeremyVignelles** [comment]
I've seen `--fps-fps=...` can you try it? https://wiki.videolan.org/VLC_command-line_help/

**Comment by wangning08115** [comment]
This parameter is invaild:
I use below option:
String[] options = {
                "--fps-fps=5"
                };

And i output log in VLC DisplayVideo callback function, And DisplayVideo function be invoked  still 15 Times per second, So it not right for me.

below is DisplayVideo output log with TimeStamp:

DisplayVideo=2019-02-26 17:15:20 026
DisplayVideo=2019-02-26 17:15:20 106
DisplayVideo=2019-02-26 17:15:20 169
DisplayVideo=2019-02-26 17:15:20 249
DisplayVideo=2019-02-26 17:15:20 296
DisplayVideo=2019-02-26 17:15:20 361
DisplayVideo=2019-02-26 17:15:20 416
DisplayVideo=2019-02-26 17:15:20 480
DisplayVideo=2019-02-26 17:15:20 581
DisplayVideo=2019-02-26 17:15:20 625
DisplayVideo=2019-02-26 17:15:20 704
DisplayVideo=2019-02-26 17:15:20 770
DisplayVideo=2019-02-26 17:15:20 816
DisplayVideo=2019-02-26 17:15:20 895
DisplayVideo=2019-02-26 17:15:20 960
DisplayVideo=2019-02-26 17:15:21 026
DisplayVideo=2019-02-26 17:15:21 106
DisplayVideo=2019-02-26 17:15:21 172
DisplayVideo=2019-02-26 17:15:21 255
DisplayVideo=2019-02-26 17:15:21 315
DisplayVideo=2019-02-26 17:15:21 382
DisplayVideo=2019-02-26 17:15:21 470
DisplayVideo=2019-02-26 17:15:21 515
DisplayVideo=2019-02-26 17:15:21 583
DisplayVideo=2019-02-26 17:15:21 627
DisplayVideo=2019-02-26 17:15:21 709
DisplayVideo=2019-02-26 17:15:21 777
DisplayVideo=2019-02-26 17:15:21 861
DisplayVideo=2019-02-26 17:15:21 907
DisplayVideo=2019-02-26 17:15:21 975
DisplayVideo=2019-02-26 17:15:22 028
DisplayVideo=2019-02-26 17:15:22 096
DisplayVideo=2019-02-26 17:15:22 189
DisplayVideo=2019-02-26 17:15:22 237
DisplayVideo=2019-02-26 17:15:22 316
DisplayVideo=2019-02-26 17:15:22 385
DisplayVideo=2019-02-26 17:15:22 469
DisplayVideo=2019-02-26 17:15:22 509
DisplayVideo=2019-02-26 17:15:22 578
DisplayVideo=2019-02-26 17:15:22 685
DisplayVideo=2019-02-26 17:15:22 716
DisplayVideo=2019-02-26 17:15:22 786
DisplayVideo=2019-02-26 17:15:22 869
DisplayVideo=2019-02-26 17:15:22 907

**Comment by jeremyVignelles** [comment]
Please share a sample code? where did you pass that options object?

**Comment by wangning08115** [comment]
My code init:

 String[] options = {
                "--fps-fps=5"
                };
            string[] vlcMediaPlayerOptions = options;
            var directoryInfo = libDirectory ?? throw new ArgumentNullException(nameof(libDirectory));

            //–vc1-fps=
            this.MediaPlayer = new VlcMediaPlayer(directoryInfo, vlcMediaPlayerOptions);
            this.MediaPlayer.TimeChanged += MediaPlayer_TimeChanged;
            this.MediaPlayer.PositionChanged += MediaPlayer_PositionChanged;
            this.MediaPlayer.MediaChanged += MediaPlayer_MediaChanged;

**Comment by jeremyVignelles** [comment]
It is possible that the fps plugin is not used when using the video callbacks. maybe you can manually ignore frames inside your callback?

**Comment by wangning08115** [comment]
Ok, i will manually ignore frames inside DisplayVideo callback .
