### ISSUE TITLE
Muting one VlcPlayer object mutes all

### ISSUE THREAD

**Issue by perkalkyl** [ZeBobo5/Vlc.DotNet#524]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop333
- **Vlc.DotNet project used** : WinForms & Core
- **libvlc version** : 3.0.4 (x86) downloaded
- **.net version** : 4.6.2
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary

I am using 3 individual VlcPlayer objects.
Two of them are .DotNet.Forms.VlcControl instances, and the third is a .Core.VlcPlayer instance.
When calling myVlcPlayer1.Audio.ToggleMute(); on one of the instances, all three toggles the mute so all three is either muted or not muted.

I am unsure how confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
This is a known issue of libvlc itself (it happens on libvlcsharp too). if you could share a sample code to reproduce the issue, that would help us

**Comment by perkalkyl** [comment]
Oh, ok. Is there any way around it @jeremyVignelles  ? 
I could of course put together a simple C# forms application with two players and a mute button, but I am unsure how much use you would have of it if this is a known issue.

**Comment by jeremyVignelles** [comment]
maybe setting the volume to 0?
This is a known issue by me, but so far, I never found the time to report that to VLC.

**Comment by perkalkyl** [comment]
setting the volume produces the same result. Tried that already.
I tried to set the parameter to "-an" when loading the media via 
MyVlcControl.SetMedia(myFileInfo,  new string[] {"-an"}); 
which theoretically should disable the audio altogether, but that didnt work either :-(

**Comment by devkanro** [comment]
It seem a bug of LibVlc 3.0

You can see this thread https://forum.videolan.org/viewtopic.php?t=147229

If you have multiple player in your application, set volume of one of those, and volume of all player will be changed, so, if you set some diff for your players, it will case some conflict.

In this thread, he said set ‘--aout=directsound’ to vlc can solve it, I have tried it, it works.

**Comment by perkalkyl** [comment]
@devkanro  thank you for your info. I would like to test it, but can't figure out how to set that flag in Vlc.DotNet.Core. I tried to use it as a flag with VlcControl.SetMedia(myfile, " --aout=directsound "), but that didn't do anything. Any help is appreciated

**Comment by jeremyVignelles** [comment]
@perkalkyl : `--` options are meant to be set at libvlc initialization, that is, you need to set them in VlcMediaPlayerOptions before EndInit

**Comment by perkalkyl** [comment]
@jeremyVignelles thank you for your info and very fast response. I have to do some readup on where to do what :-D 
I am very happy, cause it seems to work @devkanro !! Setting the flag in VlcMediaPlayerOptions as you suggested, I can now turn that particular play to mute without affecting the other players.
Thank you very much for your info guys!
