### ISSUE TITLE
Looking for any event or property to flag RTSP stream lost

### ISSUE THREAD

**Issue by jnieman21** [ZeBobo5/Vlc.DotNet#525]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

* **Vlc.DotNet.Core version** :  3.0.0-develop306
* **Vlc.DotNet.Wpfversion** :  3.0.0-develop306
* **Vlc.DotNet project used** : WPF
* **libvlc version** : v3.0.4 (nuget)
* **.net version** : 4.0
* **Project language** : C#
* **Project build architecture** : AnyCPU
* **Operating system** : (Windows ...) x64

# Summary

I'm viewing an RTSP stream, and I was hoping to add some retry logic in the event of (temporarily) lost network. However, I can't seem to find any hook or property that lets me know "hey, everything _was_ good, but I haven't seen any new frames in a while... probably this stream is dead."

**Comment by jeremyVignelles** [comment]
Are you looking for `EncounteredError`?

**Comment by jnieman21** [comment]
I'm hooked to that, but no luck. I'm basically doing this:
1. Connect to test RTSP stream (rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov)
2. Make sure everything is running fine, stream looks good
3. Disconnect wifi

The stream stops, obviously, but I never hit EncounteredError. I've let is sit in the disconnected state for ~5 minutes, and still nothing.

**Comment by mfkl** [comment]
Please share full logs and your full code.

**Comment by mfkl** [comment]
You need `EndReached`, `EncounteredError` as well as `System.Net.NetworkInformation.NetworkChange.NetworkAddressChanged` (and possibly a PInvoke call to `InternetGetConnectedState` if that's not reliable enough).

That's not a Vlc.DotNet issue though IMHO.

**Comment by mfkl** [comment]
> I don't think you need to hook into the system events.

I did have to do this (in my experience).

**Comment by mfkl** [comment]
> I don't think you need to hook into the system events.

I did have to do this (in my experience).

**Comment by jeremyVignelles** [comment]
If I remember correctly, as long has your video has started, you will get `EndReached` or `ErrorEncountered`. I don't think you need to hook into the system events.

As for RTSP live streaming, the "end reached" event should be considered the same as an error IMHO, at least for the retry mechanism.

**Comment by jnieman21** [comment]
Thanks for the responses. Jeremy, I tried hooking up to EndReached, but no dice. I'm going to try to do what I'm doing in an example app real quick and send over the logs, etc. Because yeah, this feels like all of those handlers logically _should_ be firing, but in my case they're not. Hold for logs!

**Comment by jnieman21** [comment]
In the process of building a simple example of the error, I think I found the source of the issue. 

I was previously passing the following as media options when creating the player, so that when/if the stream ended, the control would automatically repeat it:
string[] mediaOptions = { "input-repeat=65535" };
vlcControl.SourceProvider.MediaPlayer.SetMedia(mediaUri, mediaOptions);

If I include the repeat option in the mediaOptions, the MediaPlayer.EndReached never fires when the network goes down. If I remove that option (and change it to string[] mediaOptions = {};) , it works great. The event fires when network goes down. (Note, the same is true for the "end" of the stream. When the video ends without the repeat option, EndReached fires, but with the repeat option, it doesn't fire, and there's no indication that the video ended and restarted. Not necessarily a bad thing, but FYI.)

So I don't know if this is a bug or a expected behavior. As a note, if I remove that option, then when the video stream ends (rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov), the video doesn't restart. It does restart if I leave the repeat option in. For my current project, I don't expect the stream to ever end, so it's less relevant to me, but it could be relevant to others.

I think I'm going to take out the repeat option, then just handle an EndReached manually and attempt to restart the video, just the same as if a networking error had occurred. 

Sample project here if it's useful: https://github.com/jnieman21/VLC.DotNet.IssueSample

**Comment by jeremyVignelles** [comment]
Thanks for your analysis. it is indeed the expected behavior . if you repeat 3,the EndReached event is only triggered after the third loop. handling the EndReached manually offers you more flexibility, so I'd recommend that way.

**Comment by jnieman21** [comment]
Good to know. As an aside then, if I wanted to repeat forever, is there any way to get a call when the stream dies, like in the network failure case?

**Comment by jeremyVignelles** [comment]
No, there's no way to differenciate. streams can fail for a wide variety of reasons, so I imagine that making an API for that would be hard.

**Comment by ShayanFiroozi** [comment]
Hi , 
i've found a solution which is perfectly working for me in unstable connections(for RTSP)

Setup a system timer which check the media state in a specific period of time.

` 
 private void Setup_WatchDog_Timer()
        {
            myTimer = new System.Timers.Timer(5000);
            myTimer.Elapsed += new ElapsedEventHandler(myTimer_Elapsed);
            myTimer.Enabled = true;
            myTimer.AutoReset = true;
            myTimer.Start();

        }

        public  void myTimer_Elapsed(object sender, ElapsedEventArgs e)
        {
            if(vlcModule.GetCurrentMedia().State != Vlc.DotNet.Core.Interops.Signatures.MediaStates.Playing &&
                vlcModule.GetCurrentMedia().State != Vlc.DotNet.Core.Interops.Signatures.MediaStates.Opening)
            {
                vlcModule.Stop();

                vlcModule.Play();
            }
        }
`
