### ISSUE TITLE
Green Snapshot

### ISSUE THREAD

**Issue by swanom** [ZeBobo5/Vlc.DotNet#527]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop306
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : v3.0.6 (nuget)
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits))
- **Operating system** : Windows 10) (x64)

# Summary

When I try to take a snapshot from an MP4 video I get green photo. 
What can I do to correct this problem?

**Comment by jeremyVignelles** [comment]
Did you try on VLC? this looks like a hardware acceleration issue. can you try with `:avcodec-hw=none` in the media arguments (in Play() or SetMedia())

**Comment by mfkl** [comment]
Share your graphic card models and drivers, and your media if possible.

**Comment by jeremyVignelles** [comment]
Did you fix your issue?
Closing it for now, feel free to reopen if you still need help.

**Comment by MinChanSike** [comment]
Green snapshot happen both on VLC and Vlc.DotNet when `Hardware-accelerated decoding` is enable and `Video Effects` is enable. 
Even when `Hardware-accelerated decoding` is enable, 
if `Video Effects` is disable, green snapshot doesn't happen.

**Operating system**: Windows 10 (x64)
## Graphic Card
**Card name**: NVIDIA GeForce 930MX
**Manufacturer**: NVIDIA
**Chip type**: GeForce 930MX
**DAC type**: Integrated RAMDAC
**Device Type**: Render-Only Device
**Driver Name**: nvldumdx.dll
**Driver Model**: WDDM 2.5
**Driver Version**: 25.21.14.2525
**DDraw Status**: Enabled
**D3D Status**: Enabled
**AGP Status**: Enabled
**Detachable GPU**: No
**Hybrid Graphics GPU**: Discrete

**Comment by jeremyVignelles** [comment]
If this happens in VLC, it does not belong to this project. Report to videoLAN directly
