### ISSUE TITLE
Accesing properties vlc in another form

### ISSUE THREAD

**Issue by Dcdaniel17** [ZeBobo5/Vlc.DotNet#528]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop333
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (Please fill) (x86/x64) + how did you get it?using x86
- **.net version** : 4.6.1
- **Project language** : (C#/VB.net)C#
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits)) 64
- **Operating system** : (Windows ...) (x86/x64):Windows 64bit

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

- I would like to  acces the component vlc.donet,forms.vlcontrol  of his properties "visible" from another form2.
When I am catching the propreties in the main form ,like this : `MessageBox.Show(vlc.Visible.ToString());` it is working fine.
I changed in the main designer the declaration from `private Vlc.DotNet.Forms.VlcControl vlcSTREAM1;` to `public Vlc.DotNet.Forms.VlcControl vlcSTREAM1;`.

In the form2 I have this code declared,but I get the information as False.

```
Form1 frm1 = new Form1();
            MessageBox.Show(frm1.Text.ToString()); //-->this is working
          
            MessageBox.Show(frm1.vlc.Visible.ToString()); //-->this is not working,why?
```
I am missing something?
Thanks in advance.

**Comment by jeremyVignelles** [comment]
Visible is a WinForms property, right? I'm not a WinForms developer so I can only make guesses. You will have better answers on stackoverflow with your full code.
Are you on the main thread?

**Comment by honfika** [comment]
Do you show your form?
In the 3 lines you wrote, you just create the form, but it is not displayed. So the false visible value is correct.

**Comment by jeremyVignelles** [comment]
Closing since it seems to work as expected. Feel free to reopen if not.
