### ISSUE TITLE
Memory Mapped Exception on MediaPlayer.Play(Uri)

### ISSUE THREAD

**Issue by jsymon** [ZeBobo5/Vlc.DotNet#529]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0-develop343)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (x64) - Referencing VLC libvlc 3.0.6
- **.net version** : (4.6.2)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU / x64)
- **Operating system** : (Windows 10) (x64)

# Summary

Upgraded to 343 from 322.

Calling `SourceProvider.MediaPlayer.Play(FileInfo);` works fine, however calling `SourceProvider.MediaPlayer.Play(uri, new[] { "" });`, with a UDP uri provokes the following crash:

```
[ System.ArgumentOutOfRangeException: A positive number is required.
Parameter name: capacity
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, MemoryMappedFileSecurity memoryMappedFileSecurity, HandleInheritability inheritability)
   at Vlc.DotNet.Wpf.VlcVideoSourceProvider.VideoFormat(IntPtr& userdata, IntPtr chroma, UInt32& width, UInt32& height, UInt32& pitches, UInt32& lines)](url)

```

Edit, tried 'develop333' revision, which works completely fine with Uri and FileInfo.

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
develop322 works fine?
What's your stream?

**Comment by jsymon** [comment]
> develop322 works fine?
Yes, and develop333 also.
> What's your stream?
It's an internal UDP stream, apologies.

**Comment by jsymon** [comment]
Have attached the following stackdump if interested:

![image](https://user-images.githubusercontent.com/6398627/53743529-ed5db700-3e92-11e9-8028-a498a180801c.png)

**Comment by jeremyVignelles** [comment]
Ok, then, this is introduced by PR #526 .

Can you call `(VideoTrack)MediaPlayer.GetMedia().Tracks.First(track => track.Type == MediaTrackTypes.Video).TrackInfo` and look at Width and Height?

I'd bet they are 0...

**Comment by jsymon** [comment]
> Ok, then, this is introduced by PR #526 .
> 
> Can you call `(VideoTrack)MediaPlayer.GetMedia().Tracks.First(track => track.Type == MediaTrackTypes.Video).TrackInfo` and look at Width and Height?
> 
> I'd bet they are 0...

Correct, `TrackInfo` just contains a whole bunch of zero's.

**Comment by jeremyVignelles** [comment]
Could you make a PR to fix this? we need to check `if(trackInfo.width > 0 && trackInfo.height > 0)` before assigning width and height. leave the break outside the if. Test it and publish the PR.

Otherwise, I'll do that in my free time.

**Comment by jsymon** [comment]
`if (track.Type == MediaTrackTypes.Video)
                {
                    var trackInfo = (VideoTrack)track.TrackInfo;
                    if (trackInfo.Width == 0 || trackInfo.Height == 0)
                        continue;
                    width = trackInfo.Width;
                    height = trackInfo.Height;
                    if (trackInfo.SarDen != 0)
                    {
                        width = width * trackInfo.SarNum / trackInfo.SarDen;
                    }
                    break;
                }`  does fix it, will see if I can create a PR this week...

**Comment by jeremyVignelles** [comment]
I just created #531 , which should fix your issue.
Are you able to download [those packages](https://ci.appveyor.com/project/ZeBobo5/vlc-dotnet/builds/22876167/artifacts) manually and install them in your project to confirm that they work for you?
