### ISSUE TITLE
Program crashes after disposing

### ISSUE THREAD

**Issue by canudont** [ZeBobo5/Vlc.DotNet#530]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : 
- **libvlc version** : VLC Nightly 4.0.0-20190304 (x86), https://nightlies.videolan.org/build/win32/vlc-4.0.0-20190304-0247/
**EDIT:** Just tried the same thing with VLC 3.0.6 (x86, http://ftp.videolan.org/pub/videolan/vlc/3.0.6/) and I can confirm it happens here too.
- **.net version** : 4.7.2
- **Project language** : C# (WinForms)
- **Project build architecture** : Any CPU
- **Operating system** : Windows 8.1 Pro (x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))
When disposing a VlcControl the application crashes, but the debugger doesn't catch the exception.

I **do** get this in the output:
The program '[2864] MediaPlayer.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

The application is basically a interface to a server with media files. It allows the user to select a file on the server, and play it back on the user's machine. This piece of code is the code I use to get rid of the control:

`foreach (Control c in panel1.Controls)`
`            {`
`                if (c is VideoPlayer)`(VideoPlayer is just a UserControl with a few button controls and a trackbar)
`                {`
`                    VideoPlayer vlchost = c as VideoPlayer;`
`                    vlchost.vlc.Pause();`
`                    vlchost.vlc.Dispose();`
`                }`
`                c.Dispose();`
`            }`

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Please try with the 3.0-develop version

**Comment by canudont** [comment]
Tried compiling the 3.0-develop version, that worked. But now as soon as I set the VlcLibDirectory I get this exception:

```
System.IO.FileLoadException: 'Could not load file or assembly 'Vlc.DotNet.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=84529da31f4eb963' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Inner Exception
FileLoadException: Could not load file or assembly 'Vlc.DotNet.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84529da31f4eb963' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by jeremyVignelles** [comment]
you don't need to build it, it's already on nuget, just check the "include prereleases" box

**Comment by canudont** [comment]
Got the 3.0 version to work. The application doesn't crash now but instead it locks up

**Comment by jeremyVignelles** [comment]
are you calling Dispose or any other Vlc.DotNet method from a callback? if so, I invite you to read the wiki page about that

**Comment by canudont** [comment]
Ok, read the wiki. I queued the Dispose method but that just gave me another runtime error:

![screenshot 1](https://user-images.githubusercontent.com/48257611/53835768-1f2e5680-3f43-11e9-909a-e4babc395e23.png)

I also noticed the following in the console:

`[111e23b0] avcodec decoder error: more than 25 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

`[111e23b0] avcodec decoder error: more than 25 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

`[111e23b0] avcodec decoder error: more than 36 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

`[111e23b0] avcodec decoder error: more than 52 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

`[111e23b0] avcodec decoder error: more than 67 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

`[111e23b0] avcodec decoder error: more than 83 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

`[111e23b0] avcodec decoder error: more than 99 frames of late video -> dropping frame (computer too slow ?)` 20 times
`[h264 @ 111fd040] co located POCs unavailable`
`[h264 @ 1121eb40] co located POCs unavailable`

I think it might be a bug in libvlc because both my project and Vlc.DotNet aren't written in C++

**Comment by jeremyVignelles** [comment]
Are you doing long work in a Vlc.DotNet callback, like writing logs into a file synchronously? if not, can you share your code?

**Comment by canudont** [comment]
No logging, but what code do you want :)

**Comment by jeremyVignelles** [comment]
A simple reproduction case so that I can see what's wrong.
Late frame issues indicate that something slows libvlc down, and in my experience, this is usually caused by a long-running libvlc callback or event.

**Comment by canudont** [comment]
Just realized how junk my code is. Almost every bit of code is ran in a different thread and there are a million invokes! Gonna clean up my code before bothering you.

**Comment by canudont** [comment]
Ok
Here's the VideoPlayer class:
https://pastebin.com/MQ28sLwZ
And the MainForm class:
https://pastebin.com/JQY3cqpK

**Comment by jeremyVignelles** [comment]
Your handler for PositionChanged seems like a good culprit. Can you comment it out and try again?

Specifically, you're waiting synchronously for the main thread to update the view, and by doing so, you're blocking the libvlc thread

**Comment by canudont** [comment]
Wow, that worked, but only the first time. 
I'm getting this exception (but it's on the same thread?):
![untitled2](https://user-images.githubusercontent.com/48257611/53840909-43dcfb00-3f50-11e9-80be-ab9ac9ec6ea2.png)

**Comment by jeremyVignelles** [comment]
where's your .Invoke() that you had a. few messages ago?

**Comment by canudont** [comment]
Do you see the big Invoke on the VideoPlayer class? All of those functions were seperate invokes. I just turned it into one big invoke

**Comment by canudont** [comment]
And it's on a seperate thread because the `http_uri` variable is actually just an api request link, so I first execute that api request, get the url and with set the `http_uri` variable to the direct http url

**Comment by jeremyVignelles** [comment]
You're calling closeVlc from the thread pool, you must come back to the main thread to dispose it properly, so the invoke is needed

**Comment by canudont** [comment]
This is the new closeVlc method:

```
this.Invoke(new Action(() => 
{
    VideoPlayer vlc = StateInfo as VideoPlayer;
    vlc.vlc.Dispose();
    vlc.Parent.Dispose();
}));
```

It just freezes the application.

**Comment by jeremyVignelles** [comment]
Please publish the full code on a github repo so that I can clone the project and see myself. I will look at it later

**Comment by canudont** [comment]
Okay!

**Comment by canudont** [comment]
Solved by actually aborting the thread of VideoPlayer

**Comment by wutangyuan** [comment]
> Solved by actually aborting the thread of VideoPlayer

How did you solve the problem? Can you share your solution？
