### ISSUE TITLE
Unable to find vlclib on Linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by wilderlopes83** [ZeBobo5/Vlc.DotNet#534]
I have a question about using Vlc.DotNet on Linux (Ubuntu 18.04)

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Core (console)
- **libvlc version** :  5.6.0. I installed according with instructions from https://code.videolan.org/videolan/LibVLCSharp/blob/master/docs/linux-setup.md
- **.net version** : Core 2.1
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Linux(Ubuntu 18.04)

I'm new on Linux and and I'm trying to run the simple recording sample > https://github.com/ZeBobo5/Vlc.DotNet/tree/develop/src/Samples/Samples.Core.Recording

Worked fine on Windows but is not working on Linux. The error message is:
Unhandled Exception: System.IO.FileNotFoundException: Unable to find the specified file.
   at Vlc.DotNet.Core.Interops.VlcInteropsManager..ctor(DirectoryInfo dynamicLinkLibrariesPath)
   at Vlc.DotNet.Core.Interops.VlcManager.GetInstance(DirectoryInfo dynamicLinkLibrariesPath)
   at Vlc.DotNet.Core.VlcMediaPlayer..ctor(DirectoryInfo vlcLibDirectory)
   at Recorder.Program.Main(String[] args) in /media/wilder/HDD-DADOS/estudo/Ecad/RadioOnlineRecorder/Recorder/Program.cs:line 20

`// Default installation path of VideoLAN.LibVLC.Windows
            //var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));
            var libDirectory =  new DirectoryInfo("/usr/lib/x86_64-linux-gnu");
`   

I've changed  the original libDirectory variable from Windows configuration to the Linux configuration according with command whereis libvlc. The error ocurred when I try to run VlcMediaPlayer:

`using (var mediaPlayer = new Vlc.DotNet.Core.VlcMediaPlayer(libDirectory))`

I confirm that my issue doesn't happen in VLC itself neither on Windows environment.

Thanks in advance!

**Comment by jeremyVignelles** [comment]
Linux is not supported on Vlc.DotNet. I did try to implement it a long time ago, but nothing has been finished yet.

Please use LibVLCSharp instead

**Comment by wilderlopes83** [comment]
Dear JeremyVignelles,

Thank you for your fast answer!
