### ISSUE TITLE
VLC Streaming Problem

### ISSUE THREAD

**Issue by Shirinrahman** [ZeBobo5/Vlc.DotNet#536]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : v2.2.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : v3.0.6 . NuGet Package
- **.net version** : v4.0
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10

Hi,
I am writing a software that could just show me the three different CCTV feeds simultaneously, let me click on one of them. Selected single-camera will play at desired position on same Window and all-three-cameras view and work reliably. All should be work on one single Window( three different camera feeds and clicked camera feed) . I am using RTSP Protocol and VLC will play the IP cameras feeds.
The problem which I faced was, I can't stream more than two feeds at a time . If I tried to play it will stop the videos and it will looks like a still image. Is there any way to play all videos simultaneously on same window??
Thanks,
SR

**Comment by jeremyVignelles** [comment]
Please use the Vlc.DotNet 3.0 -develop version, a lot of work has been done to make it possible to play several videos at the same time.

**Comment by Shirinrahman** [comment]
Thanks. I have installed Vlc.DotNet 3.0.0 -develop296 .But, still It shows like still Image

**Comment by jeremyVignelles** [comment]
Why not -develop345? 296 is 8 month old.

Do the app freeze?

**Comment by Shirinrahman** [comment]
ok..I have updated to develop345. But, still shows still image and not playing.

**Comment by jeremyVignelles** [comment]
Are you using Vlc.DotNet.WinForms or .Wpf?

Can you share a sample code?

Did you try the "MultiplePlayers" sample from this project?

**Comment by Shirinrahman** [comment]
I have tried to run from your sample code. My modified code are below,

namespace Samples.Wpf.Minimal.UsingWinForms
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            var control1 = new VlcControl();
            var control2 = new VlcControl();
            var control3 = new VlcControl();

            this.WindowsFormsHost1.Child = control1;
            this.WindowsFormsHost2.Child = control2;
            this.WindowsFormsHost3.Child = control3;

            var currentAssembly = Assembly.GetEntryAssembly();
            var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
            // Default installation path of VideoLAN.LibVLC.Windows
            var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            control1.BeginInit();
            control1.VlcLibDirectory = libDirectory;
            control1.EndInit();

            control2.BeginInit();
            control2.VlcLibDirectory = libDirectory;
            control2.EndInit();

            control3.BeginInit();
            control3.VlcLibDirectory = libDirectory;
            control3.EndInit();

            control1.Play(new Uri("rtsp://user:pass@192.168.2.160:8557"));           
            control2.Play(new Uri("rtsp://user:pass@192.168.2.160:8557"));
            control3.Play(new Uri("rtsp://user:pass@192.168.2.160:8557"));       
        }
    }
}

**Comment by Shirinrahman** [comment]
wpf

**Comment by jeremyVignelles** [comment]
WPF using winForms and Vlc.DotNet.Wpf are two different things. The code above uses the WinForms control. Can you try with the MultiplePlayers project instead?

Do you have any logs ?

**Comment by Shirinrahman** [comment]
MultiplePlayer using Windows Forms App??
Sorry I don't have any logs

**Comment by jeremyVignelles** [comment]
Yes, this one.

For the logs, you can try https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#how-to-debug or to pass `-vv` as a media player option.

**Comment by jeremyVignelles** [comment]
Any news about this? Closing for now, please reopen if more help is needed.
