### ISSUE TITLE
vlccontrol.length

### ISSUE THREAD

**Issue by bichumon** [ZeBobo5/Vlc.DotNet#538]
vlc.control.length gives zero for all fileformat otherthan .mp4 files

**Comment by mfkl** [comment]
Share your media file please

**Comment by bichumon** [comment]
it is a ffmpeg generated ts file
ffmpeg command:-
-y -re -i F://media//P.mp4 -vcodec libx264 -acodec mp2 -b:v 700k -b:a 64k -s 640x480 -ac 1 -g 12 -f segment -segment_time 1800 -strftime 1 F://media//"%d%m%y%H%M%S.TS" -f mpegts -vcodec copy -acodec copy udp://@239.0.0.1:5000?fifo_size=100000

**Comment by bichumon** [comment]
[240319215159.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/3000578/240319215159.zip)

**Comment by jeremyVignelles** [comment]
It gives 0 for the media whose length cannot be computed immediately. Your UDP stream is one of those examples, and this is perfectly normal.

If you need the length, please use another protocol.

**Comment by bichumon** [comment]
Thank you Jeremy. I added a small delay  after media play  event to get the length of the file
