### ISSUE TITLE
How to play video with subtitle

### ISSUE THREAD

**Issue by asimkymk** [ZeBobo5/Vlc.DotNet#543]
I have an issue (pick one) about Vlc.DotNet.

`
so how can i play this video with subtitile on vlc dotnet 
- **Vlc.DotNet version** : v3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : v16.5.1 - x86/x64 - from nuget packages
- **.net version** : v4.7.2
- **Project language** : Vb.Net
- **Project build architecture** : x86
- **Operating system** : Windows 10 64 Bit

I want to play online mkv video file on vlc dotnet with subtitle. first of all i tried to just play video without subtitle and it works without sub butwhen  i want to play with subtitle, i couldnt make it. can anyone help me.
here the codes which are working and not working :
video without subtitle (doesnt work):
`VlcControl1.SetMedia("file:///http://dl20.mihanpix.net/94/series/game.of.throne/s7/Game.Of.Thrones.S07E01.WEB-DL.720p.Tehmovies.me.mkv")`

video without subtitle (works) : 
`VlcControl1.SetMedia("http://dl20.mihanpix.net/94/series/game.of.throne/s7/Game.Of.Thrones.S07E01.WEB-DL.720p.Tehmovies.me.mkv"`

video with subtitle(doesnt work):
`VlcControl1.SetMedia("http://dl20.mihanpix.net/94/series/game.of.throne/s7/Game.Of.Thrones.S07E01.WEB-DL.720p.Tehmovies.me.mkv", "--sub-file=C:/Users/user/Desktop/testsub/Game.of.Thrones.S07E04.720p.HDTV.x264-AVS.srt")`

video with subtitle(doesnt work)(differentway2):
`VlcControl1.SetMedia("file=file:///http://dl20.mihanpix.net/94/series/game.of.throne/s7/Game.Of.Thrones.S07E01.WEB-DL.720p.Tehmovies.me.mkv", "--sub-file=file:///C:/Users/user/Desktop/testsub/Game.of.Thrones.S07E04.720p.HDTV.x264-AVS.srt")`

 I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Use `VlcMediaPlayerOptions` to set the `--` options

**Comment by asimkymk** [comment]
so how can i do it bro? i dont understand. can you explain with more details

**Comment by asimkymk** [comment]
I finally found thanks:
` VlcControl1.SetMedia("http://dl20.mihanpix.net/94/series/game.of.throne/s7/Game.Of.Thrones.S07E01.WEB-DL.720p.Tehmovies.me.mkv", "sub-file=C:\Users\user\Desktop\Game.of.Thrones.S07E04.720p.HDTV.x264-AVS.srt")
`

**Comment by tigros** [comment]
i'm looking to add a subtitle facility to my app, so far the only thing that works is --sub-file=h:\movies\English test.srt the other things like --sub-autodetect-path and --sub-autodetect-fuzzy=1 don't seem to work. maybe just sub-file will be enough but it's strange the others don't work. For example there's sometimes a Subs sub folder with .srt, be nice to load them automatically and let user choose from list instead of open file dialog.  it's lucky sub-file works tho that could sure come in handy!
