### ISSUE TITLE
How To Change Subtitle Character Encoding ?

### ISSUE THREAD

**Issue by codirx** [ZeBobo5/Vlc.DotNet#547]
I have an issue / a question (pick one) about Vlc.DotNet.WPF.

# Generic information

- **Vlc.DotNet version** : 3.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86 from official website setup
- **.net version** : 4.8
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 Pro x64

When I add Turkish subtitle to the video,  characters are problematic. How do I change the subtitle encoding and make it ISO-8859-9 ?

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
The easiest would probably be to convert your subtitle file to UTF-8?
Can VLC adjust the encoding of your subtitles? What kind of subtitles is that?

**Comment by mfkl** [comment]
Add this option`--subsdec-encoding=ISO-8859-9`

**Comment by codirx** [comment]
> The easiest would probably be to convert your subtitle file to UTF-8?
> Can VLC adjust the encoding of your subtitles? What kind of subtitles is that?

I fixed it it wasn't UTF-8. You can close
