### ISSUE TITLE
video on demand (VoD) question

### ISSUE THREAD

**Issue by Dimigergo** [ZeBobo5/Vlc.DotNet#548]
Hello! 
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.6
- **Vlc.DotNet project used** : Core
- **libvlc version** : 3.0.0 x64 VS 2017 nuget
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary

Is there any way to create RTSP stream with video on demand (VoD) option? 
When I use the VLM manager started from command batch the config file contains:

`new udpstream_ch1 vod enabled`
`setup udpstream_ch1 input "c:\Utils\VLC\sample_1080p.mp4"`
`setup udpstream_ch1 option file-caching=2000`

The VoD documentation of the new VLC lib is very poor (almost nothing) every example uses the VLM manager. 

Thanks for the response!

**Comment by mfkl** [comment]
I'd advise against using VLM if possible as it's been removed in VLC 4 (https://github.com/videolan/vlc/commit/3de6692cea140be7c14eda74b34f8f076127c98e#diff-742117824b2c0c4bf8a44487d0f7056e)

**Comment by Dimigergo** [comment]
Ohh. In this case I can't create VoD stream in the future with the VLC Api? :(

**Comment by mfkl** [comment]
with libvlc no. With vlc.exe probably still
