### ISSUE TITLE
set MediaPlayer.Rate=-2 didn't work

### ISSUE THREAD

**Issue by toto0668** [ZeBobo5/Vlc.DotNet#549]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (x64) + nuget
- **.net version** : (4.5.2)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows ...) (x64)

# Summary

set MediaPlayer.Rate=-2 didn't work

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by mfkl** [comment]
Logs? Code? 
Can't help you much with a one sentence report.

**Comment by jeremyVignelles** [comment]
Also, please tell us what kind of stream are you trying to play. Some streams can't be played backwards. Did you try in VLC?

**Comment by toto0668** [comment]
> Also, please tell us what kind of stream are you trying to play. Some streams can't be played backwards. Did you try in VLC?
here is my code:
` public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            var vlcLibDirectory = new DirectoryInfo(System.IO.Path.Combine(@"D:\Test\WpfApp1\packages\VideoLAN.LibVLC.Windows.3.0.6\build", IntPtr.Size == 4 ? "x86" : "x64"));
            var options = new string[]
            {
                
            };
            this.video.SourceProvider.CreatePlayer(vlcLibDirectory, options);
        }

        private void Play(object sender, RoutedEventArgs e)
        {
            FileInfo fileInfo = new FileInfo(@"D:\2.mpg");
            video.SourceProvider.MediaPlayer.Play(fileInfo, null);
        }

        private void Stop(object sender, RoutedEventArgs e)
        {
            ThreadPool.QueueUserWorkItem(_ => video.SourceProvider.MediaPlayer.Stop());
        }

        private void Pause(object sender, RoutedEventArgs e)
        {
            video.SourceProvider.MediaPlayer.Pause();
        }

        private float _rate = 0;
        private void Forward(object sender, RoutedEventArgs e)
        {
            _rate++;
            video.SourceProvider.MediaPlayer.Rate = _rate;// can work
        }

        private void Backward(object sender, RoutedEventArgs e)
        {
            _rate--;
            video.SourceProvider.MediaPlayer.Rate = _rate;//can't work
        }
    }`
xmal:
`    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition></RowDefinition>
            <RowDefinition Height="auto"></RowDefinition>
        </Grid.RowDefinitions>
        <vlc:VlcControl x:Name="video" Grid.Row="0"></vlc:VlcControl>
        <StackPanel Grid.Row="1" Orientation="Horizontal" Margin="10">
            <Button Content="play" Margin="10,0" Click="Play"></Button>
            <Button Content="stop" Margin="10,0" Click="Stop"></Button>
            <Button Content="pause" Margin="10,0" Click="Pause"></Button>
            <Button Content="forward" Margin="10,0" Click="Forward"></Button>
            <Button Content="backward" Margin="10,0" Click="Backward"></Button>
        </StackPanel>
    </Grid>`

**Comment by mfkl** [comment]
negative rates seem ignored. What you're probably looking for is a rate between 0 and 1 (to slow down playback).

**Comment by jeremyVignelles** [comment]
Closing as this seems like a libvlc issue and not a Vlc.DotNet issue.
