### ISSUE TITLE
video playing less than its actual duration

### ISSUE THREAD

**Issue by SukheshMajalkar** [ZeBobo5/Vlc.DotNet#550]
HI, I am using Vlc.DotNet.Form Version 3.0.0 to play a video,
I'm facing an issue of ending video 500 to 800 millisec  earlier than its actual duration.

it plays fine when i play it using actual vlc player 3.0.0
it is also playing fine in older version of  Vlc.DotNet.Form 2014.10.15.0

**Comment by jeremyVignelles** [comment]
Can you try with VLC 3.0.7? What kind of video is that?

Please fill the template, you don't say which version of libvlc you are using.

It's probably not a Vlc.DotNet issue, but rather a VLC one.

**Comment by SukheshMajalkar** [comment]
I tried using lbvlc version 3.0.0 and 3.0.6 the issue persists with both the version.
video i was using was an mp4 file.
its exact duration in 50 sec 130 millisec.

but it is playback duration with Vlc.DotNet varies from 49 sec 354 millisec to 49 sec 600 millisec.

**Comment by jeremyVignelles** [comment]
How do you notice that there is such a gap? How do you measure things?

**Comment by SukheshMajalkar** [comment]
I noticed this gap because last word from the video was not audible completely.
so to check this i printed current position of the video in EndReached Event.

   private void EndReached(object sender, Vlc.DotNet.Core.VlcMediaPlayerEndReachedEventArgs e)
        {
            var v = this.Time;
            log.Info("***************************Ivlc - IVlc_EndReached - position - " + v);
        }

which gave me following readings for same video each time i played it
***************************Ivlc - IVlc_EndReached - position - 49600
***************************Ivlc - IVlc_EndReached - position - 49602
***************************Ivlc - IVlc_EndReached - position - 49601
***************************Ivlc - IVlc_EndReached - position - 49601
***************************Ivlc - IVlc_EndReached - position - 49601
***************************Ivlc - IVlc_EndReached - position - 49602
***************************Ivlc - IVlc_EndReached - position - 49352
***************************Ivlc - IVlc_EndReached - position - 49354

**Comment by SukheshMajalkar** [comment]
I thought the issue is with vlc player so i played same video with vlc player version 3.0.6 but played completely

**Comment by SukheshMajalkar** [comment]
but not with Vlc.DotNet

**Comment by jeremyVignelles** [comment]
As you might have noticed if you listen to the TimeChanged event, updates are sent very infrequently. This is because your event handler is called on the VLC thread, and your code slows down the video playing. 

They chose to update the value frequently enough for the UI (a few times per second), but the value is not meant to be reliable enough for a clock. When you see the EndReached event, what you're getting is the last update of the Time property, which does not mean the end of the video.
I don't think you can compare that to any value in VLC, since the seek bar shows only the seconds (but trust me, there's the same issue)

If you're interestend in the length of the video, I'd suggest that you use `Length` instead.

**Comment by jeremyVignelles** [comment]
Closing. Feel free to reopen if your issue is not resolved.

**Comment by SukheshMajalkar** [comment]
Hi, still i face the same issue of cut the last portion of video 500ms

**Comment by SukheshMajalkar** [comment]
This is my code snipprt:
  public MainWindow()
        {
            InitializeComponent();
            var currentAssembly = Assembly.GetEntryAssembly();
            var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
            // Default installation path of VideoLAN.LibVLC.Windows
            var libDirectory = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory + @"LibVlc\");

            this.sourceProvider = new VlcVideoSourceProvider(this.Dispatcher);

            this.sourceProvider.CreatePlayer(libDirectory/* pass your player parameters here */);
            this.sourceProvider.MediaPlayer.Play(new FileInfo(@"D:\7944.mp4"));

            this.Video.SetBinding(System.Windows.Controls.Image.SourceProperty,
                new Binding(nameof(VlcVideoSourceProvider.VideoSource)) { Source = sourceProvider });
        }

**Comment by SukheshMajalkar** [comment]
Kindly help me about this.

**Comment by jeremyVignelles** [comment]
How do you notice that 500 ms are missing? Do you have something special at the end of the video that is not happening?

**Comment by SukheshMajalkar** [comment]
yes, after playing video i was listening the audio  then last word of video get cut

**Comment by SukheshMajalkar** [comment]
it is happening at all time not only once.

**Comment by jeremyVignelles** [comment]
And you say that it doesn't happen in VLC,. right? can you share the file?

**Comment by SukheshMajalkar** [comment]
Thanks, issue got resolved after replace latest plugins of version 3.0.7
