### ISSUE TITLE
Is calling Mute(bool) instead of ToggleMute() possible?

### ISSUE THREAD

**Issue by morl0048** [ZeBobo5/Vlc.DotNet#551]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 and x64 from NuGet 
- **.net version** : .Net Framework 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary

I remembered I saw this issue with the pause functionality some days ago:
https://github.com/ZeBobo5/Vlc.DotNet/issues/454

I was wondering if it would be possible to add a function to toggle mute without having to keep a bool on our side? Kinda like in the title of the issue...

Anyways, thanks allot for your hard work on this awesome project! 10/10 would recommend! :P

**Comment by jeremyVignelles** [comment]
Hi,
Thanks for your interest 😄 .
I've read quickly through the repo and it turns out it's already possible, though the naming is probably unclear.

Instead of `Audio.ToggleMute()`, you can just call `Audio.IsMute = true;`
