### ISSUE TITLE
sout=#duplicate = unable to mute

### ISSUE THREAD

**Issue by morl0048** [ZeBobo5/Vlc.DotNet#552]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 and x64 from NuGet
- **.net version** : .Net Core 2.1 or .Net Framework 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary

When I play a rtsp stream with the following options ... :

```
string[] options = {
":network - caching = 100",
":sout=#duplicate{dst=std{access=file,mux=mp4,dst='.\\myfile.mp4'},dst=display}"
};

vlcRecorder.Play(RtspStreamUrl, options);
```

... I can't mute my `vlcRecorder`.

I tried changing its volume to zero but I can still hear my stream playing.

I tried using the `SetMute(true)` function, but it mutes all my other viewers.

This recorder doesn't need to show the stream, it's visibility is set to false. BUT it would be nice to be able to see it. `,dst=display`

The problems seems to be comming from the `:sout=#duplicate.....` line, because when I comment it, I can mute my recorder without problem, but it won't record anymore (duh :P ).

What option could I use to be able to mute my `VlcControl` and still be able to record? 

- [ Can't test? ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
The fact that the mute option mutes all sounds pretty familiar (no pun intended).

Can you try to set `--aout=directsound` in the MediaPlayer initialization? See #524

**Comment by morl0048** [comment]
I added the `--aout=directsound` in the form designer in my `VlcMediaPlayerOptions` string array[] and now I can mute using `VlcControl.Audio.Volume = 0`. Thanks (:

I did see this post earlier, but I didn't read it completely.... ^^'

Knowing that the `--` options need to be set before the end of the MediaPlayer initialization and that the `:` options need to be set at another time was new for me.

Edit answer:
I just saw this typo in my code thanks to you (the spaces). That's why I had a different delay between my recorder and player haha!

**Comment by morl0048** [comment]
I think that calling the `SetMute(true)` function goes in the windows volume mixer and mutes the whole application. That's why it's better to set the volume to zero.
![image](https://user-images.githubusercontent.com/36162651/59710520-17837c80-91d7-11e9-82d0-fbd0cc6d6654.png)

**Comment by jeremyVignelles** [comment]
From what I understand from VLC, the default audio output plugin is "mmdevice" and uses that global mute behavior for windows. `directsound` should behave differently and be able to mute independently. Can you share verbose logs to see which audio output module is in use?

you can also try `:aout=directsound`, but I'm not sure if that will work.

**Comment by morl0048** [comment]
I changed the code I used to test this and now I can't reproduce the mute that mutes the whole application... I tried to change it back but everything works like a charm...

Anyways, just to be sure, when you talk about verbose logs, am I supposed to add a `-vvv` option to my player?

I will try to make my app have the same behavior as before and come back with logs asap (:

**Comment by jeremyVignelles** [comment]
Anyways, just to be sure, when you talk about verbose logs, am I supposed to add a --vvv option to my player? How do I get these logs?

Yes, please have a look at this : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#how-to-debug.

When you said that `SetMute(true)` muted everything with directsound, I supposed that the plugin was not correctly selected, hence asking for logs. If you're telling me that `SetMute(true)` is applied per-player, that's the behavior I was expecting.

Can we close this now?
