### ISSUE TITLE
Taking snapshot Vlc.DotNet.Form

### ISSUE THREAD

**Issue by lukmanfarizi** [ZeBobo5/Vlc.DotNet#553]
Hi, I have an issue I am using Vlc.DotNet.Form Version 3.0.0 to streaming video from cctv via rtsp connection and taking snapshot with hight and width. but the result is not same with hight and width that I am set.

`vlcControl.TakeSnapshot(outputFile, 600, 400);` but the result is the same with video resolution (1920 x 1080)

Thanks.

**Comment by jeremyVignelles** [comment]
Please use the issue template

**Comment by lukmanfarizi** [comment]
sorry my bad,

- **Vlc.DotNet version** : 3.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (x86) + nuget
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows) (x64)

# Summary
Streaming video from cctv via rtsp connection and taking snapshot with hight and width. but the image result is not same with hight and width that I am set.

vlcControl.TakeSnapshot(outputFile, 600, 400); but the result is the same with video resolution (1920 x 1080)

**Comment by lukmanfarizi** [comment]
sorry my bad,

- **Vlc.DotNet version** : 3.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (x86) + nuget
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows) (x64)

# Summary
Streaming video from cctv via rtsp connection and taking snapshot with hight and width. but the image result is not same with hight and width that I am set.

vlcControl.TakeSnapshot(outputFile, 600, 400); but the result is the same with video resolution (1920 x 1080)

**Comment by jeremyVignelles** [comment]
Thanks for reporting, there was indeed a big mistake in the WinForms control.

I'll be publishing a beta version in a moment. In the meantime, you can use

```cs
vlcControl.TakeSnapshot(new FileInfo(outputFile), 600, 400);
```
