### ISSUE TITLE
Blank Screen When Playing a Video

### ISSUE THREAD

**Issue by sutoornan** [ZeBobo5/Vlc.DotNet#555]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (Vlc.DotNet.Forms.3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (Please fill) (x86) + how did you get it? Nuget
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows 7) (x86)

# Summary

(blank screen when running. 
[Blank Screen- Code.txt](https://github.com/ZeBobo5/Vlc.DotNet/files/3309080/Blank.Screen-.Code.txt)
)

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by sutoornan** [comment]
Please Help. I have a Blank screen when trying to play a video (Windows form )

================================
Form1.Designer.cs code;
================================
namespace WindowsFormsApp3
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.vlcControl1 = new Vlc.DotNet.Forms.VlcControl();
            //((System.ComponentModel.ISupportInitialize)(this.vlcControl1)).BeginInit();
            this.SuspendLayout();
            // 
            // vlcControl1
            // 
            this.vlcControl1.BackColor = System.Drawing.Color.Black;
            this.vlcControl1.Location = new System.Drawing.Point(0, 0);
            this.vlcControl1.Name = "vlcControl1";
            this.vlcControl1.Size = new System.Drawing.Size(285, 262);
            this.vlcControl1.Spu = -1;
            this.vlcControl1.TabIndex = 0;
            this.vlcControl1.Text = "vlcControl1";
            this.vlcControl1.VlcLibDirectory = ((System.IO.DirectoryInfo)(resources.GetObject("vlcControl1.VlcLibDirectory")));
            this.vlcControl1.VlcMediaplayerOptions = new[]
{
    "-vv",
    "--file-caching=3500",
    "--network-caching=3500"
};
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 262);
            

            vlcControl1.Click += (object sender, System.EventArgs e) => { };
            this.Controls.Add(this.vlcControl1);
            this.Name = "Form1";
            this.Text = "Form1";
            //((System.ComponentModel.ISupportInitialize)(this.vlcControl1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Vlc.DotNet.Forms.VlcControl vlcControl1;
        
    }
}


================================
Program.cs code:
================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp3
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }
    }
}
==============================
Form1.cs code:
==============================
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp3
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            //vlcControl1.Play("https://cliptionary.org/hd1/temp/15618_1.mp4");
            vlcControl1.Play(new Uri("https://cliptionary.org/hd1/temp/15618_1.mp4"));
        }
    }
}

Thanks.

**Comment by jeremyVignelles** [comment]
As said in the other thread, please fill the issue template, and paste your code properly with the code block syntax

**Comment by sutoornan** [comment]
Please see Attached.

**Comment by jeremyVignelles** [comment]
Thanks,
Can you play your video with VLC itself?

Do you have some logs in your app?

**Comment by sutoornan** [comment]
I did not try playing the video it in VLC.

Sorry, I don't have any log files

**Comment by jeremyVignelles** [comment]
Please try. If that doesn't work, it's not an issue with Vlc.DotNet. Look at the message window in VLC to see what's happening

**Comment by sutoornan** [comment]
I don't have the VLC player. Where should I download it from?

**Comment by sutoornan** [comment]
The video runs fine when using the  VLC Player.

**Comment by jeremyVignelles** [comment]
I'm sorry, but copy/pasting what you said on github in a .txt file and sending it again on github is not a good way to report an issue.

Either you have a relevant code (like 10 lines of code) that I can copy/paste into a sample project (tell me which), or you have a demo git repository on github that I can download and run directly.

Please also attach logs, see this page : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#how-to-debug

**Comment by afshin-blue** [comment]
I had same issue, on some PC it is working and on other it does not works,after enabling log i saw it is looking for  plugins.dat file

**main debug: loading plugins cache file** E:\Visual Studio 2019\VlcDotNetWpfForm\VlcDotNetWpfForm\bin\Debug\libvlc\win-x86\plugins\plugins.dat
main warning: **cannot read** E:\Visual Studio 2019\VlcDotNetWpfForm\VlcDotNetWpfForm\bin\Debug\libvlc\win-x86\plugins\plugins.dat: **No such file or directory**
main debug: recursively browsing `E:\Visual Studio 2019\VlcDotNetWpfForm\VlcDotNetWpfForm\bin\Debug\libvlc\win-x86\plugins'

**Then it is also looking for same file in Visioforge SDK installed location**

main debug: loading plugins cache file C:\Program Files (x86)\VisioForge\VisioForge .Net SDKs VLC Redist\plugins\\plugins.dat
main warning: This doesn't look like a valid plugins cache
main debug: recursively browsing `**C:\Program Files (x86)\VisioForge\VisioForge .Net SDKs VLC Redist\plugins\'**

I just rename VisoForge folder then it is start working no Black screen any more.
I don't know from where this VisioForge .Net SDKs VLC Redist has been installed and it is not in add and remove section to uninstall. 
also don't know why VLC looking for VisoForge.
Maybe if package contain this file plugins.dat it won't looking for it.
I hope it can solve others that have Black screen with Audio problem.

**Comment by jeremyVignelles** [comment]
@afshin-blue : Do you have an environment variable on your machine that is named `VLC_PLUGIN_PATH` and that point to that VisioForge .Net SDK? That would cause conflicts...

**Comment by afshin-blue** [comment]
@jeremyVignelles i checked variable path on system and you were right it was there. i believe  visio.forge sdk  uninstaller did not removed the path.thanks
