### ISSUE TITLE
How to enable telnet control to streaming server?

### ISSUE THREAD

**Issue by somk3zzz** [ZeBobo5/Vlc.DotNet#557]
# Generic information
- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (Core)
- **libvlc version** : (3.0.7.1) (x64)
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10) (x64)
# Summary
How to enable telnet control?
Here I bring the following lines, but nothing happens. Help

```
var options = new string[]
            {
                "-I telnet --telnet-port=4212 --telnet-password=123"
            };
using (var mediaPlayer = new Vlc.DotNet.Core.VlcMediaPlayer(libDirectory, options))
```

Im using this sample [https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Samples/Samples.Core.Streaming/Program.cs](url)

**Comment by jeremyVignelles** [comment]
Hello,
You are using the options in the wrong way. You must split your string by spaces, this is why you have a `string[]`

Can you try with this?
`"-I", "telnet",...`

**Comment by somk3zzz** [comment]
> Здравствуйте! 
> Вы неправильно используете параметры. Вы должны разделить вашу строку на пробелы, поэтому у вас есть`string[]`
> 
> Вы можете попробовать это?
> `"-I", "telnet",...`

var options = new string[]
            {
                "-I", "telnet", "--telnet-port", "4212", "--telnet-password", "123"
            };
should it look like this?

**Comment by jeremyVignelles** [comment]
looks better

**Comment by somk3zzz** [comment]
> looks better
tnx, im trying latter

**Comment by somk3zzz** [comment]
> looks better


Here is an example of a work program with management. There is a contact!
```
using System;
using System.IO;
using System.Reflection;
using Vlc.DotNet.Core;

namespace TestSream
{
    class Program
    {
        static void Main()
        {
            var options = new string[]
            {
                "--control",
                "telnet",
                "--telnet-port",
                "4212",
                "--telnet-password",
                "123"
            };

            var currentDirectory = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            // Default installation path of VideoLAN.LibVLC.Windows
            var libDirectory =
            new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));
            var mediaPlayer = new VlcMediaPlayer(libDirectory, options);
            mediaPlayer.Play();
            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }
    }
}
```

**Comment by jeremyVignelles** [comment]
If it works, I'm closing this 😉

**Comment by somk3zzz** [comment]
> If it works, I'm closing this 😉

Ok) tnx so much)
