### ISSUE TITLE
toolbar control

### ISSUE THREAD

**Issue by pandaliveTV** [ZeBobo5/Vlc.DotNet#558]
Vlc.Dotnet no toolbar control   

how add toolbar control  and Fullscreen vlc.Dotnet ?
 #vb.net

**Comment by jeremyVignelles** [comment]
What do you call "toolbar control"? you need to make your own control and call Vlc.DotNet features.
For fullscreen, you can draw the player over a fullscreen WinForms window.

**Comment by pandaliveTV** [comment]
The volume control bar and stop appears when you move the mouse  How Add?

**Comment by jeremyVignelles** [comment]
You have to write them yourself.
Vlc.DotNet only provides the video player, not the controls.

**Comment by pandaliveTV** [comment]
I am a novice in programming. Is there an explanation or no

**Comment by pandaliveTV** [comment]
After the screen is magnified, the color appears below
https: ///2.top4top.net/p_1266e8nfk1.png

**Comment by jeremyVignelles** [comment]
There are no such explanations on this repository.
You can start with the samples in the repository. You can have a look at the advanced winforms sample, it has buttons, but a lot of things are left for you to have a beatiful application.

I'm sorry, but I am volunteer on this project and I can't afford to spend too much time to explain you how to create WPF or WinForms apps. You will find a lot of tutorials on the internet.
