### ISSUE TITLE
Does VLC need to be installed to use Vlc.DotNet?

### ISSUE THREAD

**Issue by yetmorestuff** [ZeBobo5/Vlc.DotNet#56]
Hi,

I'm new to Vlc.DotNet - does VLC need to be installed to be able to build and run an app that uses Vlc.DotNet?

If VLC is required / installed, is a specific version needed?

If it isn't required, will there be conflicts if it is!?

I currently have vlc-2.1.5-win32 installed and have been unable to get my WPF app (.NET 4.0) to play any rtsp network video streams using the Vlc.DotNet.Wpf 2.1.62 NuGet package - see my comment on issue https://github.com/ZeBobo5/Vlc.DotNet/issues/49.

Many thanks.

**Comment by RafalNiewinski** [comment]
You only need a VLC libraries. You can find them in this repository in "lib" directory. You should define your library path in the event like in the sample application:

```c#
        public MainWindow()
        {
            InitializeComponent();
            myControl.MediaPlayer.VlcLibDirectoryNeeded += OnVlcControlNeedsLibDirectory;
        }

        private void OnVlcControlNeedsLibDirectory(object sender, Forms.VlcLibDirectoryNeededEventArgs e)
        {
            var currentAssembly = Assembly.GetEntryAssembly();
            var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
            if (currentDirectory == null)
                return;
            if (AssemblyName.GetAssemblyName(currentAssembly.Location).ProcessorArchitecture == ProcessorArchitecture.X86)
                e.VlcLibDirectory = new DirectoryInfo(Path.Combine(currentDirectory, @"..\..\..\lib\x86\"));
            else
                e.VlcLibDirectory = new DirectoryInfo(Path.Combine(currentDirectory, @"..\..\..\lib\x64\"));
        }
```

**Comment by yetmorestuff** [comment]
Thanks @RafalNiewinski.

Still can't get working, so a bit more detail...

My app (WPF, .NET 4.0) was created in Visual Studio 2010. Here is what I have done so far:

1) Within VS, I installed the NuGet Vlc.DotNet.Wpf 2.1.62 package (published 04/03/2015), which in turn installed the dependancies Vlc.DotNet.Core, Vlc.DotNet.Core.Interops and Vlc.DotNet.Forms. This gave the System.IO.DirectoryNotFound as described earlier when attempting to play an rtsp stream.

2) I downloaded libvlc.dll and libvlccore.dll from the repository on this site (ZeBobo5/Vlc.DotNet/lib/x86) into a Lib directory in my project.

3) Edited OnVlcControlNeedsLibDirectory with the paths to the Lib directory, as suggested.

4) Set 'Build Action' for each to 'Content' and 'Copy to Output Directory' as 'Copy always'.

Now when attempting to play any rtsp network video streams I get "System.AccessViolationException - Attempted to read or write protected memory. This is often an indication that other memory is corrupt.". Same if I attempt to play a local AVI.

Am I doing something else wrong?

Why is it not possible to simply install the Vlc.DotNet.Wpf NuGet package from with VS? Is there some other package(s) I need?

Is the package I install from within VS different in some way to that which is in https://github.com/ZeBobo5/Vlc.DotNet?

Thanks in advance,

**Comment by yetmorestuff** [comment]
Thanks @RafalNiewinski! Got it working now - looks like it not only needs the vlc libraries but the entire Lib directory structure, including the plugins directory, (otherwise you get a "System.AccessViolationException - Attempted to read or write protected memory. This is often an indication that other memory is corrupt.").
