### ISSUE TITLE
Unhandled exception in Vlc.DotNet.Core.Interops.VlcManager.GetMediaTracks

### ISSUE THREAD

**Issue by jurek993** [ZeBobo5/Vlc.DotNet#560]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (Please fill) (x86) + VideoLANVLC.Windows nuget
- **.net version** : 4.7.1
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows) (x86/x64)

# Summary

Sometimes when I try play video I vlc crash with unhandled ex. 

Information from event log:

 `System.ArgumentException
   in Vlc.DotNet.Core.Interops.VlcManager.GetMediaTracks(Vlc.DotNet.Core.Interops.VlcMediaInstance)
   in Vlc.DotNet.Core.VlcMedia.get_Tracks()
   in Vlc.DotNet.Wpf.VlcVideoSourceProvider.VideoFormat(IntPtr ByRef, IntPtr, UInt32 ByRef, UInt32 ByRef, UInt32 ByRef, UInt32 ByRef)`

Any sugestion?

**Comment by jeremyVignelles** [comment]
Can you share more info about the media you're trying to play and/or a source code reproducing the issue? does the issue happen with the WPF sample from this repository?

**Comment by jeremyVignelles** [comment]
Closing for now, please reopen with more info.
