### ISSUE TITLE
How to create video file from bitmaps in memory?

### ISSUE THREAD

**Issue by daveMueller** [ZeBobo5/Vlc.DotNet#565]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.7.1 + VideoLAN.LibVLC.Windows from nuget package
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows x64

# Summary

I have bitmaps in my memory and want to create a video with them using Vlc.DotNet. My first attempt is to create a ```VLCMedia``` object that was created by ```VlcMediaPlayer.SetMedia(Stream stream, params string[] options)``` and pass the ```BitmapSource``` as ```MemoryStream```.

```
_recorderStream = new MemoryStream();

var mediaPlayer = new VlcMediaPlayer(_libDirectory);
mediaPlayer.SetMedia(_recorderStream, ":sout=#file{dst='E:/video.mpg'}");

mediaPlayer.Play();

while (_isRecording)
{
	Dispatcher.Invoke(() =>
	{
		var encoder = new BmpBitmapEncoder();
		encoder.Frames.Add(BitmapFrame.Create((BitmapSource) VideoSource.Clone()));
		encoder.Save(_recorderStream);
	});
}
_recorderStream.Close();
```

A video file is created and data is written to it, but I can't see any picture when I play it.
Any idea what I'm doing wrong or how I can improve my attempt?

**Comment by jeremyVignelles** [comment]
As far as I know, there is no API for that, and I'm not sure that VLC can play a bunch of bmp pictures as a video. However, the format you're suggesting is very close to the MJPEG format. Can you try to encode your pictures as JPEG? I'm not really sure about how VLC would play that though...

**Comment by jeremyVignelles** [comment]
Closing since an answer has been provided. Feel free to reopen if needed, I'll reply.

**Comment by daveMueller** [comment]
Yes sorry, thanks for closing.
