### ISSUE TITLE
Google VP9 Encoding / libvlc 4

### ISSUE THREAD

**Issue by AEAEAEAE4343** [ZeBobo5/Vlc.DotNet#566]
# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.0.0 x86 nuget
- **.NET version** : .NET Framework 4 Client Profile
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 Pro Insider Preview Build 18936 x64

# Summary
I am trying to create an application that basically serves Youtube videos (just as a challenge to increase my coding skills). This ATM works really well except there is one issue. If a VP9 encoded video is fetched (which happens a lot, because internal Youtube rendering is mostly VP9) VLC rendering completely bugs out. The image is divided in 2 or 4 vertical bars with big gray blocks as seen in image 1.  Key frames are rendered correctly though as seen in image 2. Happens on some computers only. Happens with some VP9 files only. This is an ancient bug with VLC though it has been fixed in the VLC 4 nightly builds. My question basically is: Are there any plans to support libvlc 4.0.0?

**Image 1:**
![Image 1](https://user-images.githubusercontent.com/34800109/61494116-9bd34600-a9b5-11e9-98d8-d9e25e22b6cd.png)
**Image 2:**
![Image 2](https://user-images.githubusercontent.com/34800109/61494122-a1309080-a9b5-11e9-849a-0ebf3e8be502.png)
**NOTE:** I am in no way saying that the developers of Vlc.DotNet should fix this problem. I'm just documenting this and asking if the newer versions of VLC will be supported.

- [x] I confirm that my issue **DOES** happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
I don't know if there are plans for backporting the fix you mentioned in VLC 3. That would be the most straightforward for fixing that with Vlc.DotNet.

libvlc 4 support has not started yet in Vlc.DotNet. It is tracked by #545  . It may or may not be implemented in a future Vlc.DotNet release depending on my free time and community interest.

However, support for libvlc 4 is being implemented in LibVLCSharp, maybe you could give it a try?
