### ISSUE TITLE
Any VlcMediaPlayer option tag for not showing player but still play?

### ISSUE THREAD

**Issue by morl0048** [ZeBobo5/Vlc.DotNet#569]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : Core
- **libvlc version** : x86 and x64 from NuGet
- **.net version** : .Net Core 2.1 or .Net Framework 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary
I would like to know if there is any flag I could pass to my `VlcMediaPlayer`'s options to make it play but without showing a viewer.

I'm coding an app to make a window10 machine be able to take snapshots from a 
 rtsp livestream, when a timer ticks/elapses,  without having a player showing the video from this livestream.

My C# project is formless so, I only added the `Vlc.DotNet.Core` and `Vlc.DotNet.Core.Interops` NuGet packages.

Here's what my code looks like:

```
//Verify vlc libs
DirectoryInfo di;

//Get vlc libs
if (IntPtr.Size == 4)
    di = new DirectoryInfo(Path.GetFullPath(@".\libvlc\win-x86\"));
else
    di = new DirectoryInfo(Path.GetFullPath(@".\libvlc\win-x64\"));

if (!di.Exists)
{
    //Find vlc libs folder
    var folderBrowserDialog = new FolderBrowserDialog
    {
        Description = "Select Vlc libraries folder.",
        RootFolder = Environment.SpecialFolder.Desktop,
        ShowNewFolderButton = true
    };
    if (folderBrowserDialog.ShowDialog() == DialogResult.OK)
    {
        di = new DirectoryInfo(folderBrowserDialog.SelectedPath);
    }
}

//Create player
_vlcMediaPlayer = new VlcMediaPlayer(di, new string[] { ":network-caching=100" });

_timSnapRecorder.Interval = _snapshotInterval;
_timSnapRecorder.Elapsed += new System.Timers.ElapsedEventHandler(TimSnapRecorder_Elapsed);
_timSnapRecorder.AutoReset = true;
_timSnapRecorder.Start();

```

I have a timer running in the background and when it ticks/elapses I take a snapshot from my `VlcMediaPlayer`.

```
private void TimSnapRecorder_Elapsed(object sender, EventArgs e)
{
    if (_snapshotRecording)
        _vlcMediaPlayer.TakeSnapshot(new FileInfo(savePath));
    else
        _timSnapRecorder.Stop();
}
```

**Comment by mfkl** [comment]
try `":no-video"` or `"--no-video"`

**Comment by morl0048** [comment]
This flag doesn't seem to work. I still get a window opened named `VLC (Direct3D9 output)`. (same as before)

**Comment by mfkl** [comment]
Can you share your full code in a git repo?

**Comment by morl0048** [comment]
With this flag, I don't get a window, but my `VlcMediaPlayer` can't take snapshots anymore... (Sorry for the confusion)

**Comment by morl0048** [comment]
Here`s a link to a new project i created to help you help me (:

https://github.com/morl0048/streamRecorder

**Comment by morl0048** [comment]
You'll have to change the rtsp link in the Program.cs file

and

you might have to uninstall and reinstall the VideoLAN.LibVLC.Windows NuGet package to make it work.

**Comment by jeremyVignelles** [comment]
How would you hide a TextBox? You can probably use the same way to hide a video player.
However, using a timer to take snapshots is usually the wrong way to solve the problem. You will find many instances of that in the issues in this repo, just look at "snapshot".

I am in vacation right now, so I might not answer quickly to your questions

**Comment by morl0048** [comment]
Thanks for the feedback, I'll keep looking! (:

**Comment by jeremyVignelles** [comment]
Hope you found a solution.

Closing this for now. Feel free to reopen if this is still an issue.
