### ISSUE TITLE
How to play H264 Annex B NALU byte[]?

### ISSUE THREAD

**Issue by a44281071** [ZeBobo5/Vlc.DotNet#570]
I want to display remote android phones screen capture in my WPF application.

The phones Record the screen and encode [H264 Annex B NALU]，then send to me by grpc like `MyScreenCommand(byte[] datas)`.

##### Question 1
I received datas, and write to [NamedPipeServerStream]. And opend a [VlcPlayerProvider] like this: 
``` csharp
    // pipe server
    namedPipeServerStream = new NamedPipeServerStream(pipeId, PipeDirection.Out);
    // pipe client player
    provider.MediaPlayer.Play($@"stream://\\\.\pipe\{pipeId}");
```
Maybe it can't work. Is there any other way?

##### Question 2
vlc player display nothing by [VlcVideoSourceProvider.VideoSource], but it's state is [MediaStates.Playing].

Is It can't play Data Block Beginning with [00 00 00 01 41 e4 40 1e fa 0a 28 c3 2f fd 05..........]?

**Comment by jeremyVignelles** [comment]
Hi,
I am on vacation right now and I can't really check anything from here.
My guess is that you should try to play with VLC CLI itself. Cances are that if you can do that with VLC, you will be able to play with your application.

I think that you will find more accurate answers on vlc forums.

If you manage to find a solution, please post it here 🙂

**Comment by a44281071** [comment]
We can play named pipe by string url `\\.\pipe\pipename`.
See:
[https://stackoverflow.com/a/15226490/3655746](url)

**Comment by jeremyVignelles** [comment]
So you don't have any issue anymore? Can we close this issue?
I really recommend that you ask your question on the VLC forum instead.
