### ISSUE TITLE
How to retrieve libvlc version

### ISSUE THREAD

**Issue by espinosaluis** [ZeBobo5/Vlc.DotNet#573]
Is there a way to read the libvlc version that Vlc.DotNet is using?
I know you can get the current Vlc.DotNet version by calling the method ProductVersion()
and I was wondering if there is something similar with VLC.

I need to know this to be sure our customers are running the latest.

Thanks.

**Comment by jeremyVignelles** [comment]
I'm on my phone, but can you try `player.Manager.VlcVersion` ?

**Comment by espinosaluis** [comment]
Thanks... Sorry for the dumb question, but is there an easy way to retrieve the VlcManager from a Vlc.DotNet.Forms.VlcControl object so I can access to that property?

**Comment by espinosaluis** [comment]
I got it to work by doing this. Hopefully that's the best way!

`string GetVersion()
        {
            String libvlcFolder = Path.GetTempPath() + "libvlc\\win-x64";
            DirectoryInfo di = new DirectoryInfo(libvlcFolder);
            Vlc.DotNet.Core.Interops.VlcManager a = new Vlc.DotNet.Core.Interops.VlcManager(di, null);
            return a.VlcVersion;
        }`

**Comment by jeremyVignelles** [comment]
This was not a dumb question since it has not been documented.
If you already have the control, then you can get the media player from it, and then get the manager and the version as I said

**Comment by espinosaluis** [comment]
Thanks for your reply. My control has been initialized, but still don't see a property called manager.
Is it hidden somewhere else?

**Comment by jeremyVignelles** [comment]
The Manager property is on the media player. Do you have a `VlcMediaPlayer` or `MediaPlayer` property ?

**Comment by espinosaluis** [comment]
That's it! Thanks. I found it here:
Vlc.DotNet.Forms..vlcControl.VlcMediaPlayer.Manager.VlcVersion
