### ISSUE TITLE
Is it possible to display multiple image overlays on the screen?

### ISSUE THREAD

**Issue by espinosaluis** [ZeBobo5/Vlc.DotNet#574]
I know you can do that with one image by modifying the logo property like this:

Vlc.DotNet.Core.ILogoManagement logo= vlcControl1.Video.Logo;
fileName = "c:\\LaserTrac\\head2.bmp";
logo.File = fileName;
logo.Enabled = true;
logo.Opacity=500;

Is it possible to do that with multiple images so they all appear on the screen simultaneously?

Thanks

**Comment by jeremyVignelles** [comment]
I didn't even know this was a thing...
Looking at the documentation of the underlying function, this doesn't seem possible : https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__video.html#gaecd71e68f9e486423390cc6b4b843724

Looking at the logo module, this doesn't really seem possible either : 
https://github.com/videolan/vlc-3.0/blob/master/modules/spu/logo.c

I don't know how you could achieve that. Maybe you can ask videolan directly?

Overlaying the image over the video control would be easier to do I guess...

**Comment by espinosaluis** [comment]
That's too bad. Thanks for your reply and research!
