### ISSUE TITLE
Frame buffering between pause and play while streaming.

### ISSUE THREAD

**Issue by shade-less** [ZeBobo5/Vlc.DotNet#576]
I have an issue / a question (pick one) about Vlc.DotNet.

When the VLC player streaming is paused for some time the application still receives frames and after that "play" is called - player starts from the frame that actually appeared after streaming was paused. Is it possible to continue live stream after pause/play was called without buffering any frames between those commands were called? 

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : Windows x86/x64 (Both are targeted)

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Not as far as I know.
I would probably try to freeze the frame on pause, and let it continue on resume.
Since you're on WPF, I think it would be easy to copy the frame from the image source and use it in the Image tag, and then restore the original imageSource

**Comment by shade-less** [comment]
I think I provided a bit too little information.
What we actually do is that we take a snapshot of the current frame and open image editor with this frame. At this moment window of image editor is static and user interacts with it. There is a possibility to view a live stream at this window and here the problem occures.
As initialization of new VlcControl can take up to 15 seconds on slow computers, we want to pass already initialize VlcControl as argument. When image editor window is opened - we put current live stream on pause.
The problem is that after we restore the live stream - it starts exactly where it was paused and it is no longer "live". Also, computer continues to buffer packets even after stream was paused, but we don't actually need them.
So, we want to continue live stream without initializing new VlcControl. The great plus will be stop buffering, but I think I will figure it out from your previous answer.

The code for pausing and playing is the following:

`       
        public LiveVideoVlcPlayer(IDirectoryInfo vlcLibraryDirectory, string[] options)
        {
            _videoPlayer = new VlcControl();
            _videoPlayer.SourceProvider.CreatePlayer(vlcLibraryDirectory.DirectoryInfo, options);
            _videoPlayer.Background = Brushes.White;
        }

        public void AddToUiChildren(UIElementCollection children)
        {
            if (children.Contains(_videoPlayer))
            {
                return;
            }
            children.Add(_videoPlayer);
        }

        public void Pause()
        {
            _videoPlayer.SourceProvider.MediaPlayer.Pause();
        }

        public void Play(Uri videoSource)
        {
            // https://wiki.videolan.org/Documentation:Streaming_HowTo/Command_Line_Examples/
            _videoPlayer.SourceProvider.MediaPlayer.SetMedia(videoSource);
            _videoPlayer.SourceProvider.MediaPlayer.Play();
        }

        /// <summary>
        ///     Continue paused video.
        /// </summary>
        public void Play()
        {
            _videoPlayer.SourceProvider.MediaPlayer.Play();
        }

        /// <summary>
        ///     Removing the player from a visual thee will pause the video
        /// </summary>
        /// <param name="children"></param>
        public void RemoveFromUiChildren(UIElementCollection children)
        {
            Pause();
            if (!children.Contains(_videoPlayer))
            {
                return;
            }

            children.Remove(_videoPlayer);
        }
`

Thank you for your help!

**Comment by jeremyVignelles** [comment]
Hi,
You can have a look at https://github.com/ZeBobo5/Vlc.DotNet/tree/develop/src/Samples/Samples.Wpf.Image.

In this sample, we're creating a VideoSourceProvider and attach it to a WPF image element.

In your case, I would attach the VideoSource to both your main player and to your "live preview". That way, you don't miss any frame and continue playing with the same media player.

This wouldn't be possible with LibVLCSharp nor with Vlc.DotNet.Forms, but Vlc.DotNet.Wpf offers the flexibility to do that.

**Comment by shade-less** [comment]
> Not as far as I know.
> I would probably try to freeze the frame on pause, and let it continue on resume.
> Since you're on WPF, I think it would be easy to copy the frame from the image source and use it in the Image tag, and then restore the original imageSource

Sorry for wasting your time, but could you specify how exactly can I use the copied image frame in the image tag? I just cannot figure out what is image tag. 

Thanks for your time!

**Comment by jeremyVignelles** [comment]
I'm not really familiar with how ImageSource works, but you have `VlcVideoSourceProvider.VideoSource`, which is an Image that changes several times per second.

I don't know if you can copy it that way, but I would try https://docs.microsoft.com/fr-fr/dotnet/api/system.windows.media.imaging.bitmapsource.clonecurrentvalue?view=netframework-4.8#System_Windows_Media_Imaging_BitmapSource_CloneCurrentValue .
Please tell me how things are going.

**Comment by shade-less** [comment]
> 
> I'm not really familiar with how ImageSource works, but you have `VlcVideoSourceProvider.VideoSource`, which is an Image that changes several times per second.
> 
> I don't know if you can copy it that way, but I would try https://docs.microsoft.com/fr-fr/dotnet/api/system.windows.media.imaging.bitmapsource.clonecurrentvalue?view=netframework-4.8#System_Windows_Media_Imaging_BitmapSource_CloneCurrentValue .
> Please tell me how things are going.

Sorry for long answer, just today were working over the project. I haven't figured out how to clone MediaPlayer and stop its from buffering frames. However, I will continue working on this project and will share the solution if I will figure it out.

In addition to buffering pause I would like to lessen the buffering time and I found that libvlc just ignores the parameters (I used "--network-caching=200") and there is still problem with delay of 5-6 seconds. Should I use "--network-caching=200" or ":network-caching=200"?

**Comment by jeremyVignelles** [comment]
both should be used at different places (: for the media), but since you're pausing, it might well be ignored.

I wouldn't pause the player at all, but you need to find a way to copy the image first.

**Comment by shade-less** [comment]
I found a solution how to continue live-streaming after pause. I used "--network-caching=150" and "--sout-mux-caching=150" options and it helped to pause video and continue live stream. It still buffers all the frames, but it continues live-view streaming with this parameters, not from the place where I paused stream.
