### ISSUE TITLE
UDP/rtsp stream latency inconsistencies with multiple vlc instances

### ISSUE THREAD

**Issue by irootuser** [ZeBobo5/Vlc.DotNet#577]
- **Vlc.DotNet version** : (3.0)
- **Vlc.DotNet project used** : (WinForms) wrapped in WPF windowsformhost
- **libvlc version** : (3.0.7) (x86) + via nuget
- **.net version** : (4.6.1)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows 10) (x64)

I am porting an old app that was using the Ax libs at version 0.9.9 to use Vlc.DotNet. With the old 0.9.9 versions of VLC there were numerous issues with memory leaks and application crashes which appear to have been resolved by the upgrade, however we now are having issues with getting consistent latency across multiple instances in a single app.

Basically this app has multiple panes of video streams (4 or 6) which each have a vlc instance wrapped by a windows form host. If I point the instances at the same stream there are very noticeable differences in latency between the panes in the app. Each one of the instances is basically being used/initialized following the sample WPF+Winforms app from this repo. I have played around with different settings for network-caching, but I still always seem to intermittently end up with panes that have 1-2 seconds of difference in observed latency (even if they are pointed at the same source stream).

Backend streams are UDP and rtsp.

Does anyone have any tips on where I should look to try and resolve these inconsistencies between vlc instances?

Thanks

**Comment by jeremyVignelles** [comment]
As explained on gitter, VLC now adds buffering and does not play frames as they come anymore.
Moreover, whenever a frame comes late, the buffer is dynamically increased to avoid losing frames.
This is how VLC works nowadays, but things are getting better for low-latency scenarios in VLC4, without any promise that it will be the same latency than pre-3 versions.

**Comment by irootuser** [comment]
Thanks for the info. Is there a specific version of Vlc.DotNet 2.x that might work out better for lower latency with UDP and rtsp streams?

I looked at falling back with nuget, but i did not see anything under 3.0.

**Comment by jeremyVignelles** [comment]
We started publishibg versions on nuget starting with 3.0. Back in the days, the procedure was to use the VLC that was installed on the computer, and specify manually the path to there.
Please be aware that 2.x versions of VLC are end of life, and you won't get support from VideoLAN

**Comment by irootuser** [comment]
Would you happen to know of any decoder settings that I could investigate to try and stop VLC 3.x from dynamically increasing the buffer size?

Just wondering if there is a trade off that could be made in video quality which would keep my multiple streams in sync latency wise.

**Comment by jeremyVignelles** [comment]
I am not aware of such option. The best bet would be to ask videolan directly.

**Comment by irootuser** [comment]
Another thing I noticed is that when a stream ends up with more observed latency  I find the following line in the log:
`ts warning: Broken stream: pid 68 sends packets with dts 888900us later than pcr, applying delay`

When a stream has good results this line is not present in the logs^

[good.log](https://github.com/ZeBobo5/Vlc.DotNet/files/3623533/good.log)
[bad.log](https://github.com/ZeBobo5/Vlc.DotNet/files/3623534/bad.log)

My guess is that this added delay is what is causing some of my vlc instances to lag behind

**Comment by irootuser** [comment]
I resolved this for now with:
`--no-ts-pcr-offsetfix`

After passing this argument all of the instances seem to stay in sync now. I assume this probably means my streams are corrupted in some way at the source, but for now this will work.
