### ISSUE TITLE
CPU overuse

### ISSUE THREAD

**Issue by shade-less** [ZeBobo5/Vlc.DotNet#578]
I have  a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.1-develop356
- **Vlc.DotNet project used** : WPF
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows x64

# Summary

I am using WPF version of Vlc.DOtNet and I faced a problem with CPU overuse. While 4k video stream (h.264) in VLC player requires 16-18% of CPU, my application uses about 32-34% of CPU (when video is not loaded - application usage is around 1-2%). Sometimes it uses even more processors power.

Is it possible to use some parameter to reduce the usage of CPU?

These are the parameters I currently use:

`
"--no-lua",
"--sout-transcode-high-priority",
"--network-caching=300", 
"--sout-mux-caching=300", 
"--prefetch-buffer-size=250000", 
"--clock-jitter=0", 
"--clock-synchro=0",
"--no-sout-smem-time-sync",
// Logging
"--file-logging", 
"--logfile=VLCLog.log",
"-vvv"
`

- [+] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Please read this : https://github.com/ZeBobo5/Vlc.DotNet#writing-a-wpf-app--migrating-wpf-control-from-2x

> You might notice a performance impact when reading, for example, a 4k @ 60 fps video on a low-end computer.

Don't use the WPF control for what you're doing.
