### ISSUE TITLE
Ad-hoc recording support?

### ISSUE THREAD

**Issue by MinChanSike** [ZeBobo5/Vlc.DotNet#579]
As my testing Vlc.DotNet samples repo, there is no ad-hoc recording feature.
I would like to know, it is support ad-hoc recording feature like **VLC Player**?

![image](https://user-images.githubusercontent.com/2868221/65233940-4840be00-db06-11e9-933c-9377468c2a42.png)

- [x] Continuous recording is working.
- [ ] Ad-hoc recording support?

_Thank you so much for your effort._

**Comment by jeremyVignelles** [comment]
As far as I know, this belongs to the features that are reserved for VLC and that aren't exposed to libvlc
