### ISSUE TITLE
Title property is in Chinese language

### ISSUE THREAD

**Issue by adrians75** [ZeBobo5/Vlc.DotNet#58]
Why Title property return something in Chinese language ? 
I test with this code:
vlcControl.GetCurrentMedia().Title
and
Vlc.DotNet.Core.VlcMedia media = new VlcMedia(vlcKey, new FileInfo(fileName), null)
media.Title

Is kind of funny :). I triggered a protection ?

If you have any suggestion, please help me :)
Thanks!

![vlcinaction](https://cloud.githubusercontent.com/assets/12475233/7667785/a29002e0-fc20-11e4-8d5b-f36e52a23aa6.png)

**Comment by wuzhenda** [comment]
It's not Chinese language,it‘s  gibberish.

**Comment by adrians75** [comment]
Thanks for the clarification!
Then, how to get the correct Title, not gibberish?

**Comment by wuzhenda** [comment]
I think it's just the Character coding problem,why not try read the file name in your own code,try utf-8,unicode etc?

**Comment by adrians75** [comment]
Thanks again, 
Is ok with files, but I need to play YouTube media or RTSP - online video. There this property, title, is very useful.

**Comment by xDoJohn** [comment]
Someone should go over the source code, to make sure all native text is converted to ANSI. That's the problem...

**Comment by xDoJohn** [comment]
Change line 16 in VlcManager.GetMediaMeta.cs (Core.Interops project) to this: return Marshal.PtrToStringAnsi(ptr);

**Comment by adrians75** [comment]
Thanks! Solve the problem. :)
