### ISSUE TITLE
[Question] Authentication on Vlc.DotNet

### ISSUE THREAD

**Issue by NGame1** [ZeBobo5/Vlc.DotNet#580]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : (WinForms & WPF)
- **.net version** : 4.7
- **Project language** : (C#)
- **Project build architecture** : (x86 & x64)
- **Operating system** : (Windows 7 & Above) (x86/x64)

# Summary
I want to play a web RTSP URL witch asking for authentication. 
How can I add authentication in VLC Control in my code? 
![image](https://user-images.githubusercontent.com/19765248/65371715-bb1f7580-dc7b-11e9-8ff6-61d3097e0957.png)
The screenshot above is from VLC UWP on Windows 10 when I try to play my RTSP URL
Thanks

**Comment by jeremyVignelles** [comment]
You can use `:rtsp-user=...` and `:rtsp-pwd=...`(not really sure about the names, not on my computer) in the media options if you know them at initialization.
If you want the user to enter credentials, you can have a look at the Dialog feature. I think we have a sample for that in this repository.

**Comment by NGame1** [comment]
Hi there, 
Thanks really. I found the solution rtsp://user:pass@URL
But I don't know now how can I make sure that the URL needs authentication or no? 
hope to be able to find the sample you mentioned.

**Comment by jeremyVignelles** [comment]
user:pass is deprecated and will trigger a warning in the log.
If you need to know whether the stream requires authentication, you can use the Dialog API as mentionned before. Either you will be called because the server asks for authentication, or you don't get called and the stream doesn't require auth

**Comment by jeremyVignelles** [comment]
See https://github.com/ZeBobo5/Vlc.DotNet/tree/develop/src/Samples/Samples.Wpf.Dialogs

**Comment by NGame1** [comment]
It worked. 
Thanks really for your help
