### ISSUE TITLE
Two question: one about DLLs and second about the duration

### ISSUE THREAD

**Issue by halexic** [ZeBobo5/Vlc.DotNet#581]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.8
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 and x64
- **.net version** : 4.6.4
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system**: Windows 7 x64

# Summary
FIRST QUESTION:
I want to have only must needed DLLs in my "Release" version. I just use VLC Control in WinForms without any special effects and when I build the project (it is set to x64) but I always get inside "Release" folder one folder named "libvlc" which has both folders "win-x86" and "win-x64) and total size of both is 320MB (which is a lot for my simple example I would like to share). Is it enough to have only "libvlc.dll" and "libvlccore.dll" DLLs?

SECOND QUESTION:
I have a playlist of images and video and I want to set specified duration for each image in my playlist so when player comes to specific image it will show it for given duration. I think now it is 10 seconds by default but I want to change this. How can I achieve this to make my image show for 20 seconds before another playlist item is shown?

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by ghaith100994** [comment]
the first questing set up the CPU platform to X64

**Comment by mfkl** [comment]
> FIRST QUESTION
> Is it enough to have only "libvlc.dll" and "libvlccore.dll" DLLs?

No. You need at least some plugins, those 2 dlls don't do much by themselves.

See https://github.com/mfkl/libvlc-nuget#Build-and-packaging-customization-with-MSBuild and https://github.com/mfkl/LibVLC.Windows.Light. Also, you don't necessarily need x64 and x86.

> SECOND QUESTION

I guess you can just use a .NET timer, check the name of the media and call next() as needed.

**Comment by jeremyVignelles** [comment]
@ghaith100994 is right about the fact that choosing x64 or x86 will allow libvlc-nuget to pick only the libraries for that platform. Choosing AnyCPU would make the build script copy both libvlc.

@mfkl's first link gives more in-depth explanations on how you could copy only what you want. You'll have to make some tests to figure out the perfect combination for what you want, but sometimes, the results can be suprising. For example, I've never been able to get rid of mmdevice (audio on windows), despite I'm not using audio at all...

For the second part, I guess you are looking for `:image-duration=20`, but I didn't try, just found it there : https://github.com/videolan/vlc-3.0/blob/f25d3ba368fa2daad34171ad14a42efd6c672ba1/modules/demux/image.c#L88

The next time you have two questions at once, I'd prefer that you open two separate thread to keep things clear for future readers. Thanks 👍

**Comment by halexic** [comment]
> 
> 
> @ghaith100994 is right about the fact that choosing x64 or x86 will allow libvlc-nuget to pick only the libraries for that platform. Choosing AnyCPU would make the build script copy both libvlc.
> 
> @mfkl's first link gives more in-depth explanations on how you could copy only what you want. You'll have to make some tests to figure out the perfect combination for what you want, but sometimes, the results can be suprising. For example, I've never been able to get rid of mmdevice (audio on windows), despite I'm not using audio at all...
> 
> For the second part, I guess you are looking for `:image-duration=20`, but I didn't try, just found it there : https://github.com/videolan/vlc-3.0/blob/f25d3ba368fa2daad34171ad14a42efd6c672ba1/modules/demux/image.c#L88
> 
> The next time you have two questions at once, I'd prefer that you open two separate thread to keep things clear for future readers. Thanks +1

Thank you all. I tried giving duration as parameter in Play method but it didn't help me, maybe I didn't specify it well (tried few combinations):

vlcPlayer.Play(fileInfo, new string[] { "image-duration=20" });
vlcPlayer.Play(fileInfo, new string[] { ":image-duration=20" });
vlcPlayer.Play(fileInfo, new string[] { "image-duration:20" });

**Comment by jeremyVignelles** [comment]
The second form looks correct to me. otherwise, you could try with `--image-duration=20` in the VlcMediaPlayerOptions array

**Comment by halexic** [comment]
> 
> 
> The second form looks correct to me. otherwise, you could try with `--image-duration=20` in the VlcMediaPlayerOptions array

Great, it works.

**Comment by ghaith100994** [comment]
you can open vlc command helper and search for all command for image that help
https://wiki.videolan.org/VLC_command-line_help
