### ISSUE TITLE
When a clip finishes playing I lose clip.

### ISSUE THREAD

**Issue by taurojo** [ZeBobo5/Vlc.DotNet#583]
# Generic information

- **Vlc.DotNet version** : (3.0.8.0)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (3.0.8.0) (x86) 
- **.net version** : (4.7.1)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows 10) (x86)

# Summary

When a clip finishes playing I lose the controls.
Go at a time.
`vlcontrol.SourceProvider.MediaPlayer.Position = (float)0;`

 Or play the clip again.
`ThreadPool.QueueUserWorkItem(_ => vlcontrol.SourceProvider.MediaPlayer.Play());`

I was try the option "--play-and-pause", not work for me.
How not to lose the clip when we reach the end of its reproduction?

**Comment by mfkl** [comment]
Can you share a git a repo with a small repro? I don't know what lose the controls or lose the clip means.

**Comment by taurojo** [comment]
Sorry for the short explanation, I think with the code you will find better.
If I upload a simple video. At the end of its reproduction I can not press the button to go to a time and play it.
I lose the video to be able to move it, go to a point, etc ...
I would like to make a simple player with in and out buttons. But at the end of its reproduction I can not play with the clip

```

<Window x:Class="test_player.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:test_player"
        xmlns:vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid Margin="0,0,0,0">

        <Vlc:VlcControl xmlns:Vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf" x:Name="MyControl" Margin="31,10,197,54" />
        <Button x:Name="start_and_play" Content="Button" HorizontalAlignment="Left" Margin="624,211,0,0" VerticalAlignment="Top" Width="75" Click="Start_and_play_Click"/>


    </Grid>
</Window>


using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Windows;
using Vlc.DotNet.Wpf;

namespace test_player
{
   
    public partial class MainWindow : Window
    {


        public MainWindow()
        {
            InitializeComponent();


            var vlcLibDirectory = new DirectoryInfo(@"C:\Program Files\VideoLAN\VLC\");

            var options = new string[]
            {
                // VLC options can be given here. Please refer to the VLC command line documentation.
            };

            this.MyControl.SourceProvider.CreatePlayer(vlcLibDirectory, options);
            this.MyControl.SourceProvider.MediaPlayer.Play(@"file:///C:/Users/xxxx/Downloads/flame.avi");


        }

      
        private void Start_and_play_Click(object sender, RoutedEventArgs e)
        {
            MyControl.SourceProvider.MediaPlayer.Position = 0;
            MyControl.SourceProvider.MediaPlayer.Play();
        }
    }
}
```

**Comment by jeremyVignelles** [comment]
I think this is a VLC bug, not Vlc.DotNet. Maybe you can play the video again and pause it so that you can seek? It's not great, but...

Please open a bug at VideoLAN
