### ISSUE TITLE
System.AccessViolationException when creating new player window

### ISSUE THREAD

**Issue by mirtec001** [ZeBobo5/Vlc.DotNet#585]
I have an issue / a question (pick one) about Vlc.DotNet.Wpf

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.0 and 3.0.8 x64 downloaded from VLC
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : x86/x64
- **Operating system** : Windows 10 x64

# Summary

When attempting to create a new player for a WPF application, I'm receiving System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

MainWindow.xaml.cs

```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace TSP
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            string currentDirectory = @"C:\Users\mirte\Downloads";

            var vlcLibDirectory = new DirectoryInfo(System.IO.Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            var options = new string[]
            {
                // VLC options can be given here. Please refer to the VLC command line documentation.
                "-vvv"
            };
            this.MyControl.SourceProvider.CreatePlayer(vlcLibDirectory, options);
            
            // Load libvlc libraries and initializes stuff. It is important that the options (if you want to pass any) and lib directory are given before calling this method.
            this.MyControl.SourceProvider.MediaPlayer.Play("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov");
        }
    }
}
```

MainWindow.xaml
```XAML
<Window x:Class="TSP.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TSP"
        mc:Ignorable="d"
        Title="VLC Player Window" Height="450" Width="800">
    <Grid RenderTransformOrigin="0.503,0.487">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="125*" />
            <ColumnDefinition Width="667*" />
        </Grid.ColumnDefinitions>
        <Grid
            Grid.Column="0"
            VerticalAlignment="Top"
            Height="75"
            Margin="20,20,20,0">
            <Grid.RowDefinitions>
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
            </Grid.RowDefinitions>
            <Button x:Name="OpenDev" Grid.Row="0" Content="Open Dev" HorizontalAlignment="Left" VerticalAlignment="Top" Width="75"/>
            <Button x:Name="Record" Grid.Row="1" Content="Record" HorizontalAlignment="Left" VerticalAlignment="Top" Width="75"/>
            <Button x:Name="Exit" Grid.Row="2" Content="Exit" HorizontalAlignment="Left" VerticalAlignment="Top" Width="75" />

        </Grid>
        <Vlc:VlcControl
            Grid.Column="1"
            xmlns:Vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf" x:Name="MyControl" />


    </Grid>
</Window>

```

I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Any libvlc logs? where did you get your libvlc? did you extract all plugins? Why didn't you use the LibVLC nuget package?

**Comment by mirtec001** [comment]
I installed all NuGet packages.  I'm using Visual Stuido 2019.  I didn't see any VLC logs as the project won't compile with the error.  Do you see anything in the code that could be causing the issue?

**Comment by mirtec001** [comment]
VLC is downloaded through the zip as I'm trying to make the package portable.

**Comment by jeremyVignelles** [comment]
When I mentionned the nuget package, I meant this one : https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/
It allows you to redistribute libvlc with your application easily, and it embeds both x86 and x64 version of libvlc. Moreover, you can select which plugins to copy (see the repo's documentation).

>  I didn't see any VLC logs as the project won't compile with the error.

Do you mean that this crash occurs when you build the project, not when you run it?

**Comment by mirtec001** [comment]
I didn't know about that NuGet.  I'll try building that in to my application and will report back.  

The crash does occur on build.

**Comment by mirtec001** [comment]
That package helped get the program to compile, however I'm getting:
```LOG
main debug: looking for access_demux module matching "C:\Users\misikp\Videos\big_buck_bunny_480p_h264.mov": 15 candidates
main debug: no access_demux modules matched
main debug: creating access: C:\Users\misikp\Videos\big_buck_bunny_480p_h264.mov://
main debug: looking for access module matching "C:\Users\misikp\Videos\big_buck_bunny_480p_h264.mov": 26 candidates
main debug: no access modules matched
main error: Your input can't be opened
```
I uploaded the log.  
Will you see if you can point me in the right direction?

[Logs.log](https://github.com/ZeBobo5/Vlc.DotNet/files/3697869/Logs.log)

**Comment by jeremyVignelles** [comment]
use file:///c:/... in the url or pass a fileInfo

**Comment by mirtec001** [comment]
Thank you for your patience.  Everything works.  I would put a note in the beginner's guide about https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/.  Will you please close this issue?

**Comment by jeremyVignelles** [comment]
Isn't it already written in the wiki?
