### ISSUE TITLE
Play a video with audio / video tracks separate.

### ISSUE THREAD

**Issue by Kajirinn** [ZeBobo5/Vlc.DotNet#586]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x86)
- **.net version** : (4.7.2)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10 64 bit)

# Summary

Forgive my ignorance, I've looked all over and can't figure this problem out. I'm trying to play a video with audio and video tracks separate. All I've got is the stream url of both items, usually `.Play(muxed-url)` does the trick when I want muxed; but I can't get the command lines to work without it (first time I'm using them as well.).

Thanks in advance.

**Comment by jeremyVignelles** [comment]
I would play them with two separate media players, one with audio disabled, the other with video disabled.
I'm not sure, but I think you can disable audio/video with --no-audio and --no-video . Check the VLC command line help to know for sure

**Comment by Kajirinn** [comment]
That's the thing, I have two separate streams for audio and video so I wouldn't need to disable the audio and video on the two players. But I preferably wouldn't want two players as they could get out of sync. Is there really no other way?

**Comment by mfkl** [comment]
Have you managed to get this done with the VLC desktop app? That'd be the first step.

**Comment by jeremyVignelles** [comment]
Sorry, I misunderstood your question. Isn't there an option like that to select another audio file? I know there is for subtitles, but for audio, I'm not sure...

**Comment by Kajirinn** [comment]
I've tried pretty much everything but I'm not that familiar with vlc, so sadly I couldn't get it to work myself.

**Comment by Kajirinn** [comment]
Having said that, I just found the solution...

```
vlcPlayer.Play(video-stream-url, string[] { ":input-slave=" + audio-stream-url });
```

**Comment by jeremyVignelles** [comment]
nice, thanks for sharing!
