### ISSUE TITLE
Online media from YouTube is not played

### ISSUE THREAD

**Issue by adrians75** [ZeBobo5/Vlc.DotNet#59]
I try to play a YouTube video and nothing happens.
RTSP stream from my dvr/camera is played fine.
I run my project in x86 with Net 4.0

If you have any suggestion, please help me :)
Thanks!

**Comment by GonzRu** [comment]
How did you get youtube video url?
I get url using [savefrom](http://ru.savefrom.net/?rmode=false) and sample app is playing video (example [url](http://r3---sn-fpgxapo3-4vge.googlevideo.com/videoplayback?ms=au&mv=m&mt=1431869564&dur=273.136&mm=31&upn=t2zlJGqSQBY&id=o-ALlrYmHKz05F_OFd5qs79_f_f1i-HahU8tQ4Jz8zKTm0&ipbits=0&key=yt5&ip=177.184.134.235&sver=3&pl=23&ratebypass=yes&initcwndbps=297500&expire=1431891193&itag=22&fexp=916632%2C922333%2C9408107%2C9408142%2C9408199%2C9408593%2C9408626%2C9408705%2C9408710%2C9408983%2C9409208%2C9412466%2C9412982%2C9413007%2C9413011%2C9413123%2C9414852%2C945137%2C948124%2C952612%2C952637%2C952642&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&pcm2cms=yes&source=youtube&mime=video%2Fmp4&signature=416E3EB467E3E25ACA4C4CE635D0788FEAFD212F.9A22586908867088524A879FD20C7110794E2C4D&title=Kuroshio+Sea+-+2nd+largest+aquarium+tank+in+the+world+-+%28Please+Don%27t+Go+by+Barcelona%29))

**Comment by adrians75** [comment]
I use both ways, but any of them don't work.
https://www.youtube.com/watch?v=lbT_bXZxgq4
https://youtu.be/lbT_bXZxgq4
The sample app give me this in output (click): The thread 0x21cc has exited with code 0 (0x0).

**Comment by GonzRu** [comment]
No, you need direct url.
this https://www.youtube.com/watch?v=lbT_bXZxgq4 and this https://youtu.be/lbT_bXZxgq4 isn't direct url
i don't know how to take direct url from code, but i am sure that it is possible =)

for your example video direct url is [this](http://r1---sn-ubpouxgg5-n8me.googlevideo.com/videoplayback?initcwndbps=3830000&sver=3&ms=au&itag=22&ratebypass=yes&source=youtube&dur=282.099&mv=m&id=o-APxwst2EhkqhUR9djoaky8JOoXRtI1jXQrAPbzSqRSdk&key=yt5&upn=4V4xBb844mM&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&ip=37.131.208.141&fexp=936117%2C9405446%2C9407662%2C9408142%2C9408587%2C9408706%2C9408710%2C9408880%2C9409223%2C9409272%2C9412515%2C9413023%2C9413031%2C9413341%2C945137%2C946008%2C948124%2C952612%2C952637%2C952642&signature=696274D3C13B5653A0BEA4565930DB52B6D3A4CB.58C1302024944FC067252FB6CE4F71C025C2560C&mime=video%2Fmp4&pl=21&expire=1431977680&mm=31&ipbits=0&mt=1431955966&title=Look+to+the+Sky+-+Planetside+2+Cinematic+Video)

How to get direct url you can find [here](http://www.codeproject.com/Tips/323771/YouTube-Downloader-Using-Csharp-NET)

**Comment by adrians75** [comment]
I think this is the link, that can be used:
http://www.youtube.com/get_video_info?video_id=lbT_bXZxgq4&el=detailpage

But in an earlier version of vlc wrapper for c# the YouTube video work very well.
Only I had to include "lua" extensions (director).

**Comment by GonzRu** [comment]
yeah, you are right, destop vlc is playing simple youtube urls, but Vlc.DotNet isn't playing and i don't know why
workaround - take direct url as i wrote above =)

> But in an earlier version of vlc wrapper for c# the YouTube video work very well.
can you show last commit where vlc.dotnet is working with simple youtube urls?

**Comment by adrians75** [comment]
![simivlcplayer1](https://cloud.githubusercontent.com/assets/12475233/7777121/ea688a04-00c8-11e5-874f-b429e6d76179.png)
Rename the extension to zip. In \bin\Debug\vlc\ you must add \plugins and \lua.

**Comment by jeremyVignelles** [comment]
Closing as this is an old issue. Feel free to reopen if needed

**Comment by ebalmol** [comment]
Hi @adrians75.

I'm trying to use your simivlcplayer1 test project because I need Youtube videos (but I am not able to load them with the library) but I have a problem:
- LibVlcHandle is not initialized and always returns Intpr.Zero, any idea?

Thanks!

**Comment by jeremyVignelles** [comment]
@ebalmol : Did you call EndInit() on the Vlc control?

**Comment by ebalmol** [comment]
I think the project is using a really old version of the library and I cannot convert it to new version (and set begininit and endinit).
I will try another way to find what's happenig with Youtube videos.
Thanks @jeremyVignelles !
