### ISSUE TITLE
Unable to set audio track

### ISSUE THREAD

**Issue by InfiniteImp** [ZeBobo5/Vlc.DotNet#590]
I can't find a way to set current audio track in Vlc.DotNet.  

# Generic information

- **Vlc.DotNet version** : 3.1.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.0.8.1 via Package Manager
- **.net version** : 4.7.2   (tried 4.5 as well)
- **Project language** : VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64 1903

# Summary

I can't find a way to set current audio track in Vlc.DotNet.  The video has several languages.  I am able to retrieve a list via VlcControl1.GetCurrentMedia.Tracks.   Google searches report that to change audio track you are supposed to use Player.Audio.Tracks.Current = xx but that doesn't work because 'Integer cannot be converted to TrackDescription'.   If I try Player.Audio.Tracks.Current.ID = xx I get a 'read only property' error.

- [ ] I confirm that my issue doesn't happen in VLC itself.

VLC itself allows audio track switching correctly.

**Comment by jeremyVignelles** [comment]
Use one of the values from `Player.Audio.Tracks.All` to set into `Player.Audio.Tracks.Current`.

**Comment by InfiniteImp** [comment]
Works perfectly.  Thank you!
