### ISSUE TITLE
New winform project, no errors, no form

### ISSUE THREAD

**Issue by imtrobin** [ZeBobo5/Vlc.DotNet#591]
Hi, new to project, created a new WinForm project and pulled in the nuget and control. When I run, nothing happens, no error, nothing shows up.

![image](https://user-images.githubusercontent.com/531606/67446238-84ee6080-f642-11e9-9aac-4764ae426982.png)

Under debugger, it says

![image](https://user-images.githubusercontent.com/531606/67446358-ef9f9c00-f642-11e9-8228-0a3802e5d29f.png)

Install-Package Vlc.DotNet.Forms -Version 3.0.0
Install-Package VideoLAN.LibVLC.Windows -Version 3.0.8.1
c# .net 4.7, AnyCPU, Window 10 64

**Comment by mfkl** [comment]
Arch CPU mismatch? Please provide a git repo with a reproducible example.

**Comment by imtrobin** [comment]
Here's the project

https://filedn.com/l3TGy7Y83c247u0RDYa9fkp/temp/vlc/TestVLCDotNet.zip

You need to the path of the libvlc as I hardcoded it.

**Comment by jeremyVignelles** [comment]
Please follow the installation steps from the wiki and the sample codes.
Also, please fill the issue template, there is a section there just for this kind of issue people are always having : What is your project architecture? What version (32/64) of libvlc are you using.

You are probably trying to load a win64 version of libvlc with anyCPU, but "Prefer 32 bits" is checked and your process is 32 bits (that's the most common case)
Don't "hardcode" the path if you are using AnyCPU, compute it depending on the process architecture.

If I'm wrong, please reopen with the issue template filled

**Comment by imtrobin** [comment]
yup, the prefer 32bit option is the problem, thanks.
