### ISSUE TITLE
how to enable gpu accelerate

### ISSUE THREAD

**Issue by Luoyingliang** [ZeBobo5/Vlc.DotNet#592]
I hava a question that how can i enable gpu accelerate

**Comment by jeremyVignelles** [comment]
It's enabled by default with VLC 3, unless your GPU has been explicitely excluded by the VLC developers. Are you able to use hardware acceleration on the VLC app?

**Comment by Luoyingliang** [comment]
but from my observation there was disable gpu accelrate feature,how can i enable it

**Comment by Luoyingliang** [comment]
this issue similar to #441
