### ISSUE TITLE
Audio.Delay not working

### ISSUE THREAD

**Issue by BitKing2** [ZeBobo5/Vlc.DotNet#595]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms & Core
- **libvlc version** : 3.0.8 x86 acquired via the official FTP site 
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows x64

# Summary

I am building a Windows Form App in Visual Studio, using Vlc.DotNet.Forms.

When attempting to set audio delay via `vlcControl.Audio.Delay`, nothing happens and the audio plays with no delay.

The relevant code follows:

``` C#
public void PlayMedia()
{
  vlcControl1.Audio.Delay = 1000;
  vlcControl1.Play();
}
```

The loaded media plays, but with no delay in the audio.

- [ X ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Sorry, I totally forgot your issue. do you have any logs to share?

**Comment by BitKing2** [comment]
No problem. No I don't have any logs, since it didn't raise any exceptions or warnings. 

Is there a way to enable verbose logging for VLC.NET? Or maybe I'm missing a log it already is generating?

**Comment by jeremyVignelles** [comment]
Yes, there is a way
https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#how-to-debug

**Comment by jeremyVignelles** [comment]
I just read the documentation about the underlying method:
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__audio.html#ga8e2d21265f597723e978d325cab285b5
The values there are expressed in microseconds, so 1 ms would probably not be significant enough.

Would you mind trying with bigger values?

**Comment by jeremyVignelles** [comment]
Assuming the issue has been fixed by now. Closing.
