### ISSUE TITLE
Keyboard media controls

### ISSUE THREAD

**Issue by Kajirinn** [ZeBobo5/Vlc.DotNet#598]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x86) + how did you get it?
- **.net version** : (4.7.2)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10 64 bit)

# Summary

With most media players you can control them with "keyboard media controls". I'm not really sure how to describe them, but they'd be the skip right, skip left, pause etc on your keyboard. I'm having trouble finding how to implement this with vlcdotnet.

Thanks in advance.

**Comment by jeremyVignelles** [comment]
Hello. You have to implement that yourself. Handle the keyboard events yourself, but be aware that VLC will intercept keyboard events, unless you set `IsKeyInputEnabled=false`.
If you are using WPF, events will need to be handled on the WindowsFormsHost

**Comment by Kajirinn** [comment]
Thanks for the reaction, I was hoping that wasn't the case but after a bit of googling I found out using hooks was the best solution. [This](https://www.codeproject.com/Articles/7294/Processing-Global-Mouse-and-Keyboard-Hooks-in-C) project helped me to achieve this. After that it was simply the case of subscribing to the keydown event and using the 'MediaPlayPause, MediaNextTrack etc' keys to control the vlccontrol.
