### ISSUE TITLE
Audio track cuts off a few seconds too soon.

### ISSUE THREAD

**Issue by Kajirinn** [ZeBobo5/Vlc.DotNet#599]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x86)
- **.net version** : (4.7.2)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10 64 bit)

# Summary

This may be an odd one,

I've been looking all over for this issue, as the title suggests the audio track cuts off before the video ends. I've found out this only happens when using the `":input-slave=url"` with audio streams option as playing regular muxed streams seem to work just fine. Throughout my googling I've found [some](https://forum.videolan.org/viewtopic.php?t=148543) threads suggesting 'wasapi' might be the solution but I haven't been able to get that working.

I'm completely on board with this one and will provide any code or time I have to offer.

Thanks in advance.

**Comment by mfkl** [comment]
> suggesting 'wasapi' might be the solution but I haven't been able to get that working.

Why not?

Possibly related but not sure https://trac.videolan.org/vlc/ticket/22929

**Comment by Kajirinn** [comment]
The frames look fine, the video still plays it's just the last 2-3 seconds ish of the audio cut off. And I've tried to use wasapi but haven't found the command line for it, there seems to be little documentation on that.

**Comment by mfkl** [comment]
Maybe `--mmdevice-backend=wasapi` https://wiki.videolan.org/VLC_command-line_help/

**Comment by Kajirinn** [comment]
I've tried that but it doesn't seem to be working. I'll try to reproduce the bug in vlc itself in the meantime.

**Comment by Kajirinn** [comment]
I've noticed that `PositionChanged` cuts off right when the audio cuts off. The video continues to play and when that stops `EndReached` is called. Definitely sounds like some some sort of bug.

**Comment by jeremyVignelles** [comment]
Yes, it looks like a bug, but if it does happen in VLC, we can't do anything about it in this repo, please open a bug on VLC side.

**Comment by Kajirinn** [comment]
Have been able to reproduce the bug in vlc itself. It only happens when using two separate streams, if you were to use two seperate files instead it'll work just fine. I'll open a bug on their site as you suggested, thanks for helping regardless.
