### ISSUE TITLE
How to get a mp3's front cover!?

### ISSUE THREAD

**Issue by CodingOX** [ZeBobo5/Vlc.DotNet#6]
I need to get the front cover in a mp3。
I use vlc mediaplayer play a mp3,It can show the front cover。
But I don't know how to get it ? can you help me with your code?

**Comment by ZeBobo5** [comment]
I think the better way is to use another library which provide it on easy way, like, but not tested, [TagLib Sharp](https://github.com/mono/taglib-sharp/). It is available on NuGet package.

Vlc is not the better library to parse metadatas.
