### ISSUE TITLE
get no key in dictionary  exception in Vlc.DotNet.Core.VlcMediaPlayer.cs

### ISSUE THREAD

**Issue by wuzhenda** [ZeBobo5/Vlc.DotNet#60]
it happens in 
                foreach (var loadedMedia in VlcMedia.LoadedMedias[this])
                {
                    loadedMedia.Dispose();
                }

so I add a judgement ,but I don't  know why?

```
        if (VlcMedia.LoadedMedias.ContainsKey(this))
        {
            foreach (var loadedMedia in VlcMedia.LoadedMedias[this])
            {
                loadedMedia.Dispose();
            }
        }
```

**Comment by xDoJohn** [comment]
Almost all of the Disposing functions don't work just remove it, and test your code again.

     if (VlcMedia.LoadedMedias.ContainsKey(this))
        {
            foreach (var loadedMedia in VlcMedia.LoadedMedias[this])
            {
                //loadedMedia.Dispose();
            }
        }

**Comment by jeremyVignelles** [comment]
Is that still an issue? If yes, please reopen and provide more details.
