### ISSUE TITLE
Multiple VLCControls on a form

### ISSUE THREAD

**Issue by Schnazey** [ZeBobo5/Vlc.DotNet#600]
I have an issue with multiple VLCControls on a form. 

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (Please fill) (x64) + downloaded from VLC website.
- **.net version** : (4.6.2)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows .7) (x64)

# Summary

If I add multiple controls on a form and play a video in all I can see the videos in all controls.  However if I try to mute just one of them, they all mute.  If I try to unmute just one, they all unmute.  If a video is not playing in one of the controls and I unmute that one and mute the rest.  The rest all mute.  If I mute the one not playing a video and unmute one of the others that are playing, they all unmute.

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
This is a known issue : https://github.com/ZeBobo5/Vlc.DotNet/issues/524#issuecomment-466763262 

Use `--aout=directsound`

**Comment by jeremyVignelles** [comment]
Closing since it has been answered.
