### ISSUE TITLE
Unable to clear last frame of video played from control when playback ends.

### ISSUE THREAD

**Issue by InfiniteImp** [ZeBobo5/Vlc.DotNet#601]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.08.1 via Package Manager
- **.net version** : 4.7.2
- **Project language** : VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64 1909

# Summary

When I finish playing back a video to the end (EndReached fires), exit my player window, then start a new video, the previous video's last frame appears for 1/2 second before the new video starts playback.  Is there a way for me to completely clear the VLCPlayer control after a video ends or before a new one begins?  

I've tried .ResetMedia, .Refresh, hiding/redisplaying the control.  No luck.

I have not experienced this issue in VLC itself.

**Comment by jeremyVignelles** [comment]
Do you dispose the media player and create a new one each time or do you reuse the same? In the second case, you should probably call Stop()

**Comment by InfiniteImp** [comment]
That worked, thank you!
Closing this ticket.

**Comment by InfiniteImp** [comment]
Ok, there's a problem with this.  With some videos, executing a .Stop() after EndReached fires causes the application to hang.  There's no way of resuming it, you just have to terminate it.  If I test this in Visual Studio I find that the .Stop statement just hangs.  I can still stop the application in the IDE but code past the .Stop will not execute.

For the videos where .Stop works, it's timing dependent.  If the .Stop is executed immediately after playback ends, it does not lock up.  If I pause before executing the .Stop() statement it locks up.

Any ideas?

**Comment by jeremyVignelles** [comment]
Are you in that case? https://github.com/ZeBobo5/Vlc.DotNet/wiki/Vlc.DotNet-freezes-(don't-call-Vlc.DotNet-from-a-Vlc.DotNet-callback)

**Comment by InfiniteImp** [comment]
No.  In EndReached I set a timer and from the Timer_Tick event I execute the code I need.

**Comment by jeremyVignelles** [comment]
Please open a new issue for that, and share a minimal sample code on github.
