### ISSUE TITLE
Retrieving video codec info

### ISSUE THREAD

**Issue by InfiniteImp** [ZeBobo5/Vlc.DotNet#603]
I have a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.08.1 via Package Manager
- **.net version** : 4.7.2
- **Project language** : VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64 1909

# Summary

How can I retrieve video codec info for the currently playing video?   I can see several tracks in VlcControl1.GetCurrentMedia.Tracks and there is audio information there but no video.  

The information I'm after is what you get when you use VLC's right-click -> Tools -> Codec Information -> Stream 0, Stream 1, etc, specifically whether it's HEVC (H.265) and so on.

Thanks.

**Comment by mfkl** [comment]
Have you parsed the stream/media?

Share your full code

**Comment by InfiniteImp** [comment]
Right now I don't know where to look.  I searched for 'codec' in the previously resolved issues and it pointed me at .GetCurrentMedia, so I started there.  That's where I got the audio track codec info.  No idea how to "parse the stream".  Is there documentation you can point me at?

    Dim vlcm As VlcMedia = VlcControl1.GetCurrentMedia

    strTemp = ""

    For Each i As Interops.MediaTrack In vlcm.Tracks
      strTemp &= i.Id & ":" & i.Description & ":" & i.Type & vbCrLf
    Next

    MsgBox(strTemp)

**Comment by mfkl** [comment]
https://github.com/ZeBobo5/Vlc.DotNet/issues/568

**Comment by InfiniteImp** [comment]
Ok, I checked that code and it basically gives me the same result as above.  None of the MediaTrack items contain video codec info.  The new test code is:

    Dim vlcm As VlcMedia = VlcControl1.GetCurrentMedia
    vlcm.Parse()

    strTemp = "ID: " & vlcm.TrackID & vbCrLf

    Dim mediaTrack() As Interops.MediaTrack = vlcm.Tracks

    For Each i As Interops.MediaTrack In mediaTrack
      strTemp &= i.Id & ":" & i.Description & ":" & i.Type & vbCrLf
    Next

    MsgBox(strTemp)

**Comment by mfkl** [comment]
Like I said
> Share your full code

I have no idea what your media is.

**Comment by InfiniteImp** [comment]
Got it.  The code to set the media is not in the same place as this test code so it's hard to say what specifically you need to know.  The entire program is pages long.  

So, Before I executed the above test code I called the following with these parms:
strFilename="Astra.UHD.Demo.2160p.UHDTV.AAC.HEVC.x265-LiebeIst.mkv"
blnShowPlayer=True
lngStartAtSeconds=(varies, depending where I left off.  Value is in milliseconds)

Private Sub StartPlayer(ByVal strFilename As String, ByVal blnShowPlayer As Boolean, Optional ByVal lngStartAtSeconds As Long = 0)
    Dim structRecent As New RecentlyPlayedStruct
    Dim fi As IO.FileInfo
    fi = New IO.FileInfo(strFilename)
    Dim vlcm As VlcMedia
    Dim strNameOnly As String
    Dim fntFont As Font

    If System.IO.File.Exists(strFilename) = False Then
      MsgBox("The file '" & strFilename & "' no longer exists.", vbExclamation)
      Exit Sub
    End If

    tbProgress.Maximum = 0

    strNameOnly = GetFilenameOnly(strFilename)
    If lngStartAtSeconds = 0 AndAlso mdictRecents.ContainsKey(strNameOnly) Then
      structRecent = mdictRecents.Item(strNameOnly)

      lngStartAtSeconds = structRecent.StoppedSeconds
    End If

    'Must be done after the player panel resizes to ensure proper manual positioning of lblLastPlayed below
    If mdictRecents.ContainsKey(strNameOnly) Then
      structRecent = mdictRecents.Item(strNameOnly)

      lblLastPlayed.Text = "Last played " & Format(structRecent.PlayDate, "MMM. dd, yyyy hh:mm tt")
      lblLastPlayed.Visible = True
      lblLastPlayed.Location = New Point(pnlProgress.Width - lblLastPlayed.Width - 2, lblLastPlayed.Top)
    Else
      lblLastPlayed.Text = ""
      lblLastPlayed.Visible = False
    End If

    Call LogEvent("Player form shown")
    mstrCurrentFile = strFilename

    mstrCurrentName = GetFilenameOnly(mstrCurrentFile)
    lblProgressMovieName.Text = mstrCurrentName

    'Must be done after both lblProgressMovieName and lblLastPlayed have been set
    If lblProgressMovieName.Font.Size <> msngOrigMovieNameFontSize Then
      'Resize back to the standard font size and see if this movie will fit
      fntFont = New Font("Arial", msngOrigMovieNameFontSize, FontStyle.Regular)
      lblProgressMovieName.Font = fntFont

      fntFont = New Font(lblLastPlayed.Font.Name, msngOrigMovieNameFontSize, FontStyle.Regular)
      lblLastPlayed.Font = fntFont
    End If

    If lblProgressMovieName.Left + lblProgressMovieName.Width + 10 > lblLastPlayed.Left Then
      'It won't fit, so drop font size by 2
      fntFont = New Font("Arial", lblProgressMovieName.Font.Size - 2, FontStyle.Regular)
      lblProgressMovieName.Font = fntFont

      fntFont = New Font(lblLastPlayed.Font.Name, lblLastPlayed.Font.Size - 2, FontStyle.Regular)
      lblLastPlayed.Font = fntFont

      lblLastPlayed.Location = New Point(pnlProgress.Width - lblLastPlayed.Width - 2, lblLastPlayed.Top)
    End If

    lblPlayerStatus.Text = "Playing " & mstrCurrentName
    Application.DoEvents()
    Call LogEvent("Starting video playback")

    lstLanguages.Items.Clear()
    lblPlayTime.Text = ""
    lblPlayTime.Text = ""
    mblnTimerEvent = False

    VlcControl1.Location = New Point(0, 0)
    VlcControl1.Size = pnlPlayer.Size

    menuCurrentMode = CurrentModeEnum.PlayMovie

    Call LogEvent("Setting media")
    VlcControl1.SetMedia(fi)
    Application.DoEvents()

    Select Case menuPlayingFrom
      Case PlayingFromEnum.Added
        pnlMain.Visible = False
        Application.DoEvents()
      Case PlayingFromEnum.FileSelection
        pnlFileSelection.Visible = False
        Application.DoEvents()
      Case PlayingFromEnum.Recent
        pnlMain.Visible = False
        Application.DoEvents()
    End Select

    Call ShowPlaybackIcon(CurrentPlayMode.Play)

    Call LogEvent("Play starting")
    VlcControl1.Play()
    Application.DoEvents()

    If blnShowPlayer = True Then
      Call LogEvent("Showing player form")
      pnlPlayer.Size = pnlMain.Size
      pnlPlayer.Location = pnlMain.Location

      pnlMain.Visible = False
      Application.DoEvents()

      pnlPlayer.Visible = True
      pnlPlayer.BringToFront()

      VlcControl1.Focus()
      Application.DoEvents()
    End If

    If lngStartAtSeconds > 0 Then
      vlcm = VlcControl1.GetCurrentMedia
      vlcm.Parse()

      VlcControl1.VlcMediaPlayer.Time = lngStartAtSeconds
      Call UpdateVideoTime(lngStartAtSeconds, vlcm.Duration.TotalMilliseconds)
      Call UpdateProgressBar()

      vlcm = Nothing
    End If

    tmrPlayTimer.Interval = 500
    tmrPlayTimer.Enabled = True

    Call ShowPlayerNotification("Playing", mstrCurrentName, 2, False)

    Call AddToRecentlyPlayed()
  End Sub

**Comment by mfkl** [comment]
Try inspecting that info when the `MediaPlayer.Playing` event fires.

**Comment by InfiniteImp** [comment]
I did.  I execute the test code once I see the movie playing.  Depending on the movie I play, I either get a mix of movie title and audio codec info or I get nothing useful at all.  So, for the above 4K demo I get this:

ID: (blank)
0::1
1::0

Meaning i.ID=0, i.Description is blank, i.Type is either 0 or 1.

**Comment by mfkl** [comment]
Can you share your file (or a part of it)?

**Comment by InfiniteImp** [comment]
I'm sure I can.  It's just a 4K demo.  Do I just attach it here or do I need to put it on a dropbox or something?  1.6GB.

**Comment by mfkl** [comment]
Cut a part of it if you can (with VLC record function for example). On Dropbox is fine.

**Comment by InfiniteImp** [comment]
Done.  I tested the 1-minute clip (4k2.mp4) and it reproduces the issue I'm seeing.
The link is: https://www.dropbox.com/s/jwaf998maxtjsfa/4k2.mp4?dl=0

**Comment by mfkl** [comment]
```
var media = new Media(libVLC, @"C:\PathTo\4k2.mp4");
await media.Parse();
var track = media.Tracks.First();
var codec = FromFourCC(track.Codec);
var h = track.Data.Video.Height;
var w = track.Data.Video.Width;
```

This works. Tried with libvlcsharp, but you will get same result with vlc.dotnet (slightly different APIs, maybe).

**Comment by InfiniteImp** [comment]
What is FromFourCC() and do I need it?  Actually even if I did, I don't have a "track.data" or a "track.codec".  I do have a track.CodecFourcc but that gives back a UInteger.

**Comment by mfkl** [comment]
Yes, you need it. You need to search for yourself a bit, I can't write all your code for you. Look at https://github.com/ZeBobo5/Vlc.DotNet/blob/f0d3e2aca37500ccd2710c8b9b286ccc485f1636/src/Samples/Samples.WinForms.Advanced/Sample.cs

**Comment by InfiniteImp** [comment]
Thanks for the help.  I'll look into it more in the morning.  I was hoping there was a simple property somewhere that would give me video codec info of the currently playing movie and it's turned into something way more involved than I expected.  

However, even if/when I do find FromFourCC I still don't have access to "track.data" and "track.codec" so I expect it won't help me.  I get this feeling that these properties are somewhere else for VB than they are in C#.

Hopefully Jeremy will see this and have a simple approach.

Again, I appreciate you taking the time to look at this.

**Comment by jeremyVignelles** [comment]
From martin's link, I've seen : `myVlcControl.GetCurrentMedia().Tracks` which gives a track list, and for each track (`mediaInformation` there), you can call `FourCCConverter.FromFourCC(mediaInformation.CodecFourcc)`. Is there anything else you need?

**Comment by InfiniteImp** [comment]
Awesome, thanks.  The last question I have relating to this is how do I translate the value returned by .FromFourCC, (which in this case is "hevc") into the string that VLC displays "MPEG-H Part2/HEVC (H.265)"?

**Comment by jeremyVignelles** [comment]
Try this:
`mediaPlayer.Manager.GetCodecDescription(MediaTrackTypes.Video, mediaInformation.CodecFourcc)`

**Comment by InfiniteImp** [comment]
Works perfectly, thanks Jeremy!
