### ISSUE TITLE
Crashes on Load

### ISSUE THREAD

**Issue by TheCrafters001** [ZeBobo5/Vlc.DotNet#604]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.0.8.1 x86, I got it via the ReadMe
- **.net version** : 4.6.2
- **Project language** : VB.net
- **Project build architecture** : x86 (prefer 32bits)
- **Operating system** : Windows 10 x64 (64-Bit)

# Summary

Hello, when I add the VLC Control, and change the VLCLib location, and I run the app, it seems to crash instantly. (it is on a separate form, you get to it by clicking a button) I am wondering why it does it. And I have found out, on the x64 version of it, it claims it is not a win32 application. What could be causing this? The [repo](https://github.com/TheCrafters001/Flash-Player-2) is here, the issue is [here](https://github.com/TheCrafters001/Flash-Player-2/tree/master/src/Flash%20Player%202/Video).

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
If you are building a x86, or AnyCPU (prefer 32 bits), you should be using the x86 version of libvlc.

See this sample for proper libvlc initialisation : https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Samples/Samples.WinForms.Minimal/Sample.cs

Do you have any log?

**Comment by TheCrafters001** [comment]
@jeremyVignelles 
I followed the example link above. Sadly I do not have any logs, but I do have this error:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=An error occurred creating the form. See Exception.InnerException for details.  The error is: 'VlcLibDirectory' must be set.
  Source=Flash Player 2
  StackTrace:
   at Flash_Player_2.My.MyProject.MyForms.Create__Instance__[T](T Instance) in :line 190
   at Flash_Player_2.My.MyProject.MyForms.get_Media_Player()
   at Flash_Player_2.Form1.Button2_Click(Object sender, EventArgs e) in C:\Users\TheCrafters001\Documents\GitHub\Flash-Player-2\src\Flash Player 2\Form1.vb:line 7
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at Flash_Player_2.My.MyApplication.Main(String[] Args) in :line 81

Inner Exception 1:
Exception: 'VlcLibDirectory' must be set.
```
but the error occurs on this
``` VisualBasic
Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Media_Player.Show() ' error occurs here
        Me.Close()
    End Sub
```
What could be causing the error? (I am using VB.NET)
https://github.com/TheCrafters001/Flash-Player-2/commit/4ae24d5a49ee1b74bdb396ab6883808f9e6a4cf9 https://github.com/TheCrafters001/Flash-Player-2/blob/master/src/Flash%20Player%202/Form1.vb#L7

**Comment by jeremyVignelles** [comment]
You need to either provide a VlcLibDirectory, or you must handle the VlcLibDirectoryNeeded event on the control.

**Comment by TheCrafters001** [comment]
@jeremyVignelles Now the error is slightly different, but the same.
```
Dim currentAssembly = Assembly.GetEntryAssembly()
Dim currentDirectory = New FileInfo(currentAssembly.Location).DirectoryName
Media_Player.VlcControl1.VlcLibDirectory = New DirectoryInfo(Path.Combine(currentDirectory, "libvlc", If(IntPtr.Size = 4, "win-x86", "win-x64"))) ' Error occurs here
Media_Player.show() ' no longer here
```
But on the form "Meda_Player"  I have the following code:
```
Imports Vlc
Imports AxWMPLib
Imports Vlc.DotNet.Core
Imports Vlc.DotNet.Forms
Imports Vlc.DotNet.Forms.VlcControl
Imports Vlc.DotNet.Wpf.VlcControl
Imports Vlc.DotNet.Wpf
Imports System
Imports System.IO
Imports System.Reflection
Imports System.Windows.Forms

' <summary>
' When the Vlc control needs to find the location of the libvlc.dll.
' You could have set the VlcLibDirectory in the designer, but for this sample, we are in AnyCPU mode, And we don't know the process bitness.
' </summary>
' <param name="sender"></param>
' <param name="e"></param>

Public Class Media_Player
    Private Sub Media_Player_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub
    Private Sub vlcControl_VlcLibDirectoryNeeded(ByVal sender As Object, ByVal e As Vlc.DotNet.Forms.VlcLibDirectoryNeededEventArgs)
        Dim currentAssembly = Assembly.GetEntryAssembly()
        Dim currentDirectory = New FileInfo(currentAssembly.Location).DirectoryName
        e.VlcLibDirectory = New DirectoryInfo(Path.Combine(currentDirectory, "libvlc", If(IntPtr.Size = 4, "win-x86", "win-x64")))
    End Sub
End Class
```
What am I missing?

**Comment by jeremyVignelles** [comment]
I don't know about VB.net, but do you get into the vlcControl_VlcLibDirectoryNeeded ? Have you linked it in the winForms designer?

If you've never used the library before, I suggest that you have a look at the wiki and the sample codes.

**Comment by TheCrafters001** [comment]
@jeremyVignelles 
I have, and they lead me back to the sample projects. I have also tried to use the designer file, but I cannot get it to work. VB.NET is sadly the only language I know how to read and write. So, reading the C# code does not really help me. I can read a little bit of the syntax, but not all of it.

**Comment by jeremyVignelles** [comment]
Is the code on your repo up-to-date with your current code? Did you manage to associate the event handler with the event?
when you put a breakpoint inside the event handler, does it get triggered?

**Comment by TheCrafters001** [comment]
@jeremyVignelles I just updated the code to the must current page.

**Comment by jeremyVignelles** [comment]
You don't need Vlc.DotNet.Wpf since you're doing WinForms.
Your VlcLibDirectory = code is useless, only the event handler must be done.

**Comment by TheCrafters001** [comment]
@jeremyVignelles 
Could you show me what file you mean? is it Form1.vb or Media_Player.vb?

**Comment by TheCrafters001** [comment]
The issue has been closed for the following reason:

- I am not going to use this library. It is too confusing for me to work with. Thanks for any help, though!

**Comment by jeremyVignelles** [comment]
I'm sorry to read that. I am not a WinForms developer nor a VB developer, so I couldn't really help...

**Comment by jeremyVignelles** [comment]
Feel free however to come back later if you need to give it another go.
