### ISSUE TITLE
[Question] Disable thumbnail preview in WPF + WinForms VlcControl

### ISSUE THREAD

**Issue by Granathar** [ZeBobo5/Vlc.DotNet#608]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 (NuGet)
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 x64

I have a VLC WinForms control inside of WindowsFormsHost for my WPF application. Everything works fine in general, but before I had VlcControl embedded into my application mouse hover over application icon in taskbar showed me preview of whole application window. Right now it shows video being played inside VlcControl - what is even worse it shows only one while there are two VlcControls, so the camera preview is not even complete.

How can I stop VlcControl from taking over and display preview of whole application window as it was before?

**Comment by jeremyVignelles** [comment]
As far as I remember, someone already posted a question about it here. I think it's either an issue with libvlc, with windows, or whith the way winforms integrates with WPF. In any case, I'm not sure I can do something in Vlc.DotNet.

**Comment by Granathar** [comment]
So what can I do apart from disabling thumnail preview entirely in Windows 10? I tried using WPF VLC control, but it had very bad performance (lack of acceleration probably?) and had to use WinForms version instead.

**Comment by jeremyVignelles** [comment]
> but it had very bad performance (lack of acceleration probably?)

Yes, as said in the README, I don't recommend using it if you care about perfs

**Comment by jeremyVignelles** [comment]
It seems that you can provide your own thumbnail : https://stackoverflow.com/questions/17484978/c-sharp-on-mouseover-at-taskbar-a-preview-is-generated-how-can-i-achieve-thi

**Comment by jeremyVignelles** [comment]
Did you manage to find a solution?

I'm closing this for now, feel free to reopen if needed.
