### ISSUE TITLE
Resuming playback of a DVD folder

### ISSUE THREAD

**Issue by InfiniteImp** [ZeBobo5/Vlc.DotNet#609]
I have question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version : 3.1.0.0
- **Vlc.DotNet project used : WinForms
- **libvlc version : 3.08.1 via Package Manager
- **.net version : 4.7.2
- **Project language : VB.net
- **Project build architecture : AnyCPU
- **Operating system : Windows 10 x64 1909

# Summary

When working with a DVD folder (VIDEO_TS) how can I resume playback at a particular title?  The DVD has several opening sequences, a menu and a main title.  If the user stops playback while watching the main title, how can I return to that point later?  Right now if I set .Time it applies that to the opening sequence which makes sense but I need it to jump to the main title and apply the .Time to it.

**Comment by jeremyVignelles** [comment]
I've never played with DVD myself in libvlc, but I know that you can specify chapters/title from the MRL (the URL that you pass when you create the media).

Maybe see : https://wiki.videolan.org/VLC_command-line_help/

I hope this helps, otherwise, unless there is something I don't remember from the libvlc API, you're probably stuck.

**Comment by InfiniteImp** [comment]
Thanks for that.  
Ok, I found a way to play the video and jump to a specific title using the VLC command line.  Now, how can I get VLC to tell me the title number currently playing so that when the user stops playback I can save that title #?

**Comment by jeremyVignelles** [comment]
Can the `mediaPlayer.TitleChanged` event be helpful for that?

**Comment by InfiniteImp** [comment]
Thank you!  
That in combination with the MRL method of setting media did it.
Closing this ticket.
