### ISSUE TITLE
How to rewind backwards after reaching end?

### ISSUE THREAD

**Issue by AqlaSolutions** [ZeBobo5/Vlc.DotNet#610]
Error when trying to `Play()` the same file after reached end.

            if (!_player.IsPlaying)
            {
                _player.Stop();
                _player.Play(_currentFileName); // also tried _player.Play()
            }
```

[0c59f3c8] main input error: VLC is unable to open the MRL '[filename]'. Check the log for details.
[0c59f3c8] main input error: Your input can't be opened
```

I need this because changing `_player.Time` after reaching end doesn't do anything.

**Comment by jeremyVignelles** [comment]
Please check the content of _currentFileName. It must be a MRL (file://...)

Next time, don't forget the issue template

**Comment by AqlaSolutions** [comment]
The content of the `_currentFileName` is not changed and the first original call `Play(_currentFileName)` succeeded so the file was played till its end. Though it's not in `file://` format - it's just a normal windows file path. If it was the cause it wouldn't play the first time too.

Sorry for the issue template.

**Comment by AqlaSolutions** [comment]
Just check with `file://` format and it doesn't work the same

**Comment by AqlaSolutions** [comment]
I think there might be a workaround - playing some "placeholder" video before playing `_currentFileName` again

**Comment by jeremyVignelles** [comment]
Strange. you could also try instanciating a Media object and passing it over and over to the media player.

**Comment by AqlaSolutions** [comment]
It seems that's what `Play()` method already does - sets another media.

Logs for not working Play:

> removing module "inhibit"
> removing module "freetype"
> removing module "yuvp"
> removing module "swscale"
> Creating an input for 'f://'
> using timeshift granularity of 50 MiB
> creating access: f:\folder\filename.wmv://
> looking for access module matching "f:\folder\filename.wmv": 26 candidates
> no access modules matched
> no access_demux modules matched
> Your input can't be opened
> VLC is unable to open the MRL 'f:\folder\filename.wmv'. Check the log for details.
> creating demux: access='f:\folder\filename.wmv' demux='any' location='' file='(null)'
> looking for access_demux module matching "f:\folder\filename.wmv": 15 candidates
> `f:\folder\filename.wmv' gives access `f:\folder\filename.wmv' demux `any' path `'
> using timeshift path: C:\Users\Vlad\AppData\Local\Temp

With `file://`:

```

Creating an input for 'filename.wmv'
using timeshift granularity of 50 MiB
using timeshift path: C:\Users\Vlad\AppData\Local\Temp
creating demux: access='file' demux='any' location='f:/folder/filename.wmv' file='\\f:\folder\filename.wmv'
looking for access_demux module matching "file": 15 candidates
cannot open DVD (\\f:\folder\filename.wmv)
creating access: file://f:/folder/filename.wmv
looking for access module matching "file": 26 candidates
cannot open file \\f:\folder\filename.wmv (Invalid argument)
 (path: \\f:\folder\filename.wmv)
VLC is unable to open the MRL 'file://f:/folder/filename.wmv'. Check the log for details.
The thread 0x5538 has exited with code 0 (0x0).
The thread 0x65a4 has exited with code 0 (0x0).
no access modules matched
`file://f:/folder/filename.wmv' gives access `file' demux `any' path `f:/folder/filename.wmv'
Your input can't be opened
no access_demux modules matched

```

The first time it's correctly opened:

> Creating an input for 'filename.wmv'
> using timeshift granularity of 50 MiB
> using timeshift path: C:\Users\Vlad\AppData\Local\Temp
> `file:///f:/folder/filename.wmv' gives access `file' demux `any' path `/f:/folder/filename.wmv'
> creating demux: access='file' demux='any' location='/f:/folder/filename.wmv' file='f:\folder\filename.wmv'
> looking for access_demux module matching "file": 15 candidates
> no access_demux modules matched
> looking for access module matching "file": 26 candidates
> received first data after 0 ms
> pre-buffering done 1024 bytes in 0s - 1000000 KiB/s
> using stream_filter module "cache_read"
> looking for stream_filter module matching "any": 24 candidates
> creating access: file:///f:/folder/filename.wmv
>  (path: f:\folder\filename.wmv)
> Using stream method for AStream*

**Comment by AqlaSolutions** [comment]
Oops, I found the reason) The first time I used `FileInfo`
