### ISSUE TITLE
How to get the frame data of video at a specific time?

### ISSUE THREAD

**Issue by Hummel-Wang** [ZeBobo5/Vlc.DotNet#612]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (x64) 
- **.net version** : (4.6)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows  10) (x64)

# Summary
1. Init Vlc player code, such as:
string vlcDir = @"D:\Program Files\VideoLAN\VLC";
vlcLibDirectory = new DirectoryInfo(vlcDir);
recordShow.SourceProvider.CreatePlayer(vlcLibDirectory);
recordShow.SourceProvider.MediaPlayer.Play(new Uri(myVideo.FileFullName));

2. I want to get a video image of a certain point in time，But I didn't find the right api or function. so, How can I write code to achieve the function？ Thank you....

**Comment by jeremyVignelles** [comment]
I'm on my phone, but the general idea is seek to time and get frame data, either by taking a snapshot to a file, or because you subscribed to the video callback events ( see vlc.dotnet.wpf implementation)

**Comment by Hummel-Wang** [comment]
Thanks for your reply.
That`s what i think,  but it is difficult. I got the time only.
I'll see vlc.dotnet.wpf implementation. Thank you very much.

**Comment by jeremyVignelles** [comment]
LibVLC 4 includes a new snapshot API that you can see here : https://github.com/videolan/vlc/blob/885e4eb8f492ff0496be99a72a92d303b7b6e89a/include/vlc/libvlc_media.h#L845

This new API seems to generate a thumbnail_generated event, that contains a picture : https://github.com/videolan/vlc/blob/78d3d6a3c62292ae379024e32a1a808483e7f3a1/include/vlc/libvlc_events.h#L242

So it seems doable to have an in-memory representation of the picture, but:
- It's implemented in libvlc4, which is currently under heavy development
- I'm not sure Vlc.DotNet will support libvlc4 one day (this is tracked by #545 ). I recommend that you follow the [LibVLCSharp](https://code.videolan.org/videolan/LibVLCSharp) project, which will probably implement libvlc 4 APIs before this project does.

I'm closing this for now, feel free to reopen if you feel this question hasn't been answered.
