### ISSUE TITLE
How to reduce memory usage?

### ISSUE THREAD

**Issue by ShemJM** [ZeBobo5/Vlc.DotNet#613]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : VLC.DotNet.Forms
- **libvlc version** : x86 + how did you get it? Nuget 
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows ...) (x86/x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))
Watching an RTSP stream using a WindowsFormHost in a WPF application. The memory usage is very high.

I understand that this isn't a problem with VLC but is there a way I can reduce the usage in the code?

**Comment by jeremyVignelles** [comment]
What do you call "very high"?
Reducing the stream quality on the receiving end won't help, you still need to decode and buffer the stream in full quality before reducing it, involving a transcoding operation. you would instead use more resources.
Can you configure your video source instead?

**Comment by ShemJM** [comment]
I see, I will try to reduce the resolution on the source. 

Very high is around 200Mb for each stream.

Thank you and sorry for posting here when it is not really related to this project :D

**Comment by jeremyVignelles** [comment]
200MB or Mb ? anyway, that seems indeed high. do you observe the same behavior with VLC itself?

**Comment by ShemJM** [comment]
200Mb, I see the same with VLC and even when I just watch the stream in the browser. I managed to get it to 170Mb by reducing it to 720p
