### ISSUE TITLE
Black screen with sound

### ISSUE THREAD

**Issue by AEAEAEAE4343** [ZeBobo5/Vlc.DotNet#615]
I have an issue with Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.0.7.1 x86 http://download.videolan.org/pub/videolan/vlc/3.0.7.1/win32/vlc-3.0.7.1-win32.7z
- **.net version** : 4
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 7 build 7601 x64

When creating a VlcControl and playing a video file, I get a black screen with sound and the following debug output:
`main debug: picture might be displayed late (missing 9 ms)`
`main warning: picture is too late to be displayed (missing 22 ms)`
I have absolutely no idea what causes it.

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by mfkl** [comment]
Share your full code please

**Comment by jeremyVignelles** [comment]
We can't help without a code sample. Try with the sample code, and tell us if it still does the same.

Closing for now.
