### ISSUE TITLE
How to get screenshots of rtsp without streaming it live?

### ISSUE THREAD

**Issue by jamols09** [ZeBobo5/Vlc.DotNet#616]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.8.1
- **Vlc.DotNet project used** : WinForms/Core
- **libvlc version** : x86 nuget
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows x64

# Summary

1. I have at least 20 cameras and I need to screenshot then at the same time without using too much resources from the computer. My best bet is to skip looking every camera rtsp stream but instead get their screenshots at interval x. Is this possible or can there be any work around?

**Comment by jeremyVignelles** [comment]
You can use the video callback feature for that, but the stream will still be decoded and frame still rendered into memory. See [here](https://code.videolan.org/mfkl/libvlcsharp-samples/tree/master/PreviewThumbnailExtractor.Skia) for an example of how I implemented that with LibVLCSharp, and [here](https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs) to see how this API is used for the WPF implementation in Vlc.DotNet.

I don't know any other way with libvlc 3.x, but there will be a snapshot API in libvlc 4.x, but that would require that Vlc.DotNet support it, see #545 . LibVLCSharp will probably get support for that before Vlc.DotNet does (if it does one day).

**Comment by jeremyVignelles** [comment]
This question has an answer, closing. Reopen if needed.
