### ISSUE TITLE
Play video from byte array how?

### ISSUE THREAD

**Issue by graysuit** [ZeBobo5/Vlc.DotNet#617]
**Can we play video using its bytes array.**

# Generic information
- **Vlc.DotNet project used** : (WinForms)
- **.net version** : (latest)
- **Project language** : (VB.net)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows ...) (x86)

# Summary
Sir i searched full internet but I didn't got my answer and I think internet now closing for vb.net.
It is not problem with your repository, I just want to ask an question.
**Can we play video using its bytes array?**

# Example
Lets suppose I have an video abc.mp4.
I converted it to base64 encoding like this below:
`Dim code as Byte() = Convert.ToBase64String( "kahgdjasAAAAAAAAA==")`

**And how can i load this video without dropping anywhere.**

**Comment by jeremyVignelles** [comment]
Hello,
You can wrap your byte array in a MemoryStream() and use player.SetMedia(yourStream).

I'm not a VB developer so I can't really provide a sample code.

**Comment by graysuit** [comment]
@jeremyVignelles C# also accepted,
Both vb.net and C# are related so much,
Just syntax is little bit different.

Yes give me the C# code,
Or any other code,
I will manage to put in my code.

**Comment by jeremyVignelles** [comment]
Pseudocode, untested:

```cs
var videoByteArray = Convert.FromBase64String(base64String);
this._memoryStream = new MemoryStream(videoByteArray); // Don't forget to dispose that when you close the player.
player.Play(this._memoryStream);
```

**Comment by graysuit** [comment]
@jeremyVignelles Thanks for helping.
Does this code is for **Vlc.DotNet** ?
Or any other player?
Or works with any player?

**Comment by jeremyVignelles** [comment]
This is for Vlc.DotNet's media player.

**Comment by graysuit** [comment]
@jeremyVignelles Sir, one more thing,
**Where to download LibVLC directory?**

As stated in the description that **Vlc.DotNet is wrapper around LibVLC,**
But I didn't get any LibVLC dll or directory in the source code.
I tried searching on internet but didnt got any idea.

I tried these examples:
[Samples.WinForms.Minimal/Sample.cs](https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Samples/Samples.WinForms.Minimal/Sample.cs)

**Where to download LibVLC directory?**

**Comment by jeremyVignelles** [comment]
There is a nuget package for that. Have a look at the csproj

**Comment by graysuit** [comment]
**Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks** 

@jeremyVignelles Thanks a lot sir,
This worked for me and solved my problem,
I was searching that for more than 10-15 days on internet,
You are doing good thing,
Keep it up.

**Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks**
