### ISSUE TITLE
Error when running sample.

### ISSUE THREAD

**Issue by rafaelf82** [ZeBobo5/Vlc.DotNet#618]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : Latest
- **Vlc.DotNet project used** : Samples.Wpf.Minimal.UsingWinForms
- **libvlc version** : x64 fomr nuget
- **.net version** : Same as sample
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows10 x64

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))
Just run the sample.

This is displayed in a console window and nothing else happens:

[0000022564d708b0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[0000022564f23f80] prefetch stream error: cannot seek (to offset 220056366)
[00000225650b5db0] avi demux error: no key frame set for track 0
[00000225650b5db0] avi demux error: no key frame set for track 1
[00000225650b5db0] avi demux error: no key frame set for track 0
[00000225650b5db0] avi demux error: no key frame set for track 1
[0000022564d708b0] main audio output error: too low audio sample frequency (0)
[00000225651cc0a0] main decoder error: failed to create audio output
[0000022564d708b0] main audio output error: module not functional
[00000225651cc0a0] main decoder error: failed to create audio output

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Maybe the URL is broken? can you try another file/url?

**Comment by rafaelf82** [comment]
The URL is correct I guess, I made a new program on a different project and it worked.

It's the sample code/project that's broken, I don't know why.

I guess you can close the issue.

The code I tried is the one at : https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Samples/Samples.Wpf.Minimal.UsingWinForms/MainWindow.xaml.cs

The URL : http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi

**Comment by jeremyVignelles** [comment]
So if I understand correctly, the same code in another project works fine? maybe the libvlc install was corrupt?

**Comment by mfkl** [comment]
That usually happens when you have no audio output available. An easy way to reproduce is to unplug all your speakers/headphones and disable the audio devices in the Windows Sounds menu.

**Comment by mfkl** [comment]
And that server is crazy slow. Took 15s before it displayed the first few frames, and it was not smooth after that.

**Comment by rafaelf82** [comment]
> So if I understand correctly, the same code in another project works fine? maybe the libvlc install was corrupt?

I'm going to have to guess it's maybe that, as I said it happened on the sample project, I did check the libvlc files on the folder, I'm not sure what happened, I guess it doesn't happen to others so I believe it was something on my end, I closed it anyway as I made my own project and everything worked so it's not an big issue either.
