### ISSUE TITLE
RTSP video locks up after a few minutes of playback

### ISSUE THREAD

**Issue by yetmorestuff** [ZeBobo5/Vlc.DotNet#62]
If I build and run the **Vlc.DotNet.Wpf.Samples - CLR 4 - .Net 4.0** sample (as x86) on Windows 8.1 Pro 64bit and playback video from an RTSP network stream (I have tried several, both from the internet and locally), playback works fine but then stops after a few minutes (anything from 2 mins to 10 mins of more). In this 'stopped video' state, my application continues to work until I call any _MediaPlayer_ method, upon which it locks up. If I pause the debugger, the next executing statement is inside whichever MediaPlayer method was called and it never returns.

I can play the same RTSP streams inside VLC player (2.1.5 Rincewind) without any issues.

There are many warnings in the vlc-log.txt file, such as "main warning: picture is too late to be displayed (missing 149 ms)", but these are also present when the video is playing normally. I've no idea how to interpret the other warnings, such as:

main debug: resampling stopped (drift: 68986 us)
main warning: playback too late (68986): up-sampling
main warning: playback too early (-64078): down-sampling

...but again these are all also present when the video is playing normally.

Anybody got any idea what could be causing this? 

I appreciate there may not be much to go on here but I've no idea where to start looking...

Please let me know if you need further details.

Thanks.

**Comment by taishmanov** [comment]
I have met same problem in Vlc.DotNet.Wpf (version 2.1.126). Video stops even if I play rtsp stream by VLC media player(2.2.4) and see lost frames. But other media players work fine. Setting frame rate (fps) to 10 on my IP camera helped for me. But 10 fps is so expensive for me. Any ideas?

**Comment by jeremyVignelles** [comment]
Can you try with a more recent version, like the latest VLC nightly?

**Comment by taishmanov** [comment]
I had decided to use ffmpeg with C# wrapper and now it works fine.

**Comment by jeremyVignelles** [comment]
ok. no answer from original poster, closing for now.
