### ISSUE TITLE
How to compress image on TakeSnapShot before saving file

### ISSUE THREAD

**Issue by jamols09** [ZeBobo5/Vlc.DotNet#620]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : **VideoLAN.LibVLC.Windows -Version 3.0.8.1**
- **Vlc.DotNet project used** : **WinForms**
- **libvlc version** : **x86**
- **.net version** : **4.5.2**
- **Project language** : **C#**
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : **Windows x64**

# Summary

I know how to take image with the TakeSnapShot() and FileInfo but I wan't to compress the Image before saving it as image file. Is it possible with TakeSnapShot function?

This is the initial code for image compression  (special thanks to Rafnas T P)

```
using (Bitmap bmp1 = new Bitmap(SourcePath))
            {
                ImageCodecInfo jpgEncoder = GetEncoder(ImageFormat.Jpeg);
                System.Drawing.Imaging.Encoder QualityEncoder = System.Drawing.Imaging.Encoder.Quality;
                EncoderParameters myEncoderParameters = new EncoderParameters(1);
                EncoderParameter myEncoderParameter = new EncoderParameter(QualityEncoder, quality);
                myEncoderParameters.Param[0] = myEncoderParameter;
                bmp1.Save(DestPath, jpgEncoder, myEncoderParameters);

            }
```

This is my code so far but DrawBitMap always draw black images (my full code is commented out)

```
        public void TakeScreenshot(object sender, EventArgs e)
        {
            bmp = new Bitmap(vlcControl1.Width, vlcControl1.Height);
            vlcControl1.DrawToBitmap(bmp, vlcControl1.ClientRectangle); //compress image in memory
            BitmapCompress(bmp, 40);
        }

        public void BitmapCompress(Bitmap bitmap, int quality)
        {
            var time = DateTime.Now.ToString("yyyy-mm-dd hh~mm~ss");
            dir = Directory.GetParent(Environment.CurrentDirectory).Parent.FullName + "\\screenshots\\" + time + ".jpeg";
            //ImageCodecInfo jpgEncoder = GetEncoder(ImageFormat.Jpeg);
            //System.Drawing.Imaging.Encoder QualityEncoder = System.Drawing.Imaging.Encoder.Quality;
            //EncoderParameters myEncoderParameters = new EncoderParameters(1);
            //EncoderParameter myEncoderParameter = new EncoderParameter(QualityEncoder, quality);
            //myEncoderParameters.Param[0] = myEncoderParameter;
            //bitmap.Save(dir, jpgEncoder, myEncoderParameters);
            bitmap.Save(dir, ImageFormat.Jpeg);
        }
```

**Comment by jeremyVignelles** [comment]
I don't know how DrawToBitmap works, but chances are that it can't play well with libvlc, because libvlc draws directly to the hwnd using windows API rather than using the WinForms mechanism.

TakeSnapshot, on the other hand, doesn't have many configuration options as far as I know.

This leaves you with few options:
- Draw to a temp folder, reopen the jpeg and recompress it.
- Use the video callback API, as done in the libvlcsharp thumbnailer example (discouraged)

This is all I can think of for now

**Comment by jamols09** [comment]
Thanks for the immediate reply. I hope this functionality would be added soon.

**Comment by jeremyVignelles** [comment]
I wouldn't count on it. It's a missing libvlc feature

**Comment by jeremyVignelles** [comment]
LibVLC 4 includes a new snapshot API that you can see here : https://github.com/videolan/vlc/blob/885e4eb8f492ff0496be99a72a92d303b7b6e89a/include/vlc/libvlc_media.h#L845

This new API seems to generate a thumbnail_generated event, that contains a picture : https://github.com/videolan/vlc/blob/78d3d6a3c62292ae379024e32a1a808483e7f3a1/include/vlc/libvlc_events.h#L242

So it seems doable to have an in-memory representation of the picture, but:
- It's implemented in libvlc4, which is currently under heavy development
- I'm not sure Vlc.DotNet will support libvlc4 one day (this is tracked by #545 ). I recommend that you follow the [LibVLCSharp](https://code.videolan.org/videolan/LibVLCSharp) project, which will probably implement libvlc 4 APIs before this project does.

I'm closing this for now, feel free to reopen if you feel this question hasn't been answered.
