### ISSUE TITLE
Pass video running to a new form.

### ISSUE THREAD

**Issue by jamols09** [ZeBobo5/Vlc.DotNet#624]
Is it possible to play the video in a newly created form without creating the vlccontrol again?

My scenario is that in my first Form I have already created a control for the video which is hidden but playing. The reason its hidden because I want to capture the image without displaying it (which is I'm done with that) so I'm silently capturing the img from the video and storing it in the file.

I do not know how to implement the vlccontrol that is already running then play it in the new form. 
I do not want to create a new control in the new form because it's like running 2 videos with the same content at once which is not good in memory usage.

**Comment by jeremyVignelles** [comment]
I don't really know about how WinForms works, but is it possible to reparent a form?

VLC has an API to change the window handle, but I don't know if it can do that while the video is playing

**Comment by jeremyVignelles** [comment]
closing as new feature will not be implemented in Vlc.DotNet, and that's probably not easily doable in any libvlc binding.
