### ISSUE TITLE
Cannot play more than 20 videos simultaneously

### ISSUE THREAD

**Issue by puruslotion** [ZeBobo5/Vlc.DotNet#626]
# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : 3.0.8.1 x86 + NuGet
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : (Windows 10 Home x64

# Summary

Hello,

I am trying to create an app for surveillance purposes. 

Everything works fine when playing 20 or less instances of VlcControl on a single Form; CPU usage is fluctuating between 10-15%. However, as soon as I try to play more than 20 instances of VlcControl, CPU usage soars to about 80-100%. I am a bit perplexed.

Thank you.

Specs: 
i7-7700HQ
32 GB RAM
512 GB RAM
GTX 1050

**Comment by mfkl** [comment]
https://code.videolan.org/videolan/LibVLCSharp/issues/262

**Comment by puruslotion** [comment]
I would like to add that this problem appears to be more or less solved in version 4 of the VLC nightly build. VlcControl scales linearly, CPU usage is kept under control and GPU is more involved. Although, starting the streams has become significantly slower.

I am, however, facing another problem now. It is not possible to call vlcControl.SourceProvider.Dispose() manually, which causes major memory leaks.

**Comment by jeremyVignelles** [comment]
This library does not (yet?) support libvlc4.
