### ISSUE TITLE
Does latest VLC supports somehow DRM PlayReady and/or Widevine?

### ISSUE THREAD

**Issue by QuantumDeveloper** [ZeBobo5/Vlc.DotNet#627]
Hi, 

I am looking for a video/audio player for my project.
The main requirement that player should support play a protected video stream with DRM like MS Playready and/or Google Widevine.

Does VLC supports at least something of these protections? Or if not, maybe it can be configured somehow?

**Comment by mfkl** [comment]
Have you tried to play the stream with the VLC app?

**Comment by QuantumDeveloper** [comment]
I didnt find any example of using it with DRM content, so no, I did try.

**Comment by jeremyVignelles** [comment]
If you cannot play it with VLC 3.0, Vlc.DotNet can't do anything for you.
I don't know what the DRM you mentionned are, but chances are that it should play it out of the box or not playing at all.

**Comment by QuantumDeveloper** [comment]
Actually this is quite hard to check because drm stream is under additional network protection, so I need to enter my credentials and add some headers to the request. Thats why I am asking here. Maybe someone already faced with DRM content on vlc

**Comment by jeremyVignelles** [comment]
What kind of stream is that ? HTTP? TCP? UDP ?
What kind of content? MPEG-TS? MPEG-DASH?

As far as I know, there is currently no way to add headers to the HTTP requests in VLC, which means you would have to place the request yourself and serve a stream to VLC.

Things you can try :
- Look for the names you mentioned in the VLC source code
- Ask the question on the #videolan IRC channel, be patient. If no answer, then
- Ask the question on the VLC forum
- Try to dump the stream with C#, into a file, and then feed it to VLC

**Comment by QuantumDeveloper** [comment]
I need MPEG-DASH with DRM Playready or Widevine. 
Just remembered that MS has some examples with URL of corresponding streams. So, I checked and found that DASH stream itself played without issues, but stream with DRM protection is not playing, which is sad. 

Does anyone know at least one working player for C# with support of mentioned technologies?

**Comment by jeremyVignelles** [comment]
I don't know of any library like that, but it sounds like this DRM security is proprietary so you probably won't find anything else than the official client.

**Comment by QuantumDeveloper** [comment]
Not very good news as far as native windows player cannot play DRM frrm WPF because of some unknown bug.

**Comment by jeremyVignelles** [comment]
After a quick search, there doesn't seem to be a good option in the .NET world for you. Maybe you can embed a web view with cefsharp or something?

Anyway, I don't think I can do more for you here, so I'm closing this topic.

**Comment by michellehwang** [comment]
Hey @QuantumDeveloper, did you ever figure out a solution? I'm looking for a video player on Windows that can support Widevine since Windows Media Player does not and I don't have a PlayReady license server.

**Comment by QuantumDeveloper** [comment]
@michellehwang  For me solution was to use Google Browser library integrated to my project and use shaka player inside. Unfortunately there is no other way to do this right now.
