### ISSUE TITLE
How to play MPEG-DASH from protected internet connection

### ISSUE THREAD

**Issue by QuantumDeveloper** [ZeBobo5/Vlc.DotNet#628]
Hi.

I wish to know is there a way to play video from MPEG-Dash manifest, which require custom headers to access the links inside the manifest?

Is this scenario can be achieved using VLC or it can play only manifests without internet access restrictions?

**Comment by jeremyVignelles** [comment]
As far as I know, there is no way to give VLC specific HTTP headers, but there is this issue: https://trac.videolan.org/vlc/ticket/14094

If that's not what you want, please open an issue for VLC directly.
