### ISSUE TITLE
Why Position is float, but Length is long?

### ISSUE THREAD

**Issue by QuantumDeveloper** [ZeBobo5/Vlc.DotNet#629]
I am wondering why is this so?
For, example, if video is long, for ex, 10 hours, position seems cannot navigate through all the timeline using float. I think they should be both of long type.

Or I am missing something?

**Comment by QuantumDeveloper** [comment]
Ah, sorry. I missed that fact that Position is from 0 to 1, but again. What about calculation errors converting float to long if I need to seek to the exact frame, I could easily miss because of rounding errors.
Am I right?

**Comment by jeremyVignelles** [comment]
you're right, this is why position is computed from time and length, and not the other way around.
Please note however, that depending on the input you are using, precise seeking is not always possible (like almost never). LibVLC4 will introduce a precise seek feature, but i'm not sure about when or if Vlc.DotNet will implement libvlc 4, LibVLCSharp would be a safer bet.
