### ISSUE TITLE
WPF refers to the vlc.net.wpf to close the WPF form. Windows events report an error kernelbase.dll exception

### ISSUE THREAD

**Issue by wutangyuan** [ZeBobo5/Vlc.DotNet#630]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (/WPF/)
- **libvlc version** : ((x86) (x86/x64) + how did you get it?（website）
- **.net version** : (.Net Framework 4.7.2)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows X64) (x86/x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace vlctest
{
          /// <summary>
        /// MainWindow.xaml 的交互逻辑
        /// </summary>
        public partial class MainWindow : Window
        {
            //获取输出目录
            private static string appPath = AppDomain.CurrentDomain.BaseDirectory;
            //vlc文件的地址
            private DirectoryInfo vlcLibDirectory = new DirectoryInfo(appPath + @"VLC");
            //配置项
            string[] options = new string[]
            {
                // VLC options can be given here. Please refer to the VLC command line documentation.
            };
            public MainWindow()
            {
                InitializeComponent();
                //创建播放器
                this.vlcControl.SourceProvider.CreatePlayer(vlcLibDirectory, options);
                //http协议视频流
                this.vlcControl.SourceProvider.MediaPlayer.Play(new Uri("http://vd3.bdstatic.com/mda-jkm0b29x51bvqdzs/sc/mda-jkm0b29x51bvqdzs.mp4"));
                //rtmp协议
                //this.vlcControl.SourceProvider.MediaPlayer.Play(new Uri("rtmp://58.200.131.2:1935/livetv/hunantv"));
                //本地视频
               // this.vlcControl.SourceProvider.MediaPlayer.Play(new Uri("d:/1.avi"));
                //添加播放结束事件
                //其他事件 请自行查看
                this.vlcControl.SourceProvider.MediaPlayer.EndReached += MediaPlayerEndEvent;

            }
            private void MediaPlayerEndEvent(object sender, Vlc.DotNet.Core.VlcMediaPlayerEndReachedEventArgs e)
            {
                //播放结束，循环播放本地视频
                Task.Factory.StartNew(() => {
                    this.vlcControl.Dispose();
                    Application.Current.Dispatcher.BeginInvoke(new Action(() => {
                        this.vlcControl.SourceProvider.CreatePlayer(vlcLibDirectory);
                        this.vlcControl.SourceProvider.MediaPlayer.Play(new Uri("d:/1.avi"));
                        this.vlcControl.SourceProvider.MediaPlayer.EndReached += MediaPlayerEndEvent;
                    }));
                });
            }
        }
    }
`

`<Window x:Class="vlctest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:vlctest"
        xmlns:vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <vlc:VlcControl x:Name="vlcControl"></vlc:VlcControl>
    </Grid>
</Window>
`

while Closed the this windows, Windows events report an error kernelbase.dll exception

![图片](https://user-images.githubusercontent.com/50666934/77223543-83e14100-6b98-11ea-98bc-d69f6ed56f6c.png)

Thanks!

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by wutangyuan** [comment]
![1584782170(1)](https://user-images.githubusercontent.com/50666934/77223657-8ee8a100-6b99-11ea-8a79-e310adc0ad90.png)

**Comment by jeremyVignelles** [comment]
Can you send a complete minimal code on github so that I can clone and try to reproduce locally?

**Comment by wutangyuan** [comment]
> Can you send a complete minimal code on github so that I can clone and try to reproduce locally?

hello! I had upload the minimal code on github [git@github.com:wutangyuan/VLCWpfTest.git](url).thanks for you help.

**Comment by jeremyVignelles** [comment]
Thank you, I will try to reproduce soon, feel free to ping me on Wednesday if you don't hear back :slightly_smiling_face:

**Comment by jeremyVignelles** [comment]
I saw this : https://raw.githubusercontent.com/wutangyuan/VLCWpfTest/master/guide.png
Any reason you're not using the NuGet package?

https://www.nuget.org/packages/VideoLAN.LibVLC.Windows

Do you reproduce the issue with the NuGet package?

**Comment by wutangyuan** [comment]
> I saw this : https://raw.githubusercontent.com/wutangyuan/VLCWpfTest/master/guide.png
> Any reason you're not using the NuGet package?
> https://www.nuget.org/packages/VideoLAN.LibVLC.Windows
> Do you reproduce the issue with the NuGet package?

yes,I copy from the  vlcplayer installation package

**Comment by wutangyuan** [comment]
> I saw this : https://raw.githubusercontent.com/wutangyuan/VLCWpfTest/master/guide.png
> Any reason you're not using the NuGet package?
> https://www.nuget.org/packages/VideoLAN.LibVLC.Windows
> Do you reproduce the issue with the NuGet package?

I'll try downloading it from nuget soon.thanks！

**Comment by wutangyuan** [comment]
> I saw this : https://raw.githubusercontent.com/wutangyuan/VLCWpfTest/master/guide.png
> Any reason you're not using the NuGet package?
> https://www.nuget.org/packages/VideoLAN.LibVLC.Windows
> Do you reproduce the issue with the NuGet package?

Hello,I reproduce the issue with the NuGet package,but same problems had happended. 
The vlc.net.form and the vlc.net.wpf(version 2.2.0) are no such problem.

**Comment by jeremyVignelles** [comment]
Great, commit that to https://github.com/wutangyuan/VLCWpfTest/

Please also remove your VLC.zip file from the repo, and the packages folder. Add a .gitignore file at the root of your repo and add this file content : https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
Always do that when you publish C# code in a git, it avoids pushing/pulling heavy files.

**Comment by wutangyuan** [comment]
> Great, commit that to https://github.com/wutangyuan/VLCWpfTest/
> Please also remove your VLC.zip file from the repo, and the packages folder. Add a .gitignore file at the root of your repo and add this file content : https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
> Always do that when you publish C# code in a git, it avoids pushing/pulling heavy files.

Hello, I had already committed the issue to https://github.com/wutangyuan/VLCWpfTest/ 
please  clone and try to reproduce.Thank you so much!

**Comment by jeremyVignelles** [comment]
Looks related to #542 somehow. I managed to reproduce with the minimal WPF sample in this repo in net47, but not in netcoreapp.

Just for curiosity, is there any good reason you are using the Wpf control, other than "because I'm writing WPF". As stated here : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#vlcdotnetwpf , prefer using the WinForms package for perf reasons.

**Comment by wutangyuan** [comment]
> 
> 
> Looks related to #542 somehow. I managed to reproduce with the minimal WPF sample in this repo in net47, but not in netcoreapp.
> 
> Just for curiosity, is there any good reason you are using the Wpf control, other than "because I'm writing WPF". As stated here : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#vlcdotnetwpf , prefer using the WinForms package for perf reasons.



Yes, our project needs to use WPF controls, because we need to put other controls on the vlcplayer control. If WinForms package is used, the above operations cannot be implemented.
anyway,thank you very much for your answer.

**Comment by wutangyuan** [comment]
> 
> 
> Looks related to #542 somehow. I managed to reproduce with the minimal WPF sample in this repo in net47, but not in netcoreapp.
> 
> Just for curiosity, is there any good reason you are using the Wpf control, other than "because I'm writing WPF". As stated here : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#vlcdotnetwpf , prefer using the WinForms package for perf reasons.

Hello!  
I find that as long as I call the vlcplayer's dispose method manually when I close the Winsow, I can solve the problem.

`  protected override void OnClosing(CancelEventArgs e)
        {
            vlcControl.SourceProvider.Dispose();
            vlcControl.Dispose();
            base.OnClosing(e);
        }`
