### ISSUE TITLE
VlcMediaplayerOptions adding two parameters problems 

### ISSUE THREAD

**Issue by brokolililer** [ZeBobo5/Vlc.DotNet#633]
I have an issue  about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (x64)  Nuget downloaded
- **.net version** : (4.7.2)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows 10) (x64)

# Summary

Hi, I am using Vlc.DotNet.Forms. 

```
           #My Sample Code        
  
            this.control = new VlcControl();
            var currentAssembly = Assembly.GetEntryAssembly();
            var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
            var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));
            control.BeginInit();
            control.VlcLibDirectory = libDirectory;
            control.Dock = DockStyle.Fill;
            control.VlcMediaplayerOptions = new[] {"--aout=directsound"};
            //control.VlcMediaplayerOptions = new[] {"--input-repeat=65535"};
            control.EndInit();
            this.Controls.Add(control);
            control.SetMedia(new Uri(@"" + url + ""));
            control.Play();
```
If I use only ,
`control.VlcMediaplayerOptions = new[] {"--aout=directsound"};`
parameters. Volume problem was fixing. But I want to repeat(loop) video. And If I use only `control.VlcMediaplayerOptions = new[] {"--input-repeat=65535"};` parameters. Repeat(loop) was fixing. So I want to use both of them. How can I do it?
I am unsure how confirm that my issue doesn't happen in VLC itself.

**Comment by mfkl** [comment]
```
new[] {"--aout=directsound", "--input-repeat=65535"};
```

**Comment by brokolililer** [comment]
Thank you so much <3
