### ISSUE TITLE
VLC.DotNet WinForm doesn't work on RightToLeft forms

### ISSUE THREAD

**Issue by ShayanFiroozi** [ZeBobo5/Vlc.DotNet#636]
VLC.DotNet WinForm doesn't work on **RightToLeft** forms.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : WinForms With (Right To Left Forms)
- **libvlc version** : 3.0.8 + Nuget.
- **.net version** : 4.5.1
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : (Windows 10) (x64)

My Code : 

`

            VlcControl vlcCam = new VlcControl();

            Assembly currentAssembly = Assembly.GetEntryAssembly();
            string currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;

            // Default installation path of VideoLAN.LibVLC.Windows
            DirectoryInfo libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", "win-x86"));

            vlcCam.BeginInit();

            vlcCam.VlcLibDirectory = libDirectory;
            // vlcCam.VlcMediaplayerOptions = new[] { "--file-logging", "--logfile=Logs.log" };

            vlcCam.BackColor = Color.DarkGray;
            vlcCam.Dock = DockStyle.Fill;

            vlcCam.EndInit();

            //this.pnl_cam_live.Controls.Add(vlcCam);
            this.Controls.Add(vlcCam);
            vlcCam.BringToFront();

            //  string[] _MediaOtions = new[] { "--input-repeat=65535", "--preferred-resolution={-1 720 (HD (720p))" };

            vlcCam.SetMedia(new FileInfo(@"H:\Sample.mp4"));

            vlcCam.Play();

`

**What Happens :** 

When i run this code on a form with **RightToLeft = true** , nothing happens , 
it seems the video is playing ( i know from CPU working percentage ) but i can not see the video , and after video ends(my video is 1 minute) my entire app hangs up.

**Simply i found it's all about the **RightToLeft** properties**.

Thank you.

**Comment by jeremyVignelles** [comment]
Are you able to reproduce with the WinForms sample?

**Comment by ShayanFiroozi** [comment]
> Are you able to reproduce with the WinForms sample?

In this time unfortunately no , but you just need to set your C# form **RightToLeft** Properties to **true** and you will see it will not work. that's it.

**Comment by jeremyVignelles** [comment]
Just tried. It seems that you need to set RightToLeft to Yes on your VlcControl:

```cs
            var control = new VlcControl();
            control.RightToLeft = RightToLeft.Yes;
```
