### ISSUE TITLE
Unable to Cast to Chromecast

### ISSUE THREAD

**Issue by RichieRogers** [ZeBobo5/Vlc.DotNet#637]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0-develop364
- **Vlc.DotNet project used** : Windows Application
- **libvlc version** : nuget x64 3.0.10.0
- **.net version** : .net 4.7.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64

# Summary

Code:
            var currentDirectory = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            using (var mediaPlayer = new Vlc.DotNet.Core.VlcMediaPlayer(libDirectory))
            {
                var mediaOptions = new[]
                {
                    ":sout=#chromecast{ip=192.168.16.1, demux-filter=demux_chromecast}",
                    ":sout-keep",
                    "--file-logging", "-vvv", "--logfile=Logs.log"
                };

                mediaPlayer.SetMedia(new FileInfo(@"Files\Atomic.mp3"), mediaOptions);
                mediaPlayer.Play();
            }

Result:
[0910e338] main tls client error: connection error: Interrupted function call
[09159858] stream_out_chromecast stream out error: cannot load the Chromecast controller (Failed to create client session)
[091370e8] main stream output error: stream chain failed for `chromecast{ip=192.168.16.1, demux-filter=demux_chromecast}'
[09159d78] main input error: cannot start stream output instance, aborting

- [*] I confirm that my issue doesn't happen in VLC itself.
VLC:
"C:\Program Files\VideoLAN\VLC\vlc.exe" "C:\Temp\Atomic.mp3" --sout "#chromecast{ip=192.168.16.1, demux-filter=demux_chromecast}"

Which works
VLC version: 3.0.4

Can anyone let me know what i suspect I'm doing wrong?

Thanks,
Richie

**Comment by jeremyVignelles** [comment]
Not sure if chromecast is supported as-is with libvlc, and I've never seen anyone trying with Vlc.DotNet.
LibVLCSharp however has tested support for chromecast, I'd recommend that you try it 🙂

**Comment by RichieRogers** [comment]
I've had a play around with LibVLCSharp and just got it working, so will look at using that.
VLC.dotnet looked to be the "neater" solution, so shame I can't use that.

Thanks,
Richie

**Comment by jeremyVignelles** [comment]
I'm glad it helped.
Please tell us how LibVLCSharp is neater than Vlc.DotNet.
LibVLCSharp was created after, to create a modern and cross-platform binding for the libvlc API.

The idea is to make LibVLCSharp the official binding for .NET, and it will be the first to support libvlc 4.

Please tell us how you think Vlc.DotNet is neater and how we can improve LibVLCSharp.

Also, please don't hesitate to reach us on libvlcsharp's gitter to share your ideas :)

**Comment by RichieRogers** [comment]
I actually meant VLC.dotnet seems neater and i'd have preferred to keep using that.

Thanks,
Richie

**Comment by jeremyVignelles** [comment]
Yes, that's what I said. Please tell us why 🙂

**Comment by RichieRogers** [comment]
Hi,
For the bare basics of simply playing a file and, if it had worked, casting to a Chromecast, VLC.dotnet seemed to require a lot less code.
Perhaps, for more straightforward media playing, LibVLCSharp is easier and certainly appears to be pretty impressive. 
Keep up the good work,

Richie

**Comment by mfkl** [comment]
> For the bare basics of simply playing a file and, if it had worked, casting to a Chromecast, VLC.dotnet seemed to require a lot less code.

Can you be more specific please? Any feedback helps to make libvlcsharp better.

Your code from https://github.com/ZeBobo5/Vlc.DotNet/issues/637#issue-609153050 in libvlcsharp could give something like this:

```
Core.Initialize();
using var libvlc = new LibVLC();
using var mp = new MediaPlayer();
using var media = new Media(libvlc, new Uri(@"Files\Atomic.mp3"));
media.addOption(":sout=#chromecast{ip=192.168.16.1, demux-filter=demux_chromecast}");
media.addOption(":sout-keep");
media.addOption("--file-logging", "-vvv", "--logfile=Logs.log");
mp.Play(media);
```

You probably shouldn't mix libvlc options syntax though (pick `:` for media, not `--`).
