### ISSUE TITLE
Null Reference Exception When Disposing Many Viewers At Once

### ISSUE THREAD

**Issue by Nickprovs** [ZeBobo5/Vlc.DotNet#639]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : 3.0.8.0 - x64 + From VLC Media Player Directory
- **.net version** : 4.5.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** :  Windows 10 x64

# Summary

Launched 6-9 (no joke -- that's just the range I tested) RTMP streams in a grid. Then, on button press -- dispose of them. This exception seems to intermittently occur.

![Odd](https://user-images.githubusercontent.com/30559588/81112129-2e64b780-8eec-11ea-996a-67912522f425.PNG)

- [ X] I confirm that my issue doesn't happen in VLC itself.

If I add a null check in the fire-and-forget action -- I never get the exception again.
![MaybeFix](https://user-images.githubusercontent.com/30559588/81112288-65d36400-8eec-11ea-923c-11f34d54557e.PNG)

**Comment by jeremyVignelles** [comment]
Hi,
Can you open a PR for this one and #640 ?

Good finding 🙂

**Comment by Nickprovs** [comment]
Thanks! Added a PR for #639 and #640 .

PR at #641

**Comment by jeremyVignelles** [comment]
Fixed by #641 in v 3.1.0-develop372
