### ISSUE TITLE
Index Out of Range Exception When Disposing Many Viewers At Once

### ISSUE THREAD

**Issue by Nickprovs** [ZeBobo5/Vlc.DotNet#640]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : 3.0.8.0 - x64 + From VLC Media Player Directory
- **.net version** : 4.5.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** :  Windows 10 x64

# Summary

Launched 6-9 (no joke -- that's just the range I tested) RTMP streams in a grid. Then, on button press -- dispose of them. This exception seems to intermittently occur.

![Odd3](https://user-images.githubusercontent.com/30559588/81112681-09bd0f80-8eed-11ea-919f-31980c8266a3.PNG)

- [ X] I confirm that my issue doesn't happen in VLC itself.

If I add a lock around the work done with the myInteropDelegates dictionary in VLCLibraryLoader -- I don't get the exception anymore. I believe that because I'm opening many streams at once -- the insertions are happening too quickly on different threads and the dictionary's internal array is not resizing properly.

If I do this -- I no longer get this issue.

![MaybeFix3](https://user-images.githubusercontent.com/30559588/81113320-05ddbd00-8eee-11ea-9c61-aff9ec2499db.PNG)

**Comment by Nickprovs** [comment]
Added a pull request #641

**Comment by jeremyVignelles** [comment]
Fixed by #641 in v 3.1.0-develop372
