### ISSUE TITLE
Playing video from Byte Array takes huge RAM

### ISSUE THREAD

**Issue by graysuit** [ZeBobo5/Vlc.DotNet#643]
I have an issue about Vlc.DotNet.
Here's the full source code: <a href="https://github.com/graysuit/vlc.dotnet.issue.bytearray/tree/master/VB_Project">VB_Project</a>
Here's the single C# file: <a href="https://github.com/graysuit/vlc.dotnet.issue.bytearray/blob/master/C%23_Code/form1.cs">form1.cs</a>
Here's the windows binary <a href="https://github.com/graysuit/vlc.dotnet.issue.bytearray/tree/master/VB_Project/vlcplayer1/bin/Debug">Debug</a>

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86/x64 + nuget
- **.net version** : latest 4.8
- **Project language** : C#/VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows10_x86

# Summary

**Whenever I play video from byte array** then **it takes huge amount of CPU + memory.**
I am seeing this in task manager,

<h1>Analysis </h1>
<b>File size</b>== 3.1 MB<br>
<b>CPU usage</b> == 6%--14%<br>
<b>Memory</b> == 50 MB<br><br>

As you can see it is normal but **it get increases as file size increases,**
But same **streaming URL takes normal memory,**
Even file size is bigger or smaller.<br><br>

- [ ] I confirm that my issue doesn't happen in VLC itself. (in URL streaming video directly e.g http://video.mp4)

**Comment by jeremyVignelles** [comment]
Closing this since after investigations on twitter, it was normal, because you were reading the stream entirely into memory.
However, there is indeed an issue with CryptoStream : #647
