### ISSUE TITLE
winform Vlc crash witchout any hint while  Fast switching the url

### ISSUE THREAD

**Issue by wutangyuan** [ZeBobo5/Vlc.DotNet#644]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (Auto Select the Program version) (x86/x64) + Nuget
- **.net version** : (Net472)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows 10 Home) (x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))
winform Vlc crash witchout any hint while  Fast switching the url

I started a thread, switching a set of links every 10 seconds, and switching a url every 10 seconds inside the custom vlc control. However, they always crash for no reason. and the Windows Event Viewer also cannot find the reason

there are Demo: https://github.com/wutangyuan/VlcWinformCrashDemo
- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Can you narrow down your repo to the minimum? I see different things in your UI like DataTemplates and that makes things harder for me to analyze.

**Comment by wutangyuan** [comment]
> 
> 
> Can you narrow down your repo to the minimum? I see different things in your UI like DataTemplates and that makes things harder for me to analyze.

thank you for yor reply!  I had Push the minimum Code to the repo .

**Comment by wutangyuan** [comment]
hello,i have found that When I call  “stop()” and “play()” frequently, it will report the exception recycled by GC. But I didn't call GC .Finally, the program crashed.
![WechatIMG4](https://user-images.githubusercontent.com/50666934/82221260-58899100-9952-11ea-961b-fe920d386450.png)
![WechatIMG2](https://user-images.githubusercontent.com/50666934/82221271-5b848180-9952-11ea-9625-1ffbd0a3dff5.png)

**Comment by jeremyVignelles** [comment]
you are checking VlcProvider and its media player outside of your `Task.Factory.StartNew(() => )`, which can cause race conditions, because you don't know how long does it take for a thread to be available.

As a general advice, I would use `Task.Run()` instead of `Task.Factory.StartNew`

Do you really need it ? you don't seem to be inside a libvlc callback.

Also, your try/catch will never catch anything except task scheduling errors. Since you don't await the task, this function will continue and you will be out of the try/catch before the callback executes.

Please try to simplify your code, there seems to be something wrong with it.

**Comment by wutangyuan** [comment]
Hello,I simplified my code,and run the code. but The exception of kernelbase is often thrown.

**Comment by wutangyuan** [comment]
<img width="310" alt="834186c3788b53e1274c6a393ed8bb6" src="https://user-images.githubusercontent.com/50666934/82294118-350d2780-99e0-11ea-8145-b9f19b40cfd7.png">

**Comment by jeremyVignelles** [comment]
Why did you close this @wutangyuan ? How did you solve your issue ?

**Comment by wutangyuan** [comment]
> 
> 
> Why did you close this @wutangyuan ? How did you solve your issue ?
with some suggestions,I found that I could solve the problems by modifying the code.
![0ef7953ac9156654c4ae285485385b2](https://user-images.githubusercontent.com/50666934/82810878-203e0180-9ec2-11ea-870e-ce049656740f.jpg)

**Comment by jeremyVignelles** [comment]
Thanks so the issue was on your side then? Good to know you found an answer !

**Comment by wutangyuan** [comment]
> Thanks so the issue was on your side then? Good to know you found an answer !

This problem is caused by the resource competition of VLC player caused by multithreading.
thank you so much for your help!
