### ISSUE TITLE
Push an update to NuGet ?

### ISSUE THREAD

**Issue by RegisStGelais** [ZeBobo5/Vlc.DotNet#649]
The NuGet package manager for solution in visual studio still only show version 3.0.0

Is there a plan to update it ?

**Comment by jeremyVignelles** [comment]
The latest prerelease package has all the features from the develop branch. Yes, there will be an update to master (which will push a release package to NuGet), but no release date yet.

**Comment by RegisStGelais** [comment]
Tks for your answer. I noticed that there is a new project called VLCsharp.
I am only working on winForms. Is it worth migrating the new VLCsharp ?

**Comment by RegisStGelais** [comment]
I looked a bit at VLCsharp but I was not able to find a good example of winforms using the VideoView UI component.

**Comment by jeremyVignelles** [comment]
Hi,
Here it is : https://code.videolan.org/videolan/LibVLCSharp/-/tree/3.x/samples/LibVLCSharp.WinForms.Sample

As far as I know, you won't find the component inside the Visual studio designer (PRs welcome !), but it works.

I will close this thread since I answered your questions.

**Comment by RegisStGelais** [comment]
Tks for your help.
I was able to convert my project to use VLCsharp  :)
