### ISSUE TITLE
Exporting the video after variable crop settings

### ISSUE THREAD

**Issue by MRmP** [ZeBobo5/Vlc.DotNet#65]
Hi,
This might be a special case, and not really an issue but Ive tried to wrap my head around it for quite some time and I haven't found out how to do it, or if its possible.

What I'm trying to achieve is to play a video on my winform, then adjust zoom level and which part of the video im watching by using cropgeo,

Lets say I want to following an object on the video by zooming in and moving the "camera" to the left/right. I want to export this out to a new video. Either in realtime as the user is navigating, or to write down all crop settings then transcode the new video. 

Ive tried the recording option, but that seem to export the video without my zoom/crop settings.

Suggestions? ('m also open for other ways to capture it, as long as I do it in code and not use "fraps" and similar)

**Comment by AdamLytx** [comment]
Did you get a solution?

**Comment by jeremyVignelles** [comment]
I don't really know how to solve this issue, but it doesn't look like it's something that should be implemented in Vlc.DotNet, and I'm not aware of any current way to do this with libvlc itself.

I'm closing this, feel free to reopen if there is something we can do.
