### ISSUE TITLE
Video background flickers on window resize

### ISSUE THREAD

**Issue by Pangger** [ZeBobo5/Vlc.DotNet#651]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.2.2-develop246)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (Please fill) (x86/x64)
- **.net version** : (4.7.2)
- **Project language** : (C#)
- **Project build architecture** : (x86/x64)
- **Operating system** : (Windows 10 Pro) (x64)

# Summary

When i start resizing the app window, background of video(left and right black lines) starts flickering.

**Comment by mfkl** [comment]
Share a repro project please. Video of what you see also, if you can

**Comment by jeremyVignelles** [comment]
Are you really using a 2.x version? Is there any good reason why you don't upgrade to the 3.x WinForms?

**Comment by Pangger** [comment]
Here is the video. libvlc version is 3.0.7
[bandicam 2020-06-11 14-57-34-715.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/4764783/bandicam.2020-06-11.14-57-34-715.zip)

**Comment by mfkl** [comment]
> 
> 
> Here is the video. libvlc version is 3.0.7
> [bandicam 2020-06-11 14-57-34-715.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/4764783/bandicam.2020-06-11.14-57-34-715.zip)

Doesn't play in VLC. Try updating vlc.dotnet as jeremy suggested.

**Comment by jeremyVignelles** [comment]
Indeed, the file length is 0 inside the zip...

**Comment by jeremyVignelles** [comment]
Closing since it didn't have any replies in a while.
