### ISSUE TITLE
How to set the Display  to fill the whole VLC control

### ISSUE THREAD

**Issue by wutangyuan** [ZeBobo5/Vlc.DotNet#652]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (Please 3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** :  (x64) +Nuget
- **.net version** : (472)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows X64) 

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

How to set the Display  to fill the whole VLC control，I try to  set   VlcProvider.Video.AspectRatio = $"{(int)this.ActualWidth+20}:{(int)this.ActualHeight}";  but the effect is not good,there's always a black edge on the video.

How to set the screen to fill the whole control with different video streams?

![1592904341(1)](https://user-images.githubusercontent.com/50666934/85387048-ef132880-b576-11ea-8e01-fea24a005ab4.jpg)

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
Here is an example of how this is done in LibVLCSharp in the MediaPlayerElement:

https://code.videolan.org/videolan/LibVLCSharp/-/blob/3.x/src/LibVLCSharp/Shared/MediaPlayerElement/AspectRatioManager.cs#L130

Update the AspectRatio:
- When the ESChanged event is triggered (this is when you can get the Width and Height
- Each time your view is resized

**Comment by wutangyuan** [comment]
> 
> 
> Hi,
> Here is an example of how this is done in LibVLCSharp in the MediaPlayerElement:
> 
> https://code.videolan.org/videolan/LibVLCSharp/-/blob/3.x/src/LibVLCSharp/Shared/MediaPlayerElement/AspectRatioManager.cs#L130
> 
> Update the AspectRatio:
> 
>     * When the ESChanged event is triggered (this is when you can get the Width and Height
> 
>     * Each time your view is resized

Thank for you reply.I found that as long as I set  VlcProvider.Video.AspectRatio = $"{VlcProvider.Width}:{VlcProvider.Height}", I can solve the problem

![1592964238(1)](https://user-images.githubusercontent.com/50666934/85489302-63df7480-b602-11ea-85fb-b80bc466f95a.jpg)
