### ISSUE TITLE
vlcControl: Display controls for pause, stop, rewind, etc.

### ISSUE THREAD

**Issue by rrirower** [ZeBobo5/Vlc.DotNet#656]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0
- **Vlc.DotNet project used** : Winforms
- **libvlc version** : 3.0.11 x64 from Nuget.
- **.net version** : 4.8
- **Project language** : C#
- **Project build architecture** : x64 (prefer 32bits))
- **Operating system** : Windows x64

# Summary

I have the control embedded in a winform.  It shows the video correctly.  Is there a way (method, property) to display controls to manage the video (ie. pause, plays, stop, rewind, forward, etc.)?  Or, do I need to handle that myself?

**Comment by jeremyVignelles** [comment]
Second option, they're not part of the libvlc API.
LibVLCSharp has a MediaPlayerElement to do that, but it is made for Xamarin.Forms.
