### ISSUE TITLE
How to control Equalizer

### ISSUE THREAD

**Issue by subh-kundu** [ZeBobo5/Vlc.DotNet#657]
I have an issue equalizer about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.1.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** 3.0.8.0
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (x64)
- **Operating system** : (Windows 10) (x64)

# Summary

How to adjust 10band graphic equalizer and amplifier. please provide code.
is it possible

**Comment by jeremyVignelles** [comment]
You can do that with the same options as the VLC command line, but as far as I know, you can't adjust the equalizer dynamically at runtime.

**Comment by subh-kundu** [comment]
![Untitled](https://user-images.githubusercontent.com/64629942/87576100-7d9a4600-c6ee-11ea-889e-53db58e09968.png)
what is the command line?
I have found this equalizer code on codeproject.com it was nVLC.LibVlcWrapper something

**Comment by jeremyVignelles** [comment]
Do your own researches and share your findings here. I don't know every aspect of VLC.

https://wiki.videolan.org/VLC_command-line_help

**Comment by mfkl** [comment]
there is a libvlc equalizer api but its not surfaced by vlc.dotnet.
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__audio.html#gad252fff10bf02bc8436b3beab4badef9

**Comment by jeremyVignelles** [comment]
Does that mean it is exposed by LibVLCSharp ?

**Comment by mfkl** [comment]
Yes.

**Comment by subh-kundu** [comment]
I agree with Mr. mfkl 
**there is a libvlc equalizer api but its not surfaced by vlc.dotnet.**
pls. update it is very important every users and programmers

Image adjustment is available such as (hue, brightness, contrast, saturation, gamma) working perfectly but not audio equalizer available right now.

Hi all users please share your projects, next time i share my project.

**Comment by jeremyVignelles** [comment]
> pls. update it is very important every users and programmers

I've been maintaining this project for 3-4 years and as far as I know, this has never been asked. Since Vlc.DotNet is going into maintenance mode, I'm not sure it is worth the effort to add new features here. I encourage you to switch to LibVLCSharp.
However, if you create the PR for that, I might merge it. Otherwise, I'll let this open for someone interested to implement that.

**Comment by subh-kundu** [comment]
Hi
jeremyVignelles, thanks your quick response. I your project followed 3 years ago, but never share my experience because it's a very good platform for every one learn and quickly coding and make own project quickly, no doubt  Vlc.DotNet is a good.

but it is very important for me make a basic media player, this features
audio equalizer, Image adjustment (it's already make it), run time change visualization

regards,
subh

**Comment by subh-kundu** [comment]
hi
all don't judge me for my coding, it's messy i'm not a good programmer

**Comment by jeremyVignelles** [comment]
Can you upload that on a github repository instead? it's easier to review, especially on mobile.

**Comment by subh-kundu** [comment]
okay sir, give me few days I upload my github account.

**Comment by jeremyVignelles** [comment]
Vlc.DotNet is in maintenance mode and will not get any new features. LibVLCSharp has the feature implemented.
