### ISSUE TITLE
Change playback rate without audio lag

### ISSUE THREAD

**Issue by AqlaSolutions** [ZeBobo5/Vlc.DotNet#659]
Whenever I change the `Rate` property on a player the audio disappears for a second or so. Are there any options to avoid such lag when changing the rate?

**Comment by jeremyVignelles** [comment]
Please fill the issue template and describe what you're trying to play. A sample code and verbose logs would also be appreciated

**Comment by AqlaSolutions** [comment]
I thought it's a pretty common issue that happens on any video files - whenever you try to change playback rate you have to wait the lag before you can continue watching. Ok, I'll come back after I collect the logs.

This is only audio-related lag. It seems there is some audio buffer which needs to be refilled after changing the rate but it happens only after some period of time.

**Comment by jeremyVignelles** [comment]
I don't think that the whole playback rate is something that is very well tested on the libvlc side. There's probably a bug to report in here.

As for the workarounds, you could try to have a look at network caching...

**Comment by jeremyVignelles** [comment]
Closing as it is likely a libvlc bug.
