### ISSUE TITLE
Audio Channels in VLC_Control

### ISSUE THREAD

**Issue by F-Alireza** [ZeBobo5/Vlc.DotNet#66]
Hey Guys :
im in a bad Trouble. i have Some Video Files that have 4 or 6 Audio Channels.
 but how can i detect each audio channel level????
i wanna design Audio bar for each channel .

tnQ for you answers.....

**Comment by xDoJohn** [comment]
Try this code..., otherwise you could always use MediaInfo, just ask me for a sample.

var mediaInformations = myVlcControl.GetCurrentMedia().TracksInformations;
            foreach (var mediaInformation in mediaInformations)
            {
                if (mediaInformation.Type == Core.Interops.Signatures.MediaTrackTypes.Audio)
                {
                    int ChannelNumbers = mediaInformation.Audio.Channels;
                }
            }

**Comment by jeremyVignelles** [comment]
An answer has been provided but no feedback from original poster, closing.
