### ISSUE TITLE
该视频我开久会模糊是什么问题造成的

### ISSUE THREAD

**Issue by superghy** [ZeBobo5/Vlc.DotNet#662]
我连摄像头 我开久会模糊是什么问题造成的,有时开的次数多也会加载不了

**Comment by jeremyVignelles** [comment]
Issues are only posted in english. I don't understand your language.

Please also fill the issue template.

**Comment by superghy** [comment]
> Issues are only posted in english. I don't understand your language.
> 
> Please also fill the issue template.

I use this component to play the camera. If I play it for a long time, it will blur what's causing it,


code:
     vlcControl1.Play(jkip1);

**Comment by jeremyVignelles** [comment]
Probably unrelated with this component. Try with VLC itself and with another player, but the culprit might be the camera.
