### ISSUE TITLE
--repeat comand doesn't work in Vlc.DotNet.WPF

### ISSUE THREAD

**Issue by nusuev** [ZeBobo5/Vlc.DotNet#663]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0
- **Vlc.DotNet project used** : WPF & Core
- **Project language** : C#
- **Operating system** : Windows  x64

# Summary

I am trying to retrieve the rtsp stream from my server, and when I disconnect vlc (after sending a Teardown request), I want the vlc to reconnect.
When run from the console (`vlc --repeat --rtsp-tcp rtsp://ip:port`) everything works. But when running from wpf application, the --repeat command doesn't work.

```
var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

this.VlcControl.SourceProvider.CreatePlayer(libDirectory, new string[] { "--rtsp-tcp", "--repeat" });

string liveLink = $"rtsp://{ip}:{port}/{kid}";

this.VlcControl.SourceProvider.MediaPlayer.Play(liveLink);
```

already tried using the command `--loop` and `--insert-repeat=65535`
nothing works
can anyone suggest a solution to the issue?

**Comment by mfkl** [comment]
some flags work only in VLC, not in libvlc. See https://github.com/ZeBobo5/Vlc.DotNet/issues/96 for alternatives.
