### ISSUE TITLE
 PDB cant be open or found vlc interpos

### ISSUE THREAD

**Issue by martinmachain** [ZeBobo5/Vlc.DotNet#667]
when i debug a project visual studio net form with a vlc controll a message appears:
C:\Users\Administrator\source\repos\web 7\WebPlayer\WebPlayer\bin\x64\Debug\Vlc.DotNet.Core.Interops.pdb:  PDB cant be open or found.

I assigned the lib vlc folder and the error still happens, i search manually the pdb but i dont found it

**Comment by mfkl** [comment]
Hi,

I don't think the PDBs are shipped. Please use the issue template though

**Comment by jeremyVignelles** [comment]
They're not shipped and will not be. Maybe for LVS?
