### ISSUE TITLE
how do i show srt subtitles?

### ISSUE THREAD

**Issue by miunidll** [ZeBobo5/Vlc.DotNet#669]
I have a question about Vlc.DotNet.

I looked up the documentary and I did not find anything that explains how to use srt files and show on video.

can somebody just explain? a simple video with subtitles.

- I confirm that my issue doesn't happen in VLC itself.

**Comment by mfkl** [comment]
https://github.com/ZeBobo5/Vlc.DotNet/issues/432

https://github.com/ZeBobo5/Vlc.DotNet/issues/543

https://github.com/ZeBobo5/Vlc.DotNet/issues/426

https://github.com/ZeBobo5/Vlc.DotNet/issues/147

**Comment by miunidll** [comment]
> #432
> 
> #543
> 
> #426
> 
> #147

thx
