### ISSUE TITLE
Mouse events not firing during video playback

### ISSUE THREAD

**Issue by InfiniteImp** [ZeBobo5/Vlc.DotNet#674]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64, via Package Manager
- **.net version** : 4.7.2
- **Project language** : VB
- **Project build architecture** : AnyCPU/
- **Operating system** : Win10 x64

# Summary

I can't get the VLC control to recognize mouse movement or input while playing a video.  I searched other issues and found a reference to "SetMouseInput" but can't find such a property.  I did find VlcControl1.Video.IsMouseInputEnabled but setting that to True or False doesn't change anything.  What do I need to set so that I can read mouse movement and clicks?

Thanks.

- [X] I confirm that my issue doesn't happen in VLC itself.  Right-click in VLC while playing a movie does pop up a menu.

**Comment by jeremyVignelles** [comment]
`IsMouseInputEnabled = False` should be the way to go.
Did you try to handle events at the Forms level rather than on the video control or the other way around?

**Comment by InfiniteImp** [comment]
I just tried it and the form isn't getting the mouse events either.  I now have trace code both in the control _MouseMove and _MouseClick as well as the them and neither is firing.  

Does it matter where the IsMouseInputEnabled is?  I tried it both in Form_Load as well as just after starting video playback.  Neither worked.

**Comment by jeremyVignelles** [comment]
I'd place it just after the media player creation, but it shouldn't matter that much, because there's nothing about that on the documentation : https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__video.html#gad53def725dd5a50a3823b68ed31bca1a

Can you share a minimal repro so we can try locally ?

**Comment by InfiniteImp** [comment]
Ok, I've created a sample project.  You'll notice that before the video starts playing, mouse events are captured.  When it starts playing, mouse movement events no longer fire.

It's a VS 2019 project.  May be a bit big (with all the supporting files) but you should be able to just unzip it and test.

OneDrive link is below.
https://1drv.ms/u/s!ArGs7qZ8uBHEjgdkGALLW08A3zhL?e=454z66

**Comment by jeremyVignelles** [comment]
As said here, it seems that you need to set both IsMouseInputEnabled and IsKeyInputEnabled to false for it to work, not sure why : 
https://github.com/ZeBobo5/Vlc.DotNet/issues/473#issuecomment-433434865

**Comment by InfiniteImp** [comment]
Perfect, that worked!  Thanks!

In case this comes up in the future for anyone, I needed to do VlcControl1.Video.IsMouseInputEnabled = False and   vlcControl1.Video.IsKeyInputEnabled = False in Form_Shown in order for this to work.  

I'll close this ticket.
