### ISSUE TITLE
RTSP to file transcode, no video stream

### ISSUE THREAD

**Issue by monotwist** [ZeBobo5/Vlc.DotNet#676]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64, installed package in Visual Studio
- **.net version** : Framework 4.8
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 x64

# Summary
Transcoded file contains video stream when libPath set to VLC Player (3.0.11) root folder. 
When it is set to nuget package's path (_bin\Debug\libvlc\win-x64_) there is only audio stream
```
using (var vlcPlayer = new Vlc.DotNet.Core.VlcMediaPlayer (new DirectoryInfo (libPath)))
{
    var rtspUrl = new Uri("rtsp://hidden.com:6620/" + param3); //param3 == auth data
    var recFileName = Path.Combine (recordsPath, $"{DateTime.Now:dd.MM.yyyy_HH-mm-ss}.mp4");
    var recPrm = ":sout=#transcode{vcodec=mp4v,vb=750,scale=1,acodec=mp3,ab=64}:std{access=file,mux=mp4,dst=" + recFileName + "}";
    vlcPlayer.SetMedia (rtspUrl, recPrm);
    vlcPlayer.Play ();
    
    while(vlcPlayer.Time <= 0)
    {
        await Task.Delay(500);
    }
    var startTime = vlcPlayer.Time;
    while(vlcPlayer.Time - startTime < 15 * 1000)
    {
        await Task.Delay(500);
    }

    vlcPlayer.Stop();
}
```

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
That's expected because that's how libvlc works: You can't transcode the stream and show it at the same time, as far as I know
