### ISSUE TITLE
parameter   network-caching   do not function

### ISSUE THREAD

**Issue by lucasnaidero** [ZeBobo5/Vlc.DotNet#677]
I have an issue / a question (pick one) about Vlc.DotNet.

I try to insert the parameter following
:network-caching=20
but   do not function, I have a delay about 1000 ms

# Generic information

- **Vlc.DotNet version** : 3.1
- **Vlc.DotNet project used** : (WinForms
- **libvlc version** : (/x64) 
- **.net version** : 4.7.2
- **Project language** : (C#/VB.net)
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows ...) (x86/x64)

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

- [x] I confirm that my issue doesn't happen in VLC itself. With VLC with :network-caching=20  I don't feel dalays

**Comment by jeremyVignelles** [comment]
This has nothing to do with Vlc.DotNet. Please try with the same VLC version than your libvlc.
VLC 2.x indeed honored that value for very small values of network-caching, but that's not the case with VLC 3.x.
Delays with VLC is a well-known issue.

**Comment by lucasnaidero** [comment]
VLC is 3.0.10
libvlc il 3.0.11.0
i think they are really similar, but the behaviour isn't 
it is my opinion that the options do not are taken by the software.
can you suggest me an option to use to test  if the functionallity is correct?

In any case I write also the code I wrote to define the VlcMediaplayerOptions :

  this.vlcControl1.Text = "vlcControl1";
            this.vlcControl1.VlcLibDirectory = null;
            this.vlcControl1.VlcMediaplayerOptions = new string[] {
        ":network-caching=20",
        ":file-caching=20"};
            this.vlcControl1.VlcLibDirectoryNeeded += new System.EventHandler<Vlc.DotNet.Forms.VlcLibDirectoryNeededEventArgs>(this.vlcControl1_VlcLibDirectoryNeeded);
            //

**Comment by jeremyVignelles** [comment]
use -- for VlcMediaPlayerOptions, and IIRC, the key and value must be in two different strings, like `"--network-caching", "20",`

**Comment by Lua12138** [comment]
> use -- for VlcMediaPlayerOptions, and IIRC, the key and value must be in two different strings, like `"--network-caching", "20",`

I tried 
```csharp
var vlc = new VlcControl();
var vlc_options = new string[] { "--demux", "h264", "--udp-caching", "0", "--tcp-caching", "0", "--realrtsp-caching", "0", "--network-caching", "0", "--no-ts-trust-pcr", "--sout-ts-shaping", "10", "sout-ts-dts-delay", "20" };
vlc.VlcMediaplayerOptions = vlc_options;
vlc.VlcLibDirectoryNeeded += VlcLibDirectoryNeeded;
((System.ComponentModel.ISupportInitialize)(vlc)).EndInit();
vlc.Play(new MyStream(socketVideo), vlc_options);
```

but it not works, always 2s delay

**Comment by jeremyVignelles** [comment]
Please read my other statement that VLC 3 doesn't honor the low values of network-caching.

libvlc4 will have a low-delay option (but libvlc4 will not be compatible with vlc.DotNet)

As a rule of thumb, try with VLC and if it doesn't work either, it's not an issue with this project
