### ISSUE TITLE
1

### ISSUE THREAD

**Issue by sundermanhqd** [ZeBobo5/Vlc.DotNet#678]

**Comment by jeremyVignelles** [comment]
Not sure what you mean by "trimming audio" but that doesn't *sound* like something VLC does. As for audio conversion, please use the same parameters as VLC.

**Comment by sundermanhqd** [comment]
> Not sure what you mean by "trimming audio" but that doesn't _sound_ like something VLC does. As for audio conversion, please use the same parameters as VLC.

Can you show me example, please how to convert


Trim video: 
I have mp4 file for example 

Duration video 1 minute 
I need two video, 30 sec duration each

**Comment by jeremyVignelles** [comment]
I don't know, that's not the right place to ask.
Try to do that with the VLC command line, and then use that command line in Vlc.DotNet.
