### ISSUE TITLE
Memory leak for every new media?

### ISSUE THREAD

**Issue by xDoJohn** [ZeBobo5/Vlc.DotNet#68]
Everytime i load a new file, the total used memory of my application keeps increasing...

**Comment by DominikPalo** [comment]
Me too... after playing 5-6 videos my app consumes 1GB RAM and then crashes

**Comment by xDoJohn** [comment]
Someone has created a fix for the issue:

https://github.com/ajhatt-catapult/Vlc.DotNet/commit/019166a7c9e77a1b2e2ac8e97de3cbb07ad2981c
