### ISSUE TITLE
如何通过VlcMediaPlayer获取视频的原始宽和高?

### ISSUE THREAD

**Issue by fgh345** [ZeBobo5/Vlc.DotNet#680]
播放器在初始化后 没有返回此参数

**Comment by mfkl** [comment]
Please use english and follow the issue template.

**Comment by fgh345** [comment]
How to get the original width and height of video through VlcMediaPlayer?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mfkl"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 下午2:41
收件人: "ZeBobo5/Vlc.DotNet"<Vlc.DotNet@noreply.github.com&gt;; 
抄送: "君值韶华莫等闲"<1145073867@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ZeBobo5/Vlc.DotNet] 如何通过VlcMediaPlayer获取视频的原始宽和高? (#680)





 
Please use english and follow the issue template.

**Comment by fgh345** [comment]
mediaPlayer.SetVideoFormatCallbacks(vFormat,clearUp);

private uint VideoFormat(out IntPtr userdata, IntPtr chroma, ref uint width, ref uint height, ref uint pitches, ref uint lines)

**Comment by mfkl** [comment]
Please check older issues, it's been asked before https://github.com/ZeBobo5/Vlc.DotNet/issues/243
Using the callbacks isn't really the way to go, unless you want to handle the rendering yourself.

**Comment by fgh345** [comment]
I want to make drag zoom, so I use width and height to calculate the ratio




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mfkl"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 下午2:51
收件人: "ZeBobo5/Vlc.DotNet"<Vlc.DotNet@noreply.github.com&gt;; 
抄送: "君值韶华莫等闲"<1145073867@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [ZeBobo5/Vlc.DotNet] 如何通过VlcMediaPlayer获取视频的原始宽和高? (#680)





 
Please check older issues, it's been asked before #243
 Using the callbacks isn't really the way to go, unless you want to handle the rendering yourself.
