### ISSUE TITLE
The sound will be distorted

### ISSUE THREAD

**Issue by ycl0120** [ZeBobo5/Vlc.DotNet#681]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** :  3.0.11.0 x86 + official Website
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 x64

# Summary
I want to do a little program about AB Loop Player with Vlc.DotNet, but I have one problem.
The sound will be distorted if I change rate to 0.8 and change position.
If rate equal 1 and change position anyway, the sound is always nice.
I don't know how to solve it.

vlcControl1.Rate = 0.8; //speed slower
vlcControl1_TimeChanged(object sender, Vlc.DotNet.Core.VlcMediaPlayerTimeChangedEventArgs e){
    if ( e.NewTime >= bPosition)   {   //AB Loop
        vlcControl1.Position = aPosition;
    }
}

- [V] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
That's probably not a Vlc.DotNet issue but rather a libvlc issue

**Comment by ycl0120** [comment]
Thanks for your reply.
I try this with VLC media player and it's ok, 
So, I think that  maybe my programming is not good.
Could you give me more advice?

**Comment by jeremyVignelles** [comment]
You could create a minimal dotnet project that reproduces the issue (like a console app) and host that on github
You could try to reproduce with a C code in this sample : https://github.com/jeremyVignelles/TestLibvlcNative
You could also ask the videolan devs and open a ticket in their bug tracker.

**Comment by ycl0120** [comment]
Thank you very much, Mr. jeremyVignelles.
