### ISSUE TITLE
winform sample for get frame 

### ISSUE THREAD

**Issue by masgh021** [ZeBobo5/Vlc.DotNet#683]
hello ,
i search this sample [wpfsample](https://github.com/ZeBobo5/Vlc.DotNet/blob/fb42e9a59950fcc27738d0f36477812727ee2152/src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs#L111-L112)
But i can't understand it ,
is  there a sample for winform to get every frame from video ???
please send link .

**Comment by Upanc** [comment]
try SetVideoCallbacks,or see https://www.codeproject.com/Articles/109639/nVLC

**Comment by digibum** [comment]
Same here. There is no simple sample that would show how to get Bitmap from each frame for later proccessing.

The WPF sample isnt working for me: Attempted to read or write protected memory...
@Upanc link uses another wrapper, not a solution for me.

And also no good documentation on SetVideoFormatCallbacks and SetVideoCallbacks.

**Comment by jeremyVignelles** [comment]
Vlc.DotNet is not maintained anymore, so I won't be documenting those APIs

I highly recommend that you switch to LibVLCSharp instead of Vlc.DotNet, or if you want a lower-level solution, FFMpeg.Autogen

**Comment by digibum** [comment]
Thank you @jeremyVignelles!
Actualy I'm using LibVlcSharp but it's the same there. No usable sample for frame extraction.

**Comment by jeremyVignelles** [comment]
Then you missed the [Thumbnailer example](https://code.videolan.org/mfkl/libvlcsharp-samples/-/tree/master/PreviewThumbnailExtractor)

**Comment by digibum** [comment]
I have used that sample, but it uses code:
sourceStream.Read(MemoryMarshal.AsBytes(image.GetPixelMemoryGroup().Single().Span))
wich is not available in .Net 4.8 and I havent found an alternative for this method.

**Comment by jeremyVignelles** [comment]
That's because it uses ImageSharp, it just means "read in your own buffer". You can have a look at [this other sample using SkiaSharp](https://code.videolan.org/mfkl/libvlcsharp-samples/-/tree/master/)

Anyway, please stop spamming here, you're in the wrong repo.
