### ISSUE TITLE
Some command lines work, others don't

### ISSUE THREAD

**Issue by VitorS0uza** [ZeBobo5/Vlc.DotNet#684]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86
- **.net version** : 4.7.2
- **Project language** :VB.net
- **Project build architecture** :AnyCPU (prefer 32bits))
- **Operating system** : Windows 10 x64

# Summary

Commands like --no-video work perfectly, but when I try to trigger an audio filter like scaletempo_pitch, it doesn't work. At the Windows command prompt it works perfectly, but not at DotNet.

I am entering the following commands one per line in the properties window
`--audio-filter=scaletempo_pitch
--pitch-shift=-12.00000`

And nothing happens. Can someone help me?

**Comment by jeremyVignelles** [comment]
I just learned yesterday that audio filters can't be used in libvlc, it's a known libvlc issue, but I don't know if it has already been reported

**Comment by VitorS0uza** [comment]
Thanks for the answer. do you know any other similar lib that has some similar filters and audio effects?

**Comment by jeremyVignelles** [comment]
Unfortunately, I don't
