### ISSUE TITLE
scaletempo_pitch filter not working

### ISSUE THREAD

**Issue by jiatao99** [ZeBobo5/Vlc.DotNet#685]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : NuGet latest
- **Vlc.DotNet project used** : WinForm
- **libvlc version** :  x64
- **.net version** : .net 5
- **Project language** : c#
- **Project build architecture** : AnyCPU
- **Operating system** : Win64

# Summary scaletempo_pitch filter not working

```
      var options = new string[] { $"--pitch-shift=2", "--audio-filter=scaletempo_pitch" };
       //VlcMediaPlayer Player instance
       Player.Play(new System.IO.FileInfo(_current.Path), options);
```

This there anyway to change audio tone and still sync with Video? VLC GUI works perfectly.

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Audio filters cannot be used through libvlc. That's a limitation of libvlc.
