### ISSUE TITLE
how to split or cut a video？

### ISSUE THREAD

**Issue by BigQ517** [ZeBobo5/Vlc.DotNet#686]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : (x86/x64)  
- **.net version** : .net 4.6
- **Project language** :C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows x64

# Summary

how to split or cut a video？

**Comment by jeremyVignelles** [comment]
This is not the proper place to ask questions like these : 
- Either you know how to do that with the VLC command line, and in that case you just apply the same command line parameters to Vlc.DotNet
- Or you don't know how to do that with VLC, and I suggest you to start from here : https://wiki.videolan.org/VLC_command-line_help
