### ISSUE TITLE
"Direct Show Device Fails to Open"  If it Contains a Failed Device in a List of Capture Devices

### ISSUE THREAD

**Issue by appysrinath** [ZeBobo5/Vlc.DotNet#687]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.1.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (3.0.12.0) (x64) + Official VLC
- **.net version** : (4.6.1)
- **Project language** : (VB.net)
- **Project build architecture** : (x64)
- **Operating system** : (Windows 10) (x64)

# Summary

Im Trying To Open a Direct Show Device
But It Fails to Open By Showing a *Wrong Direct Show Device* Name

For Ex: I Have Selected "Exxxx Vxxx Dxxx#1"
It Shows Error Opening "CxxxxxSxxxPxxx"

if The Device "CxxxxxSxxxPxxx" is Removed it Plays "Exxxx Vxxx Dxxx#1" Device AV Correctly

(What happens, when, how? Steps to reproduce (with sample codes))

For Ex: I Have Selected "Exxxx Vxxx Dxxx#1"
It Shows Error Opening "CxxxxxSxxxPxxx"

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Please share the code you're using to select the device. Did you try with the VLC command line?

**Comment by appysrinath** [comment]
> Please share the code you're using to select the device. Did you try with the VLC command line?

**Did you try with the VLC command line?**  _Yes Sir... It Working Fine_

Vlc Command Line : "C:\Program Files\VideoLAN\VLC\vlc.exe" dshow:// :dshow-vdev="Ekomsys Video Device#1" :dshow-adev="Ekomsys Audio Device#1"

VB.Net : *VlcControl1.Play("dshow://:dshow-vdev=Ekomsys Video Device#1 :dshow-adev=Ekomsys Audio Device#1")*

This is The Code Im Using..

**Comment by jeremyVignelles** [comment]
try:
`VlcControl1.Play("dshow://", ":dshow-vdev", "Ekomsys Video Device#1", ":dshow-adev", "Ekomsys Audio Device#1")`

Parts that start with `:` are options, and are not part of the MRL.

Is there any good reason you're not using LibVLCSharp instead of this project ?

**Comment by appysrinath** [comment]
> try:
> `VlcControl1.Play("dshow://", ":dshow-vdev", "Ekomsys Video Device#1", ":dshow-adev", "Ekomsys Audio Device#1")`
> 
> Parts that start with `:` are options, and are not part of the MRL.
> 
> Is there any good reason you're not using LibVLCSharp instead of this project ?

Im Very Slow in **LibVLCSharp** Sir...

The Same Old Problem Sir After Using `VlcControl1.Play("dshow://", ":dshow-vdev", "Ekomsys Video Device#1", ":dshow-adev", "Ekomsys Audio Device#1")` This code

[Log.txt](https://github.com/ZeBobo5/Vlc.DotNet/files/6363564/Log.txt)

**Comment by jeremyVignelles** [comment]
try variations like:
`VlcControl1.Play("dshow://", new [] { ":dshow-vdev=\"Ekomsys Video Device#1\"", ":dshow-adev=\"Ekomsys Audio Device#1\"" })`

**Comment by appysrinath** [comment]
> try variations like:
> `VlcControl1.Play("dshow://", new [] { ":dshow-vdev=\"Ekomsys Video Device#1\"", ":dshow-adev=\"Ekomsys Audio Device#1\"" })`


I Just Found Where the Issue is But I Can't Solve it...

Sir... For Ex : If There is Following Devices Alphabetically 

BLACKMAGIC WDM CAPTURE
CHANNEL STUDIO PRO
DECKLINK VIDEO CAPTURE
Ekomsys Video Device#1

its Choosing The **First Device** According to Alphabetically Even if We Are Are Specifying The Device Name Also its Not Considering
Its Not issue With The Code...

**Comment by jeremyVignelles** [comment]
Please try variations of what I sad above, maybe removing the quotes, like so : `":dshow-vdev=Ekomsys Video Device#1"`
If you have other devices, does it work when you select any other device that is not the first ?

Otherwise, send me full verbose logs.

**Comment by appysrinath** [comment]
> Please try variations of what I sad above, maybe removing the quotes, like so : `":dshow-vdev=Ekomsys Video Device#1"`
> If you have other devices, does it work when you select any other device that is not the first ?
> 
> Otherwise, send me full verbose logs.

Sorry Im Unable To Start Logger  Please Help For Starting Im Unable to Compose The Code

**Comment by appysrinath** [comment]
> Please try variations of what I sad above, maybe removing the quotes, like so : `":dshow-vdev=Ekomsys Video Device#1"`
> If you have other devices, does it work when you select any other device that is not the first ?
> 
> Otherwise, send me full verbose logs.

[---Logs---.log](https://github.com/ZeBobo5/Vlc.DotNet/files/6365680/---Logs---.log)

**Comment by appysrinath** [comment]
> Please try variations of what I sad above, maybe removing the quotes, like so : `":dshow-vdev=Ekomsys Video Device#1"`
> If you have other devices, does it work when you select any other device that is not the first ?
> 
> Otherwise, send me full verbose logs.

**Following Works Perfectly with VLC Even If We Are Having Multiple Devices**
`"C:\Program Files\VideoLAN\VLC\vlc.exe" dshow:// :dshow-vdev="Ekomsys Video Device#1" :dshow-adev="Ekomsys Audio Device#1"`

But in Code `VlcControl1.Play("dshow://:dshow-vdev=""Ekomsys Video Device#1"":dshow-adev=""Ekomsys Audio Device#1")` This is Having Issue If We Are Having Multiple Devices

**Comment by jeremyVignelles** [comment]
Please split the arguments in separate strings, `dshow://` is the MRL, and the other things are media player options.

**Comment by appysrinath** [comment]
> Please split the arguments in separate strings, `dshow://` is the MRL, and the other things are media player options.

Tried This But No Use Sir....
`VlcControl1.Play("dshow://", ":dshow-vdev=Ekomsys Video Device#1", ":dshow-adev=Ekomsys Audio Device#1")`


Have You Checked The Logs Sir....
[---Logs---.log](https://github.com/ZeBobo5/Vlc.DotNet/files/6367261/---Logs---.log)

**Comment by appysrinath** [comment]
> Please split the arguments in separate strings, `dshow://` is the MRL, and the other things are media player options.

Sir Can You Help Me in Solving This Issue Please....?

**Comment by jeremyVignelles** [comment]
> Have You Checked The Logs Sir....

Yeah, I've looked at them, and that's why I told you to  split the arguments. If you don't do what I'm doing, and don't send me the appropriate logs, I won't waste my time trying to play the guessing game.

**Comment by appysrinath** [comment]
> try variations like:
> `VlcControl1.Play("dshow://", new [] { ":dshow-vdev=\"Ekomsys Video Device#1\"", ":dshow-adev=\"Ekomsys Audio Device#1\"" })`

Thank You Sir For Your Help........ My Issue is Resolved By The Following Code....
`VlcControl1.Play("dshow://", ":dshow-vdev=Ekomsys Video Device#1", ":dshow-adev=Ekomsys Audio Device#1")`
