### ISSUE TITLE
Wiki home page links broken

### ISSUE THREAD

**Issue by czhower** [ZeBobo5/Vlc.DotNet#69]
https://github.com/ZeBobo5/Vlc.DotNet/wiki

The links for Forms and WPF are circular and point back to the same home page.

**Comment by xDoJohn** [comment]
They haven't written a documentation yet. So try the samples for now:

https://github.com/ZeBobo5/Vlc.DotNet/tree/master/src/Samples

**Comment by jeremyVignelles** [comment]
Getting started has now been written
