### ISSUE TITLE
(re-edit)Can vlc.dotnet play RTP over TCP(RFC 4751) H.264 video stream?

### ISSUE THREAD

**Issue by RUANRUI1995** [ZeBobo5/Vlc.DotNet#692]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86/x64+ Nuget
- **.net version** : .Net Framework 4.5.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows x64

# Summary
I will use some screenshots to explain my question here.

-First
I use a TCP/UDP test program (NetAssist) to create a TCP server,bind 192.168.1.58:17302.It's my computer's port.
![image](https://user-images.githubusercontent.com/18418418/122844131-8c906c00-d333-11eb-912a-a45e19113532.png)

-Secondly
I use my program and my video camera to start video streaming via RTP over TCP.
![image](https://user-images.githubusercontent.com/18418418/122844345-0f192b80-d334-11eb-9685-52ca66b50bc6.png)

-Next
A TCP Connection is created.Using Wireshark to capture packets.
![image](https://user-images.githubusercontent.com/18418418/122844569-89e24680-d334-11eb-9932-7c4bf0792dcc.png)

When I decode as RTP,you can see that the TCP payload is a RTP packet with a two-bytes rfc4571 header,which is the length of the RTP packet.
![image](https://user-images.githubusercontent.com/18418418/122844834-15f46e00-d335-11eb-85a7-e9268a368785.png)

So I think it is not a typical RTSP over TCP protocol,because it is very simple and does not have the magic byte and channel byte at header.Also it doesn't need OPTION,DESCRIBE,SETUP...

-At Last
It,s possible to play this kind of video stream using vlc.dotnet?

**Comment by mfkl** [comment]
I think so

**Comment by jeremyVignelles** [comment]
`--rtsp-tcp`

**Comment by RUANRUI1995** [comment]
> I think so

I am a little confuse now.I have a video camera device, when I select tcp streaming,it will try to connect to a IPEndPoint and create the tcp connection before start streaming.So this IPEndPoint should has a Listener tcp socket as a server.But I can not find where to setup a tcp socket on vlc.dotnet.

**Comment by RUANRUI1995** [comment]
> `--rtsp-tcp`

Thanks for replying.I had tried this command before but it was not I want.I think my problem now is how can i play video  streaming from a camera, but as a tcp server first.

**Comment by ALittleDruid** [comment]
你需要的是一个rtsp服务器,摄像头推送视频流到rtsp服务器,vlc从rtsp服务器拉取
rtsp服务器可以用easydarwin搭建

What you need is an RTSP server. The camera pushes the video stream to the RTSP server, and the VLC pulls it from the RTSP server

RTSP server can be built with easydarwin

**Comment by RUANRUI1995** [comment]
Thanks all .Problem solved.
