### ISSUE TITLE
Can't set VlcLibDirectory

### ISSUE THREAD

**Issue by RemyPatault** [ZeBobo5/Vlc.DotNet#693]
I have an issue about Vlc.DotNet.

# Generic information

    Vlc.DotNet version : 3.1.0
    Vlc.DotNet project used : WinForms
    libvlc version : x86/x64+ Nuget
    .net version : .Net Framework 5.0
    Project language : C#
    Project build architecture : AnyCPU
    Operating system : Windows x64

# Summary

Hello,

I can't seem to put the path of VLC in the VlcLibDirectory field of the VlcController settings (grayed out field), and when I want to write it in code, the line gets deleted after a while.

Does anyone have a solution ?

**Comment by jeremyVignelles** [comment]
Don't edit auto-generated files.
As for the grayed-out field, I never encountered this. You can set it in code in the InitializeComponent method

**Comment by RemyPatault** [comment]
That's what I did, but every time I change the design the line gets deleted

**Comment by jeremyVignelles** [comment]
Sorry, not IN the InitializeComponents, but after the InitializeComponents call in your constructor. It's been a while since I last wrote WinForms...

**Comment by RemyPatault** [comment]
It doesn't work. `System.Exception : ''VlcLibDirectory' must be set.'` is thrown in the InitializeComponent method.

**Comment by jeremyVignelles** [comment]
Could you send me your InitializeComponent method? it seems something is wrong with it...

**Comment by RemyPatault** [comment]
`private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            
            this.vlcControl1 = new Vlc.DotNet.Forms.VlcControl();
            
            ((System.ComponentModel.ISupportInitialize)(this.vlcControl1)).BeginInit();
            this.SuspendLayout();
            
            // 
            // vlcControl1
            // 
            this.vlcControl1.BackColor = System.Drawing.Color.White;
            this.vlcControl1.Location = new System.Drawing.Point(25, 120);
            this.vlcControl1.Name = "vlcControl1";
            this.vlcControl1.Size = new System.Drawing.Size(920, 540);
            this.vlcControl1.Spu = -1;
            this.vlcControl1.TabIndex = 12;
            this.vlcControl1.Text = "vlcControl1";
            this.vlcControl1.VlcMediaplayerOptions = null;
            
            this.Controls.Add(this.vlcControl1);
           
            ((System.ComponentModel.ISupportInitialize)(this.vlcControl1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }`

I just put the code in relation to VLC because it is really long

**Comment by jeremyVignelles** [comment]
Ah well, I forgot about the EndInit. you can also set a VlcLibraryDirectoryNeeded handler, which is more flexible, but the other field shouldn't be grayed out, there's something wrong with your project and I don't know what.

Please try to reproduce in a minimal project

**Comment by RemyPatault** [comment]
I created a new project to test but it doesn't work either. 

![vlc](https://user-images.githubusercontent.com/79002705/123217364-c8aa0500-d4ca-11eb-8cc4-6e2f315edfd2.PNG)

**Comment by jeremyVignelles** [comment]
Did you follow the instructions at https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#vlcdotnetforms ?

**Comment by RemyPatault** [comment]
Yes I do.

It works with VlcLibraryDirectoryNeeded. Thanks a lot for your help
