### ISSUE TITLE
I want to develop UI in raspberry pi. Is there any way?

### ISSUE THREAD

**Issue by bbhxwl** [ZeBobo5/Vlc.DotNet#694]
I tried GTK? Using VLC, I can play sound, but no image, I don't know why?

https://github.com/GtkSharp/GtkSharp/issues/264

**Comment by jeremyVignelles** [comment]
Probably the wrong repo, Gtk is only supported in LibVLCSharp

**Comment by bbhxwl** [comment]
> Probably the wrong repo, Gtk is only supported in LibVLCSharp

This code I can have sound in Windows 10, but no image, there are many errors in raspberry, it seems that it can not run. Hope to get help, I have a project to play video in raspberry pie, but I only know C #. If C #, I can only use Python's Qt5, but I'm not very proficient in Python

**Comment by jeremyVignelles** [comment]
Use this:
https://code.videolan.org/videolan/LibVLCSharp/-/blob/3.x/samples/LibVLCSharp.GTK.Sample/Program.cs

Hwnd is windows-specific, you can't use it on linux.


If it still doesn't work, report your issue there : https://code.videolan.org/videolan/LibVLCSharp/-/issues

**Comment by bbhxwl** [comment]
> Use this:
> https://code.videolan.org/videolan/LibVLCSharp/-/blob/3.x/samples/LibVLCSharp.GTK.Sample/Program.cs
> 
> Hwnd is windows-specific, you can't use it on linux.
> 
> If it still doesn't work, report your issue there : https://code.videolan.org/videolan/LibVLCSharp/-/issues

Net core 3.1 has no videoview. The example you give is net framework

**Comment by bbhxwl** [comment]
> Use this:
> https://code.videolan.org/videolan/LibVLCSharp/-/blob/3.x/samples/LibVLCSharp.GTK.Sample/Program.cs
> 
> Hwnd is windows-specific, you can't use it on linux.
> 
> If it still doesn't work, report your issue there : https://code.videolan.org/videolan/LibVLCSharp/-/issues

For help, I will not use net core 3.1 to display in Linux.

**Comment by jeremyVignelles** [comment]
We only support mono's GtkSharp which doesn't support .net core. We plan to implement GtkSharp/GtkSharp later, but feel free to do the PR for that

**Comment by bbhxwl** [comment]
> We only support mono's GtkSharp which doesn't support .net core. We plan to implement GtkSharp/GtkSharp later, but feel free to do the PR for that
I also tested the GTKSharp of mono, which can't play VLC

  public LibVLC _libVLC;
        public MediaPlayer _mp;
        public Form1()
        {
            Core.Initialize();
            InitializeComponent();
            _libVLC = new LibVLC();
            _mp = new MediaPlayer(_libVLC);
            videoView1.MediaPlayer = _mp;
            var media = new Media(_libVLC, new Uri("https://bj.bcebos.com/kpy-organizations/U2943159/videos/2021062612303528372289135202.mp4"));
          bool b=  _mp.Play(media);
         }



![image](https://user-images.githubusercontent.com/26525599/123529514-7e6f9080-d723-11eb-9be6-89cfb9775b22.png)

**Comment by bbhxwl** [comment]
> We only support mono's GtkSharp which doesn't support .net core. We plan to implement GtkSharp/GtkSharp later, but feel free to do the PR for that

sudo apt install libvlc-dev
sudo apt install vlc
sudo apt install gtk-sharp2

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/123529595-65b3aa80-d724-11eb-862b-ce6cb8b0cd09.png)

**Comment by bbhxwl** [comment]
> We only support mono's GtkSharp which doesn't support .net core. We plan to implement GtkSharp/GtkSharp later, but feel free to do the PR for that

https://github.com/videolan/libvlcsharp/blob/3.x/docs/linux-setup.md

libvlc.so and libvlccore.so will be located at /usr/lib. Should you want to load the libvlc libraries from another location than /usr/lib, you'd need to set LD_LIBRARY_PATH.

Where is libvlc.so and libvlccore.so

**Comment by jeremyVignelles** [comment]
Please copy the sample I gave you and stop sending messages on this closed issue

**Comment by bbhxwl** [comment]
> Please copy the sample I gave you and stop sending messages on this closed issue
I really tested it. I can't. My English is not good. I hope I can help. Can raspberry be CSharp + VLC?


![image](https://user-images.githubusercontent.com/26525599/123548304-d1366000-d796-11eb-849c-4251fff14ed9.png)

**Comment by bbhxwl** [comment]
I really tested it. I can't. My English is not good. I hope I can help. Can raspberry be CSharp + VLC?
