### ISSUE TITLE
How to support Chinese directories？

### ISSUE THREAD

**Issue by hanksoft** [ZeBobo5/Vlc.DotNet#696]
always response Exception “System.IO.DirectoryNotFoundException” when vlcControl1.SetMedia(new System.IO.FileInfo(playUrl));  on Vlc.DotNet.Core.Interops.dll

**Comment by jeremyVignelles** [comment]
Please fill the issue template and ibclude all info.
Please also include the folder name you're trying to load

**Comment by hanksoft** [comment]
use this solved：
`vlcPlayer.SetMedia("file:///"+playUrl); `
