### ISSUE TITLE
My program was frozen during the setmedia operation

### ISSUE THREAD

**Issue by hanksoft** [ZeBobo5/Vlc.DotNet#697]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version 3.1: (Please fill)
- **Vlc.DotNet project used WinForms : (WinForms/WPF/Core)
- **libvlc version x64 : (Please fill) (x86/x64) + how did you get it? there
- **.net version 4.5 : (Please fill)
- **Project language C# : (C#/VB.net)
- **Project build architecture  AnyCPU : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system x64 : (Windows ...) (x86/x64)

# Summary

I want to automatically play the next episode in the endreached event, but setmedia does not respond after obtaining the local file。what can i do?

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by hanksoft** [comment]
private void vlcPlayer_EndReached(object sender, VlcMediaPlayerEndReachedEventArgs e)
{
	this.Invoke(new Action(() =>
    {
		ListViewItem nowItem = lstPlayList.FindItemWithText(RuntimePlayer.PlayName);
		if (nowItem != null)
		{
			nowItem.ForeColor = Color.Black;
			int nextIndex = nowItem.Index + 1 >= lstPlayList.Items.Count ? 0 : nowItem.Index + 1;
			lstPlayList.Items[nextIndex].Selected = true;
			ListViewItem nextItem = lstPlayList.SelectedItems[0];
			if (nextItem != null)
			{
				if (RuntimePlayer.IsAuditLogined && nextItem.Tag is MediaSet)
				{
					RuntimePlayer.PlayMedia = nextItem.Tag as MediaSet;
					LogHelper.WriteDebugLogEx(string.Format("Ready for next video {0}", nextItem.Text));
					labCaption.Text = string.Format("{0} [{1}]", nextItem.Text, RuntimePlayer.PlayMedia.MediaSrc);

					//RuntimePlayer.PlayName = string.Format("{0} [{1}]", nextItem.Text, RuntimePlayer.PlayMedia.MediaSrc);
					ImportMedia(RuntimePlayer.PlayMedia.LocalUrl.ToString());
				}
				else
				{
					ImportMedia(nextItem.Tag.ToString());
				}
				nextItem.ForeColor = Color.Red;
			}
			else
			{
				LogHelper.WriteDebugLogEx("Cant get Media info");
			}
		}
	});
}

public void ImportMedia(string playUrl)
{	
	if (vlcPlayer.GetCurrentMedia() != null)
	{
		LogHelper.WriteDebugLogEx(vlcPlayer.GetCurrentMedia().State.ToString());

		if (vlcPlayer.GetCurrentMedia().State == Vlc.DotNet.Core.Interops.Signatures.MediaStates.Playing)
		{
			LogHelper.WriteDebugLogEx("ready play this video" + playUrl);
			vlcPlayer.Stop();
		}
		//for test
		if (vlcPlayer.GetCurrentMedia().State == Vlc.DotNet.Core.Interops.Signatures.MediaStates.Ended)
		{			
			vlcPlayer.EndInit();
			//vlcPlayer.Stop();
			//vlcPlayer.ResetMedia();
		}
	}

	if (File.Exists(playUrl))
	{		
		FileInfo tmpInfo = new System.IO.FileInfo(playUrl);
		if (MediaUtils.isRightExt(tmpInfo.Extension))
		{			
			try
			{
				if (RuntimePlayer.IsAuditLogined)
				{
					vlcPlayer.SetMedia(tmpInfo);  
				}
				else
				{
                                        //this cant response
					vlcPlayer.SetMedia("file:///" + tmpInfo.FullName);  //resolve chinese directory
				}
				vlcPlayer.Play();
				btnPlay.Image = Properties.Resources.pause;				
								
				VlcMedia media = vlcPlayer.GetCurrentMedia();
				media.Parse();
				labNameTip.Text = tmpInfo.FullName;
				labNameTip.Visible = true;
				labNameTip.BringToFront();

				labLengthTip.Text = tmpInfo.Length;
				labLengthTip.Visible = true;
				labLengthTip.BringToFront();

				foreach (MediaTrack item in media.Tracks)
				{
					if (item.TrackInfo is VideoTrack)
					{
						VideoTrack info = item.TrackInfo as VideoTrack;
						labCodeTip.Text = info.Width.ToString() + "x"+ info.Height.ToString();
						labCodeTip.Visible = true;
					}
				}

			}
			catch (Exception ex)
			{
				LogHelper.WriteErrorLogEx(ex.ToString());
			}
		}
		
	}
	

}

**Comment by jeremyVignelles** [comment]
[Read the wiki](https://github.com/ZeBobo5/Vlc.DotNet/wiki/Vlc.DotNet-freezes-(don't-call-Vlc.DotNet-from-a-Vlc.DotNet-callback))

**Comment by hanksoft** [comment]
> 
> 
> [Read the wiki](https://github.com/ZeBobo5/Vlc.DotNet/wiki/Vlc.DotNet-freezes-(don't-call-Vlc.DotNet-from-a-Vlc.DotNet-callback))

Its work. Thanks.
