### ISSUE TITLE
(two bugs)Can't get aspect ratio and fps!

### ISSUE THREAD

**Issue by CodingOX** [ZeBobo5/Vlc.DotNet#7]
First,I use code like "  string aspectRatio=  vlcControl1.VideoProperties.AspectRatio;",but the result always empty.
Second,I use code " float fps= vlcControl1.FPS;",sometimes can't get fps。Forexample the win7 default video ,media path is "C:\Users\Public\Videos\Sample Videos\Wildlife.wmv"
Tank you!

**Comment by ZeBobo5** [comment]
This is how LibVlc works. You can ask it to Vlc team.
