### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by czhower** [ZeBobo5/Vlc.DotNet#70]
Running the WPF sample, with ANY video I use when I close the mainwindow this exception is thrown:

Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Vlc.DotNet.Core.Interops.dll

Windows 7 x64, VS2013

**Comment by spoiledtechie** [comment]
Agreed.  We can't dispose of the player properly.  This is an issue.

**Comment by hanzhangxian** [comment]
Yes, I also encountered the same problem
Windows7  x86 vs2010
