### ISSUE TITLE
Could not find type 'Vlc.DotNet.Forms.VlcControl'. Please make sure that the assembly that contains this type is referenced.

### ISSUE THREAD

**Issue by abdeslambirnbaum** [ZeBobo5/Vlc.DotNet#72]
I tried to run Vlc.Dotnet project. I am getting following error on each and every Sample page. What is wrong that i am doing wrong while using this project?

Could not find type 'Vlc.DotNet.Forms.VlcControl'. Please make sure that the assembly that contains this type is referenced. If this type is a part of your development project, make sure that the project has been successfully built using settings for your current platform or Any CPU.  

Also getting following problem:

The variable 'myVlcControl' is either undeclared or was never assigned.

**Comment by xDoJohn** [comment]
Did you add the references? Check them again and make sure if the library is complied for the same platform as your application (Example: x86 for x86, x64 for x64).

**Comment by abdeslambirnbaum** [comment]
But I tried to run solution AS IT. When i build project; it doesn't give any error. But when i open Sample form; instead of form; it shows error. All reference were added by default. Source code is OK with platform.

**Comment by abdeslambirnbaum** [comment]
You were write.It was related ( x86 for x86, x64 for x64).issue.

**Comment by antferr** [comment]
It only works in x86, for me
