### ISSUE TITLE
Vlc Control error - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by danielb7390** [ZeBobo5/Vlc.DotNet#73]
Hi!
Just found this and it seems nice but as soon as i add the control to the form i get a error:
"Code generation for property 'Time' failed. Error was 'Property acessor 'Time' on object 'vlcControl1' threw the following exception: 'Object reference not set to an instance of an object."

This is the same as Issue #43 , since that issue was closed with a workaround (that works) but it's not the expected way to do it?

**Comment by xDoJohn** [comment]
I think because the vlc control hasn't loaded libvlc yet, so before you try accessing the time property you should load a file, then use the event 'playing' to start your timer or something.
