### ISSUE TITLE
Incorrect taskbar thumbnail in WPF version

### ISSUE THREAD

**Issue by DonovanMeijer** [ZeBobo5/Vlc.DotNet#75]
Anyone else?

![t-2](https://cloud.githubusercontent.com/assets/9619050/8093133/7337fc2a-0fbf-11e5-81e7-e9134b30212d.png)
![t-1](https://cloud.githubusercontent.com/assets/9619050/8093135/764a067e-0fbf-11e5-92d6-cb27e845f3d7.png)

**Comment by jeremyVignelles** [comment]
Is it really a Vlc.DotNet issue ?

Anyway, in the 3.0.0 release of this library, the WPF control has been rewritten.
