### ISSUE TITLE
Console window with log/debug info

### ISSUE THREAD

**Issue by agherardi** [ZeBobo5/Vlc.DotNet#76]
Hi,
When I start the Forms Sample program, every time I click the Play button a console window pops up that displays some log/debug information.

Is there a way to prevent that console window from popping up?

Thank you in advance.

**Comment by xDoJohn** [comment]
Someone hard-coded in intro the library, you could try building in release 'mode'. I don't know if its based on the debug-attachment.

**Comment by agherardi** [comment]
Release has the same problem. I think I found a solution, though. In Release mode, we should set the --quiet option when initializing the library:

        internal VlcMediaPlayer(VlcManager manager)
        {
            Manager = manager;
    #if DEBUG
            Manager.CreateNewInstance(new[]
            {
                "--extraintf=logger",
                "--verbose=2"
            });
    #else
            Manager.CreateNewInstance(new[]
            {
                "--quiet"
            });
    #endif

**Comment by agherardi** [comment]
Issue closed as patch was merged with https://github.com/ZeBobo5/Vlc.DotNet/pull/78
