### ISSUE TITLE
After playing entire video file, player control doesn't stretch/shrink with window

### ISSUE THREAD

**Issue by agherardi** [ZeBobo5/Vlc.DotNet#80]
Using the 4.5 Vlc.DotNet.Wpf.Samples sample program from the master branch.

Scenario:
1. Modify the sample's source code to play a shorter video clip.
2. Click play button 
3. Change the size of the window by dragging the bottom-right corner. As expected, the player control stretches/shrinks to fit within the window, without overlapping the buttons.
4. Wait for entire video to play
5. Click play button again.
6. The video starts playing again.
6. Change the size of the window by dragging the bottom-right corner. Now the player control remains the same size - it doesn't stretch/shrink.

**Comment by agherardi** [comment]
I found out that the problem goes away if Vlc.DotNet.Wpf.VlcControl  extends WindowsFormsHost instead of HwndHost. Here's the code:

    using System;
    using System.Runtime.InteropServices;
    using System.Windows.Interop;
    using Vlc.DotNet.Core.Interops;
    using System.Windows.Forms.Integration;

    namespace Vlc.DotNet.Wpf
    {
      public class VlcControl : WindowsFormsHost
      {
          public Forms.VlcControl MediaPlayer { get; private set; }

          public VlcControl()
          {
              MediaPlayer = new Forms.VlcControl();
              this.Child = MediaPlayer; 
          }
      }
    }

Does this approach seem reasonable? Are there any reasons to use HwndHost instead of WindowsFormsHost?

**Comment by higankanshi** [comment]
You can see my project xZune.Vlc，this has native WPF Control.
https://github.com/higankanshi/xZune.Vlc

xZune.Vlc used share memory and InteropBitmap to display video.
But xZune.Vlc isn't perfect yet, but you can help me improve it.

**Comment by agherardi** [comment]
Any updates on this? I submitted a pull request https://github.com/ZeBobo5/Vlc.DotNet/pull/84 .

**Comment by agherardi** [comment]
Any updates?

**Comment by qzzf1w** [comment]
This really helped me

**Comment by qzzf1w** [comment]
Thanks

**Comment by jeremyVignelles** [comment]
closed as this PR was merged a long time ago
