### ISSUE TITLE
Memory retains allocated after video reaches end

### ISSUE THREAD

**Issue by DominikPalo** [ZeBobo5/Vlc.DotNet#81]
It seems there is a big problem in library with disposing of memory after video reaches end. If I stops video manually during playback (by calling MediaPlayer.Stop()), all memory consumed by video is released and all works fine. But if video reaches end, memory is not released and every new played video increases amount of memory used by app. I tried to add MediaPlayer.Stop() method into handler of EndReached event, but it doesn't help - MediaPlayer.Stop() releases memory only if it is called during playback... 

I'm using libraries compiled from latest sources and WPF control for playback.

Memory graphs:
1) Top - closing videos by manual calling of Stop()
2) Bottom - closing videos by reaching end

http://postimg.org/image/p7j6v0rj7/

**Comment by colleonimattia** [comment]
I have the same issue here.

**Comment by wolf-germany** [comment]
The EndReach event is the only one which calls "ResetFromMedia()" in addition. Don't know why? 

```c#
private void OnMediaPlayerEndReachedInternal(IntPtr ptr)`
        {
            ResetFromMedia();
            OnMediaPlayerEndReached();
        }
```

ResetFromMedia() also unregister all events, which I believe is only wanted when closing the program.
```C#
private void ResetFromMedia()
        {
            UnregisterEvents();
            if (VideoHostControlHandle != IntPtr.Zero)
            {
                var ctrl = Control.FromHandle(VideoHostControlHandle);
                if (ctrl != null && ctrl.InvokeRequired)
                {
                    ctrl.Invoke(new ResetFromMediaCoreDelegate(ResetFromMediaCore), ctrl);
                }
                else
                {
                    ResetFromMediaCore(ctrl);
                }
            }
            else
            {
                ResetFromMediaCore(null);
            }
        }
```

Maybe it's a good idea to investigate here.

**Comment by wolf-germany** [comment]
For test, I just comment out the function call "ResetFromMedia" within the EndReached event handling.
```C#
private void OnMediaPlayerEndReachedInternal(IntPtr ptr)`
        {
            // ResetFromMedia();
            OnMediaPlayerEndReached();
        }
```
The result:
- no additional memory allocation after end of media reached. 
- but, the last frame of a played video will remain on screen.

**Comment by ZeBobo5** [comment]
Close with latest nuget packages

**Comment by DominikPalo** [comment]
I'm testing the latest NuGet package and memory problem still occurs... If video is closed using `Stop()` memory is deallocated correctly, but when video reaches end, only small amount of memory is deallocated (approx 10% of memory alllocated on video start). The only difference to the previous version is that the last frame of a played video will remain on screen after video reaches end.

![image](https://cloud.githubusercontent.com/assets/1623257/11955043/3f6b1e94-a8ae-11e5-86d5-43f621352169.png)

**Comment by ZeBobo5** [comment]
Do you think it's a Vlc.DotNet library problem and not a LibVlc problem?

I'm so sorry but I'm alone and I don't have time on few next month to continue project. But I'm always pleased to have pull requests. If someone could investigate or continue to perfom the project, documentations, evolutions... I will be happy to add to project members

**Comment by simonbuehler** [comment]
maybe https://github.com/vlc-qt/vlc-qt/issues/34 is related?

**Comment by dohisev** [comment]
Was this solved? I'm having the same problem using the libvlc with Qt in a simple application, the last frame remains on the screen and doesn't respond to resizing or anything, and it doesn't play again until I press the stop button. Is there any solution yet?

https://stackoverflow.com/questions/47361153/libvlc-media-player-end-reached-weird-behavior

**Comment by jeremyVignelles** [comment]
Is it still an issue with vlc 3.0.0 and the latest -develop NuGet package? Closing for now, feel free to reopen/ask for reopening if this is still an issue.
