### ISSUE TITLE
MediaOptions works differently in Vlc.DotNet and directly in VLC.exe

### ISSUE THREAD

**Issue by ivanbydg** [ZeBobo5/Vlc.DotNet#83]
Hi,

I've a problem with recording and simultaneously playing video stream with SOUND

Sample stream: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

VLC (2.2.1) works fine
VLC.exe -I dummy -vvv rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov --sout="#duplicate{dst=std{access=file,mux=ts,dst='test.avi'},dst=display}"

Vlc.DotNet (VLC lib 2.2.1) play and record without sound :-(

mediaOptions = ":sout=#duplicate{dst=std{access=file,,mux=ts, dst='test.avi'},dst=display}";
myVlcControl.MediaPlayer.Play(new Uri(path), mediaOptions);

Could anybody help me?

Thanks in advance

**Comment by Beast76** [comment]
Hi,

please try out my solution on issue #86 and the merged fix on #103.

Beast76

**Comment by jeremyVignelles** [comment]
Fixed by #103 ?
