### ISSUE TITLE
TakeSnapshot

### ISSUE THREAD

**Issue by adrians75** [ZeBobo5/Vlc.DotNet#85]
VlcManager.TakeSnapshot produces nothing :(

I modify the 3 th parameter in byte[] and still nothing. The old wrapper project is working fine with this functionality (picture capture) and with this code.What's happening doctor Ze? :)
## VlcManager.TakeSnapshot.cs

...
GetInteropDelegate<TakeSnapshot>().Invoke(mediaPlayerInstance, 0, Encoding.UTF8.GetBytes(filePath), width, height);.
....
## libvlc_video_take_snapshot.cs

[LibVlcFunction("libvlc_video_take_snapshot")]
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate int TakeSnapshot(IntPtr mediaPlayerInstance, uint num, byte[] filePath, uint width, uint height);

**Comment by wildeyes** [comment]
+1, this is an important functionality piece.

**Comment by jeremyVignelles** [comment]
Is this still an issue? Do you have any special characters in your path? Please reopen if this is still an issue.
