### ISSUE TITLE
Get video by frames

### ISSUE THREAD

**Issue by serdarkaracay** [ZeBobo5/Vlc.DotNet#87]
Hi,
I'm studied Vlc.DotNet.
I cant't find frame related methots.
I want the video export frames.
Startdart video 24 frames/second

How do video by frames.

**Comment by seekerquoc** [comment]
pls fix this, i have same problem

**Comment by jeremyVignelles** [comment]
As of Vlc.DotNet 3.0, you can use SetVideoFormatCallbacks and SetVideoCallbacks to get video frame by frame. See an example of implementation in the WPF control.

**Comment by Mamad4D** [comment]
example for SetVideoCallbacks please.

**Comment by wangning08115** [comment]
@Mamad4D   You can see the WPF sample, Then can change some code for you.
You must change some code youself.  I think jeremyVignelles is busy.
