### ISSUE TITLE
Working example in VB 2013, sound works but no video

### ISSUE THREAD

**Issue by macpit** [ZeBobo5/Vlc.DotNet#88]
Hi all,

I have an issue with the video output, maybe can some one help me to an working example in VB 2013?

This code i have actually:

Imports Vlc.DotNet.Core
Imports Vlc.DotNet.Core.Interops
Imports Vlc.DotNet.Forms
Imports System.IO

Public Class Form1
    Private Sub vlc()
        Dim dirVlc = New DirectoryInfo("C:\Program Files (x86)\VideoLAN\VLC")

        Dim vlCtrl = New VLC.DotNet.Forms.VlcControl

        vlCtrl.Anchor = (System.Windows.Forms.AnchorStyles.Top And System.Windows.Forms.AnchorStyles.Bottom And System.Windows.Forms.AnchorStyles.Left And System.Windows.Forms.AnchorStyles.Right)
        REM vlCtrl.Anchor = New System.Windows.Forms.AnchorStyles

        vlCtrl.BackColor = System.Drawing.SystemColors.ButtonShadow
        vlCtrl.Location = New System.Drawing.Point(12, 12)
        vlCtrl.Name = "Name Test"
        vlCtrl.Size = New System.Drawing.Size(400, 200)
        vlCtrl.TabIndex = 0
        vlCtrl.Text = "Text Test"

        vlCtrl.VlcLibDirectory = dirVlc

        REM vlCtrl.Play(New Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"))
        vlCtrl.Play(New FileInfo("v:\BigBuckBunny_320x180.mp4"))

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Application.EnableVisualStyles()
        Application.SetCompatibleTextRenderingDefault(False)
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        vlc()
    End Sub
End Class

**Comment by higankanshi** [comment]
Have you added the vlCtrl to your Form1?

I can't VB.
But in C#, we should add the Control to Form1

Maybe you can try:
```VB
Private Sub vlc()
    ...
    Me.Controls.Add(vlCtrl) 'Add vlCtrl to Form1

    vlCtrl.Play(New FileInfo("v:\BigBuckBunny_320x180.mp4"))
```

**Comment by higankanshi** [comment]
Have you added the vlCtrl to your Form1?

I can't VB.
But in C#, we should add the Control to Form1

Maybe you can try:
```VB
Private Sub vlc()
    ...
    Me.Controls.Add(vlCtrl) 'Add vlCtrl to Form1

    vlCtrl.Play(New FileInfo("v:\BigBuckBunny_320x180.mp4"))
```

**Comment by macpit** [comment]
Hello higankanshi,

Thank you! That's the solution to add the Control to the Form1.
