### ISSUE TITLE
TakeSnapshot Not wporking....

### ISSUE THREAD

**Issue by qzzf1w** [ZeBobo5/Vlc.DotNet#91]
I Have Tried TakeSnapshot and no luck also tried

  VlcMediaPlayer player = new VlcMediaPlayer(vlcLibDirectory);
            player.SetMedia(LocalFile,
                           "--rate=1",
                           "--video-filter=scene",
                           "--vout=dummy",
                           "--start-time=1",
                           "--stop-time=15",
                           "--scene-format=png",
                           "--scene-ratio=1",
                           "--scene-prefix=snap",
                           @"--scene-path=C:\temp\",
                           "vlc://quit");

```
        player.Play();
```

No luck

**Comment by jeremyVignelles** [comment]
Which version of libvlc are you using? Could you provide a sample code for TakeSnapshot?

**Comment by jeremyVignelles** [comment]
Feel free to reopen if this is still an issue
